### ISSUE TITLE
apiRef and Select

### ISSUE THREAD

**Issue by sidot3291** [jamesmfriedman/rmwc#101]
The MCW Select API offers a way of passing a focusIndex into openMenu:
https://material.io/components/web/catalog/input-controls/select-menus/

I'm wondering how I can use this with RMWC.  I see the apiRef prop, but haven't figured out how I could hook in to use openMenu.

**Comment by jamesmfriedman** [comment]
Hi @sidot3291,

Here is a working example. I won't get into exact details on how to use any specific MDC api, you can get into their docs and also explore the object that is being returned from apiRef, but here is an example I think that might help you. With that said, RMWC doesn't do anything to manipulate the api class, its the actual object returned from `MDCConstructor(el)` (i.e. MDCSimpleMenu, MDCSelect).

```jsx
class SelectWithApiRef extends React.Component {
  handleApi(selectApi) {
    this.selectApi = selectApi;

    // Now anywhere in your class you can reference selectApi
    this.selectApi.foundation_.adapter_.openMenu(1);
  }
  render() {
    return (
      <Select
        apiRef={selectApi => this.handleApi(selectApi)}
        options={['Cookies', 'Pizza', 'Icecream']}
      />
    );
  }
}
```

**Comment by jamesmfriedman** [comment]
@sidot3291 Did this work for you?

**Comment by sidot3291** [comment]
Hi @jamesmfriedman - thanks for the response.  I just got around to testing, and I'm still having some trouble but I'm closer.

The posted code does roughly what you'd expect - it opens the menu with the desired focus on load.  The menu is in the wrong location on the page, but I assume that's because of some render ordering issues.

I want it to happen when the Select is clicked, so I moved the code to an onClick event and preventedDefault, but that didn't work.  The menu opened without the given focus, as though my onClick event didn't fire (although logging shows that it did).  Any ideas on how to resolve?

Thanks!

Code:
```
  onClick(e) {
    e.preventDefault();
    console.log("I fired");
    this.selectApi.foundation_.adapter_.openMenu(6);
  }

  render() {
    return (
      <div>
        <Select
          apiRef={selectApi => this.handleApi(selectApi)}
          label="Select"
          onClick={this.onClick.bind(this)}
          options={[
            {value: '1', label: '1 Cookies'},
            {value: '2', label: '2 Cookies'},
            {value: '3', label: '3 Cookies'},
            {value: '4', label: '4 Cookies'},
            {value: '5', label: '5 Cookies'},
            {value: '6', label: '6 Cookies'},
            {value: '7', label: '7 Cookies'},
            {value: '8', label: '8 Cookies'},
            {value: '9', label: '9 Cookies'},
            {value: '10', label: '10 Cookies'},
            {value: '11', label: '11 Cookies'},
            {value: '12', label: '12 Cookies'},
            {value: '13', label: '13 Cookies'},
            {value: '14', label: '14 Cookies'},
            {value: '15', label: '15 Cookies'},
          ]}
        />
      </div>
    )
  }
```

**Comment by jamesmfriedman** [comment]
Ah! I have a better idea of whats happening now. The apiRef is working just fine, this might just have to go in as a feature request. React using synthetic events so I'm not sure that prevent default would actually work for stopping the event.

You could possible try evt.stopPropagation? Otherwise the ability to open a Select at a specific index might have to be something that is added in the RMWC code that is prop driven.

**Comment by j-o-d-o** [comment]
I think you would have to use onClick on the div and use stopPropagation() there

**Comment by sidot3291** [comment]
stopPropagation didn't work.  I'm not sure how MDC fires events, but they weren't affected by onClick or onClickCapture stopPropagation.

I think you're right that this would be best approached through props, but it doesn't look like MCW is prepared to handle it.  If you call openMenu() before triggering the menu directly, the menu doesn't receive proper alignment or styling.

It turns out there's an `open_()` directly on `foundation_` that _will_ apply the correct alignment (and then calls openMenu on the adapter), but that function doesn't accept a focusIndex.

The combination of all these things led me to the bamboozle of a solution shared below, but I think it's best to close this unless MCW adds better support.  I hope to draw up an issue over there within a few days.

A wrapper component:
```
import React, { Component } from 'react';
import { Select } from 'rmwc';
import {MDCSelectFoundation} from '@material/select';

export class FocusableSelect extends Component {

  constructor(props){
    super(props);
    this.state = {value: props.value};
  }

  _handleApi(selectApi) {
    this.selectApi = selectApi;
  }

  _defaultFocus(){
    const { focusOption, options } = this.props
    if(focusOption){
      return options.indexOf(focusOption)
    } else {
      return 0;
    }
  }

  _onClick(e) {
    const { foundation_ } = this.selectApi
    
    const focusIndex = foundation_.selectedIndex_ < 0 ? this._defaultFocus() : foundation_.selectedIndex_;

    if(!foundation_.adapter_.isMenuOpen()) {
      foundation_.disableScroll_();
      const {OPEN, LABEL_FLOAT_ABOVE, BOTTOM_LINE_ACTIVE} = MDCSelectFoundation.cssClasses;

      foundation_.setMenuStylesForOpenAtIndex_(focusIndex);
      foundation_.adapter_.addClassToLabel(LABEL_FLOAT_ABOVE);
      foundation_.adapter_.addClassToBottomLine(BOTTOM_LINE_ACTIVE);
      foundation_.adapter_.addClass(OPEN);
      foundation_.animationRequestId_ = requestAnimationFrame(() => {
        foundation_.adapter_.openMenu(focusIndex);
        foundation_.isFocused_ = true;
      });
    } 
  }

  render() {
    const { focusIndex, ...other } = this.props;

    return (
      <div className="focusable-select">
        <Select 
          apiRef={selectApi => this._handleApi(selectApi)}
          {...other} 
        />
        <div onClick={this._onClick.bind(this)} className="focusable-select-target"/>
      </div>
    );
  }
}

export default FocusableSelect;
```

Custom scss to capture clicks and retain hover:
```
.focusable-select {
  position: relative;

  .focusable-select-target {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: black;
    opacity: 0;
    transition: opacity 15ms linear;
    cursor: pointer;
    &:hover {
      opacity: 0.04;
    }
  }
}
```

**Comment by j-o-d-o** [comment]
good job on getting it to work! But as you mentioned, it's probably better to try to add some pr to MDC to support this behavior more easily than to build in workarounds into rmwc.
I will close this, but feel free to open it again if you see the need for additional discussion!
