### ISSUE TITLE
Select float above not set when value is null

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#104]
When Select mounts with a value, it should automatically set the label to "float-above"

**Comment by j-o-d-o** [comment]
I can't reproduce this bug. When there is a Select with a hardcoded value property, that would mean it "mounts with a value" right?

**Comment by j-o-d-o** [comment]
https://github.com/jamesmfriedman/rmwc/blob/633d9c846c428009103f99b2060fcd9d632e768e/src/Select/index.js#L27

Don't know if you already looked into it. But guess this line is the problem. null equal false in if clause. 
Question is, should it be the default behavior to show the first selection in the list if the value is null?

Here is a usecase: I have something i want the user to select. I write `this.state = { my_selection: null }` and `<Select value={this.state.my_selection} ... />`. Now the user thinks: "Ah cool, I wanted to have the first selection anyway and presses submit". But `this.state.my_selection` is still `null`. 

Thoughts?

**Comment by jamesmfriedman** [comment]
Yeah thats where I landed as well. Didn't get a chance to dig in any farther. It has something to do with the default selection. Null is definitely not a valid option for a value, but it's defaulting to the first option in options.

**Comment by j-o-d-o** [comment]
Okay, so the issue is actually to set the placeholder or the label (non floating) if value is null?

**Comment by jamesmfriedman** [comment]
the actual issue seems to be that `undefined = no selected value` from the select , and `null = first value selected`

**Comment by jamesmfriedman** [comment]
Thanks for the PR (And for scrubbing the issues today). I really don't know what the "right" or "expected" solution is. I'll pull the PR tomorrow and play around with it.
