### ISSUE TITLE
Elevation tag does not appear to be working.

### ISSUE THREAD

**Issue by ALMaclaine** [jamesmfriedman/rmwc#112]
### What RMWC Version are you using?
v0.28.0

### What browser(s) and React Version is this bug affecting?

All seemingly.

### What build system are you using?

Create React App

### What are the steps to reproduce the bug?

Use the elevation tag.

### What is the expected behavior?

For the elements to elevate/add drop shadow.

### What is the actual behavior?

No elevation/drop shadow.

### Any other information you believe would be useful?

I hope I haven't made a simple mistake.  I started with a fresh create-react-app, installed rmwc and attempted to use Elevation right inside App.js to raise the standard text.  I've tried in my own projects as well, and the example code. No elevation under any circumstances.

Here's a repo I made with fresh react app, and just the elevation tag inside App.js

https://github.com/ALMaclaine/rmwc-elevation-bug/blob/master/src/App.js

Thanks

**Comment by jamesmfriedman** [comment]
Yes, you forgot to include the styles. Please read the installation guide in the docs ;)

**Comment by ALMaclaine** [comment]
Embarrassing.  Thank you, works fine now.

**Comment by jamesmfriedman** [comment]
No worries, happens to the best of us.
