### ISSUE TITLE
bug(TabBar): Initialization loop

### ISSUE THREAD

**Issue by izakfilmalter** [jamesmfriedman/rmwc#116]
```
withMDC.js:133 MDCTabBar failed to initialize because of the following error: RangeError: Maximum call stack size exceeded
    at MDCTabBarFoundation.init (mdc.tabs.js:672)
    at MDCTabBar.MDCComponent (mdc.tabs.js:260)
    at new MDCTabBar (mdc.tabs.js:1782)
    at _class.mdcComponentInit (withMDC.js:130)
    at _class.mdcComponentReinit (withMDC.js:154)
    at didUpdate (index.js:188)
```

```
withMDC.js:133 MDCTabBar failed to initialize because of the following error: <failed to convert exception to string>

mdcComponentInit | @ | withMDC.js:133
-- | -- | --
  | mdcComponentReinit | @ | withMDC.js:154
  | didUpdate | @ | index.js:188
  | mdcComponentInit | @ | withMDC.js:148
  | mdcComponentReinit | @ | withMDC.js:154
  | didUpdate | @ | index.js:188


```

Just updated from `2.0.0` to `2.0.2`.

**Comment by jamesmfriedman** [comment]
@izakfilmalter I really need you to at least post code examples otherwise I can't help. You're really good at uncovering edge cases so far :)

**Comment by izakfilmalter** [comment]
@jamesmfriedman I figured out what is causing the issue. I am using the `Link` component from react-router v4 as a tab. Working on a example repo right now.

```jsx
import { Link } from 'react-router-dom';

[...]

<Tab tag={Link} to={`/about`}>
  About Us
</Tab>
```

**Comment by jamesmfriedman** [comment]
Aw! That'd be pretty cool if we could get that to work.

Originally tag was just a convenience method for rendering proper semantics, but at some point I realized I had accidentally made a magical component extension feature.

If we can't get it to work, the simple solution is to just put it inside the tab and style it appropriately.
```jsx
<Tab>
  <Link to={'/about'}>About Us</Link>
</Tab>
```

Glad it's a weird edge case though. Again, you've been awesome at finding those haha

**Comment by izakfilmalter** [comment]
It was working in v1.0.0. So it should continue to work theoretically.

**Comment by izakfilmalter** [comment]
It seems like I am getting stuck here constantly: https://github.com/jamesmfriedman/rmwc/blob/master/src/Tabs/index.js#L173

**Comment by jamesmfriedman** [comment]
If you can post the exact list of tabs and how you're rendering I might be able to help better.

I ran into an issue the other day with the children key check. I had a boolean check like 
```
{isThisFeatureOn && <Tab>My Tab</Tab>}
```

This would cause an error because `isThisFeatureOn` wasn't actually a boolean. I solved it with this:
```
{!!isThisFeatureOn && <Tab>My Tab</Tab>}
```

Probably not your issue, but an area I ran into the same problem. There was a guy (Vladek Palaszewski) who did some major work on the TabBar to get it working under a lot of various conditions, but he apparently completed disappeared from Github and the internet.

**Comment by izakfilmalter** [comment]
So after some more poking around this seems to be a `styled-components` issue.

**Comment by jamesmfriedman** [comment]
Is it one we can curtail in this library? Hit me with as many details as you can. I also want to add styled components to the documentation.

**Comment by izakfilmalter** [comment]
@jamesmfriedman Repro: https://github.com/izakfilmalter/rmwc-jest

Ya I need to write up a section on styled-components for the docs, as well as react-router stuff.

**Comment by izakfilmalter** [comment]
Basically it's detecting a change in the class names because of how `styled-components` works as a `hoc`.

**Comment by izakfilmalter** [comment]
When you wrap a component in a HOC the displayName is gonna change.

```

**Comment by izakfilmalter** [comment]
`const tabsLengthMismatch = React.Children.toArray(nextProps.children).length !== api.tabs.length`

Is there any reason why we can't do the above? Tests pass with it.

**Comment by jamesmfriedman** [comment]
Yes! That works just fine. That code was from the guy that did the heavy lifting, he was just trying to be explicit, but to my knowledge there will never be any other kid of children for the TabBar. If there is, we can readdress.

And sorry I beat you to the PR, I pushed to the MDC 29 branch. I'm going to give it one more run through and then release. Glad you figured this out!
