### ISSUE TITLE
Different props for Slider :change and :input events

### ISSUE THREAD

**Issue by sidot3291** [jamesmfriedman/rmwc#118]
For Slider, both the :change and :input events are mapped to onChange:
https://github.com/jamesmfriedman/rmwc/blob/master/src/Slider/index.js#L77

Functionally, the :input event is similar to onSlide, while the :change event is similar to onSlideStop:
https://material.io/components/web/catalog/input-controls/sliders/#events

Should the :input event map to onInput instead?

**Comment by j-o-d-o** [comment]
Good point. I'd say there should be an `onInput()` and `onChange()` callback.

**Comment by jamesmfriedman** [comment]
@j-o-d-o took care of it @sidot3291. Will go out with the next release, probably today if we can get some approval on the MDC29 branch.
