### ISSUE TITLE
<TextInput /> label overlaps editing area when user removes text

### ISSUE THREAD

**Issue by romanlv** [jamesmfriedman/rmwc#122]
### What RMWC Version are you using?
1.0.2

### What browser(s) and React Version is this bug affecting?
- all browsers
- Chrome 63.0.3239.132 (Official Build) (64-bit) on Mac 

### What build system are you using?
webpack

### What are the steps to reproduce the bug?

Can be seen on https://codesandbox.io/s/mojvqn57r9 

When user types value in the text field and removes it, while field is focused, the label overlaps with the editing line, see screenshots provided 

It only happens when `value` property is passed to the `TextField` and it's empty 

![empty value while focused](https://user-images.githubusercontent.com/841342/35356294-fa8f9352-011d-11e8-9669-19e546fd99fb.png)

### What is the expected behavior?

Label should be above editing line
![label above editing line](https://user-images.githubusercontent.com/841342/35356359-2db04434-011e-11e8-978c-bb907e6e68a0.png)

**Comment by jamesmfriedman** [comment]
Thanks for this. I’ll get it fixed for the upcoming release.

**Comment by jamesmfriedman** [comment]
Will be released with 1.1.0
