### ISSUE TITLE
ParcelJS fails to compile rmwc.

### ISSUE THREAD

**Issue by SleeplessByte** [jamesmfriedman/rmwc#123]
### What RMWC Version are you using?
`rmwc@^1.0.2`

### What build system are you using?
ParcelJS ([Website](https://parceljs.org/) [GitHub](https://github.com/parcel-bundler/parcel))

### What are the steps to reproduce the bug?

```
yarn add rmwc
# import any component from the package anywhere
yarn start
```

### What is the expected behavior?
It works.

### What is the actual behavior?
Unknown plugin xxx where xxx is anything from the `babel` group in the `package.json` of `rmwc`.

### Any other information you believe would be useful?

The Dev Dependencies of the package are not installed, since those dependencies are only required to develop THAT package:

```
rmwc@^1.0.2:
  version "1.0.2"
  resolved "https://registry.yarnpkg.com/rmwc/-/rmwc-1.0.2.tgz#56c05e47fa5e9c078e9c7f1624088a5a36708385"
  dependencies:
    classnames "^2.2.5"
    material-components-web "^0.28.0"
```

However, the `babel` group will run always. I don't know if this is an issue with `babel`, `parceljs` or `rmwc`; if it's one of the former, this issue will help others find it. It is likely this issue is related or equal to https://github.com/parcel-bundler/parcel/pull/559, and thus nothing needs to happen on the rmwc side.

Installing all the dev dependencies (as dev dependency) is a [valid] work around. Alternatively you may simply remove the `babel` key from `.../node_modules/rmwc/package.json`.

**Comment by jamesmfriedman** [comment]
Couple of things. A repro would be super helpful for this. But more importantly, all of the code is babel-ed before being published to NPM. You can see for yourself if you download that resolved url and open the zip file up.

https://registry.yarnpkg.com/rmwc/-/rmwc-1.0.2.tgz#56c05e47fa5e9c078e9c7f1624088a5a36708385

Glanced at that issue you posted, seems like it could be related. Happy to find a fix if it's something on the RMWC side but my gut tells me that ParcelJS is trying to do something with babel that it doesn't need to with RMWC because it *thinks* babels are a dependency.

**Comment by jamesmfriedman** [comment]
Immediately after I posted that, I realized I might not need that stuff in package.json anymore. I changed the build system recently to Create React App and I don't believe those things are used at all. Standby.

**Comment by jamesmfriedman** [comment]
Ok, so I do need those configuration values since they are the ones that actually get used when transpiling the code for publishing to NPM. I can put them in a .babelrc file instead, but something tells me ParcelJS will have the same problem?

**Comment by SleeplessByte** [comment]
@jamesmfriedman Yesh, this is a ParcelJS issue (after browsing their repo again), and you don't need to solve this on your end. 

However, now if someone runs into this, it's recorded for them to see :)

**Comment by jamesmfriedman** [comment]
Ok, problem will be fixed with tomorrows release. I moved the configuration over to a babelrc file and ignored the babelrc file when I publish.

**Comment by jamesmfriedman** [comment]
Just released, should be fixed. Let me know if the problem persists.

**Comment by SleeplessByte** [comment]
Confirmed @jamesmfriedman . Works like a charm.
