### ISSUE TITLE
ClassNames are prepended instead of appended, forcing !important or weird specifiers.

### ISSUE THREAD

**Issue by SleeplessByte** [jamesmfriedman/rmwc#124]
### What RMWC Version are you using?

`1.0.2`

### What build system are you using?

`ParcelJS`

### What are the steps to reproduce the bug?

1. Add any component
1. Add `classname="foo"`

### What is the expected behavior?

```HTML
<Component class="mdc-component mdc-ripple-upgraded foo">
   ...
```

### What is the actual behavior?

```HTML
<Component class="foo mdc-component mdc-ripple-upgraded">
   ...
```

### Any other information you believe would be useful?

The problem with this behaviour is that it becomes "difficult" to override the mdc styles. For example, when adding a button, the class `.mdc-button` will set the `min-width`. If you'd like to override this with a class, you have to specify:
```CSS
.mdc-button.foo {
  min-width: 10px;
}
```

or

```CSS
.foo {
  min-width: 10px !important;
}
```

Ideally, we don't care about the mdc class at all. All this requires is appending the classname instead of prepending; as in general you'll modify with your local classes.

**Comment by jamesmfriedman** [comment]
The order of classes in HTML don't actually matter. What actually matters is the order of your css that you're including.

**Comment by SleeplessByte** [comment]
That's right!

Thanks :)
