### ISSUE TITLE
TextFields lose MDC controlled classNames when className prop is passed

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#128]
```jsx
<TextField className="foo"/>
```

When this field is typed in, it will appear focused until it re-renders on value change. The TextField will then lose its `focused` class.

One potential fix is to manually assign the classes. Another one is to mimic the Ripple component and collect all MDC classes to pass along.

**Comment by NSWIDER** [comment]
this bug is still present in 1.8.3

**Comment by jamesmfriedman** [comment]
@NSWIDER do you have a repro of your issue? The className on TextField gets added to the TextField container, not the input itself.
