### ISSUE TITLE
TypeError: undefined is not a function on Samsung Browser 3.5 on Android (Lollipop)

### ISSUE THREAD

**Issue by greggzst** [jamesmfriedman/rmwc#134]
### What RMWC Version are you using?
1.0.2

### What browser(s) and React Version is this bug affecting?
Samsung Browser 3.5 on Android (Lollipop) browser details:
![screenshot_2018-01-28-17-28-43](https://user-images.githubusercontent.com/17675583/35484496-dfb81d16-0450-11e8-9c5e-9a410b903136.png)

React 16.2.0

### What build system are you using?
Create React App

### What are the steps to reproduce the bug?
Open browser and go to http://192.168.2.105:3000 provided by create-react-app on my local network.

### What is the expected behavior?
See the website as in other browsers.

### What is the actual behavior?
![screenshot_2018-01-28-09-50-07](https://user-images.githubusercontent.com/17675583/35484389-8c39b56a-044f-11e8-840f-c5e239eb4f4e.png)

![screenshot_2018-01-28-09-50-19](https://user-images.githubusercontent.com/17675583/35484399-96ac5f52-044f-11e8-8671-22bd92907e56.png)

![screenshot_2018-01-28-09-50-26](https://user-images.githubusercontent.com/17675583/35484393-90fba5cc-044f-11e8-8af2-125401b649f2.png)

### Any other information you believe would be useful?
In this project I use `Grid`, `Card`, `Drawer`, `Toolbar` and `Elevation`.

**Comment by jamesmfriedman** [comment]
At a quick glance it looks like String.startsWith is not available on the string prototype. 

RMWC is transpiled down to es5, in looking at the compatibility table it looks like the startswith method is widely supported. 

I'll look into this more, but my immediate suggestion would be to manually polyfill the string method for now. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

**Comment by greggzst** [comment]
Thanks for your tip but I think it is something deeper. After I installed https://github.com/mathiasbynens/String.prototype.startsWith 

I get this:
![screenshot_2018-01-28-19-05-45](https://user-images.githubusercontent.com/17675583/35485467-869d85ee-0460-11e8-9f34-61a8a70ebbfd.png)

**Comment by jamesmfriedman** [comment]
Same problem, different builtin. You need to polyfill Array.from. 

RMWC doesn't include these because most modern browsers has support for them.

**Comment by greggzst** [comment]
I did use this https://www.npmjs.com/package/array.from and I still get the error.

**Comment by jamesmfriedman** [comment]
I'll look into getting these things polyfilled better. Another thing in there is the Set function. Thanks for bringing this up. You may want to look into adding the babel core polyfill and see if that helps.

**Comment by greggzst** [comment]
Thanks! When can I expect a new version with polyfilled functions? Yeah, I'll try that.

**Comment by jamesmfriedman** [comment]
MDC releases every 2 weeks, and RMWC has been keeping pace. If I get time this week I'll look into it and put it out as a patch. You can track any updates on this with https://github.com/jamesmfriedman/rmwc/issues/new

Really though, including this should solve your problems for now and offer the most compatibility for your app. https://babeljs.io/docs/usage/polyfill/

**Comment by greggzst** [comment]
I added `babel-polyfill` and it works and even better before adding it when I tested my app on Google Page Insights it was shown as a blank page and after adding it it presents the app and the content. So you should definitely work on polyfilling RMWC not only for compatibility but for SEO as well.

**Comment by jamesmfriedman** [comment]
That's kind of the point of polyfills though, you only add them if your target platforms require them. 

In this particular case I'm not utilizing those methods that often so it will be pretty easy to code around them with ES5 instead of polyfilling them.

**Comment by greggzst** [comment]
Okay, I understand. Thanks!

**Comment by jamesmfriedman** [comment]
No problem @greggzst. I have the other task to make improvements on this, you ok with me closing this one out?

**Comment by greggzst** [comment]
Of course, you can close it.
