### ISSUE TITLE
bug(Tabs): TypeError: props.children.map is not a function

### ISSUE THREAD

**Issue by izakfilmalter** [jamesmfriedman/rmwc#142]
If you have one `Tab` in a `TabBar`, and any action happens that requires an update, you're gonna have a bad time.

![image](https://user-images.githubusercontent.com/5874330/35937389-0b74b5e8-0c14-11e8-9728-02c4fad0c324.png)

Repro repo: https://github.com/izakfilmalter/rmwc-jest

Run it and click on the tab, app crashes.

**Comment by jamesmfriedman** [comment]
Interesting. Seems like children.map is non-existent when there is a single element.

https://stackoverflow.com/questions/29464577/why-doesnt-this-props-children-map-work

**Comment by izakfilmalter** [comment]
Ya think we need to use the React.Children helpers.

**Comment by jamesmfriedman** [comment]
Ah good call. Lets fix this for the next release.

**Comment by jamesmfriedman** [comment]
Fixed in 1.2.0
