### ISSUE TITLE
TextField does not change aspect when set as "disabled"

### ISSUE THREAD

**Issue by alecchisi** [jamesmfriedman/rmwc#147]
### What RMWC Version are you using?

>RMWC 1.2.0

### What browser(s) and React Version is this bug affecting?

Any browser

### What build system are you using?

> Webpack + Create-React-App

### What are the steps to reproduce the bug?

Adding a `<TextField disabled>` element to a React JSX component.

### What is the expected behavior?

The Textfield should be rendered as disabled, by adding the `mdc-text-field--disabled` to the wrapping `<div>`

### What is the actual behavior?
Inspecting the DOM, you cannot see the `mdc-text-field--disabled`  added.

**Comment by j-o-d-o** [comment]
Good catch! PR should fix this.

**Comment by j-o-d-o** [comment]
Resolved with the release of 1.2.1
