### ISSUE TITLE
CardPrimaryAction should have an href 

### ISSUE THREAD

**Issue by ataliadvanstep** [jamesmfriedman/rmwc#152]
CardPrimaryAction should have an href property to allow user to be redirected to the link.

<a class="mdc-card__primary-action" href="#">

Here the official sample:
view-source:https://material-components-web.appspot.com/card.html

**Comment by ataliadvanstep** [comment]
stupid question. just need to use onClick

**Comment by jamesmfriedman** [comment]
Not stupid at all. You can also do...

```
<CardPrimaryAction tag="a" href="..." />
```

or if you're using ReactRouter

```
<CardPrimaryAction tag={Link} to="..." />
```

**Comment by ataliadvanstep** [comment]
thanks. really elegant solution ! I like it. May be you should update the documentation ?

**Comment by jamesmfriedman** [comment]
It’s in the getting started section. It’s an api Wide feature

**Comment by ataliadvanstep** [comment]
Ok great ! Thanks 😊

Le mer. 28 févr. 2018 à 12:21, James Friedman <notifications@github.com> a
écrit :
