### ISSUE TITLE
Minor: hamburger menu icon ripple off center

### ISSUE THREAD

**Issue by dandv** [jamesmfriedman/rmwc#154]
I'm a first-time user of both RMWC and MDC, so this might be an MDC bug, but it affects the demo site. After I hard-reload https://jamesmfriedman.github.io/rmwc/ in Chrome desktop mode, the ripple isn't centered on the hamburger menu icon (or the click location):

![rmwc hamburger icon ripple off center](https://user-images.githubusercontent.com/33569/36940135-029a0e8c-1ef2-11e8-861b-4d47dcb201b7.gif)

If I switch to mobile emulation and back, the ripple is centered.

**Comment by jamesmfriedman** [comment]
The toolbar menu icons don't usually have a ripple on them, I just added one manually with the ripple component, but you are correct! That is a weird rendering issue, I'll look into it.

**Comment by jamesmfriedman** [comment]
This should be fixed with the next release https://github.com/jamesmfriedman/rmwc/pull/165

**Comment by jamesmfriedman** [comment]
Fixin in 1.4.0
