### ISSUE TITLE
TextField label above decision

### ISSUE THREAD

**Issue by jicheol-ryu** [jamesmfriedman/rmwc#156]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC is just a React wrapper for Google's official MDC that provides a props based interface for their components. Is the bug being caused by RMWC, or MDC? Please do your best to track down where the bug is originating from and post your issue to the proper repository. MDC bugs should be filed here https://github.com/material-components/material-components-web/issues.

Also, please note that RMWC does not contain any styles of its own, so if you're having any style related issues it is probable that the issue is with MDC.

Bugs that would likely be caused by RMWC:
- synchronicity issues: The underlying MDC component or behavior does not match up with your props.
- missing MDC features: MDC says you can do "X" but there is no prop or option for it in RMWC.

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What RMWC Version are you using?

1.2.0

### What browser(s) and React Version is this bug affecting?

all browser

### What build system are you using?

Webpack

### What are the steps to reproduce the bug?

1. define TextField with uncontrolled method. ( without value property )
2. update any state for re-render.

### What is the expected behavior?

Label should stay in above while input element has value.

### What is the actual behavior?

Label doesn't stay in above.

### Any other information you believe would be useful?

next is code in text field.
'mdc-text-field__label--float-above': props.value || props.focused

should check input element is empty or not.

**Comment by jamesmfriedman** [comment]
Nice catch!

I'm in process of rewriting the components to be direct foundation implementation which should resolve sync issues like this. Thanks for reporting.

**Comment by afixoftrix** [comment]
What can we use in the meantime for a fix?

**Comment by jamesmfriedman** [comment]
In the meantime, you can just make it a controlled text field

**Comment by jamesmfriedman** [comment]
Fixed with 1.5
