### ISSUE TITLE
Add property to center GridList

### ISSUE THREAD

**Issue by alecchisi** [jamesmfriedman/rmwc#157]
It could be great if a GridList could be centered, by a prop in `<GridList>` element.

The prop should add a CSS property to the 'mdc-grid-list__tiles' class, applied to the `<ul>` element: 
`justify-content: center`

Now I'm doing this manually, adding the same property to a CSS module class, applied to my component: 

```
.mdcGridListTiles ul {
    justify-content: center;
}
```

**Comment by jamesmfriedman** [comment]
Thanks for the comment @alecchisi. RMWC strives to be an un-opinionated wrapper around material-web-components. While this feature might be useful, it's not one that implements any MWC behavior. 

Your solution is the recommended way of achieving it though. Another option is to make a wrapping component that can handle your additional features and props.
