### ISSUE TITLE
Add top-app-bar

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#164]
Putting this in here as a reminder. Top app bar was released in MDC 32 but didn't contain and publicly viewable documentation. Waiting until the feature is more fleshed out.

**Comment by pmackay** [comment]
Looks like top app bar will replace toolbar:

>The existing MDCToolbar component and styles will be removed in a future release. Some of its functionality will be available in the MDC Top App Bar package instead. Bugs and feature requests will no longer be accepted for the mdc-toolbar package. It is recommended that you migrate to the mdc-top-app-bar package to continue to receive new features and updates.

**Comment by jamesmfriedman** [comment]
Yeah, I don't really get why... This is one of those random changes that seems to hurt everyone downstream. I'll keep both around but drop in the deprecation notice until the old app bar is officially removed.

**Comment by SleeplessByte** [comment]
The stupid thing is that when `Toolbar` came out, as a pattern, it was NOT meant to be the "top-app-bar". It *could* be used as the `Appbar` (the old name), but also could be used anywhere else where you needed it. It came with examples too.

Now they are completely moving away from that again. I've tried to use "top-app-bar" but it doesn't have as many features as the current `Toolbar`.

**Comment by jamesmfriedman** [comment]
Added in 1.6
