### ISSUE TITLE
SEO for https://jamesmfriedman.github.io/rmwc/

### ISSUE THREAD

**Issue by Joostvanderlaan** [jamesmfriedman/rmwc#166]
Hi James, I wanna point you to the fact that whatever search you do in Google related to RMWC, the site never shows up, only the GitHub files. You might wanna do something about that / check your github pages config.

![image](https://user-images.githubusercontent.com/2742259/37519473-816a2a86-2919-11e8-8f54-21b67860eda9.png)

**Comment by jamesmfriedman** [comment]
I have limited experience with SEO. Is this something you can help with? I know setting proper page titles would be a good start.

**Comment by Joostvanderlaan** [comment]
Allright, after looking into it I see that you use CRA. Now that's a SEO problem since it is not really crawlable by default. What you need is Server Side Rendering (SSR) OR a static site generator to generate the site. The second option is impossible at the moment, since I do not know any static site generator that plays nice with Storybook. That leaves us with the first option, I found an example here: https://medium.com/bucharestjs/upgrading-a-create-react-app-project-to-a-ssr-code-splitting-setup-9da57df2040a
I do have experience with Static site generators, but not with CRA & SSR. So I don't think I can help you out here...

**Comment by jamesmfriedman** [comment]
The good news is Google started crawling SPAs a few years back, so I think it might be as simple as fixing the page titles, adding in descriptions, a sitemap, and some additional content.

**Comment by Joostvanderlaan** [comment]
yeah, that's indeed what Google says. In practice it's not indexed properly in most cases. That's why tools like prerender still exist.

**Comment by jamesmfriedman** [comment]
Ah, good call. I'll start there :)

**Comment by CoVoCre** [comment]
Also, it's really too bad because typing react material design doesn't bring out rmwc although it's really, apart from material ui which is really on another path, the best project !

**Comment by jamesmfriedman** [comment]
Thanks! I’ll look into this more this week.

**Comment by oliviertassinari** [comment]
Does material-components-web support server side rendering?

**Comment by jamesmfriedman** [comment]
Yes, It’s a feature of RMWC that has decent test coverage. Haven’t personally used it but I know people are.
