### ISSUE TITLE
Full-Width Text Field rendering is broken

### ISSUE THREAD

**Issue by davidye** [jamesmfriedman/rmwc#168]
### What RMWC Version are you using?

> 1.3.0

### What browser(s) and React Version is this bug affecting?

> Chrome 65

### What build system are you using?

> Webpack

### What are the steps to reproduce the bug?

> Render a TextField with fullwidth (but not textarea).

### What is the expected behavior?

> See reference at: https://material-components-web.appspot.com/text-field.html

### What is the actual behavior?

>  When focused, the input control is incorrectly aligned and the label should not move.

**Comment by jamesmfriedman** [comment]
@davidye if you look closer you'll notice they are using the placeholder attribute, and not a label.

Simply replace the label prop with placeholder in RMWC.

```jsx
<TextField fullwidth placeholder="Full Width..."/>
```

**Comment by davidye** [comment]
I see, thanks for the answer! Maybe worth throwing an error when full width and label are both set?

**Comment by jamesmfriedman** [comment]
It's strange to say the least. I feel like it's an oversight in the MDC library. I usually just use a css class to make the normal text-width 100%
