### ISSUE TITLE
Slider fails to initialize when given a min higher than 100

### ISSUE THREAD

**Issue by jonvuri** [jamesmfriedman/rmwc#173]
### What RMWC Version are you using?

1.3.0

### What browser(s) and React Version is this bug affecting?

Chrome 65

### What build system are you using?

Webpack / Babel

### What are the steps to reproduce the bug?

Initialize a Slider with a `min` prop of 101 or higher, and a `max` higher than the min.

### What is the expected behavior?

The Slider properly initializes with the given min and max

### What is the actual behavior?

material-component-web returns an initialization error complaining that the min cannot be higher than the max:

<img width="1664" alt="screen shot 2018-03-25 at 10 41 26" src="https://user-images.githubusercontent.com/2074135/37876930-4fd483d4-3019-11e8-9657-c46e8d1ec2ab.png">

### Any other information you believe would be useful?

This seems like it might be due to the way that both min and max are set up as independently synced properties with no notion of dependency / constraint. This error is probably happening when rmwc tries setting the min before setting the max, so the max is still at its default value of 100.

**Comment by jamesmfriedman** [comment]
Bad news and good news @jrajav.

Bad news is, the issue is upstream: https://github.com/material-components/material-components-web/issues/2269

The good news is, I found a workaround for now. Removing the aria-valuemin attribute from the DOM corrects the issue, and according to my tests and using it, the slider still works as it is supposed to. I'm going to put the fix in with the SSR branch and get the patch out tomorrow.

**Comment by jamesmfriedman** [comment]
I implemented a workaround in the 1.4.1 patch. I'm going to leave this issue open and label it as an MDC bug so I can "unfix" it when they correct the issue on their end.

**Comment by 101arrowz** [comment]
Given that [the problem has been fixed upstream](https://github.com/material-components/material-components-web/pull/3315), this issue should be closed.

**Comment by jamesmfriedman** [comment]
Finally! Every once in a blue moon I audit these. I’ll leave this open so I can take out the extra handling in RMWC.
