### ISSUE TITLE
Grid Cell Position Support

### ISSUE THREAD

**Issue by tworkman512** [jamesmfriedman/rmwc#178]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC is just a React wrapper for Google's official MDC that provides a props based interface for their components. Is the bug being caused by RMWC, or MDC? Please do your best to track down where the bug is originating from and post your issue to the proper repository. MDC bugs should be filed here https://github.com/material-components/material-components-web/issues.

Also, please note that RMWC does not contain any styles of its own, so if you're having any style related issues it is probable that the issue is with MDC.

Bugs that would likely be caused by RMWC:
- synchronicity issues: The underlying MDC component or behavior does not match up with your props.
- missing MDC features: MDC says you can do "X" but there is no prop or option for it in RMWC.

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What RMWC Version are you using?

> 1.2.0

### What browser(s) and React Version is this bug affecting?

> Chrome Version 65.0.3325.181

### What build system are you using?

> Webpack.

### What are the steps to reproduce the bug?

> Seems like this is just a missing feature in RMWC. In MDC, it says that you can align the position of the cells in your grid, yet I do not see any support or ability to do in RMWC. Am I missing something?

### What is the expected behavior?

> I should be able to align the position of the cells within a grid in RMWC. 

### What is the actual behavior?

> There doesn't appear to be any ability to do what is mentioned above.

**Comment by jamesmfriedman** [comment]
Will add to the next release

**Comment by jamesmfriedman** [comment]
This has been added and will go out in the next release (sometime this week)
