### ISSUE TITLE
TextField label is placement incorrect on Dialogs

### ISSUE THREAD

**Issue by trentin** [jamesmfriedman/rmwc#180]
The label of the TextField aligns on the right of the input when used on a Dialog

(If the fullwidth flag is used the label text is placed underneath the line)

Thanks

[sample code](https://github.com/jamesmfriedman/rmwc/files/1874480/index.js.txt)

<img width="883" alt="dialog" src="https://user-images.githubusercontent.com/975213/38290706-e89d43fe-381f-11e8-84e4-9a92329018ce.png">

**Comment by j-o-d-o** [comment]
When looking at the mdc docs: https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield

It says:

> NOTE: Do not use mdc-floating-label within mdc-text-field--fullwidth. Labels should not be included as part of the DOM structure of a full width text field.

Other then that, I can not reproduce this behaviour with the provided code: https://codesandbox.io/s/6x4oylp88n

Can you try to reproduce it in the sandbox?

**Comment by trentin** [comment]
Thanks for the quick response, I have isolated the issue

The project I'm working on makes use of SSR, if I rollback to 1.3.0 the problem goes away but when I upgrade to 1.4.1 the issue returns.

(Note: I cannot reproduce the problem on a standard react project)

**Comment by jamesmfriedman** [comment]
@trentin this shouldn't have anything to do with SSR. Every 1.X release of RMWC is bound to a new release of material-components-web. The bug is likely in material-components-web, when you roll back to 1.3, you are actually rolling back to material-components-web 31 as well which probably didn't have the issue.

**Comment by trentin** [comment]
@jamesmfriedman thanks, I will report the issue to material-components-web

**Comment by trentin** [comment]
Feedback and apologies

We have tracked down the issues, it seems the dev server was caching the previous version of the css. Once we fixed this issue the problem resolved. 

Thanks for the quick response

**Comment by jamesmfriedman** [comment]
No worries @trentin, glad you found the problem.
