### ISSUE TITLE
Select className issue

### ISSUE THREAD

**Issue by j-o-d-o** [jamesmfriedman/rmwc#199]
https://github.com/jamesmfriedman/rmwc/blob/80917c0f3e0385c3e59a1270ceae3a38cd510a84/src/Select/index.js#L106-L115

Sorry man, I just "reviewed" the PR and come around with an issue right after the merge...

But I think we are missing to catch classNames here, with this implementation it writes the classNames not only to `SelectRoot` but also to `SelectNativeControl` via the rest parameter.

https://github.com/jamesmfriedman/rmwc/blob/80917c0f3e0385c3e59a1270ceae3a38cd510a84/src/Select/index.js#L127

Then something like this can happen: https://codesandbox.io/s/ymznoxwvxx

**Comment by jamesmfriedman** [comment]
Resolved with 1.5.1
