### ISSUE TITLE
Misbehavior & wrong style in disabled Select 

### ISSUE THREAD

**Issue by bcardiff** [jamesmfriedman/rmwc#200]
## RMWC or MDC?
RMWC

### What RMWC Version are you using?

1.5.1

### What are the steps to reproduce the bug?

Demo at: http://g.recordit.co/xRxNebENLf.gif
Sandox at: https://codesandbox.io/s/n38lrv5p34

When using `disabled={true}` prop in the Select by default, the control can't be enabled after.

If the `disabled={false}` is initially user, and then turned to `true`, the end visual aspect is different from the one that is disabled by default. Yet, the behavior in this second case is good w.r.t. the user been able to interact with the control

**Comment by jamesmfriedman** [comment]
Thank you for reporting this. I'll look into a patch and a test for this today.

**Comment by jamesmfriedman** [comment]
The issue has been patched with 1.5.2.

**Comment by bcardiff** [comment]
Thanks for the quick fix! I was going mention that I just found that the `options` prop of the `<Select>` is being forwarded to `<option>` elements and hence in React 15 it is complaining regarding unknown prop error.

https://codesandbox.io/s/8nr2mrol68

But you were to fast here. Let me know if you want me to fill a separate issue for this.

**Comment by bcardiff** [comment]
I don't find the reason for `options: createSelectOptions(opt.options)` in https://github.com/jamesmfriedman/rmwc/blob/44fae50b7e3dbc097c2fcb2e1774470531ff5721/src/Select/index.js#L79 and that is the line I think is generating the additional options property.
