### ISSUE TITLE
Extra options propagated to Selects' option elements

### ISSUE THREAD

**Issue by bcardiff** [jamesmfriedman/rmwc#201]
Since rmwc 1.5.0 there a options option injected in option elements https://codesandbox.io/s/8nr2mrol68

The offending code is `options: createSelectOptions(opt.options)` in https://github.com/jamesmfriedman/rmwc/blob/44fae50b7e3dbc097c2fcb2e1774470531ff5721/src/Select/index.js#L79 

Extracted from https://github.com/jamesmfriedman/rmwc/issues/200#issuecomment-379343719

The fix should consider support for optgroups .

This was noticed while using React 15 since it signal when additional props are passed to some html elements. In React 16 this happens silently.

**Comment by jamesmfriedman** [comment]
I've setup a testing framework #202 that covers testing in all React versions back to 15.5 and have corrected this bug (as well as several others).

I dug really deep into trying to get rid of the React.PropTypes warning, but that one seems to be coming from React itself, and not RMWC.

If you want to take a moment to review the PR and verify it works, that would be a huge help in getting this patched up.

**Comment by jamesmfriedman** [comment]
Fixed with release 1.5.3. Thanks for reporting
