### ISSUE TITLE
Error importing Slider in React app and https://jamesmfriedman.github.io/rmwc

### ISSUE THREAD

**Issue by umaknow-jessica** [jamesmfriedman/rmwc#204]
### What RMWC Version are you using?

> 1.5.3

### What browser(s) and React Version is this bug affecting?

> Browser : Internet Explorer 11
> React Version : 16.3.1
> User Agent String : Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko

### What build system are you using?

> Webpack

### What are the steps to reproduce the bug?

> import something from rmwc (in my case, "import {Slider} from 'rmwc/Slider';")
> run app in Internet Explorer

### What is the expected behavior?

> I should be able to import the slider without any error

### What is the actual behavior?

> When executing the steps, I have the following error : TypeError: Object doesn't support property or method 'getOwnPropertySymbols'

### Any other information you believe would be useful?
> I have the same error if I navigate to [https://jamesmfriedman.github.io/rmwc/sliders](https://jamesmfriedman.github.io/rmwc/sliders) in Internet Explorer

**Comment by jamesmfriedman** [comment]
Hi Jessica,

I need to document browser support, but I haven't focused any attention on anything below evergreen browsers (read, IE).

WIth that said, this is an easy fix. MDN shows that this method isn't available in IE  so you just need to polyfill it. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols

My advice for any project trying to support legacy browsers would be to include the babel polyfill which should help you across the board with issues such as this. https://babeljs.io/docs/usage/polyfill/

**Comment by jamesmfriedman** [comment]
I'm going to close this one out @umaknow-jessica in favor of #205. Hope that helped.
