### ISSUE TITLE
onSelect and onClose not called for Menu/MenuItem when content is more than a text node

### ISSUE THREAD

**Issue by puopg** [jamesmfriedman/rmwc#206]
## RMWC or MDC?

RMWC

## Bugs

```onSelect``` and ```onClose``` not called for Menu/MenuItem when content is more than a text node 

### What RMWC Version are you using?

1.4.1

### What browser(s) and React Version is this bug affecting?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

### What build system are you using?

> Webpack

### What are the steps to reproduce the bug?

1. Wrap a ```<span>``` with text and use that in a ```<MenuItem>``` Component. 
2. Click on the text, not the negative space around the text. (You should be clicking on the <span>)
3. Nothing happens, other than making the row gray. 
4. Click around the text, so this time in the negative space. 
5. Now the click handler is called and the dropdown menu is closed. 

### What is the expected behavior?

```onSelect``` callback should be called. As should ```onClose```.

### What is the actual behavior?

Nothing happens.

### Any other information you believe would be useful?

You can actually just go the to rmwc example site and navigate to the menu component. Then open your debug tools and change the content in the menu item from a text node (thats what is there in the example) to a ```<span>``` wrapping the text. Then try to click on the text as in the reproduction steps.

**Comment by jamesmfriedman** [comment]
I just checked and this problem appears to be upstream. Please report it to MDC if you get a chance. You can repro on their demo page.

https://material-components-web.appspot.com/menu.html

**Comment by d-Pixie** [comment]
I also came to the conclusion that this is upstream, basically replaced all the RMWC components with their rendered HTML. Annoying bug.

Did you report it @puopg ? If not I will and if you did could you paste the upstream issue link here for tracking please?

**Comment by puopg** [comment]
I did not end up reporting it to MDC unfortunately. All you man!

**Comment by jamesmfriedman** [comment]
This appears to be fixed in MDC 37. Will be released with 1.8.

**Comment by jamesmfriedman** [comment]
I closed the prematurely, this is indeed still an issue.

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5
