### ISSUE TITLE
TabBarScroller can't show indicator

### ISSUE THREAD

**Issue by 26903651** [jamesmfriedman/rmwc#207]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What RMWC Version are you using?

1.5.3

### What browser(s) and React Version is this bug affecting?

chrome 65.0.3325.181
react 16.2.0

### What build system are you using?

Create React App

### What are the steps to reproduce the bug?

I just follow the tabs demo :
`<TabBarScroller>`
`  <TabBar`
`    activeTabIndex={this.state.activeTabIndex4}`
`    onChange={evt => this.setState({'activeTabIndex4': evt.target.value})}`
`>`
`    <Tab>Cookies</Tab>`
`    <Tab>Pizza</Tab>`
`    <Tab>Icecream</Tab>`
 `   <Tab>Chocolate</Tab>`
`    <Tab>Fishsticks</Tab>`
`    <Tab>Ratatouille</Tab>`
`    <Tab>Bread</Tab>`
`    <Tab>Rolls</Tab>`
`    <Tab>Sushi</Tab>`
`    <Tab>Cupcake</Tab>`
`  </TabBar>`
`</TabBarScroller>`

### What is the expected behavior?

When the width is small, there would be an indicator button on the right 

### What is the actual behavior?

The indicator can't be shown, but in demo https://jamesmfriedman.github.io/rmwc/tabs, it's worked.

**Comment by j-o-d-o** [comment]
As it works in the Demo and also in the Sandbox (https://codesandbox.io/s/ymznoxwvxx) I would guess the issue is somewhere else in the code.

**Comment by 26903651** [comment]
OK, I found the problem, it cause by my css rules
