### ISSUE TITLE
Combining rmwc + react-select

### ISSUE THREAD

**Issue by rjdestigter** [jamesmfriedman/rmwc#209]
### Any other information you believe would be useful?
Not a bug, just a share for those wanting to to use react-select. I was able to combine rmwc's `TextField` nicely with the renderer options `react-select` provides and some style overrides: https://codesandbox.io/s/728z54x8p1

**Comment by jamesmfriedman** [comment]
Thanks for this @rjdestigter. @izakfilmalter Had brought up adding a section to the docs of external library integrations. I think this is a good example of something that fits nicely with that. I'll make an issue to add a third party library integration section.

**Comment by jamesmfriedman** [comment]
Closing since not an issue

**Comment by mike391** [comment]
> Thanks for this @rjdestigter. @izakfilmalter Had brought up adding a section to the docs of external library integrations. I think this is a good example of something that fits nicely with that. I'll make an issue to add a third party library integration section.

Was this ever accomplished for react-select v2?
