### ISSUE TITLE
The "select" does not search for when it is writting in

### ISSUE THREAD

**Issue by ilysander** [jamesmfriedman/rmwc#211]
### What RMWC Version are you using?

 rmwc ^1.4.0

### What browser(s) and React Version is this bug affecting?

All

### What build system are you using?

 Webpack

### What are the steps to reproduce the bug?

import {Select} from 'rmwc/Select';

<Select id="country_id" name="country_id" label="Country" className="selectFull" options={this.state.countries} onChange={event => this.handleInputChange(event, 'country_id')}/>

### What is the expected behavior?

The "select" does not search for when it is writting in, functionality by default in all the selects, including those of MDC
https://material-components-web.appspot.com/select.html

when I write "Fr" the corresponding "fruit" is selected.

This becomes very tedious that does not have that search functionality.

I do not know if it's a bug, but I have not seen it being talked about anywhere. Or i use it in the wrong way?

### What is the actual behavior?

Nothing

**Comment by jamesmfriedman** [comment]
@ilysander you might be doing something in your own app blocking the keyboard events.

In the RMWC docs, this works as expected. https://jamesmfriedman.github.io/rmwc/select-menus

**Comment by jamesmfriedman** [comment]
@ilysander any update on this? It appears to be working as it is supposed to.

**Comment by jamesmfriedman** [comment]
@ilysander I can't verify this issue. It doesn't appear to be present in RMWC's docs or in Google's. Let me know if you can reproduce the issue in the sandbox.
