### ISSUE TITLE
bug(IconToggle): Element is not properly destroyed/unmounted

### ISSUE THREAD

**Issue by ricardobrandao** [jamesmfriedman/rmwc#215]
## Bugs

Element is not properly destroyed/unmounted

### What RMWC Version are you using?

> 1.5.4

### What browser(s) and React Version is this bug affecting?

> Chrome

### What build system are you using?

> Create React App

### What are the steps to reproduce the bug?

> Click on an icon toggle and immediatly remove the element from the DOM. In order to reproduce it just click on the recycle bin of any item in this [codesandbox](https://codesandbox.io/s/988znwqxz4).

### What is the expected behavior?

> Properly destroy/unmount the element.

### What is the actual behavior?

> An exception is thrown when trying to access an unexisting element.

**Comment by jamesmfriedman** [comment]
Thank you so much for the repro, definitely helps. Will look into it.

**Comment by jamesmfriedman** [comment]
@ricardobrandao that was a great bug and great find. Patched and deployed 1.5.5!

**Comment by ricardobrandao** [comment]
Hi James,

That was quick! 😄 Thank you so much for kindly solving this so fast.  I'll give it a try as soon as it hits npm.

**Comment by ricardobrandao** [comment]
I'm just confirming that this was fixed on 1.5.5 😃

**Comment by jamesmfriedman** [comment]
Awesome, thanks for the validation @ricardobrandao
