### ISSUE TITLE
Button applies className twice

### ISSUE THREAD

**Issue by jrajav** [jamesmfriedman/rmwc#218]
### What RMWC Version are you using?

1.5.5

### What browser(s) and React Version is this bug affecting?

All

### What build system are you using?

Webpack 4, Babel 7

### What are the steps to reproduce the bug?

Render a Button component with a className on it:

```
<Button className='button-class' raised>
  Button label text
</Button>
```

### What is the expected behavior?

The className is included once on the container element of the Button.

### What is the actual behavior?

The className is actually included twice on the container element, duplicated in the resulting `class=""`.

### Any other information you believe would be useful?

This seems like it might be due to the way the full set of properties are spread onto the ButtonRoot element - which includes the className property.

https://github.com/jamesmfriedman/rmwc/blob/master/src/Button/index.js#L93

**Comment by Wroud** [comment]
i think it related with #216

**Comment by jamesmfriedman** [comment]
Found it. Will go out in the next patch
