### ISSUE TITLE
TopAppBar missing action item when the mode is changed to "shortCollapsed={true}" via update

### ISSUE THREAD

**Issue by zkynet** [jamesmfriedman/rmwc#226]
### What RMWC Version are you using?

       "rmwc": "^1.6.2"

### What browser(s) and React Version is this bug affecting?

     Chrome and FireFox 
     - Latest version of both

    "react": "^16.3.2",
    "react-dom": "^16.3.2",

### What build system are you using?

     Webpack

### What are the steps to reproduce the bug?

      <TopAppBar shortCollapsed={this.props.short}>

      Change the menu bar from full length to shortCollapsed via prop update.

### What is the expected behavior?

      The menu bar should animate from full length to shortCollapsed while keeping a single 
      action item in place using this class: "mdc-top-app-bar--short-has-action-item"

### What is the actual behavior?

       The menu bar does animate properly but does not apply the needed class to 
       keep a single action item.

**Comment by jamesmfriedman** [comment]
I have a feeling this bug is from MDC. Short Collapsed isn't intended to be assigned dynamically, but I'll dig in and see what I find.

**Comment by zkynet** [comment]
You can see how they are dynamically changing the TopBar on this page via controls:
https://material-components-web.appspot.com/top-app-bar.html

**Comment by jamesmfriedman** [comment]
It appears that you need both props, short and shortCollapsed. Does that fix it for you?

```
<TopAppBar shortCollapsed={this.props.short} short />
```

**Comment by jamesmfriedman** [comment]
Not sure of your final goal, but here is the toolbar in a code sandbox. It appears you can just remove `fixed`.

https://codesandbox.io/s/5vvjj0k44n

**Comment by zkynet** [comment]
Removing fixed did not fix the issue with the animation :( 

My goal is to resize the bar when the window size drops below X px.

Original bar: 
<img width="715" alt="screen shot 2018-05-15 at 08 52 35" src="https://user-images.githubusercontent.com/20964930/40046907-94cc1d36-581d-11e8-9218-5d4681521d06.png">

After prop (this.props.short) update:
<img width="492" alt="screen shot 2018-05-15 at 08 53 14" src="https://user-images.githubusercontent.com/20964930/40046889-8ebc768e-581d-11e8-8110-72c3f24b7af9.png">

**Comment by jamesmfriedman** [comment]
Did you ever figure this one out?

**Comment by zkynet** [comment]
I just wrote a script to manually apply this class "mdc-top-app-bar--short-has-action-item" and then it was fine.

**Comment by jamesmfriedman** [comment]
Was never able to repro this. Reopen if you need to.
