### ISSUE TITLE
Datatables

### ISSUE THREAD

**Issue by jordyvandomselaar** [jamesmfriedman/rmwc#227]
Is there a datatable component? Can't seem to find it, but MDC does have data tables. Am I just missing something?

**Comment by j-o-d-o** [comment]
I can't seem to find Datatables in MDC. Could it be, that you confuse MDC with MDL (which includes Datatables)?

**Comment by jordyvandomselaar** [comment]
Shucks, it's part of material.io but not MDC; https://material.io/design/components/data-tables.html

**Comment by j-o-d-o** [comment]
Well, I don't always understand the MDC teams component priorities. But thats what we are working with ; ) Here is the Github Issue / Tracker for the datatable component: https://github.com/material-components/material-components-web/issues/57

I will close this issue for now.

**Comment by iddan** [comment]
This can be reopened as MDC now includes data tables

**Comment by jamesmfriedman** [comment]
You know RMWC already has these. Why the reopen?

**Comment by iddan** [comment]
RMWC has it as an addon - it doesn't use the official component: https://material.io/develop/web/components/data-tables/

**Comment by jamesmfriedman** [comment]
What’s ironic is I’m fairly certain it’s based off my code ;). Will get it converted over.

**Comment by iddan** [comment]
@jamesmfriedman your contribution is appreciated ❤️
