### ISSUE TITLE
flow config instructions needed

### ISSUE THREAD

**Issue by veonua** [jamesmfriedman/rmwc#231]
please add instruction to read me how to configure flow with the library,
4 hours wasted in attempts to make

module.name_mapper='^rmwc\/\(.*\)$' -> '<PROJECT_ROOT>/node_modules/rmwc/\1'
module.name_mapper='^rmwc$' -> '<PROJECT_ROOT>/node_modules/rmwc/'

work, but without any result, anyway I get an error on every

import { Snackbar } from 'rmwc/Snackbar';
                              ^^^^^^^^^^^^^^^ rmwc/Snackbar. Required module not found

**Comment by veonua** [comment]
ok, finally I got some progress

had to update flow to the latest version,
remove 
'suppress_comment= \\(.\\|\n\\)*\\$FlowFixMe'
from .flowconfig

**Comment by jamesmfriedman** [comment]
The latest version makes sense, not sure why you’d have to remove FlowFixMe from your config although I believe flow includes that rule automatically now.

**Comment by jamesmfriedman** [comment]
@veonua anything else on this?

**Comment by veonua** [comment]
can you please add some info to readme so future developers would have more
smoothier experience with rmwc + flow

**Comment by jamesmfriedman** [comment]
@veonua what would you like me to add? There isn't any configuration required. What version of Flow ere you on before?

**Comment by jamesmfriedman** [comment]
Added a brief section on troubleshooting in the getting started guide. Will be live with the next release
