### ISSUE TITLE
[Question] Should I use this or wait for material-components-web-react

### ISSUE THREAD

**Issue by devxpy** [jamesmfriedman/rmwc#236]
Since google has been working on an official port of MWC, 
should I start building using this, or wait for the official, since it's in beta right now.

I am in the process of a re-write from [materialize-css](https://materializecss.com/).

[material-components-web-react](https://github.com/material-components/material-components-web-react)

**Comment by jamesmfriedman** [comment]
That’s entirely up to you and your requirements. This library is complete and being used in production cases, it includes flow types, SSR, and complete documentation. I have high hopes for the google library. Even if their components are implemented a bit differently, I’m sure down the road switching will be trivial.

**Comment by devxpy** [comment]
Alright thanks.
