### ISSUE TITLE
How to set gutter/margin in the layout grid?

### ISSUE THREAD

**Issue by devxpy** [jamesmfriedman/rmwc#237]
## RMWC

- missing MDC features: MDC says you can set "gutter/margin" for layout-grid but couldn't find a prop or option for it in RMWC.

```
⋊ ~/hasan> npm list --depth 0
hasan@0.1.0 /home/dev/hasan
├── @material/layout-grid@0.34.0
├── @material/typography@0.35.0
├── react@16.4.0
├── react-dom@16.4.0
├── react-scripts@1.1.4
└── rmwc@1.6.4
```

[Spec on layout grid](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-margins)

[MWC on layout grid](https://material.io/develop/web/components/layout-grid/)

Both mention gutter/margin, but [RMWC's layout grid](https://jamesmfriedman.github.io/rmwc/layout-grid) has no mention of it.

**Comment by jamesmfriedman** [comment]
Hi @devxpy. RMWC doesn't implement any of the SASS, but you have a few options
- If you are using the SASS from MWC and compiling your self, you can use the SASS mixins present on this page https://material.io/develop/web/components/layout-grid/
- If you are setting global spacing, you can override any of the css run time variables. Just inspect the <html> element in your web inspector to see a list of variables
```
:root {
    --mdc-layout-grid-margin-desktop: 24px;
    --mdc-layout-grid-gutter-desktop: 24px;
    --mdc-layout-grid-column-width-desktop: 72px;
    --mdc-layout-grid-margin-tablet: 16px;
    --mdc-layout-grid-gutter-tablet: 16px;
    --mdc-layout-grid-column-width-tablet: 72px;
    --mdc-layout-grid-margin-phone: 16px;
    --mdc-layout-grid-gutter-phone: 16px;
    --mdc-layout-grid-column-width-phone: 72px;
}
```
- You can also override any particular grid with CSS. Please read the docs on styling and theming to see how you can apply custom classNames or global styles through a variety of methods.

Hope that helps!

**Comment by jamesmfriedman** [comment]
@devxpy I'm always looking to improve the documentation. Is there a particular solution you'll be using?

**Comment by devxpy** [comment]
I'll put in the transforms for sass in my [alternative to create-react-app](https://github.com/pycampers/react-pages).

Then i'll try this out.

The guys over at create-react-app don't support sass natively, and i'm not trans-piling it myself.

**Comment by devxpy** [comment]
On a more personal note,
I don't understand why the MWC guys had to do this. 
I mean, either make sass native, or provide me the css bindings. 

I already have enough on my plate, fighting with the DOM.

**Comment by devxpy** [comment]
I'll try to find time and fill this in the documentation..

**Comment by devxpy** [comment]
Finally worked it out, and integrated it into [react-pages](https://github.com/pycampers/react-pages)
