### ISSUE TITLE
Add TopAppBarFixedAdjust component

### ISSUE THREAD

**Issue by devxpy** [jamesmfriedman/rmwc#245]
## RMWC or MDC? -  Not sure

 rmwc@1.6.4
 react@16.4.0
Chrome Version 67.0.3396.62 (Official Build) (64-bit)

Ejected Create react App

https://codesandbox.io/s/k2zz8n06vr  

As you can see, I have 4  `<h3>TEST</h3>`  tags below the top app bar.

### What is the expected behavior?
All 4 `<h3>TEST</h3>` tags are visible.

### What is the actual behavior?
not all of them are visible, since they somehow go under the top app bar.

**Comment by jamesmfriedman** [comment]
HI @devxpy.

As it turns out, mdc has an undocumented component that I didn't catch for RMWC.

Check out this sandbox for the quick fix, I'll make sure to add the component to the next release.

https://codesandbox.io/s/42vlkjwoy4

**Comment by devxpy** [comment]
Thanks!

**Comment by devxpy** [comment]
You forgot the "key" prop that react needs ,

here is the fixed version :)

https://codesandbox.io/s/9jmllnl9z4

**Comment by jamesmfriedman** [comment]
Fixed with release of 1.7 and MDC 36
