### ISSUE TITLE
Controlled checkbox unexpected behaviour

### ISSUE THREAD

**Issue by nbob** [jamesmfriedman/rmwc#247]
Got an unexpected behaviour using controlled `Checkbox`.

Open sandbox https://codesandbox.io/s/9504ml56r and click several times on checkbox.

Expected behaviour:
1. Checkbox always in checked state.
2. onChange calls every click on checkbox

Actual behaviour:
1. Checkbox changes its state (checked/unchecked)
2. in some cases onChange does not call

**Comment by jamesmfriedman** [comment]
Thank you for the repro! I've hit this problem before but wasn't able to reproduce it in such a concise way. Will definitely dig in.

**Comment by jamesmfriedman** [comment]
The super simple repro is actually what helped me nail down the issue, thanks for that. A fix has been deployed in version 1.7.1.

**Comment by nbob** [comment]
Thanks a lot!
