### ISSUE TITLE
Secondary colored button

### ISSUE THREAD

**Issue by nbob** [jamesmfriedman/rmwc#249]
How can I create a flat `Button` colored with secondary(accent) color?

**Comment by whyjay17** [comment]
I just added a className and used mixins to change the style.

`<Button className="secondaryButton" flat >Secondary</Button>`

and in your styles.scss, add

`.secondaryButton {
    @include mdc-button-ink-color($secondaryText);
}
`

But I am pretty sure there will be a striaghtforward way to do it.

For now, just do this.

**Comment by jamesmfriedman** [comment]
If you look at the button page in the docs there is an example using the theme prop.

**Comment by jamesmfriedman** [comment]
@nbob were you able to get your button?

Also, feel free to use the Gitter chat for questions that aren't really issues with the library.

**Comment by nbob** [comment]
Yes, I see theme prop, but it does not affect on ripple color
Ripple colored primary

**Comment by jamesmfriedman** [comment]
The Buttons (as well as anything else that has a Ripple) accepts all of the Ripple props as well. Here is the solution, sorry for the delayed reply. I'll update the docs accordingly.

`<Button flat theme="secondary" accent>With Theme</Button>`
