### ISSUE TITLE
TextField fullwidth outlined problem

### ISSUE THREAD

**Issue by nbob** [jamesmfriedman/rmwc#252]
It is not possible to interact with TextField provided with `fullwidth` and `outlined` props

https://codesandbox.io/s/38z2qjmn76

**Comment by schliflo** [comment]
Duplicate: https://github.com/jamesmfriedman/rmwc/issues/229
Basically combining these two is not allowed by MDC spec:
> NOTE: Do not use mdc-text-field--box or mdc-text-field--outlined to style a full width text field.
