### ISSUE TITLE
TabBar onChange not firing

### ISSUE THREAD

**Issue by maccuaa** [jamesmfriedman/rmwc#254]
### What RMWC Version are you using?

> 1.7.2

### What browser(s) and React Version is this bug affecting?

> All browsers. React 16.4.1

### What build system are you using?

> Webpack & Create React App

### What are the steps to reproduce the bug?

1. Go to the [RMWC Tabs](https://jamesmfriedman.github.io/rmwc/tabs) page.
1. Click on any tab in the examples. The selected tab doesn't change.
1. Go to the [MDC Tabs](https://material-components.github.io/material-components-web-catalog/#/component/tabs) demo page.
1. Click on any tab in the examples. The selected tab does change.

### Any other information you believe would be useful?

The bug seems to have been introduced in the [1.7.2](https://github.com/jamesmfriedman/rmwc/compare/v1.7.1...v1.7.2#diff-c9fd10781bd7c3eb9bb53e97c2b3f1cc) changes.  I tested 1.7.0 and 1.7.1 and the onChange prop fires correctly in both versions.

**Comment by jamesmfriedman** [comment]
Thanks for reporting this! This was a regression in 1.7.2. 

1.7.3 has been released with a fix.
