### ISSUE TITLE
TextField and Icon Actions

### ISSUE THREAD

**Issue by freetwix** [jamesmfriedman/rmwc#256]
Hey,

i'm struggling with TextFields and Icons, especially with receiving the click event:

```
<TextField
  withTrailingIcon={
    <Icon
      use="add"
      role="button"
      tabIndex={10}
      onClick={e => {
        console.log(e)
      }}
    />
  }
/>

```

Any hints here for this Use-Case?

Environment:

react: 16.2.0
material-components-web: 0.36.1
rmwc: 1.7.4

Firefox 60.0.2 /  Chrome 67.0.3396.87 

Thankx in advance and great work by the way ;)

**Comment by jamesmfriedman** [comment]
I’ve had this problem as well I believe it’s an issue with MDC. The ripple surface from the text field surface covers the icon. A few things :

- make sure you are using TextFieldIcon. The example is in the docs, this might fix your problem. 

- you can also tell increasing the z-index of the icon If the other fix doesn’t work.

**Comment by freetwix** [comment]
Argh, <TextFieldIcon> does the trick, thx a lot.
