### ISSUE TITLE
Is it possible to Completely control Dialog open state?

### ISSUE THREAD

**Issue by cdock1029** [jamesmfriedman/rmwc#265]
### What RMWC Version are you using?

> 1.7.5

### What browser(s) and React Version is this bug affecting?

> Chrome 69.0 | React 16.2

### What build system are you using?

> Webpack, React-Static

### What are the steps to reproduce the bug?

> I'm embedding a form (Formik, TextFields..) inside DialogBody. I have a Container / View separation. I'd like to **disallow** the dialog to close until I know form submitted successfully. If not, I don't want it to close and will display error. Ultimately the `Dialog` stays open depending on the `open` parameter. But it flickers if I don't change the state of this variable but click `accept` Button.

### What is the expected behavior?

> Dialog (animations and open state) is completely dependent on setting the `open` value to true or false. 

### What is the actual behavior?

> When pressing an `accept` button to submit data to a form, The `onAccept` callback fires, then the `onClose` callback fires, and then the form flickers closed, then honors the `open` value which is still set to true, and opens again... instead of staying open the entire time.
> `onClose` should fire only when `open` value changes to false. Basically it seems with these methods I'm just along for the ride, and can't really affect the dialogs behavior. If I override the `onAccept` and `onCancel`, The dialog should do **nothing** accept call those methods when buttons are clicked.

**Comment by cdock1029** [comment]
https://github.com/material-components/material-components-web/issues/1323

I guess the obvious workaround is use my own buttons..

**Comment by jamesmfriedman** [comment]
Yeah, theres nothing to be done about the delay between MDC and React, but creating your own button you can control the state of it and make it disabled if you'd like. Reopen if you have any other problems.
