### ISSUE TITLE
Always default title in SimpleTopAppBar

### ISSUE THREAD

**Issue by UFOMelkor** [jamesmfriedman/rmwc#269]
### What RMWC Version are you using?

1.8.0

### What browser(s) and React Version is this bug affecting?

Opera 54.0 / React 16.4.1

### What build system are you using?

Webpack

### What are the steps to reproduce the bug?

`<SimpleTopAppBar title="test" />`
https://codesandbox.io/s/k9k8vxn91v

### What is the expected behavior?

There should be a top app bar with the title *test*.

### What is the actual behavior?

There is a top app bar with the title *Title*.

**Comment by jamesmfriedman** [comment]
Fixed in 1.8.1
