### ISSUE TITLE
Published package install size is very large (~66MB)

### ISSUE THREAD

**Issue by lavigneer** [jamesmfriedman/rmwc#272]
### What RMWC Version are you using?

> 1.8.1

### What browser(s) and React Version is this bug affecting?

> N/A

### What build system are you using?

> N/A

### What are the steps to reproduce the bug?

> Install RMWC through yarn. Check `node_modules/rmwc` and see `react-versions` directory using 63MB of space

### What is the expected behavior?

> The `react-versions` directory should not be included in the published package as it takes up a lot of space and doesn't appear to be used anywhere in the final product.

### What is the actual behavior?

> `react-versions` is included and not used

**Comment by jamesmfriedman** [comment]
Ah, thanks for reporting! Will add to the .npmignore and republish.

**Comment by jamesmfriedman** [comment]
Fixed with 1.8.2. Good catch.
