### ISSUE TITLE
Unable to register onClick for withTrailingIcon using IconButton (or another component)

### ISSUE THREAD

**Issue by scalebig** [jamesmfriedman/rmwc#275]
### What RMWC Version are you using?

1.8.3

### What browser(s) and React Version is this bug affecting?

Chrome v 67.0.3... on OSX

user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

### What build system are you using?

Webpack 4

### What are the steps to reproduce the bug?

Created a TextField with TrailingIcon component.
 ```
       <TextField
          fullwidth
          withTrailingIcon={
            <IconButton use="close"
              onClick={ () => { self.setSearchText('') } }
            />}
          value={ self.props.searchText }  //using redux stuffs here 
          onChange={ (evt) => { self.setSearchText(evt.target.value) } } //using redux stuffs here 
          label="Search by name or enrollment code" />
```

### What is the expected behavior?

I would expect the I that I could click the close icon and have the onClick event fire.

### What is the actual behavior?

No events fire... onClick, onChange, onSkyfalling.

I am thinking that it the event is being consumed by an overlapping element or I could blame it on solar flares and moon changes 😄 

I can take out the feature out for now, fork later and attempt a fix if it is truly an issue. I thought I would ask here before I dig way deep.

#greatframework #nonopinionated

**Comment by jamesmfriedman** [comment]
I need to document this because I've had the same issue in the past.

It's actually a simple zIndex issue! The way MDC has elements stacked, the ripple blocks the click interaction from the icon. Simply up the Icon zIndex to whatever it needs to be and you should be fine. Let me know if that doesn't work.

**Comment by scalebig** [comment]
Thanks! Thats what I had assumed:

> I am thinking that it the event is being consumed by an overlapping element

I just did a chance to verify yet! I will verify ASAP.

**Comment by jamesmfriedman** [comment]
Were you able to verify this?

**Comment by scalebig** [comment]
I hadn't yet, but since you took the time to create an awesome framework - its the least that I could do! 

After some digging and using a handy z-index stacking dev tool. z-index wasn't the issue. It was that the pointer-events style property on the <i> element housing the icons was set to "none". (I will admit I hadn't seen that prop before) I imagine that for non-actionable icons this makes sense?

![image](https://user-images.githubusercontent.com/6069355/43222318-6d282c90-9015-11e8-961a-c2bf8abf5249.png)

so it fixable via CSS for now.

**Comment by scalebig** [comment]
One more note - currently to handle an event on the trailing icon you pass an Icon component with an onClick event. This creates an embedded `<i>` scenario. So you have to set pointer-events to 'auto' for the outer and the inner elements.

![image](https://user-images.githubusercontent.com/6069355/43223141-c134d6e2-9017-11e8-89bf-451672bf7b3a.png)

**Comment by jamesmfriedman** [comment]
So, that sounds like an MDC bug I need to report. I'll make sure it gets upstream

**Comment by scalebig** [comment]
I was looking closely at this again because I need to use it again - it looks like if tabindex was specified for the icon - it would be usable. So this behavior might be intended to enable actionable icons. So if tabindex attr was passed through, this may work?

**Comment by jamesmfriedman** [comment]
With 3.0.0, this should work as follows now.

<TextField withTrailingIcon={<TextFieldIcon icon="close" tabIndex="0" onClick={}>}/>

Reopen if you have an issue.

**Comment by ivanudovin-roonyx** [comment]
So what a basic Onclick option should look like for Button?
this is what I have:  <button onClick={onSubmit}>Send</button>
and this is what doesn't work with rmwc:   <SendButton onClick={onSubmit}  />

last one is basic rc:
```
export default function SendButton() {
  return (
    <div className="btn-container">
      <Button type="submit" className="btn-send" label="Send" raised />
    </div>
  )
}
```
