### ISSUE TITLE
Are you using RMWC for a project? What is it?

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#277]
Someone recently asked me to send them links of sites using RMWC in the wild. According to npm, there are lots of downloads, but RMWC doesnt (and never will) phone home.

Add any publicly available links here.

**Comment by scalebig** [comment]
I will share when we launch our web & native-hybrid for this fall! We are an Education Tech company - founded by key engineering and product management from Macmillan Education. Its been great to use so far 👍

**Comment by jamesmfriedman** [comment]
Thanks @scalebig, looking forward to seeing it.

**Comment by iddan** [comment]
We're using it for internal tools in K Health. Unfortunately they are not available publicly to inspect.

**Comment by groovenectar** [comment]
Awesome job with the library, it is a pleasure to use. Adapted for use on a web presence site here: https://www.newearthva.com/

**Comment by iddan** [comment]
I'm using it for Python Flame Chart python-flame-chart.netlify.com

**Comment by jdeanwaite** [comment]
https://nobscrypto.com
Our company is happily using it!

**Comment by danielmahon** [comment]
https://www.thefanfolio.com
The fantasy sports stock market!

Check it out, let us know what you think.

We just launched the beta of this new fantasy sports game and RMWC has been great to work with. Having previously worked with a larger but slower/buggier material design library it has been refreshing to work with something so "clean" and performant. Let the team at Google do all the hard work ;) We have other projects (web app driven kiosks and such) which may be converted over to use RMWC as well. Keep up the good work!

**Comment by emyann** [comment]
Very light and simple to use, thanks for this library, I used it to build https://profilr.io.

**Comment by jamesmfriedman** [comment]
Love the header on that site @emyann. Nice work!

And thanks for the props @danielmahon

**Comment by matthewoden** [comment]
We're currently using this at Bayer (code and sites are internal only - can't link out).

**Comment by jamesmfriedman** [comment]
@matthewoden like the Asprin? That absolutely does help :)

**Comment by Dosant** [comment]
@jamesmfriedman, We've just started using it for our landing: https://www.meetter.ai/
Exactly what we've needed to keep it light, thank you!

**Comment by jamesmfriedman** [comment]
Awesome @Dosant! Love the lander, nice and clean.

**Comment by markrmullan** [comment]
Our company is happily using RMWC for some of our customer-facing applications at www.clover.com/dashboard. Ways to obtain login creds include:

- Becoming a business
- Heading to www.clover.com/developers and registering as a third party platform dev.

Thank you for all the hard work to make this library!

**Comment by danielmahon** [comment]
@jamesmfriedman Also using RMWC for a Headless Prisma CMS I'm prototyping: https://github.com/danielmahon/opencrud-admin

![](https://github.com/danielmahon/opencrud-admin/blob/master/public/demo.gif?raw=true)

**Comment by jordyvandomselaar** [comment]
I'll post my project here when it's usable by the outside world! Hopefully won't be long 😅

**Comment by jamesmfriedman** [comment]
@jordyvandomselaar and @danielmahon those are both really awesome.

@danielmahon I'm especially excited to try yours out. Very cool concept.

**Comment by maurusrv** [comment]
good day sir @jamesmfriedman, we're using it in our point-of-sale app, but we're still in development so i can't show anything right now. once i get the go signal, i'll be notifying you again. 

PS. many thanks for this library, because i preferred it over material-ui and others. using the library felt more 'material' than any other lib that i have used in learning material design because it's more of a building block than a full blown and sometimes opinionated material implementation. 👍

**Comment by jamesmfriedman** [comment]
Love hearing that @maurusrv. Can't wait to see what you guys are building! If you love it spread the word, and as always, let me know how we can make this better.

**Comment by palnes** [comment]
We are using it extensively throughout our customer-only application at www.xeneta.com, steadily replacing most of our homegrown implementations. With the addition of the add-ons, this is clearly the most comprehensive implementation, and the documentation is beautiful!

**Comment by jamesmfriedman** [comment]
Awesome! Glad you’re enjoying it. I’m hoping to make some improvements to the docs soon, so let me know if you have any requests.

**Comment by SvenAlHamad** [comment]
We are using it for our Webiny - Serverless CMS project. 

It's used for the administration part, although we wrote a wrapper around the lib (called webiny-ui) to better fit our implementation and use-case. Otherwise, it'a a great lib - thanks @jamesmfriedman!  

Check it out - www.webiny.com

**Comment by jamesmfriedman** [comment]
@SvenAlHamad thats awesome! I'd be genuinally interested in using that service. I generally have a thin wrapper around RMWC as well for different projects which tailors the specific usecases.

**Comment by SvenAlHamad** [comment]
> @SvenAlHamad thats awesome! I'd be genuinally interested in using that service. I generally have a thin wrapper around RMWC as well for different projects which tailors the specific usecases.

Thanks :) If you do end up trying Webiny - the team would love to hear your feedback!

**Comment by maracuja-juice** [comment]
I use it for a fun side project I'm working on: https://github.com/ultimate-ttt/ultimate-ttt
Great work! 👍

**Comment by jamesmfriedman** [comment]
Dude, that is super cool, and a little trippy

**Comment by maracuja-juice** [comment]
Haha thanks. We definitely need to add a tutorial sometime otherwise most people don't get how it works 😄

**Comment by jamesmfriedman** [comment]
I originally started this library for a startup I was working on because Material-UI and React Toolbox both had some serious mobile performance issues and I was building a native quality PWA. 

This lander, as well as the app it's referencing are both built using RMWC.
https://quickcrashapp.com/

**Comment by j-o-d-o** [comment]
Been working on a toolchain to manage and train TensorFlow models remotely. Using RMWC for the frontend. A breeze as always ;)

Unfortunately, I don't have a live example :(. But I am using it regularly to train models on AWS instances.

![ezgif com-resize-min](https://user-images.githubusercontent.com/15958535/66163170-fd5b9600-e62f-11e9-9185-48ad2dbf6d35.gif)

**Comment by jamesmfriedman** [comment]
That. Is. Awesome.

**Comment by cdock1029** [comment]
Given the tremendous popularity of this great project and all the efforts put in by James himself... and that we have plenty of companies using his work to build upon for their own commercial efforts, I think we should do the right thing and give back:

Open Collective link:

https://opencollective.com/rmwc

**Comment by jamesmfriedman** [comment]
Thanks for the shout out @cdock1029! Glad people are getting value from it. I'm eyeballing a total rewrite with hooks now that they're primetime, but waiting to see how the MDC team moves.

**Comment by cdock1029** [comment]
Nice.. hooks really streamlines a lot of use cases.  I see the mcd react library has stagnated lately. Google should just pay you to do it, since you already are lol

**Comment by kale1d0code** [comment]
I was using material-ui until recently when I discovered this library
I'm using it to build a webform to integrate into an existing website for work at the moment but this is what I'd use going forward

**Comment by iddan** [comment]
Also using it for Cayley UI: https://github.com/cayleygraph/web

**Comment by gugu** [comment]
https://app.short.io
