### ISSUE TITLE
Linear Progress open prop

### ISSUE THREAD

**Issue by iddan** [jamesmfriedman/rmwc#278]
The Material Components Web interface include open and close methods.
The RMWC Linear Progress component lacks a way to trigger them idiomatically.
I suggest an `open` boolean prop that will call the open and close methods.

**Comment by iddan** [comment]
I've tried to implement it myself but the `apiRef` was never triggered and the `elementRef` raised an error.

**Comment by iddan** [comment]
Also, I was trying to get into the codebase but I got scared.

**Comment by jamesmfriedman** [comment]
easy workaround on this one until I implement it.

just add a class, because thats all their code does

```
<LinearProgress className={isClosed ? 'mdc-linear-progress--closed' : ''} />
```
