### ISSUE TITLE
elementRef with GridCell

### ISSUE THREAD

**Issue by code-sam** [jamesmfriedman/rmwc#284]
I am trying to use the `elementRef` feature to get the `clientWidth` property of a rendered `GridCell`. However, my implementation seems to use the `elementRef` feature incorrectly. 

I am relatively new to React and have perhaps not properly understood the usage documentation for the `elementRef` feature.

### What RMWC Version are you using?

1.8.3

### What browser(s) and React Version is this bug affecting?

Edge, Chrome

### What build system are you using?

> Webpack, Create React App, 

### What are the steps to reproduce the bug?

```
import React, { Component } from 'react';
import { Grid, GridCell} from 'rmwc/Grid';

class TestClass extends Component   {
    constructor(props) {
        super(props);
        this.testRef = React.createRef();
    }

    componentDidMount() {
        this.updateGrid();
    };

    componentDidUpdate() {
        this.updateGrid();
    };

    updateGrid() {
        console.log(this.testRef.current.clientWidth);
    }

    render()    {
        return (
            <div class=ClassName>
                <Grid>
                    <GridCell 
                        span='12' 
                        elementRef={testRef => this.GridCell = testRef}
                    >
                        <span/>
                    </GridCell>
                </Grid>
            </div>
        );
    }
};

```

### What is the expected behavior?

The number of pixels that the rendered Grid takes up in horizontal direction should be printed in the console. Or at least,, `console.log(this.testRef.current);` should not return `null`.

### What is the actual behavior?

`console.log(this.testRef.current.clientWidth)` returns `undefined` and `console.log(this.testRef.current);` returns `null`

**Comment by j-o-d-o** [comment]
Sorry for answering so late. You most probably resolved the issue already yourself. 
If you want to get the client with you can use `elementRef`, but in a slightly different way (you almost had it): 

```
  updateGrid() {
    console.log(this.testRef.clientWidth);
  }

  render() {
    return (
      <div className="my_class">
        <Grid>
          <GridCell span="12" elementRef={el => (this.testRef = el)}>
            <span />
          </GridCell>
        </Grid>
      </div>
    );
  }
```

**Comment by code-sam** [comment]
Many thanks for your help! Much appreciated.
