### ISSUE TITLE
The "name" attribute of inputs and controls(TypeScript)

### ISSUE THREAD

**Issue by SuperChocoman7** [jamesmfriedman/rmwc#287]
## RMWC or MDC?
RMWC

### What RMWC Version are you using?
1.8.3

### What browser(s) and React Version is this bug affecting?
All

### What build system are you using?
Create React App (TypeScript)

### What is the expected behavior?
The input element of html has "name" attribute, which is usually used to handle the change of value.
For example, assumed I have an input element: 

```html
<input name="address" type="text" />
```

And a handleChange function: 

```javascript
handleChange(e: any) {
    const { name, value } = e.target;
    //Do something with name and value.
}
```

Then I can bind the onChange event to my handleChange function: 

```html
<input name="address" type="text" onChange={this.handleChange} />
```

### What is the actual behavior?
The inputs and controls of RMWC(TextField, Checkbox, Select, Radio...)  currently have no "name" attribute.

### Any other information you believe would be useful?
However, I am able to use some tricks to achieve this in TypeScript.
Here's how I do it: 

(TS part)
```javascript
const nameAttr = { name: "address" };
```

(HTML Part)
```html
<TextField {...nameAttr} type="text" onChange={this.handleChange} />
```

Is it possible to add "name" attribute on the inputs and controls of RMWC?
That would be a more proper way to handle changes of inputs and controls.

**Comment by jamesmfriedman** [comment]
Thanks for reporting this. Took me a bit to figure out that HTMLAttributes<any> doesn't do anything... Got this properly working and applied the same fix to all of the input elements in RMWC.

Will post a patch sometime today.
