### ISSUE TITLE
`fixed` Menu prop is not documented, only works with MenuSurface

### ISSUE THREAD

**Issue by cyberhuman** [jamesmfriedman/rmwc#295]
## RMWC or MDC?

RMWC

### What RMWC Version are you using?

1.9.2

### What browser(s) and React Version is this bug affecting?

any

### What build system are you using?

webpack

### What are the steps to reproduce the bug?

```
<MenuSurfaceAnchor>
  <Menu
    fixed=true
    open=true
  >
    <MenuItem>Cookies</MenuItem>
    <MenuItem>Pizza</MenuItem>
    <MenuItem>Icecream</MenuItem>
  </Menu>
</MenuSurfaceAnchor>
```

### What is the expected behavior?

`mdc-menu-surface--fixed` class must be applied when `fixed` is true.

### What is the actual behavior?

`mdc-menu-surface--fixed` is not applied to Menu component (but is applied to MenuSurface component).

### Any other information you believe would be useful?
Menu's source code has the following code for the MenuSurfaceRoot component:
```
var MenuSurfaceRoot = exports.MenuSurfaceRoot = (0, _Base.simpleTag)({
  displayName: 'MenuSurfaceRoot',
  classNames: function classNames(props) {
    return ['mdc-menu-surface', {
      'mdc-menu-surface--fixed': props.fixed
    }];
```
but MenuRoot does not handle `fixed`:
```
var MenuRoot = exports.MenuRoot = (0, _Base.simpleTag)({
  displayName: 'MenuRoot',
  classNames: function classNames(props) {
    return ['mdc-menu', 'mdc-menu-surface'];
  },
  defaultProps: {
    tabIndex: '-1'
  }
});
```

**Comment by cyberhuman** [comment]
Cool! Thank you!

**Comment by jamesmfriedman** [comment]
Will be out in a patch today @cyberhuman. Look for 1.9.3
