### ISSUE TITLE
More documentation for List

### ISSUE THREAD

**Issue by jackjwilliams** [jamesmfriedman/rmwc#30]
I see that your documentation site actually uses a List with sub items, and the documentation has something called "ListGroup" and "ListGroupSubheader". Can you elaborate more on these react components?

**Comment by jamesmfriedman** [comment]
Oh those are just a couple of components I crappily three together. They’re not actually party of MDC. Feel free to dig through the docs code and pull them out. 

Been trying to think of a way to start creating community packages separate from rmwc to include stuff like that.

**Comment by jackjwilliams** [comment]
Gotcha, I like the simplicity of the components. You're right in that others repos / react material components are very opinionated and have very special styling requirements just to get things working.

One thing I have not been able to figure out is how to use this in webpack. You're repo has a dependency on @@material, but I have yet to find a way to import the CSS properly. Have you had any experience with this?

**Comment by jamesmfriedman** [comment]
Yeah, depends on how you are handling css in your project.

- if you're using webpacks css loader or create-react-app, just import the CSS directly
```
import 'material-components-web/dist/material-components-web.css';
```

- otherwise include it in your webpage
```
<link href="/node_modules/material-components-web/dist/material-components-web.css" />
```

I have that on the quickstart list on the docs but I have to call it out a bit better.

**Comment by jamesmfriedman** [comment]
Did that response help?

**Comment by jackjwilliams** [comment]
Yes it did, thank you!
