### ISSUE TITLE
Controlled textfield does not properly render state change for stressed characters

### ISSUE THREAD

**Issue by Deilv** [jamesmfriedman/rmwc#301]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

This bug involves react state, so it's either related to rmwc or to react itself.

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What RMWC Version are you using?

2.0.0

### What browser(s) and React Version is this bug affecting?

This bug affects Safari only (Chrome and Firefox work as intended). React version 16.5.0.

### What build system are you using?

Webpack 4.17.2

### What are the steps to reproduce the bug?

This bug is caused due to the way Safari inputs stressed characters in an input field.
Generally, to input a stressed character you need to press the key ; followed by the letter you want stressed, for example ; + ο = ό.

Normally, I would expect two calls to setState:
1. value="΄" (the stress character, only appears on macOS/iOS)
2. value="ό" (the stress character is automatically replaced by the stressed vowel)

However, what actually happens is:
1. value="΄"
2. value="΄ό"
3. value="ό"

Now, triggering onChange and setState 3 times instead of 2 isn't a big deal, react will queue the state updates anyway and render only as needed. The fun thing is, something goes wrong and the final result is state 2 value="΄ό".

You can try it yourself here: https://codesandbox.io/s/kjm1w47rv
Steps to reproduce (you need access to a non-latin keyboard such as Greek or French).
1. You need to use Safari on macOS or iOS
2. Focus the text field (click)
3. Press the stress key (usually semi-colon ;)
4. Press a vowel to be stressed.

### What is the expected behavior?

The stressed vowel should be the only character in the input field.

### What is the actual behavior?

The stress character doesn't seem to want to go away.

### Any other information you believe would be useful?

Windows is not affected because by default the stress character does not appear before the next letter is pressed. I know this is a rather specific scenario, but I've spent a few hours trying to figure it out without luck. Hopefully you may have some insight for me :)

**Comment by jamesmfriedman** [comment]
Can you make a repro and validate this with a standard html input as well? Doesn’t sound like this library is the issue.

**Comment by Deilv** [comment]
Works fine with standard html input as well as non-controlled input. It even works fine on Firefox/Chrome. The issue seems to originate somewhere between onChange(), setState() and render(). I'm still looking into this and I've also posted a question on SO.

Looking at the setState calls, the 2nd one is called with value="", yet it seems to be ignored.

**Comment by Deilv** [comment]
I have isolated the issue outside the scope of this library.

**Comment by Deilv** [comment]
It seems to be a disagreement between Safari and reactjs, haven't yet decided who's to blame. I'm still working on it.
