### ISSUE TITLE
missing TopAppBarFixedAdjust for dense/prominent/short app bars

### ISSUE THREAD

**Issue by cyberhuman** [jamesmfriedman/rmwc#302]
TopAppBarFixedAdjust uses className="mdc-top-app-bar--fixed-adjust", but dense, short, prominent and dense prominent Top App Bars should be adjusted for different heights using different class names:

- `mdc-top-app-bar--dense-fixed-adjust`
- `mdc-top-app-bar--prominent-fixed-adjust`
- `mdc-top-app-bar--dense-prominent-fixed-adjust`
- `mdc-top-app-bar--dense-short-adjust`

Probably TopAppBarFixedAdjust should also accept dense, short, and prominent props and use the correct class name?

**Comment by jamesmfriedman** [comment]
Sure. As a workaround you can manually apply those classes for now. Thanks for reporting.
