### ISSUE TITLE
<TabBar/>: Uncaught TypeError: Cannot set property 'isActive' of undefined

### ISSUE THREAD

**Issue by szamanm** [jamesmfriedman/rmwc#305]
Hey! So at first - great job with RMWC, it's really what I needed, I love it!
I just have small issue with TabBar component - I need dynamic number of tabs - so first allow user to select tabs, and after some user action, the amount of tabs will change.

```
<TabBar activeTabIndex={activeTabIndex} onChange={onTabChanged}>
    {titles.map((title, index) => <Tab key={index}>{title}</Tab>)}
</TabBar>
```

`activeTabIndex `and `titles` are provided by state, ex. 
```
{
    activeTabIndex: 0
    titles: ['a', 'b', 'c']
}
```

After user action, there's an update:

```
updateTitles(titles) {
    const activeTabTitle = this.state.titles[this.state.activeTabIndex];
    const activeTabIndex =
        titles.indexOf(activeTabTitle) !== -1 ? titles.indexOf(activeTabTitle) : 0;

    this.setState({ activeTabIndex, titles });
}
```

So it works when switching tabs, and tries to keep the selected tab even when the index changes.
The issue occurs from two scenarios: 

previous titles: ['a', 'b', 'c'], currentIndex: 2
new titles: ['a', 'b', 'd', 'c'], _so next currentIndex: 3_

which causes that error, and **breaks rendering for entire page**:
```
Uncaught Error: Out of bounds index specified for tab: 3
    at MDCTabBarFoundation.switchToTabAtIndex (mdc.tabs.js:771)
    at TabBar.setActiveTabIndex_ (mdc.tabs.js:2304)
    at TabBar.set (mdc.tabs.js:2340)
    at index.js:139
    at syncFoundationProp (withFoundation.js:57)
    at TabBar.syncWithProps (index.js:138)
    at TabBar._safeSyncWithProps (withFoundation.js:133)
    at TabBar.componentWillReceiveProps (withFoundation.js:112)
    at callComponentWillReceiveProps (react-dom.development.js:6880)
    at updateClassInstance (react-dom.development.js:7120)
    at updateClassComponent (react-dom.development.js:8333)
    at beginWork (react-dom.development.js:8966)
    at performUnitOfWork (react-dom.development.js:11798)
    at workLoop (react-dom.development.js:11827)
    at HTMLUnknownElement.callCallback (react-dom.development.js:104)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:142)
    at invokeGuardedCallback (react-dom.development.js:191)
    at replayUnitOfWork (react-dom.development.js:11302)
    at renderRoot (react-dom.development.js:11869)
    at performWorkOnRoot (react-dom.development.js:12422)
    at performWork (react-dom.development.js:12343)
    at performSyncWork (react-dom.development.js:12320)
    at interactiveUpdates (react-dom.development.js:12570)
    at interactiveUpdates (react-dom.development.js:1962)
    at dispatchInteractiveEvent (react-dom.development.js:4256)
```

so it seems, that react first updates activeTabIndex, and then adds new `<Tab/>` - that's why, for a moment, the currentIndex is 3 (which points at 4th item :)), but there's only 3 <Tab>s .

**my hackish solution** for that issue is:
```
this.setState({ activeTabIndex: 0, titles }, () =>
    this.setState({ activeTabIndex })
);
```

but there's another issue (with, or without hack from above)
previous titles: ['a', 'b', 'c', 'd'], currentIndex: 3
new titles: ['a', 'c', 'd'], _so next currentIndex: 2_

that gives following error:
```
Uncaught TypeError: Cannot set property 'isActive' of undefined
    at Object.setTabActiveAtIndex (mdc.tabs.js:2274)
    at mdc.tabs.js:778
```
Luckily, it doesn't break rendering nor causes any visible issues, so I left it that way for now ;). But it is caught by our errorHandler, so it would be great if you could take a look at this issue and help me with that!

I hope you agree that it seems to be connected with RMWC . Googling around I could see that similar framework of MWC for Vue also had similar problem: https://github.com/stasson/vue-mdc-adapter/issues/298 and it seems that they fixed it on their side.

### version:
1.7.4
React 16.2.0, Chrome

**Comment by jamesmfriedman** [comment]
Hi @szamanm, thanks for reporting this.

If you are correct in saying you are using version 1.7.4, my advice would be to upgrade to the new tab bar component. The components are now individually packaged so you can install v2.0.0 of the Tabs and use them with interfering with the rest of your components.

Just let me know about the version. If it's current, then a repro in the code sandbox would also be very helpful but I do appreciate the examples you posted.

**Comment by szamanm** [comment]
hey, wow, thanks for the quick answer, and sorry for late response :(. 
Yes I am using 1.7.4, with Typescript 2.7.2 and React 16.2.0, and I've checked the issue with individual @rmwc/tabs: 2.0.1, but I'm having a lot of troubles to use it:

first I got number of issues like that:
```
.../node_modules/@rmwc/base/simpleTag.d.ts
(47,23): Generic type 'ComponentClass<P>' requires between 0 and 1 type arguments.
```

then, after changing all `ComponentClass<any, any>` to `ComponentClass<any>` around .d.ts in the package, I got that:
```
.../node_modules/@rmwc/base/utils/noop.tsx   
(1,27): block is empty                         
```
and then:
```
.../node_modules/@rmwc/base/utils/randomId.tsx
(6,1): asterisks in jsdoc must be aligned
```
and after fixing that the tabs are displayed as native buttons, and are not working. Maybe I'm doing something wrong, but I can't confirm now if it's fixed in 2.0. I will try to investigate that slightly further tomorrow, or maybe you think that it requires it's separate bug report?

btw: It looks like TabBarScroller is missing from @rmwc/Tabs 2.0, right? In the docs here: https://jamesmfriedman.github.io/rmwc/tabs it's still available in imports, but it's not used. Comment says {/* Tabs automatically scroll with lots of content. */} (and it sort of is, if you click through all the tabs), but it's not exactly that, since it's missing the arrows to scroll. Is it a bug or feature? :)

**Comment by jamesmfriedman** [comment]
Wow, alright lots to unpack there

- Tabs go totally rewritten by Google, including the styles. When using the individual component, make sure you include the styles listed at the top of the page. You should be able to just copy paste if you're using CRA.
- I'll fix the docs issue of still talking about TabBarScroller. It is just part of the tabs now by default
- I love the cryptic typescript errors that some people get, and not others. I'll look into those. I personally use it in a a TS project and never encounter these things, but there are so many variations of TS, it's bound to happen.

**Comment by szamanm** [comment]
Ok, so after some local fixes to the package (which won't survive update) and adding styles, few necessary changes, **the issue I was reporting is gone!**. 
I'm still having TS issues mentioned above - If I can be any help, I would say that the biggest, breaking change in my TS setup could be rule no-implicit-any - turning it off "solves" many issues, but, for me, it sort of kills the reason to use TS in the first place. I'm not sure why it's turned off by default, but for sure causes a lot of confusion :(.
But maybe there's more, here's my entire tsconfig.base.json: 
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es7", "dom"],
    "sourceMap": true,
    "allowJs": false,
    "jsx": "react",
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  }
}
```
with TS 2.7.2


Anyway, thanks for your time and for your great work, I hope I didn't bother you too much!

**Comment by jamesmfriedman** [comment]
Not a bother at all. We’re trying to get the Typescript stuff right, it’s just been challenging. 

Are the local changes you’re referring to the typescript ones? I’ll be working on cleaning up be definitions today.

**Comment by szamanm** [comment]
there were some changes in the not-only-ts code, nothing very hard to discover, for example `onChange` is now `onActivate`, and `e.detail.activeTabIndex` is simply `e.detail.index`.

**Comment by jamesmfriedman** [comment]
Try 2.0.2. Massive upgrade to the TS types that should alleviate your issues.

**Comment by jamesmfriedman** [comment]
Closing because I think this is solved. Reopen if you have any issues.
