### ISSUE TITLE
Custom favicon for RMWC

### ISSUE THREAD

**Issue by web2033** [jamesmfriedman/rmwc#306]
Hi!
I would be nice to use a custom favicon instead of one from the official site.

![2018-09-12_103426](https://user-images.githubusercontent.com/11320080/45409457-e0949f00-b677-11e8-9e3c-4295ae12dc8f.jpg)

It will help distinguish them in bookmarks. Thanks!

**Comment by j-o-d-o** [comment]
Good idea. I am no designer, but here we go. It is supposed to be the react icon with the "shade style" of Material Components.

![rmwc_logo](https://user-images.githubusercontent.com/15958535/45430393-8c081880-b6a5-11e8-9b40-806cadca0e32.png)

**Comment by jamesmfriedman** [comment]
Thanks for the feedback, threw this together real quick.

![image](https://user-images.githubusercontent.com/975256/45434144-b2b15980-b67b-11e8-995e-4c9a1360b655.png)

**Comment by jamesmfriedman** [comment]
Correct, it's the Letter R done in the same style as the Material logo
