### ISSUE TITLE
TextField missing fullWidth prop

### ISSUE THREAD

**Issue by gutenye** [jamesmfriedman/rmwc#31]
Material Components Web has a [full-width](https://material.io/components/web/catalog/input-controls/text-fields/#full-width) TextField.

**Comment by jamesmfriedman** [comment]
Thanks, will add in the next release.

Until then, you should be able to add className="mdc-text-field--fullwidth" to the TextField component.

**Comment by gutenye** [comment]
@jamesmfriedman The trick works, thanks a lot.

**Comment by jamesmfriedman** [comment]
Added this in RC7 as well as another missing prop I saw in the docs.
