### ISSUE TITLE
Controlled CheckBox becomes unclickable after programmatic update

### ISSUE THREAD

**Issue by jdeanwaite** [jamesmfriedman/rmwc#312]
When a checkbox's value has been changed programmatically (aka user did not click, but we use `setState` in response to a different UI event), then the checkbox no longer responds to user clicks.

### What RMWC Version are you using?

> 2.1.0 or 2.1.1

### What browser(s) and React Version is this bug affecting?

> Chrome 69.0.3497.92

### What build system are you using?

> Webpack or Create React App

### What are the steps to reproduce the bug?

1. Clone https://github.com/jdeanwaite/rmwc-checkbox-demo
2. `yarn install` and `yarn start` to start the development server
3. Check the boxes, notice changing works well.
4. Uncheck box 1
5. Click the "Change" button to change the state of box 1 to checked
6. Now try and change the checked state of box 1 by clicking on it. Now all further clicks are ignored.

### What is the expected behavior?

> Box 1 should be able to be programmatically set, but still allow for user to change value.

### What is the actual behavior?

> After box 1 is programmatically set, the onChange event no longer fires after being clicked.

### Any other information you believe would be useful?

Interestingly enough, this is not an issue when running on Code Sandbox: https://codesandbox.io/s/zno90x9l94 

Could not find a related issue on MWC

Update: 

Just for additional testing, I swapped the RMWC checkboxes for standard browser `input` checkboxes, and the issue is not reproduced with those.

**Comment by jamesmfriedman** [comment]
Thank you for the repro! I believe the same issue would be in the code sandbox but the dialog is causing the component to re-render.

A workaround for the time being is to use an onClick handler instead of a onChange which seems to work as expected. I'll dig in shortly.

**Comment by jdeanwaite** [comment]
Ah I did not save, I removed the Dialog to match the repo. Actually I first discovered the issue within a dialog on a project that I am working on, so it does not work in dialogs either. I saved the file, so you should be able to refresh that page and get the version without the dialog.

**Comment by jdeanwaite** [comment]
> A workaround for the time being is to use an onClick handler instead of a onChange which seems to work as expected. I'll dig in shortly.

Can confirm that the workaround works. I implemented the same thing using the selected list items found here without issue: https://jamesmfriedman.github.io/rmwc/lists 

@jamesmfriedman, I cannot express enough how impressed/thankful I have been with this repo and your prompt and continued involvement.

**Comment by jamesmfriedman** [comment]
My pleasure. Spread the word, spread the love.

**Comment by jamesmfriedman** [comment]
When in doubt, rewrite the checkbox using the recommended pattern from Google...

Fixes all synchronicity issues and passes all of the previous smoke tests and issues that had come up. Live in 2.1.2.

**Comment by jdeanwaite** [comment]
Awesome!

**Comment by escorponox** [comment]
This is kinda happening again in 3.0.7. After programmatic update 50% of `onChange` events are not fired.

The `onClick` workaround still works, but it has a warning now.

**Comment by jamesmfriedman** [comment]
Thanks for reporting this. Definitely a regression. Since the components are individually packaged I’d recommend downgrading the checkbox back the to the last working version for the moment.

**Comment by escorponox** [comment]
If it helps., `2.2.0` is working pretty well

**Comment by jamesmfriedman** [comment]
This was by far the worst issue I've come across since using MDC and was really hard to find the source of. It ended up being something deep down in MDC that doesn't jive well with React. The previous checkbox didn't exhibit this issue for some complex reasons.

https://github.com/material-components/material-components-web/issues/4018

I've managed to patch the issue in 3.0.8 and we'll see if that open issue has an impact on MDC. The bad news is this bug is highly browser specific and cannot be reproduced as a test case, so manual testing is required to ensure it doesn't pop up again.
