### ISSUE TITLE
ThemeProvider broken when using camelCase options

### ISSUE THREAD

**Issue by tstirrat** [jamesmfriedman/rmwc#313]
### What RMWC Version are you using?

```
"@rmwc/theme@^2.1.0":
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/@rmwc/theme/-/theme-2.1.0.tgz#b3ee50cb16e5cfd1ec169374218dcc716b6e71ac"
  dependencies:
    "@material/theme" "~0.39.0"
    "@rmwc/base" "^2.0.2"
```

### What browser(s) and React Version is this bug affecting?

Chrome Version 69.0.3497.100 (Official Build) (64-bit) (MacOS)

### What build system are you using?

Create React App with TypeScript scripts

### What are the steps to reproduce the bug?

Do anything at all with ThemeProvider:

```ts
import { ThemeProvider } from '@rmwc/theme';
// ...
ReactDOM.render(
  <ThemeProvider
    options={{
      primary: '#303030'
    }}
  >
    <App />
  </ThemeProvider>,
  document.getElementById('root') as HTMLElement
);
```

Throws runtime error:

```ts
TypeError: (0 , _toDashCase.toDashCase) is not a function
(anonymous function)
node_modules/@rmwc/theme/index.js:103
  100 | var processedColors = Object.keys(this.props.options).reduce(function (acc, key) {
  101 |   var val = _this2.props.options[key];
  102 | 
> 103 |   key = key.startsWith('--') ? key : '--mdc-theme-' + (0, _toDashCase.toDashCase)(key);
  104 |   acc[key] = val;
  105 |   return acc;
  106 | }, {});
```

### What is the expected behavior?

ThemeProvider should work

### What is the actual behavior?

App crashes.

### Any other information you believe would be useful?

using `options={{'--mdc-theme-primary': 'red'}}` works

**Comment by jamesmfriedman** [comment]
Definitely going to need some more help isolating this issue.

My first guess its its a dependency chain issue
- Delete your node_modules folder
- Delete package-lock.json
- Reinstall deps

I've put a repro in the code sandbox as well as tested it locally on my machine and am not having the same issues. https://codesandbox.io/s/yvk4n1v2rx

If the above doesn't resolve your issue, please provide a repro-repo.

**Comment by jamesmfriedman** [comment]
I took the time to create a typescript code sandbox as well. Still not seeing the issue.

https://codesandbox.io/s/2xq08lx70r

**Comment by tstirrat** [comment]
Ooops sorry I should have reset all deps beforehand.

I did and it didnt help:

```
$ yarn outdated
yarn outdated v1.6.0
✨  Done in 0.74s.
```

I'll give you a repro thingy in a few moments.

**Comment by jamesmfriedman** [comment]
I super appreciate the repro on this, I wouldn't have caught it otherwise.

Basically, .tsx files in nested directories were accidentally being published alongside of the .d.ts files. this was causing a depencency resolution issues with webpack which was treating it as a media file... 

Pushing 2.1.3 up right now which should resolve your issue. Reopen if it doesn't.

**Comment by tstirrat** [comment]
Thanks, working great now. 🎉

**Comment by jamesmfriedman** [comment]
Woot woot!
