### ISSUE TITLE
[Question] Toolbar tabs

### ISSUE THREAD

**Issue by uiii** [jamesmfriedman/rmwc#316]
Hi, in material design docs there is lot of examples of tabs inside toolbar:
![](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1uV0Rzc2Q2RzWEz9vguOME1SoCQofEmld%2Ftabs-usage-01.png)
How could I achieve this using RMWC? I tried this:
```jsx
<Toolbar>
    <ToolbarRow>
        <ToolbarSection>
            <TabBar>
                <Tab>Cookies</Tab>
                <Tab>Pizza</Tab>
                <Tab>Icecream</Tab>
            </TabBar>
        </ToolbarSection>
    </ToolbarRow>
</Toolbar>
```
The result was:
![toolbar-tabs](https://user-images.githubusercontent.com/179219/45776400-0ced8400-bc53-11e8-99e0-344429a16675.png)
_The first tab is not visible due to being active and of purple color_

Then tried the theme, but it didn't help
```jsx
<Toolbar>
    <ToolbarRow>
        <ToolbarSection>
            <Theme use="onPrimary">
                <TabBar>
                    <Tab>Cookies</Tab>
                    <Tab>Pizza</Tab>
                    <Tab>Icecream</Tab>
                </TabBar>
            </Theme>
        </ToolbarSection>
    </ToolbarRow>
</Toolbar>
```
After a little investigating it looks like a problem on `<button>` boundary (wrapping the tabs) where the button css properties are inherited from the browser rather then the parent element.

Tested in **Chrome 69.0.3497.92**

**Comment by jamesmfriedman** [comment]
You're spot on @uiii. This used to work better with material-components-web but they opted to remove the styles that made this work properly. My personal recommendation is to use custom CSS to apply the appropriate colors. You could also wrap your TabBar in ThemeProvider and set the appropriate colors there. Here is an example in the Code Sandbox. https://codesandbox.io/s/0q4o4y9mql

Also, Toolbar is technically deprecated in favor of TopAppBar but still exists until the TopAppBar functionality can catch up.

This particular issue is out of scope for this library. I would suggest filing it upstream with material-components-web.

**Comment by jamesmfriedman** [comment]
Closing because it's out of scope for RMWC. Please see the the above example.
