### ISSUE TITLE
Ability to use Object properties as Types

### ISSUE THREAD

**Issue by manzu** [jamesmfriedman/rmwc#319]
When exporting Types as objects, property values should actually be separate types, right down so we only have string types.

Like in [Typography](https://github.com/jamesmfriedman/rmwc/blob/master/src/typography/index.js):
```javascript
export type TypographyStyles = 'headline1' | 'headline2' | 'headline3' | 'headline4' | 'headline5' | 'headline6' | 'subtitle1' | 'subtitle2' | 'body1' | 'body2' | 'caption' | 'button' | 'overline';

export type TypographyPropsT = {
  /* prettier-ignore */
  /** The typography style.*/
  use: TypographyStyles
} & SimpleTagPropsT;
```

I personally found a need to import the type of "use" in another component so the existence of TypographyStyles would help.

**Comment by jamesmfriedman** [comment]
That makes sense. I’ll add it to the list.

**Comment by manzu** [comment]
I'm happy to make a PR for this myself.
Anywhere else you have in mind to make such changes?

**Comment by jamesmfriedman** [comment]
Anywhere you think might be relevant. 

On your local machine you can run npm start, browse to the docs, make your changes, and then run npm run docgen to see how it impacts the docs props definitions.

**Comment by jamesmfriedman** [comment]
5.x.x re-implements everything as interfaces and exports all types

**Comment by manzu** [comment]
Thanks, James

**Comment by jamesmfriedman** [comment]
Maybe too soon to close this? I neglected to mention that it was reimplemented in Typescript, not Flow.

**Comment by jamesmfriedman** [comment]
Going to close this out since this is regarding Flow support. If you're still interested in Flow, please thumbs up / comment on #407
