### ISSUE TITLE
Dependencies / build size

### ISSUE THREAD

**Issue by jackjwilliams** [jamesmfriedman/rmwc#32]
I'm trying to optimize my application size, and noticed that my bundle always includes every .js file from @ material. I know rmwc depends on the css from it, but does it really depend on all of the JS files?

![image](https://user-images.githubusercontent.com/1746015/33158544-65190c82-cfd0-11e7-9310-ef31ab8bb129.png)

**Comment by jamesmfriedman** [comment]
How are you importing the code?

This would include the whole lib
```
Import { Button } from ‘rmwc’
```

This should only include the material button code and other imports from Button, let me know if it doesn’t.
```
Import { Button } from ‘rmwc/Button’
```

**Comment by jamesmfriedman** [comment]
@jackjwilliams  did that help at all?

**Comment by jackjwilliams** [comment]
Yes, sorry I thought I responded and closed this!
