### ISSUE TITLE
<Theme wrap> complaining about types in TypeScript (v3)

### ISSUE THREAD

**Issue by tstirrat** [jamesmfriedman/rmwc#320]
### What RMWC Version are you using?

```
"@rmwc/theme@^2.1.3":
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/@rmwc/theme/-/theme-2.1.3.tgz#123eed73e85caaeccf17dd79b8dd2d3d685ba376"
  dependencies:
    "@material/theme" "~0.39.0"
    "@rmwc/base" "^2.1.3"
```

### What build system are you using?

> Create React App + `react-scripts-ts`

### What are the steps to reproduce the bug?

Repo: https://github.com/tstirrat/peerping/compare/rmwc-theme-wrap-repro

### What is the expected behavior?

> `wrap` should accept `true`

### What is the actual behavior?

> TypeScript seems to think it is typed as `undefined`

```
./src/Home.tsx
(27,32): Type 'true' is not assignable to type 'undefined'.
```

**Comment by tstirrat** [comment]
This works for now 🤣:

```jsx
<Theme use="onSecondary" wrap={(true as any) as undefined}>
```

**Comment by jamesmfriedman** [comment]
Wrap as well as tag can cause some weird side effects in TS. I’m working on a new base component that should alleviate some of these issues. For now, good work around 👌

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5, been completely re-written in TS
