### ISSUE TITLE
Do add-ons need to be installed separately? CircularProgress missing from 2.2.2

### ISSUE THREAD

**Issue by danielmahon** [jamesmfriedman/rmwc#322]
Just wanted to check if RMWC Addons are supposed to be installed separately ie `yarn add @rmwc/circular-progress`, as it does not seem to be included in `rmwc@2.2.2`. If so, this should probably be made clearer in the docs (unless I missed it).

**Comment by jamesmfriedman** [comment]
Just an oversight. You can install it individually for the moment. I’ll make sure to get it added to the main rmwc package. 

Small aside, I highly recommend individually installing and updating components. Makes future upgrading significantly easier and you can handle any breaking changes individually.

**Comment by jamesmfriedman** [comment]
Fixed, published 2.2.3. You should see it on npm shortly.

**Comment by danielmahon** [comment]
> Small aside, I highly recommend individually installing and updating components. Makes future upgrading significantly easier and you can handle any breaking changes individually.

Roger that 🙇
