### ISSUE TITLE
Line wrapping problem in MenuItem

### ISSUE THREAD

**Issue by dmsteinberg** [jamesmfriedman/rmwc#324]
RMWC version: 2.2.3
Build system: create-react-app

Steps to reproduce:
1. Go to https://codesandbox.io/s/k09qw8jmv
2. Click the menu icon
3. Notice the line wrapping in the third menu item.

Expected behavior: The menu width fits the longest menu item.
Actual behavior: The third menu item is wrapped and so it overflows the menu.

This is a regression I'm seeing after upgrade from RMWC 1.8.3 to 2.2.3.

**Comment by jamesmfriedman** [comment]
This is actual a regression in MDC web. Recommended fix is to just use your own css and set white-space: nowrap on the list item.

**Comment by dmsteinberg** [comment]
Thanks, @jamesmfriedman! That's really helpful. I searched for an MDC web issue but didn't find one.

Sorry for the bogus report.
