### ISSUE TITLE
How do you implement expanding list items like in the drawer of the documentation site?

### ISSUE THREAD

**Issue by dave-hillier** [jamesmfriedman/rmwc#325]
In the documentation site, in the drawer, there are list items like "Getting Started" which when clicked reveal more items. How do you implement this?

**Comment by dave-hillier** [comment]
Nevermind, I realized I could search for the "getting started" text and I found the documentation site.

The answer is this: https://github.com/jamesmfriedman/rmwc/blob/6906ff384fb67b4b88c377a9eeacfb597db1723c/src/rmwc/docs/Submenu.js

Should this be a standard component?

**Comment by jamesmfriedman** [comment]
Early on, I would’ve said no because I was just wrapping everything from Google, but lately I’ve been adding some RMWC custom components which this is a good fit for. 

Sorry you had to see the docs code, it’s one big hack 😜. I’ll see about implementing a real version of this.
