### ISSUE TITLE
FAB Icon Offset after FAB exited goes from true to false if Dialog is closed

### ISSUE THREAD

**Issue by llapresi** [jamesmfriedman/rmwc#328]
RMWC ver. 2.2.3
[CodeSandbox Link that re-creates issue in in Chrome](https://codesandbox.io/s/n7kjz9ryll)

This is a pretty odd and specific issue but it wasn't happening to me before I updated from 1.8.3 to 2.2.3. I'm filing this as an RMWC bug because I believe it's a scripting issues which should mean the issue is with RMWC and not the MWC JavaScript itself, but I'm not sure.

The CodeSandbox link re-produces an issue where if you press the FAB to bring up the dialog and then press either Dialog's Accept or Cancel buttons, or the Button embedded in the Dialog body, the FAB's icon will have shifted position within the circular FAB shape. This does not happen if you click outside of the dialog to dismiss it, where the icon remains in the correct place.

I initially believe that this happened because of some kind of conflict with how Button ripples work because when using the inspector it seems the FAB icon was being offset due to the ripple element. After testing it with the Button in the Dialog body that has ripples disable, however, I'm not sure of this because the same issue seems to be occurring despite not causing any kind of "ripple conflict" as I theorized.

**Comment by llapresi** [comment]
I did some more testing and I think the main issue is with the .mdc-fab::before and .mdc-fab::after made in mdc-fab.

It seems that when the dialog is closed by the button, they're aligned to the bottom right corner of the FAB instead of being centered. If you toggle the width or height properties on and off, the issue fixes itself and the icon is once again property centered within the FAB.

![offset-before](https://user-images.githubusercontent.com/17561339/46237257-4dcf5200-c351-11e8-840e-e51dfddf5d7d.png)

**Comment by jamesmfriedman** [comment]
This is insanely strange. It could possible be some global styles that are applied. Dialogs just got overhauled with 0.40. Upstream so that might fix it when the next RMWC release happens. Either way I’ll look into it.

**Comment by jamesmfriedman** [comment]
Not even webkit, I tested it in safari just fine. We're down to just a Blink level issue.

**Comment by llapresi** [comment]
Oh boy

**Comment by jamesmfriedman** [comment]
Updated it to 3.0.0, same issue

https://codesandbox.io/s/z2lp9mrmk4

**Comment by llapresi** [comment]
Yeah at this point I'm gonna say that this is probably some Chrome thing.

I'd close this issue simply for being too damn obscure but there's another more obvious issue I'm noticing where the new dialogs in RMWC don't seem to have the slight "zoom-in" animation that the official demos on the MWC website has

https://material-components.github.io/material-components-web-catalog/#/component/dialog (check the examples at the bottom)

Is this a known issue or is that actual animation some other features that isn't part of the dialog system.

**Comment by jamesmfriedman** [comment]
The dialogs in the RMWC docs should have the animation. There is specifically a workaround implemented to make that happen. I checked the sandbox, it appears that occasionally it doesn't fire the first time around. I have a bug report in to MDC about it.
