### ISSUE TITLE
simpleTag blindly accesses global "name" (window.name). Bad for SSR

### ISSUE THREAD

**Issue by ppd1990** [jamesmfriedman/rmwc#33]
# Problem
simpleTag.js references window.name as global variable "name". This fails in node environment, in my case when rendering a static site with react-static

```js
Reflect.defineProperty(SimpleTag, 'name', {
  value: name,
  writable: false
});
```

# Proposed Solution

I'm not quite sure why this property even exists, but in case it is necessary I'd suggest checking for window to be present when accessing name 

```js
if (typeof window !== 'undefined') {
  Reflect.defineProperty(SimpleTag, 'name', {
    value: name,
    writable: false
  });
}
```

**Comment by jamesmfriedman** [comment]
Ah, that was actually a typo I didn’t catch from when I changed name to displaName. I also don’t think I even need that line anymore since I’m setting the displayName property in the class. 

I’ll fix it for the next release.

**Comment by jamesmfriedman** [comment]
Fixed with RC8
