### ISSUE TITLE
Import CSS Without Boilerplate

### ISSUE THREAD

**Issue by mattferrin** [jamesmfriedman/rmwc#330]
I was surprised to find the newest version of RMWC required CSS imports to style my drawer properly. It's cool and this isn't a bug report because I made the assumption it was by design. I like it.

But I find myself doing a lot of this:
```ts
import "@material/floating-label/dist/mdc.floating-label.css";
import "@material/line-ripple/dist/mdc.line-ripple.css";
import "@material/notched-outline/dist/mdc.notched-outline.css";
import "@material/textfield/dist/mdc.textfield.css";
export * from "@rmwc/textfield";
```

It would be nice if there was an alternative way to import the styles by default without needing to create custom files as library wrappers.

Maybe:
```ts
import { Textfield } from "@rmwc/styled/textfield";
```

**Comment by jamesmfriedman** [comment]
It’s not actually a change, I just documented it. Originally the docs said to include he single combined material css file (which still works) but if you care about build size then you’ll want to just import the css you need. 

There are so many ways to style things in React, including distributed CSS from mdc seemed like the right approach and still allows you to override styles in any way that makes sense to you.

**Comment by mattferrin** [comment]
I had a confusing issue with the drawer, but I think it was my environment and unique to me. Went away when I changed techniques. Anyway, please just consider this positive feedback. You can reopen if you decide to support alternative import paths that inject CSS for us.

**Comment by jamesmfriedman** [comment]
It’s not that I don’t want to, I agree it’s a bit annoying. 

Since the css is pre compiled, the only way it can be added is through a link tag in the html or using an import / require statement. The latter requires a build environment that’s setup to import css properly. While I know a lot of people use CRA which does this out of the box, other people have their own css loading solution that might include something like css modules which would cause the styling to fail. 

Do you have any ideas on how this could work otherwise?

**Comment by mattferrin** [comment]
There are many types of users:

1) CSS imports
2) SCSS imports
3) Link to CSS in HTML
4) TypeScript TypeStyle Library
5) Styled components

I'm a 4 and never a 5 (as of yet). I think it's okay to give each kind of user the exports that suit them best, when it's easy to support.

### CSS imports

```js
// .js file
import X from "@rmwc/css/X.css" // easy to support
```

### SCSS imports

```scss
// .scss file
@import "@rmwc/scss/X.scss" // harder to support, but not by much
```

### Link CSS in HTML

```html
<!–– .html file ––>
<!–– easy to support ––>
<link rel="stylesheet" type="text/css" href="@rmwc/css/X.css">
```

### TypeScript TypeStyle Library

```ts
import X from "@rmwc/typestyle/X.ts" // hard to support, I assume
```
### Styled components

I never actually do this so I'll omit my thoughts.

## Main Takeaway

You can probably support multiple environments without much hassle, but not all.
