### ISSUE TITLE
Error on installing rmwc

### ISSUE THREAD

**Issue by arpontes** [jamesmfriedman/rmwc#332]
### What RMWC Version are you using?

> latest

### What build system are you using?

> npm

### What are the steps to reproduce the bug?

In my packages.json file, there is a reference to rmwc: "latest". When I run "npm install", I get the following error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @material/layout-grid@~0.40.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@rmwc/grid'
npm ERR! notarget

I checked MDC's repository, and there is no version 0.40 of layout-grid. Not all packages has been updated to 0.40, and layout-grid is one of those wich isn't.

I also checked rmwc repository and 5 days ago a commit updating several packages to reference version 0.4 of the corresponding mdc's package was made.

**Comment by jamesmfriedman** [comment]
You're faster than I am :). Already put the patch out.

Had to do with inconsistent versioning of the MDC dependencies

**Comment by arpontes** [comment]
:-)
Thanks!
