### ISSUE TITLE
TextField onBlur handler doesn't execute

### ISSUE THREAD

**Issue by cdock1029** [jamesmfriedman/rmwc#334]
### What RMWC Version are you using?

> rmwc@3.0.3

### What build system are you using?

> Create React App

### What are the steps to reproduce the bug?

> Add an onBlur handler to TextField
> Code Sandbox: https://codesandbox.io/s/7kzo9voz1q

### What is the expected behavior?

> It executes on blur

### What is the actual behavior?

> It doesn't

### Any other information you believe would be useful?

> @material/react-text-field example included with code sandbox to show it works with that implementation

**Comment by jamesmfriedman** [comment]
Thank you so much for reporting. Textfields just had a major internal refactor. Oddly enough, I had a bullet point to take care of this exact situation that didn't get addressed before release.

Here is your updated sandbox working as expected.

Cheers
https://codesandbox.io/s/ovjr35mzj5
