### ISSUE TITLE
TextField component has "undefined" class

### ISSUE THREAD

**Issue by nichgalea** [jamesmfriedman/rmwc#335]
## RMWC or MDC?

RMWC

### What RMWC Version are you using?

3.0.4

### What build system are you using?

Typescript

### What are the steps to reproduce the bug?

Simply use the TextField component (this behaviour can also be found in the RMWC demo site).

### What is the expected behavior?

The TextField component should be rendering with all the relevant classes.

### What is the actual behavior?

An "undefined" class is being included in the element's classes.

**Comment by jamesmfriedman** [comment]
Thanks for reporting. Other than. The erroneous undefined, is this causing any other issues at the moment?

**Comment by nichgalea** [comment]
No, other than that, there doesn't seem to be any issue with the component.

**Comment by jamesmfriedman** [comment]
Fixed in 3.0.5
