### ISSUE TITLE
Relation to material-components-web-react

### ISSUE THREAD

**Issue by jgoux** [jamesmfriedman/rmwc#340]
Hello James!

I'd like to know what's your opinion about https://github.com/material-components/material-components-web-react ?

Do you intend to continue working or rmwc once they catch up? Has a merge between the 2 projects been discussed?

Have a nice day! 🌞

**Comment by jamesmfriedman** [comment]
Hi @jgoux, you can see my commentary in the Readme

https://github.com/jamesmfriedman/rmwc/blob/master/README.md#doesnt-google-have-their-own-react-wrapper

I would've loved to merge the projects early on, but they decided to go their own route and start from scratch. I'll be supporting this for the foreseeable future ;)

**Comment by jgoux** [comment]
Awesome! Sorry for the noise I totally missed this paragraph! 😅

**Comment by j-o-d-o** [comment]
The MDC team should put a **"But doesn't RMWC already exist as a React Wrapper?"** in their README ;)
