### ISSUE TITLE
Select not allowing to override global css

### ISSUE THREAD

**Issue by maxipy** [jamesmfriedman/rmwc#341]
## RMWC or MDC?

rmwc. 

## Bugs

Select not allowing to override global css using props className.

### What RMWC Version are you using?

>   "rmwc": "^3.0.3"

### What build system are you using?

> Create React App

### What are the steps to reproduce the bug?

> https://codesandbox.io/s/lk7j5549q

**Comment by jamesmfriedman** [comment]
Hi @maxipy 

Two things, one is a bug in RMWC, and the other is a problem with your code.

- Bug in RMWC: the Style prop should be applied to the root of the component
- Problem with your code: You're trying to use a style as a className.

I'll get the bug fixed today. I've updated the example to use the className to do what you wanted. I just put the style tag inline for convenience, in a real app this css will be located elsewhere likely.

https://codesandbox.io/s/2w9qw71m9j

**Comment by jamesmfriedman** [comment]
Fixed in 3.0.5
