### ISSUE TITLE
Checkbox uncheck animation reappear if component's display is toggled

### ISSUE THREAD

**Issue by lamtranweb** [jamesmfriedman/rmwc#343]
What RMWC Version are you using?
3.0.5

What build system are you using?
Webpack

What are the steps to reproduce the bug?
Something like this:
```html
<div id="foo"><Checkbox /></div>
```
If I click on the Checkbox to check it, then click again to uncheck it, then programmatically set `display: none` on `foo`, then set `display: block` on `foo`, then checkbox's unchecking animation plays again upon `foo` being shown again as a result of `display: block`.

What is the expected behavior?
If parent container's visibility is toggled, no "unchecking animation" plays again... 

This seems to be the class: `mdc-checkbox--anim-checked-unchecked`.  If a checkbox is unchecked, and once the uncheck animation is finished, this class should be removed as opposed to being left behind.

What is the actual behavior?
The checkbox is ultimately unchecked so the state is correct, but the "unchecking animation" plays again each time the parent container's visibility gets toggled.

**Comment by lamtranweb** [comment]
Note, this does not happen in @material/checkbox.

**Comment by jamesmfriedman** [comment]
Thanks for the tip. This is possibly an issue with MDC involving timing of adding and removing classes as it relates to Reacf. There have been other similar issues in the past. Let me dig in and see if I can find the root cause. Any additional information or a code sandbox repro would be very helpful.

**Comment by jamesmfriedman** [comment]
Thanks for reporting. Fixed, will be out in a patch later today.

**Comment by lamtranweb** [comment]
Thank you!
