### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by web2033** [jamesmfriedman/rmwc#344]
Hi!

What about "accordions" (a group of toggles)?
No implementations or guides for them?

**Comment by jamesmfriedman** [comment]
Oddly enough accordions were removed from the material 2 spec and there is nothing on the roadmap for mdc web.  I did like the old ones though, they’d be a fun add on component for RMWC. Are you referring to accordions or expandable menus?

**Comment by web2033** [comment]
I think accordions, they often used for FAQ sections
![accordion-3](https://user-images.githubusercontent.com/11320080/47257093-f759bd00-d491-11e8-9afb-df19fbffac89.png)

**Comment by jamesmfriedman** [comment]
Cool. I’ll see if I can dig up the one out of the old spec and build an implementation.

**Comment by jamesmfriedman** [comment]
Sorry meant to comment not close.

**Comment by jamesmfriedman** [comment]
Happy to report this functionality is coming in 5.x.x under the name collapsible list. It specifically works with the built in list component, but can technically work with any type of content.

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5 with CollapsibleList
