### ISSUE TITLE
Feature Request: Tooltip

### ISSUE THREAD

**Issue by jorgeobsidian** [jamesmfriedman/rmwc#346]
## RMWC

Is there any ETA on implementing the [Tooltip](https://material.io/design/components/tooltips.html) component?

**Comment by j-o-d-o** [comment]
I tried to introduce tooltips to MDC, but it has been a somewhat dragging process. I don't really know what the plan is in MDC, but it I think they prioritize other components for now (it was also removed from Beta milestone).

I think if tooltips are going to happen anytime soon in RMWC, they would need to be implemented as an extension component.

**Comment by jamesmfriedman** [comment]
Happy to do this. 

There are some really great third party tooltip libraries, it’s a solved problem on the technical front. I might just pull one in, wrap it’s interface, and then style it properly to be material compliant.

**Comment by VDinesh** [comment]
Any ETA on this, please?

**Comment by jamesmfriedman** [comment]
Yep, releasing this week.
