### ISSUE TITLE
<Toolbar> with fixed and flexible does not get inline css margin-top applied to <ToolbarFixedAdjust>

### ISSUE THREAD

**Issue by token419** [jamesmfriedman/rmwc#35]
First off, awesome work, I love this package since i found it last night!

I noticed that when using a <Toolbar> with the "fixed" and "flexible" properties that the <ToolbarFixedAdjust> remains at the default margin-top applied by css, but is not being overridden as it should via an inline style from javascript. I'm guessing the functionality was just over looked.

The expected functionality from the material web components can be seen here: https://material-components-web.appspot.com/toolbar/waterfall-flexible-toolbar.html

If you inspect their source, you can see they have added the following to achieve the effect (I omitted the non relevant parts):
```
function init() {
    var toolbar = mdc.toolbar.MDCToolbar.attachTo(document.querySelector('.mdc-toolbar'));
    toolbar.fixedAdjustElement = document.querySelector('.mdc-toolbar-fixed-adjust');
}
```

Code to reproduce via these components (you will not be able to see the paragraph tag because the margin is only 1 row, and not the default 4 rows from mdc-toolbar--flexible-default-behavior):
```
<Toolbar fixed="True" flexible="True" class="mdc-toolbar--flexible-default-behavior">
    <ToolbarRow>
        <ToolbarSection alignStart>
            <ToolbarMenuIcon use="menu"/>
            <ToolbarTitle>Title</ToolbarTitle>
        </ToolbarSection>
    </ToolbarRow>
</Toolbar>
<main>
    <ToolbarFixedAdjust></ToolbarFixedAdjust>
    <p>This will be unreadable</p>
</main>
```

I was able to resolve this by adding the following missing lines to the "Toolbar" "onUpdate" function:
```
var toolbarquery = _mdc.MDCToolbar.attachTo(document.querySelector('.mdc-toolbar'));
toolbarquery.fixedAdjustElement = document.querySelector('.mdc-toolbar-fixed-adjust');
```
I also verified that the correct behavior takes place when using the CSS override via ID like so:
```
#my-flexible-header {
    --mdc-toolbar-ratio-to-extend-flexible: 8;
}
```
If you add that ID to the toolbar, you will notice, the content now expands the full 8 rows instead of the default 4. I also tested with various other toolbar setups, including with no flags and saw no regression from the change.

I'd be happy to submit a pull request if you would like. As far as i can tell, this does not break any other toolbars, but please QA as necessary.

**Comment by jamesmfriedman** [comment]
Thanks for the detail on this! A PR would be great. Traveling today but I should have time to check it out tomorrow.

**Comment by token419** [comment]
For sure, I'll put one together :)

**Comment by token419** [comment]
I'm having a little bit of trouble getting it to work from the github sources since i'm not setup for typescript. I can't seem to figure out how to build it to strip out the typescript stuff like i see in npm. I may have to defer over to you. I have a local version with it working, so no rush here :)

**Comment by jamesmfriedman** [comment]
It’s actually Flow, not typescript. The NPM es5 version gets built during release, so you don’t need to worry about that.

James Friedman. UX / UI Design & Development Consulting
(407) 801-2922 | me@jamesmfriedman.com <mailto:me@jamesmfriedman.com> |
@jamesmfriedman | https://jamesmfriedman.com

**Comment by token419** [comment]
Created pull request #37 to address this issue. I was unable to test it as i couldn't get it to build without the typescript settings, but it SHOULD work :p

**Comment by token419** [comment]
Closed out #37. Thanks for your feedback! I'm going to still continue to check out/play with flow though since I've actually checked out some stuff on typescript/flow but never used them in practice, same with jest as well :)

**Comment by jamesmfriedman** [comment]
@token419, just posted a commit. Same approach you were taking, but is a React safe way to get the DOM element.

As soon as I post the next release (should be in a few minutes) Just place the ToolbarFixedAdjust element directly after your Toolbar and you should be good to go.

Also, Toolbars with MDC are tricky since you can't cleanly change between something like flexible and not flexible. Not sure if anyone would ever need to do that, but I fixed some issues to make sure that the toolbar responds appropriately to changes in its props.

**Comment by token419** [comment]
Just updated and tested and everything is working as it should. Thanks again for the quick fix :)

**Comment by jamesmfriedman** [comment]
No prob, I love getting community feedback and making this thing more robust. Let me know if anything else comes up.
