### ISSUE TITLE
Select: updating options will not float the label

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#350]
RMWC 3.0.7

If you render an outlined `Select` with an empty `options` prop and re-render with the options set, the label will not float. We come across this when rendering a select while the options are being loaded asynchronously via an API call.

Example here: https://codesandbox.io/s/w22ly7nr07

I have hacked in a workaround but it's not very pleasant: I have to cal `handleFocus_` on the RMWC component instance to ensure that the label floats and the outlined notch opens.

The sample code:

```js
import React from "react";
import ReactDOM from "react-dom";
import { Select } from "@rmwc/select";
import { Button } from "@rmwc/button";
import "@material/select/dist/mdc.select.css";
import "@material/floating-label/dist/mdc.floating-label.css";
import "@material/notched-outline/dist/mdc.notched-outline.css";
import "@material/line-ripple/dist/mdc.line-ripple.css";
import "@material/button/dist/mdc.button.css";

class App extends React.Component {
  state = { options: [] };
  ref = React.createRef();

  componentDidUpdate(_, prevState) {
    if (prevState.options.length === 0 && this.state.options.length > 0) {
      // Float the label
      this.ref.current.handleFocus_();
    }
  }

  render() {
    const style = { width: "100%", marginBottom: "1rem" };
    return (
      <>
        <Select
          style={style}
          outlined
          label="Options"
          options={this.state.options}
        />

        <Select
          style={style}
          outlined
          label="Options"
          options={this.state.options}
          ref={this.ref}
        />

        <Button
          onClick={() => {
            this.setState({ options: ["Apples", "Oranges"] });
          }}
        >
          Update options
        </Button>
      </>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by jamesmfriedman** [comment]
Much simpler work around for now, just give the select a key that changes whether or not the select is empty. Which should cause  a re-render and fix the issue.

**Comment by robcaldecottvelo** [comment]
Oh that's a beautiful idea. Thank you! And thanks again for RMWC: it really is the best Material Design library for React. All your hard work is hugely appreciated.

**Comment by jamesmfriedman** [comment]
No problem, spread the word ;)

**Comment by jamesmfriedman** [comment]
Fixed this particular issue. The Select is due for a rewrite so in the near future it should be more performant and have less edge cases like this, but for the time being, scotch tape is in place. Will put out 3.0.9 as soon as the tests pass.
