### ISSUE TITLE
Documentation missing for TextFieldHelperText

### ISSUE THREAD

**Issue by ingesy** [jamesmfriedman/rmwc#352]
It seems to have disappeared in commit 2eff658cd2ad0ea0bb1fa4d20e52c6a3e6b2ccb2

**Comment by tlxtellef** [comment]
The example on [https://jamesmfriedman.github.io/rmwc/text-fields](https://jamesmfriedman.github.io/rmwc/text-fields) contains this:
`{/* You can optionally make HelperText always visible with the persistent prop. */}
<TextFieldHelperText persistent validationMsg>The field is required.</TextFieldHelperText>`

Yet the documentation for `TextFieldHelperText` has no content explaining `persistent`, `validationMsg` or any other properties `TextFieldHelperText` has. Not even a simple description of the element and its uses.

**Comment by jamesmfriedman** [comment]
I know, just hasn't been deployed yet
