### ISSUE TITLE
Create React App 2 Fork for MDC Web/RMWC

### ISSUE THREAD

**Issue by robcaldecott** [jamesmfriedman/rmwc#353]
Not an issue per-se but using MDC Web SASS in a `create-react-app` project doesn't work because you need to configure the SASS loader to include `node_modules` in order for all the MDC SASS `@import` statements to work, and CRA does not allow this.

So I forked CRA 2.0.5 and will keep it in sync with the official release. You can use the fork via the `--scripts-version` CLI switch:

```bash
yarn create react-app my-app --scripts-version mdc-react-scripts
```

There is a sample project here that uses RMWC and the MDC SASS:

https://github.com/robcaldecott/rmwc-sample

You can use CSS modules too. Note that you need to add `node-sass` as a project dependency.

I hope someone finds this useful.

**Comment by jamesmfriedman** [comment]
Another option @robcaldecott which is a little less manual is to use react-app-rewired to simply patch the CRA app config. I've successfully done this in many many production projects. Just requires a little bit of JS fiddling to inject the rule into the right place.

**Comment by robcaldecott** [comment]
Yep, that also works (we're using it at work) but it doesn't support CRA2 yet and the author doesn't have time to work on it (although I think someone else might pick it up.)

**Comment by jgoux** [comment]
@robcaldecott I use react-app-rewired for CRA2 with https://github.com/arackaf/customize-cra and it works great!

**Comment by jamesmfriedman** [comment]
Yeah @jgoux same ^. Haven't had a single issue with CRA 2 and react-app-rewired.

**Comment by j-o-d-o** [comment]
I usually just use node-sass with npm-run-all along side the react-scripts like this:

```
    "build-css": "node-sass --include-path src --include-path node_modules src/index.scss public/bundle.css --output-style compressed --source-map false",
    "watch-css": "npm run build-css && node-sass --include-path src --include-path node_modules src/index.scss public/bundle.css -w -r --source-map true",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
```

For sure not as graceful, but it does the job ; )

**Comment by garth** [comment]
You can also use the environment variable `SASS_PATH=./node_modules`

**Comment by jamesmfriedman** [comment]
@robcaldecott thanks for posting this. I'm going to close this since it's not an issue, but it will still be in the archives for people to find.
