### ISSUE TITLE
Remove the ripple effect from the switch

### ISSUE THREAD

**Issue by lynk** [jamesmfriedman/rmwc#356]
Hi there,

is there any way to remove the ripple effect from the switch?

Thank you

**Comment by jamesmfriedman** [comment]
Undocumented on the props list but you can use ripple={false}. Is there a reason you wanted it disabled? It would be easy to add a global ripple option to disable everything if you are trying to go ripple free.

**Comment by jamesmfriedman** [comment]
Ironically, the Switch didn't have the ripple effect to begin with. What you were seeing was just the focus circle.

The easiest way to remove the ripple effect would be to select the component using some CSS rules and hide the focus effect.

**Comment by lynk** [comment]
Hi James,

thank you for looking into this. I am on another project right now but will try the removal by CSS.

**Comment by jamesmfriedman** [comment]
5.x.x gives you the ability to globally disable ripples

**Comment by jamesmfriedman** [comment]
Ripples have been refactored in V5. You can disable ripples globally now using the ThemeProvider
