### ISSUE TITLE
Slider - Uncaught Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by oste** [jamesmfriedman/rmwc#358]
## RMWC or MDC?

RMWC

### What RMWC Version are you using?

3.0.7 and 3.0.9

### What build system are you using?

Create React App

### What are the steps to reproduce the bug?

Click the Slider bar. This **cannot** be reproduced when clicking the circular part of the slider

### What is the expected behavior?

no error thrown

### What is the actual behavior?

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### Any other information you believe would be useful?

It does not occur in version 2. Sorry, not too sure what is causing this, hopefully it can be easily reproducible.

**Comment by oste** [comment]
Nice yeah, noticed they are using the foundation now. I will try to provide more details. They do seem find in the docs so yeah must be something more specific.

**Comment by jamesmfriedman** [comment]
Did you ever find out what was causing this?

**Comment by jamesmfriedman** [comment]
@oste doing updates for 41 so would be a good time to try to track down the issue if there was one.

**Comment by oste** [comment]
Sorry, putting efforts into other things at the moment. Not sure when I can get back to this. You can close it for now if you like. V2 is working ok for us at the moment.

Thanks

**Comment by jamesmfriedman** [comment]
Cool, reopen with a repro if you find the issue.

**Comment by PawnStar** [comment]
I ran into this error today with 5.6.0, and I think I've reproduced it here: https://codesandbox.io/s/rmwc-sandbox-tvl6i

**Comment by jamesmfriedman** [comment]
Thanks, I’ll take a look

**Comment by jamesmfriedman** [comment]
Safely setting the value within the min and max values now and throwing a warning. Will go out in the next release.

**Comment by jamesmfriedman** [comment]
Released with 5.7.0
