### ISSUE TITLE
Switch with a dynamic label always renders as off

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#361]
Well this is weird. If you have a `Switch` that has a label with **content that changes based on the Switch checked state** then the component always renders as "off" even though the internal state of the underlying `input` looks correct.

https://codesandbox.io/s/l79j15vxq7

Try toggling the first switch on!

I guess the dynamic label is causing a remount or something?

RMWC 3.0.9

**Comment by jamesmfriedman** [comment]
Need to look into it but this might be a similar problem to a recent checkbox issue that was buried deep down in MDC where native getters and setters were being patched causing issues with Reacts render cycle for controlled components. Thank you for reporting.

**Comment by robcaldecottvelo** [comment]
This fixes it for now (could also use a key but that seems to cause ripple issues.)

```js
class VeloSwitch extends React.Component {
  switch = React.createRef();

  componentDidUpdate(prevProps) {
    if (prevProps.label !== this.props.label) {
      // Update checked state if the label changes
      this.switch.current.foundation_.setChecked(this.props.checked);
    }
  }

  render() {
    return (
      <Switch ref={this.switch} {..this.props} />
    );
  }
}
```

**Comment by jamesmfriedman** [comment]
You definitely get the reward for finding the strangest bugs with the strangest workarounds! Thanks for always digging in and the repros, helps a bunch and the library is getting more resilient with every point release.

**Comment by robcaldecottvelo** [comment]
We do push it quite hard. I'm going to make time to contribute back.

**Comment by jamesmfriedman** [comment]
Been slowly rewriting things to the recommended adapter / foundation pattern (which is why you've been seeing some of these bugs resurface). This one was low hanging fruit so I went ahead and converted it over and added a test for the issue to prevent a regression. Will be released in a bit.
