### ISSUE TITLE
TextField: changing value programmatically not floating the label

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#362]
Oops.

https://codesandbox.io/s/1yx9nvmwoj

RMWC 3.0.9

Did the recent `required` fix introduce this I wonder? Feels a bit like whack-a-mole.

**Comment by jamesmfriedman** [comment]
Duplicate of #338

**Comment by jamesmfriedman** [comment]
Fixed and added a new test to prevent another regression. Look for the patch later today.
