### ISSUE TITLE
Do not override canvas in test polyfill if already present

### ISSUE THREAD

**Issue by bartvde** [jamesmfriedman/rmwc#366]
Would it be possible to publish the jest polyfill for rmwc testing either as a separate package or included in the current rmwc package? That will make unit testing easier for people using RMWC and not needing to copy the polyfill.

https://raw.githubusercontent.com/jamesmfriedman/rmwc/master/src/base/testPolyfill.js

TIA

**Comment by jamesmfriedman** [comment]
Hi @bartvde.

Could you be a bit more specific? It is actually published with all releases of RMWC under @rmwc/base/testPolyfill. Are you having trouble importing it or am I misunderstanding?

There are directions to set it up in the installation guide https://jamesmfriedman.github.io/rmwc/installation

**Comment by bartvde** [comment]
Ah you're totally right, I had missed that part

**Comment by bartvde** [comment]
So it seems the canvas polyfill part clobbers the canvas polyfill that we already load in jest with the canvas npm package, would a patch that checks for canvas bindings be acceptable for rmwc, i.e something like:

```
    if (!window['HTMLCanvasElement']) {
      Object.defineProperty(window['HTMLCanvasElement'].prototype, 'getContext', {
        writable: true,
        value: () => ({
          font: '',
          measureText: () => ({ width: 0 })
        })
      });
    }
```

**Comment by bartvde** [comment]
no it seems that influences the snapshot outcomes, so I guess that is not an acceptable way to fix my issue

**Comment by jamesmfriedman** [comment]
Absolutely! If  you have t
