### ISSUE TITLE
Unknown event handler onPointerDown on Slider component (add known issue to docs)

### ISSUE THREAD

**Issue by Skim-chee** [jamesmfriedman/rmwc#367]
## RMWC or MDC?

> RMWC

### What RMWC Version are you using?

> 3.0.9

### What build system are you using?

> Webpack
> Using Google Chrome: Version 70.0.3538.102 (Official Build) (64-bit) but seeing on latest Safari and Firefox Quantum
> On React 16.2.0

### What are the steps to reproduce the bug?

We were using rmwc version 1.9.3 before upgrading recently to v3.0.9 and started receiving this error
https://i.gyazo.com/e429ebd7f53e4838c4aafd437cb46719.png

I tried multiple things including stripping away all coding logic besides just having the vanilla Slider component by itself with nothing else in the react component but still received the error everytime the component mounted. Also tried importing from '@rmwc/slider' instead of 'rmwc/Slider' if that would have made a difference. Another tricky thing is I couldn't recreate the issue in code sandbox, the one below is a pretty close approximation of how we use the component as a whole in our application. 
https://codesandbox.io/s/941979nkoo

### What is the expected behavior?

Shouldn't have unknown event handler log on `onPointerDown` being fired

### Any other information you believe would be useful?

Doesn't seem to be breaking anything functionality wise, just curious if its something on our end thats making the error pop up. It seems to be related to the new foundation component refactor (saw the onPointerDown being used in events-map for the foundation components). Thanks!

**Comment by jamesmfriedman** [comment]
This is an unfortunate side effect of using the MDC stuff under the hood.

RMWC just honors the event names that are passed. In this case, the new pointer events api is being used which requires react 16.4. Any version of React prior tot that will report the unknown prop issue. 

This library has supported 15.x releases since the beginning but that is becoming more and more challenging with nuances like this.

**Comment by Skim-chee** [comment]
Ah that makes sense, it's definitely a challenge especially with all the new architecture and api changes coming into React! Thanks for the quick response, will relay that to the rest of my team. Upgrading react was in our pipeline so good to know this was related! 

Do you think possibly adding this to the "Known Issues" section on the RMWC website or elsewhere might help? The upgrade path to the latest React isn't the easiest because of all the lifecycle changes etc so might help a few people still on older versions out. 

Thank you so much for the help and for this great package :)!

**Comment by jamesmfriedman** [comment]
No prob. I do have a known issues section, I just didn't know about this one :). I'll leave this open and make sure to add it. In reality, this is a React bug, not an MDC bug so I'll change the label on it.
