### ISSUE TITLE
Simplify the issue template

### ISSUE THREAD

**Issue by garth** [jamesmfriedman/rmwc#371]
The template below is way too much. Please consider to reduce it to the headers and allow users to simply fill in the blanks?

** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC is a React wrapper for Google's official MDC that provides a props based interface for their components. Is the bug being caused by RMWC, or MDC? Please do your best to track down where the bug is originating from and post your issue to the proper repository. MDC bugs should be filed here https://github.com/material-components/material-components-web/issues.

## Bugs

Follow the template below to ensure the quickest and most accurate response to your issue.

### What RMWC Version are you using?

> Please be specific, e.g. _major.minor.patch_

### What build system are you using?

> Webpack, Create React App, Browserify, SystemJS, None, etc. Also mention if you are using Typescript or Flow.

### What are the steps to reproduce the bug?

> Please write the steps which need to be taken in order to reproduce the bug. These steps should be
> as detailed as possible. PLEASE use the Code Sandbox 
> to reproduce the bug which will allow a quicker resolution to your issue.
> - Javascript Sandbox https://codesandbox.io/s/kpy13vqnr
> - Typescript Sandbox https://codesandbox.io/s/kl0w4xp95

### What is the expected behavior?

> Please describe what the component/code should be doing that it's not.

### What is the actual behavior?

> Please describe what the component/code is actually doing that's different from what it should be
doing.

**Comment by jamesmfriedman** [comment]
Done and done
