### ISSUE TITLE
How to use select with MenuItems (or ListItems)?

### ISSUE THREAD

**Issue by doasync** [jamesmfriedman/rmwc#373]
I want to use Select Menu, but instead of native options I want `MenuItems` or maybe `ListItems`. They are called enhanced menus here: https://material-components.github.io/material-components-web-catalog/#/component/select

How can I do this?

![screenshot from 2018-11-23 03-12-09](https://user-images.githubusercontent.com/29141708/48924841-a93f3b80-eecd-11e8-8461-82a828f34e7d.png)

**Comment by jamesmfriedman** [comment]
This is actually coming with the next release but there is a bug with MDC preventing me from releasing. As soon as that bug is patched the next release with the enhanced select will be available.

**Comment by jamesmfriedman** [comment]
Released enhanced select with 4.0.0

**Comment by doasync** [comment]
Thanks
