### ISSUE TITLE
TypeScript error of 'prop-types'

### ISSUE THREAD

**Issue by foisonocean** [jamesmfriedman/rmwc#375]
Here is the error:

```
node_modules/@rmwc/base/index.d.ts:3:10 - error TS2305: Module '"/node_modules/@types/prop-types/index"' has no exported member 'default'.

3 export { default as PropTypes } from 'prop-types';
           ~~~~~~~
```

**Comment by foisonocean** [comment]
I think change `export { default as PropTypes } from 'prop-types';` to the below can fix this problem:

```typescript
import * as PropTypes from 'prop-types';
export { PropTypes };
```

**Comment by jamesmfriedman** [comment]
Thanks for reporting, will put out a patch today

**Comment by jamesmfriedman** [comment]
Apparently `export {* as PropTypes} from 'prop-types'` is considered experimental syntax? Anyways, implemented your fix, appears to have resolved the issue. Thanks again for reporting, will be live on NPM shortly as 4.0.1.
