### ISSUE TITLE
TypeError: Unable to get property 'some' of undefined or null reference

### ISSUE THREAD

**Issue by achal3** [jamesmfriedman/rmwc#38]
After following the steps 1) Git clone (2) npm install (3) npm start
I got following error

TypeError: Unable to get property 'some' of undefined or null reference
api.foundation_.componentClickHandler_
D:/..../rmwc/src/Base/withMDCDrawer.js:61
  58 | const path = evt.composedPath ?
  59 |   evt.composedPath() :
  60 |   evt.deepPath || evt.path;
> 61 | const drawerClickedWasClicked = path.some(
  62 |   el =>
  63 |     el.classList &&
  64 |     el.classList.contains('mdc-temporary-drawer__drawer')

**Comment by jamesmfriedman** [comment]
What browser are you using?

**Comment by jamesmfriedman** [comment]
Thanks for reporting. Should be fixed with 8063b492d3bce9d1d17c1654968f5323d9cd46f6
