### ISSUE TITLE
A word of thank you

### ISSUE THREAD

**Issue by jordyvandomselaar** [jamesmfriedman/rmwc#384]
Hey James,

This not a bug or feature request, this is a thank you. The components in this library are among the easiest I've ever used and so far everything works amazingly well.

Happy new year!

**Comment by jamesmfriedman** [comment]
Thanks for the kind words @jordyvandomselaar! Feel free to post in #277 with what you're working on, and keep spreading the word. It's gonna be a big year for RMWC, excited about whats coming down the pipe.
