### ISSUE TITLE
NotchedOutline example

### ISSUE THREAD

**Issue by gmosx** [jamesmfriedman/rmwc#385]
I would like to use the 'notched outline' style from Material.io

https://material.io/develop/web/components/input-controls/notched-outline/

I am wondering if there is any example showing how to achieve this style using RMWC.

Thanks (also for the useful project!)

**Comment by jamesmfriedman** [comment]
https://jamesmfriedman.github.io/rmwc/text-fields

Yep, right at the top of the text field docs under 'variants'. It's just a prop called `outlined`

**Comment by gmosx** [comment]
Thank you!
