### ISSUE TITLE
Select field not working with keyboard

### ISSUE THREAD

**Issue by anoukinsyde** [jamesmfriedman/rmwc#386]
What RMWC Version are you using [major.minor.patch]:
4.0.0, but isn't working in the demo's either (4.0.3)
https://jamesmfriedman.github.io/rmwc/select-menus

Name your build system [Webpack, Rollup...]:
Webpack

Describe the bug with as much detail as possible:
When trying to select an option in a select menu with a keyboard, the default behavior is disabled. 

Expected behavior:
When focused on the select menu, I can select the options with up and down arrows.

What really happens: 
Pressing up and down arrows does nothing. I can switch with left and right arrows though, but even as a seeing user this took me a long time to figure out (as this is not default behavior). For accessibility, this is a major issue.

**Comment by jamesmfriedman** [comment]
Select menus now have an enhanced Variant that uses a non native menu. Is this issue using the enhanced or native version of the select?

**Comment by Buffy2ndSlayer** [comment]
I am aware that the enhanced version does work with keyboard, however that control is nonstandard. For accessibility it is important that the native control works as expected. The native version of the select doesn't work with up and down key arrows.

**Comment by jesnil01** [comment]
Just noticed this as well. Navigating between the inputs works fine, but I can't change the option. 

Try to navigate between the selects only using the keyboard and try to select options in in this demo:
https://jamesmfriedman.github.io/rmwc/select-menus

And then try this, here it works:
https://material-components.github.io/material-components-web-catalog/#/component/select

**Comment by jamesmfriedman** [comment]
Fixed with the release of V5
