### ISSUE TITLE
Use a combination of value and label as key in select option

### ISSUE THREAD

**Issue by jesnil01** [jamesmfriedman/rmwc#387]
## Issue

This is an issue that my team has faced for a while now. 

Long story short: We have select options that have the same label but different values. I agree this is not really good practice but these labels are created by the user and therefor this could happen. 

As *@rmwc/select* uses label as key in `<option key={label}>` this will give us a react error of duplicate keys.

Link to line of code:
https://github.com/jamesmfriedman/rmwc/blob/master/src/select/index.js#L145

## Sandbox:
https://codesandbox.io/s/3xz5mvyo41

We're using `@rmwc/select@4.0.1`.

## Suggested solution
Use a combination of *value* and *label* as key. 

#### Change
`<option key={label} {...option} value={option.value}>`

#### To
```<option key={`${value}-${label}`} {...option} value={option.value}>```

There is a couple of more places we probably then should update as well. What do you think?  😃

**Comment by jamesmfriedman** [comment]
I think that is a totally valid fix for a total valid problem. Do you want to do a PR for this? If not I’ll see if I can get it fixed today.

**Comment by jesnil01** [comment]
I can make a PR.
