### ISSUE TITLE
Question: TypeScript & Flow status

### ISSUE THREAD

**Issue by jasonkylefrank** [jamesmfriedman/rmwc#391]
I noticed in your 2019 Roadmap that your goal is to convert all components from Flow to TypeScript.  But it also looks like you have already converted some things to TypeScript?  I'm pretty new to TypeScript and Flow, so I can't tell if some things I'm seeing are TypeScript or Flow constructs.  

The reason I'm asking is that our team is considering using this library but one of their questions was whether or not we'd need to learn Flow (in addition to TypeScript) in order to read this code.  And that's where I got stuck because to my eye quite a few things look like they are already in TypeScript, but I also see at least a few things that mention Flow.  Can you clarify please?

**Comment by jamesmfriedman** [comment]
Hi @jasonkylefrank!

Currently the entire codebase is written in Flow. During the build process, the Flow types are converted directly to typescript, and definition files are generated. As of right now, you can use this project with Typescript. There are a few places that require some workaround, but for the most part it works as billed.

The crazy thing is really how it works. Flow and Typescript are so semantically similar, the codebase has been typed in a way that is compatible with both and relies on some global find and replace to make it Typescript compatible.

There are some exception to this rule in a handful of places where Typescript types are used in the actual source which would break flow, except there are comments to tell flow to explicitly ignore them.

The reason this library is getting converted over to Typescript are as follows
- Typescript types are much richer in React than flow. For instance TS has React.HTMLProps and React.IntinsicAttributes while Flow just infers everything.
- Right now The flow types are relatively dumb, and they're being "upsampled" for lack of a better term to Typescript.  Going from TS to Flow will result in much stronger typing all the way around.
- material-components-web is getting converted to Typescript which will allow for a much tighter integration
- TS vs Flow is about 90% / 10%. So I'd rather support the 90% first class.
- I just started on this today, expect it within a week or so.

**Comment by jasonkylefrank** [comment]
@jamesmfriedman Thanks for your thorough response!  Your explanation helped a lot since I was not able to discern that most of what you currently have is actually Flow stuff!

**Comment by jamesmfriedman** [comment]
No problem. Glad you're considering it, I know it has served myself and others well so far. Let me know if I can be of any other assistance, and feel free to ping me on Discord.
