### ISSUE TITLE
List with Menu: MenuItem is overlapped by other ListItem

### ISSUE THREAD

**Issue by nguyenkevtran** [jamesmfriedman/rmwc#396]
- What RMWC Version are you using: 4.0.6

- Name your build system: Webpack

- Describe the bug with as much detail as possible: 
I'm trying to build a selectable list which also support an action menu for each list item. I'm able to reproduce the bug in this codesandbox: https://codesandbox.io/s/oovqym05k5. As you can see, when clicking the button to open the menu, the second MenuItem is missing because it is overlapped by the below ListItem.

- What happened, and what was supposed to happen:
The Menu should float above all other elements.

**Comment by jamesmfriedman** [comment]
A bit of a hack right now, but definitely works. I've run into this in my own usage and have the same issues.

https://codesandbox.io/s/2xk4353opr

A few finer points on this
- material-components-web has a concept of "hoisting" to the body to work around this
- Unfortunately, once that happens in React land, React can no longer control the element, breaking your render cycles
- The solution is for RMWC to use React.Portal internally, but this wasn't a viable option until the recent decision to drop 15.x support
- A permanent fix for this will be addressed in a 5.x version, I'll leave this ticket open until then with the workaround.

**Comment by nguyenkevtran** [comment]
What is the estimated version with a permanent fix for this? I noticed v5.1 is out now, but this issue is still not resolved.

Also, I encounter another problem using your workaround. You can see it here: [https://codesandbox.io/s/yww0zkn6wj](https://codesandbox.io/s/yww0zkn6wj) by opening menu of _the last item in list_, which is contained within a limited height.
I see there is a `hoistMenuToBody()` method in the `MenuSurface`, can it be used somehow to tackle this problem?

**Comment by jamesmfriedman** [comment]
Yes that is ultimately part of the solution, but since we are in react, using the hoisting functionality will cause react to lose track of the dom element in its render tree. Ultimately the solution to this will involve using a react portal. 

This hasn’t been forgotten. 5.x included an insane amount of work, this will be prioritized with any new work. 

Even with the above described issue, CSS can still be used to hack around this particular issue.

**Comment by jamesmfriedman** [comment]
Available in the 5.2.0-alpha.0. Added a `hoistToBody` prop.
