### ISSUE TITLE
Implement RTL on applicable components

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#4]

**Comment by DragosRotaru** [comment]
@jamesmfriedman Want help with this?

**Comment by jamesmfriedman** [comment]
Help would be awesome!

Last time I looked through the docs, it seemed like a lot of it was just dependent on the attribute dir=“rtl”. I’m sure there are cases where it is a bi more complicated than that. 

I’ll look at the docs but I good place to start might just be identifying the requirements of each component to be RTL.

**Comment by jamesmfriedman** [comment]
turns out it literally is just adding dir="rtl" on whatever you need to... 🥇

**Comment by DragosRotaru** [comment]
Ahahaha I promise I was just about to start work on it lol. Thank you!!

**Comment by jamesmfriedman** [comment]
haha, no worries. You could've told me it took you hours and I would've believed you.
