### ISSUE TITLE
Support Flow Types

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#407]
5.x.x has been converted to Typescript. If you're interested in helping restoring flow typed support, please comment here.

**Comment by eleith** [comment]
i'm interested. what is your current preference? libdefs decoupled and submitted to flow-typed or a more coupled approach internal to this project?

**Comment by jamesmfriedman** [comment]
Absolutely coupled to the project. If they can’t be automatically generated then there is little hope of them ever being accurate. My hope is that there can be a build step that can generate them from the typescript definitions.

**Comment by eleith** [comment]
any preference on libraries to use to generate them?

found a few options, this seems mature enough to try: https://github.com/joarwilk/flowgen

a build step feels like a good place to put this process. the script will likely need to do more than just run the converter as there are likely a number of assumptions ts makes that flow does or visa versa, so some knowledge will be needed in writing more manual transformations. unclear though without actually trying to run it.

thoughts? 

i can do a quick run of this and see how it looks in my project to see where it blows up?

**Comment by jamesmfriedman** [comment]
Oh to be clear I tried to crack this nut using that tool plus some home rolled code and was not successful (although I think I got relatively close). Give it a go, maybe you can figure something out that I couldn't.

**Comment by eleith** [comment]
nice. any points / pain points you could roll into a sentence or two? i'ld be happy to look into this, it would provide me a lot of value. rmwc is a pleasure to use and would love to also have it provide my type safety in my code base too =]

**Comment by jamesmfriedman** [comment]
Going to close out this issue. If anyone ever wants to take it one, feel free to reopen. But haven't heard the word flow in 6 months. It's marketshare is tanking while Typescripts is skyrocketing.
