### ISSUE TITLE
Invalid types in package.json

### ISSUE THREAD

**Issue by UFOMelkor** [jamesmfriedman/rmwc#414]
First: Thank you, James, for the hard work and time you are investing in this library. It makes using the Material Design Components really, really easy for me :+1: 

Today I did an upgrade to the newest version to try the new typescript types. Unfortunately there may be a small bug when using this library with typescript.

> What RMWC Version are you using [major.minor.patch]:

`5.1.4`

> Name your build system [Webpack, Rollup...]:

Webpack 4 with Typescript

> Describe the bug with as much detail as possible.
> What happened, and what was supposed to happen.

I noticed that since the upgrade I got no more autocompletion.

Looking into each package.json, it seems to me like the `types` entry is wrong.
Following the [TypeScript Docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) I changed `"types": "dist/index.js",` to `"types": "dist/index.d.ts",` in each package.json got full autocompletion.

This works for me locally; I'm not sure whether some scripts or anything else also need to be touched.

**Comment by jamesmfriedman** [comment]
Thanks for reporting I’ll get this fixed ASAP. 

What IDE are you using? I never caught this because VSCode appears to use another method of picking up types and works just fine.

**Comment by jamesmfriedman** [comment]
Fixed in 5.1.5

**Comment by UFOMelkor** [comment]
I'm using PhpStorm by Jetbrains.
Thank you for your fast fix. Unfortunately it seems like something went wrong.

`types` now correctly points to `dist/index.d.ts`, but the complete dist-folder is not available anymore.

You can verify the issue when looking at an upgraded version of the [TypeScript CodeSandbox](https://codesandbox.io/s/xl3yyo1llq) and the [JavaScript CodeSandbox](https://codesandbox.io/s/5x0n7l5l2k).

**Comment by jamesmfriedman** [comment]
Ah, thank you for letting me know! I hate distribution related issues because there are no tests around publishing... Fixed one issue, caused another. Re-publishing right now.

**Comment by jamesmfriedman** [comment]
Should be fixed now with 5.1.6. Sorry for the botched release

**Comment by UFOMelkor** [comment]
Thanks a lot, works like a charm now :+1:
