### ISSUE TITLE
TopAppBar: Default behavior stays fixed

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#416]
The default behavior in the docs shows functionality that shows and hides the bar as you scroll. https://material-components.github.io/material-components-web-catalog/#/component/top-app-bar/standard

**Comment by danielmahon** [comment]
Yea I noticed this in 5.x also, I figured you where aware 😉  If you don't have it implemented yet maybe look at how `react-headroom` is doing it?

**Comment by jamesmfriedman** [comment]
Fixed in the 5.2.0-alpha.0
