### ISSUE TITLE
It's not possible to use the Icon component as the message property of the Snackbar

### ISSUE THREAD

**Issue by akobylianskyi** [jamesmfriedman/rmwc#418]
Version: **5.1.7**
Codesandbox: https://codesandbox.io/s/p34p1rynlq

**Step to reproduce:**
- Pass **Icon** component as the **message** property to the **Snackbar**
- Render the **Snackbar** on the page 

**Actual behavior:**
The icon label is displayed instead of the icon image.

**Expected behavior:**
The icon image should be displayed.

![snackbar](https://user-images.githubusercontent.com/13898759/53230842-4ad25680-3690-11e9-883c-61bb2492983f.png)

**Comment by jamesmfriedman** [comment]
Thanks for reporting this. A few things:

- This was an issue buried in MDC that I found a workaround for. Being published with 5.1.8 as we speak
- In your codesandbox you're missing the styles for buttons. I went ahead and added a reference to import those styles on the snackbar docs page
- In your sandbox, you're also missing an import for the icons in your index.html file. Please read the getting started guide of the RMWC docs under optional steps.
- MDC doesn't currently support icons so this is a workaround. You'll just have to align the icon yourself, but should be easy and can be done with inline styles.

Should be live as of finishing typing this comment.
