### ISSUE TITLE
Make Typography tag name customizable instead of span

### ISSUE THREAD

**Issue by dohomi** [jamesmfriedman/rmwc#420]
Hello,
Currently the Typography is using `<span>` as a tag and adjust the class to it. Would it not be better to use a mapping of all Typography components to there corresponding tags for not colliding with global styles?
For example I'd like to:
```
<h4 class="headline2">My Headline</h4>
``` 
This would overwrite h4 global style with the headline2 stlye. Currently this would happen:
```
<h4><span class="headline2">My Headline</h4>
```
The output might be different/unexpected. Maybe better make `<span>` adjustable through a `tag` prop? Correct me if I'm wrong here..
Thanks again for the nice library

**Comment by jamesmfriedman** [comment]
This is currently customizable, just pass tag to the typography component. I'll add an example to the docs.

`<Typography tag="h1">Hello</Typography>`

**Comment by dohomi** [comment]
Ah now I see it in the component itself.. sorry for the noise.. 👍
