### ISSUE TITLE
Dialog: detail.action not exposed in typescript types

### ISSUE THREAD

**Issue by UFOMelkor** [jamesmfriedman/rmwc#427]
> What RMWC Version are you using [major.minor.patch]:

5.1.6

> Name your build system [Webpack, Rollup...]:

webpack

> Describe the bug with as much detail as possible:
> What happened, and what was supposed to happen:

The [`onClose` event handler of the Dialog-component](https://github.com/jamesmfriedman/rmwc/blob/31dfd81dd9b79514aa70e6aa1d0ce979259019fa/src/dialog/index.tsx#L100) has the type `RMWC.CustomEventT<{}>`.
This makes it impossible to detect, whether the dialog has been accepted or canceled.

Because the (great!) documentation has an example using a `event.detail.action` property, I guess it's correctly implemented but the typescript types are wrong.

**Comment by jamesmfriedman** [comment]
Thanks for reporting, this should be a quick fix I can get to tomorrow unless you’re feeling like taking a shot at a PR yourself l.
