### ISSUE TITLE
Way to disable options in Select

### ISSUE THREAD

**Issue by cha1225** [jamesmfriedman/rmwc#43]
Are you looking to disable certain options in the Select component? It is currently supported by Material Design.

**Comment by jamesmfriedman** [comment]
According to MDC's docs https://material.io/components/web/catalog/input-controls/select-menus/

> When used in components such as MDC Select, mdc-list-item’s can be disabled. To disable a list item, set aria-disabled to "true", and set tabindex to "-1".

Doesn't look like something that has to be added to RMWC, just use the aria attribute and tabIndex

**Comment by jamesmfriedman** [comment]
ah, I just realized I have it where you can pass a list of options. I'll look into this.

**Comment by jamesmfriedman** [comment]
@cha1225 I'm going to keep working on a declarative way to pass data since I believe thats how it will be used most of the time.

Until then, I made a small change that should support your case. You can now just pass ListItems as children and give them whatever attributes you want.

```javascript
<Select
  value={text('value', 'Cookies')}
  onChange={evt => action('onChange: ' + evt.target.value)()}
>
  <ListItem role="option" id="Cookies" tabIndex="0">
    Cookies
  </ListItem>
  <ListItem role="option" id="Pizza" tabIndex="-1" aria-disabled="true">
    Pizza
  </ListItem>
  <ListItem role="option" id="Icecream" tabIndex="0">
    Icecream
  </ListItem>
</Select>
```

**Comment by jamesmfriedman** [comment]
fixed with rc12
