### ISSUE TITLE
Top app bar action item not displayed

### ISSUE THREAD

**Issue by edfxphn** [jamesmfriedman/rmwc#435]
Hi.
I have an issue with app bar action items.
I am using v5.1.8

I simply try to reproduce the sample given in the doc :
```
<TopAppBar>
  <TopAppBarRow>
    <TopAppBarSection alignStart>
      <TopAppBarNavigationIcon icon="menu" />
      <TopAppBarTitle>Title</TopAppBarTitle>
    </TopAppBarSection>
    <TopAppBarSection alignEnd>
      <TopAppBarActionItem aria-label="Download" alt="Download">
        file_download
      </TopAppBarActionItem>
      <TopAppBarActionItem
        aria-label="Print this page"
        alt="Print this page"
      >
        print
      </TopAppBarActionItem>
      <TopAppBarActionItem
        aria-label="Bookmark this page"
        alt="Bookmark this page"
      >
        bookmark
      </TopAppBarActionItem>
    </TopAppBarSection>
  </TopAppBarRow>
</TopAppBar>
```

The action items of the right section are not displayed.
When inspecting elements in the browser, there is no text between `::before` and `::after`. :
```
<i aria-label="Download" alt="Download" data-mdc-ripple-is-unbounded="true" class="rmwc-icon material-icons mdc-ripple-upgraded--unbounded mdc-ripple-upgraded mdc-top-app-bar__action-item" style="--mdc-ripple-fg-size: 28px; --mdc-ripple-fg-scale: 1.71429; --mdc-ripple-left: 10px; --mdc-ripple-top: 10px;">
::before
::after
</i>
```

Any clue ?

Many thanks.
Philippe.

**Comment by jamesmfriedman** [comment]
I’ll go ahead and fix the docs on this. The ToolbarIcon contains an ‘icon’ prop that works just like any other icon prop in the docs.

**Comment by edfxphn** [comment]
Hello James,
do you suggest I use Toolbar instead of TopAppBar ?
Or include ToobarIcon inside a TopAppBar ?

**Comment by jamesmfriedman** [comment]
Sorry, early morning typo! If you read in the docs, Toolbar has been deprecated by Google. What I meant was:

`<TopBarActionIcon icon=“favorite”>`

**Comment by edfxphn** [comment]
Ah ok. clear ! many thanks ;-)

**Comment by edfxphn** [comment]
Sorry, but it seems there's no TopAppBarActionIcon, nor TopBarActionIcon, etc.. 
I've upgraded to 5.2.0 and I have compilation error on that :
```
<TopAppBarActionIcon icon="file_download">Download</TopAppBarActionIcon>
```

**Comment by jamesmfriedman** [comment]
Alright, it was early and I was trying to type code on my phone.

The example in your very first post is all of the correct components. Just specify the icon as a prop instead of a child. I'm also updating the docs to reflect the proper usage.

https://codesandbox.io/s/6v112rm73w
