### ISSUE TITLE
web application with many entity and large data with grid

### ISSUE THREAD

**Issue by mammadkoma** [jamesmfriedman/rmwc#436]
Hi all and pardon me because i'm a beginner in node js framework.
imagine we have a system with 100 entity for data entry.
Is there a sample or step by step video or article for easiest solutions and with lowest coding for making this project with these features :
1- create model(poco) layer and just write entity properties and its validation attribute for backend and frontend validations.
2- create a form automatic with a grid with these features :
a) paging & sorting & filtering for each column header.
b) data entry (insert and delete and update) for master entity.
c) open each row by plus sign click for show details entities.
d) add some custom buttons in rows for execute an action or api on server and database.
2- project can work with sqlite database or sqlserver.
3- project can give access or deny some web page and insert & delete & update &custom buttons. 
and I just write a query for create a ViewModel for grids.

**Comment by jamesmfriedman** [comment]
It would be hard to give a step by step for that, what you’re describing is an entire feature set. While there might be some other off the shelf solutions that do all od the things you are describing, RMWC doesn’t need offer it. It does however contain all of the pieces you could use to assemble something like this. 

Not sure if I can be of any more help than that at the moment other than telling you it seems to be doable with the particular components in this framework.

**Comment by mammadkoma** [comment]
at least give us a grid to bind a viewmodel query and crud it.

**Comment by jamesmfriedman** [comment]
I’m not going to have time to setup a specific video example of this. What you’re asking for isn’t specific to this framework. React.

React is the view layer. As far as the model, this can be achieved in so many ways it’s not possible to document. A simple solution would be to use React state to modify an array. I suggest you look into patterns to handle local data in React. If you want a video, there are plenty of courses on egghead.io and other sites that can show you how to handle the patterns you’re asking about.
