### ISSUE TITLE
Feature request/Help wanted: Time range with slider

### ISSUE THREAD

**Issue by nguyen-tran-qk** [jamesmfriedman/rmwc#437]
Hi,

My company's project currently needs a Material Design slider with 2 sliding thumbs in order to select a time range during the day. Something similar to the one in the image below (found on Skyscanner website).
![image](https://user-images.githubusercontent.com/15355418/54526064-41ca6180-497e-11e9-8551-3f77804539be.png)

I would like to request this variant slider to be in the RMWC kit. In the meantime, I'm also trying to make my own component for it based on RMWC's slider. But I'm not sure how to make the second thumbnail to work with the existing one. Or maybe there could be some better approaches to this matter. Do you have any idea?

**Comment by jamesmfriedman** [comment]
Just reached out to mat-web to see if it is anywhere on their roadmap. If not, I think I have some ideas of how this could be added to RMWC relatively easily.

**Comment by jcamato** [comment]
@jamesmfriedman ,

I’m fairly new to React, but I would love to hear your explanation of how to adjust RMCW slider to add an extra marker for controlling a range of values.

Thank you for all your excellent work :)
