### ISSUE TITLE
Select does not display the value label with an object selection

### ISSUE THREAD

**Issue by Kikketer** [jamesmfriedman/rmwc#44]
### What RMWC Version are you using?
0.0.1-rc9

### What browser(s) and React Version is this bug affecting?

All browsers, React 16.1.0

### What build system are you using?

WebPack

### What are the steps to reproduce the bug?

When using an object as your select values, you do not initially set the value to whatever is passed in.  This is because you have the `options.get(value)`.  If I have an object: `{1: 'Joe'}`, I will be passing in `1` as my value (not 'Joe').  Since `options.get(value)` actually does the opposite, the actual return is always `undefined`.

The following code is what is in there today, and works fine if your value and label are exactly the same (using an array is a way to do that) but it doesn't work if you use an object since the value is different than the label.

```
const getDisplayValue = (value, options, placeholder) => {
  placeholder = placeholder || '\u00a0';

  if (options) {
    return options.get(value) !== undefined ? options.get(value) : placeholder;
  }

  return value || placeholder;
};
```

### What is the expected behavior?

When using an object and having my value as the actual value of the select box, the select box should display the label that is associated with that value.

### What is the actual behavior?

```
      <Select
        value={1}
        options={{1: 'Joe'}}
      />
```
This does not show "Joe" as the selected value.

### Any other information you believe would be useful?

It may not be best to use an object as the value:label anyway.  Order for me still matters and my labels and values could be anything.  Forcing me to create an object from an ordered array does not guarantee that the order will be preserved.

My suggestion is to always accept an array to keep the order in tact but allow the array to contain objects to differentiate the label and value:

```
[
  { value: 1, label: 'Joe' }
]
```

**Comment by jamesmfriedman** [comment]
Thanks for reporting this, I'll fix it in the next release unless you want to submit a PR before then.

As far as ordering goes, it converts objects and arrays to Maps which respect the original ordering of the object, but this is good insight.

There was another issues submitted today about the ability to disable individual options, so having an array of objects makes sense for passing additional properties.

**Comment by jamesmfriedman** [comment]
I was just looking into this. In your example, you are using numbers as object keys which isn't supported or recommended. I was developing using Storybook and it works as long as they are string keys. Can you verify that on your end?

![image](https://user-images.githubusercontent.com/975256/33634423-19510d56-d9e2-11e7-9938-ef8142bafacd.png)

**Comment by jamesmfriedman** [comment]
@Kikketer Did that help?

**Comment by Kikketer** [comment]
Unfortunately it still doesn't work.  First off my data is by numbers but if I force it to be a string (in this case I really force it by slapping letters on it) it still doesn't select on the initial load because the Map.get bit that I spoke of previously.

```
  // I have to convert it to an object first because my array has id, name
  let plns = {}
  plans.forEach(plan => {
    plns[plan.id + 'abc'] = plan.name   // Slapped the abc on there to make sure the key was a string
  })

  // Now force the initial value to be a string with the same abc on it to make sure it's a string
  let val = currentValue + 'abc'
  console.log('Current Value: ', val, plns)
....
<Select value={val} options={plns} />
```

The result is `1abc` being my current value.  `1abc` is the first option in my object:
```
1abc: "test 1"
2abc: "test 2"
3abc: "test 3"
4abc: "test 4"
```

**Comment by jamesmfriedman** [comment]
There was a related issue with #43 which could provide a temporary workaround while I continue to look into this.

Basically you can build your own list items now just using children.

**Comment by j-o-d-o** [comment]
As @Kikketer mentioned, I think it is important to keep the options in an array as this guarantees order. I guess one possibility is to pass an array of objects and specify a label field, example:
```
let myOptions = [{ name: "Joe", id: "an02193j"}, { name: "Luis", id: "xn09123j"} ]

<Select
  options={myOptions}
  displayLabel="name"  // if nested labels then something like ["first_level", "name"]
/>
```


Or another possibility is to be more opinionated and force the user to use a certain format. example:
```
let myOptions = [{ rmwc_label: "Joe", original: { name: "Joe", id: "an02193j"} }, { rmwc_label: "Luis", original: { name: "Luis", id: "xn09123j"} }];
// where e.target.value would return the original object
<Select
  options={myOptions}
/>
```

Any other suggestions/opinions on that?

**Comment by ncknt** [comment]
I personally don't mind producing the `<ListItem>` directly - but the name "ListItem" isn't very intuitive in this context and needs extra attributes (`role="option"` and `tabIndex`)

It'd also be nice to support option groups (`<optgroup>`). To expand what @j-o-d-o wrote:
```
const mOptions = [
 { group: 'Group A', options: [{name: 'A1', id: 1}, {name: 'A2', id: 2}]},
 { group: 'Group B', options: [{name: 'B1', id: 3}, {name: 'B2', id: 4}]}
]
<Select options={mOptions} />```

**Comment by jamesmfriedman** [comment]
@ncknt agreed on ListItem, unfortunately thats what MDC calls it, that falls under one of the "unopiniontated" things I don't think should be changed.

Trying to sum up some of this stuff before I get in there and refactor:
- There are bugs related to the initial value being set, with objects and also with async data #54 
- There needs to be a way to set additional properties on an item, like disabled #43 
- We need to support option groups
- I would like to continue supporting a simple key object map
- I would like to continue supporting a simple flat array
- And for the most utility, something like the following...
```javascript
// Regular Select
const options = [
  {
    label: 'Cookies', // The label
    value: 'cookies', // The value
    // all other items would be spread onto the ListItem, so you can 
    // pass whatever you want
    tabIndex: 1,
    myProp: 'foo'
  },
  {
    label: 'Pizza',
    value: 'pizza',
    tabIndex: 1,
    myProp: 'foo'
  }
];

<Select options={options} />
```

```javascript
// Multi Select
const options = [
  {
    label: 'Food', // The label
    options: [
        {
          label: 'Cookies', // The label
          value: 'cookies', // The value 
        },
       {
          label: 'Pizza',
          value: 'pizza',
        }
    ]
  },
  {
    label: 'Animals', // The label
    options: [
      {
         label: 'Dog', // The label
         value: 'dog', // The value 
       },
       {
          label: 'Cat',
          value: 'cat',
        }
    ]
  }
];

<Select options={options} />
```

What does everyone thing @Kikketer @j-o-d-o @ncknt

**Comment by j-o-d-o** [comment]
So the value could be anything, an the label is whats going to be in the ListItem?
I am with you on supporting flat arrays, cant really think of good usecases for a simple key, value map where it is more convinient then using the {value:"foo", label:"foo"} structure. Might make the code much simpler by dropping that possibility.

Other then that it looks like a good plan to me :)

**Comment by jamesmfriedman** [comment]
@j-o-d-o we could support value being literally anything, and that would be enhanced functionality past MDC. Currently MDC would only support string values because it uses the dom ID attribute.

**Comment by ncknt** [comment]
That looks good to me. I also cannot find a good use case for the object map but that doesn't mean there isn't one :)
Not being limited to string values and keeping control of options is nice - for instance to show icons.

Are option groups only supported in multi-select? I realize this is probably an MDC design choice.

**Comment by jamesmfriedman** [comment]
Not sure, but it looks that way. I’ll have to dig in a bit more. Their Library is still pretty volatile so it’s hard to keep up, but I appreciate the community help, definitely is making it easier.

**Comment by jamesmfriedman** [comment]
Alright, at this point all of the select work is done in the mdc27 branch, Going to go through the changelog and docs and update the rest of the lib accordingly.

There is enough changes in the Select now that it REALLY needs documentation on how to use. I'm going to bite the bullet and get some real documentation going for the Select since the docs need work anyways.

**Comment by jamesmfriedman** [comment]
fixed with rc12
