### ISSUE TITLE
validate message on checkbox form elements

### ISSUE THREAD

**Issue by dohomi** [jamesmfriedman/rmwc#440]
Hello

Not sure how to address this but inside of form elements there is the `helpText` message missing on `<Checkbox/>`. I think it might be not available from the `mwc` itself but maybe `rmwc` should fill the gap to support error messages for checkboxes. Or did I overlook some option how to address this currently?
Cheers

**Comment by jamesmfriedman** [comment]
I would file an issue upstream for this one. I know someone that was using the text field helper text component to accomplish this but it’s definitely not something that I know of. 

Another option is to use a list item with a checkbox in it that provides a place for primary and secondary text.

**Comment by dohomi** [comment]
I created this issue https://github.com/material-components/material-components-web/issues/4537

Hopefully required prop will be supported soon and the `helpText` prop as well. I will use the TextFieldHelperText component for now.

**Comment by jamesmfriedman** [comment]
Thanks! I’ll leave this open until we get some feedback.

**Comment by dohomi** [comment]
@jamesmfriedman the material team don't seem to implement this into their core (don't ask me why..)
But I really think that this should be part of the core - maybe @rmwc should take over? I currently bump into it with every form I create because having required prop on checkboxes is almost on every GDPR consent complied form.

**Comment by jamesmfriedman** [comment]
a simple screenshot / mockup would help me give you some more guidance. It would be trivial for you to extend the existing checkbox and add the particular UI you need. Happy to point you in the right direction on that.

As far as adding it to RMWC, the form elements are extremely complex. I know the Material team works really hard on the design language and internationalization, I'd imagine they have a someone valid reason for not including it, but we can still find a way for you to meet your requirements.

**Comment by dohomi** [comment]
@jamesmfriedman thanks for coming back. I am using a form wide message helper and toggle the validation class on the checkbox component. For me its fine like this, I just though I raise this issue  that RMWC would toggle `Checkbox` error color similar like `Select` or `Textfield` elements. Feel free to close it. Hopefully there will be some efforts from MWC to raise the same behaviour to all form components.
