### ISSUE TITLE
Feature request/Help wanted: Date picker

### ISSUE THREAD

**Issue by tata81** [jamesmfriedman/rmwc#441]
Hi All,

My company's project currently needs a Material Design date picker. Something similar to the one in the image below (found on the react-date-picker website).

![image](https://user-images.githubusercontent.com/17158307/54898321-cfafca80-4ef1-11e9-8c6b-5081c4a735f7.png)

I would like to request this variant date picker to be in the RMWC. In the meantime, I'm also trying to make my own component for it based on RMWC's date picker. But I'm not sure how to proceed further? Or maybe there could be some better approaches? Do you have any idea?

**Comment by jamesmfriedman** [comment]
Date pickers are extremely complicated to build and internationalize properly. There are already a lot of components to maintain in RMWC, and my fear is that this one would blow the scope out of the water.

With that said, there are many for you to choose from, and they should play just fine with RMWC. https://react.rocks/tag/DatePicker

Also, if this is something that you wanted to tackle, PRs are happily accepted.
