### ISSUE TITLE
data table selected delay

### ISSUE THREAD

**Issue by eleith** [jamesmfriedman/rmwc#443]
the rows on the demo: https://jamesmfriedman.github.io/rmwc/data-tables have a slight delay on mouse over / hover before the rows become `selected`.

originally, i expected the selected state to work like i see in other UIs like the github issue list: https://github.com/jamesmfriedman/rmwc/issues where the selected state is activated immediately on hover, without any delay.

is this a bug or intended by design? i haven't looked at the source code yet, will jump in to see what i can learn.

**Comment by jamesmfriedman** [comment]
Its actually a subtle fade animation. The actual material spec isn't clear about it, but I believe it is leftover from when I ported over the data tables from MD-lite. I agree they are distracting, I'll remove them in the next release.

**Comment by eleith** [comment]
awesome. i can confirm if i remove the `transition: background-color` on the `.rmwc-data-table-cell` and `.rmwc-data-table-cell:before` this makes hover instant.
