### ISSUE TITLE
Feature Request: Density Provider Prop

### ISSUE THREAD

**Issue by lavigneer** [jamesmfriedman/rmwc#444]
I would like to propose a new `RMWCProvider` `dense` prop that will default the `dense` prop on related components similarly to how the `ripple` provider prop is already implemented. This would allow users to quickly define dense sections of their UIs.

If you agree that this is something worth doing, I would be more than happy to assist in the implementation.

**Comment by jamesmfriedman** [comment]
Just looked through the whole api. It does appear that there are at least 3 components that respond to a prop called dense.

It would be trivial to add `dense` to the RMWCProvider, I'm just curious if my current implementation allows stacking of the provider. Also, I'm curious if the MDC team will continue to add dense to the implementation. They had the concept of "compact" as well as dense in the past but it was removed.

**Comment by lavigneer** [comment]
Sorry I hadn't come back to this sooner. I've seen a lot of comments on MCW issues about how the current density work is being deprecated in favor of some new subsystem:

- https://github.com/material-components/material-components-web/issues/4771#issuecomment-497430760
- https://github.com/material-components/material-components-web/issues/4613#issuecomment-484527120
- https://github.com/material-components/material-components-web/issues/4539#issuecomment-476650532

Perhaps it's not worth bothering with this since it'll likely change in the future? For the particular use case that prompted my original request, I ended up using their sass variables/mixins to densify all of our application's components since we needed everything to be denser and not just the set of dense-enabled components anyways.

**Comment by jamesmfriedman** [comment]
Yeah I had talked to them about it as well, they have the desire to standardize it, but it's not high up on their priority list right now.

**Comment by lavigneer** [comment]
Ok, I'll close this then. Thank you!
