### ISSUE TITLE
Select does not float label if value missing from options

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#448]
RMWC 5.2.2

If you render a `Select` with a `value` that is not present in the `options` then the label will not float.

https://codesandbox.io/s/oxk836217q

```js
import React from "react";
import ReactDOM from "react-dom";
import { Select } from "@rmwc/select";
import "@material/select/dist/mdc.select.css";
import "@material/floating-label/dist/mdc.floating-label.css";
import "@material/notched-outline/dist/mdc.notched-outline.css";
import "@material/line-ripple/dist/mdc.line-ripple.css";

function App() {
  return (
    <Select outlined label="Fruit" value="Pear" options={["Apple", "Orange"]} />
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by robcaldecottvelo** [comment]
Note a huge problem but we cannot get a `ref` to the underlying MDC component to workaround this like we could in v4 (because `Select` is a function component.)

**Comment by jamesmfriedman** [comment]
I know we've fixed a lot of float related issues, but this one seems a bit weird. In regular HTML this wouldn't even be possible. Still happy to look into fixing this, but just don't see how it is at all valid.

One workaround would be to set the non-existant value as the placeholder.

**Comment by robcaldecottvelo** [comment]
>One workaround would be to set the non-existant value as the placeholder.

Ah, this will do the trick then. Feel free to close this.

**Comment by jamesmfriedman** [comment]
Happy to figure out another solution as well, just debating whether or not this is an actual problem. The lifecycle for the Select components in MDC is bonkers which is why this continues to be a problem.

**Comment by jamesmfriedman** [comment]
Happy to figure out another solution as well, just debating whether or not this is an actual problem. The lifecycle for the Select components in MDC is bonkers which is why this continues to be a problem.

**Comment by jamesmfriedman** [comment]
Closing since there is a workaround and this doesn't seem like it should be valid in the first place ;). Reopen if you wan't to explore alternatives.
