### ISSUE TITLE
customize theme colors?

### ISSUE THREAD

**Issue by tehfailsafe** [jamesmfriedman/rmwc#45]
Following the docs but I'm not understanding how to update things like primary or secondary colors? Is there a more clear example?

**Comment by jamesmfriedman** [comment]
these are all done at runtime through CSS vars, or build time through SASS. Please refer to the MDC documentation on how to do this. https://material.io/components/web/docs/theming/

**Comment by tehfailsafe** [comment]
Ah, I see. I was thinking of something like the styled components theming based on the way your docs are written, I could pass in values for specific colors.

https://www.styled-components.com/docs/advanced

**Comment by tehfailsafe** [comment]
From their docs, added this to my style.scss file which I load in App.js. If I try to `import material-web-components.scss` I get an error loading parent style?

```
$mdc-theme-primary: #9c27b0;
$mdc-theme-secondary: #76ff03;
$mdc-theme-background: #fff;

@import '~material-components-web/dist/material-components-web.css';
```

Above loads correctly but does not override theme colors.

**Comment by jamesmfriedman** [comment]
in your example you just posted you're loading a CSS file, not an SCSS file. If you don't need to support older browsers, just overrides the CSS vars. 

```
:root {
      --mdc-theme-primary: #ff0000;
}
```

**Comment by tehfailsafe** [comment]
I had to include the CSS instead of the SCSS becasue it crashes otherwise.
`@import '~material-components-web/material-components-web';` causes the following error:

```
@import "@material/button/mdc-button";
^
      File to import not found or unreadable: @material/button/mdc-button
Parent style sheet: /node_modules/material-components-web/material-components-web.scss
      in /node_modules/material-components-web/material-components-web.scss (line 17, column 1)
```

**Comment by jamesmfriedman** [comment]
Sorry @tehfailsafe, this is likely a problem with your build setup and RMWC doesn't include any styles on its own. Again, you can achieve what you're looking for from just using CSS vars, otherwise you'll have to setup a SASS build system. You might want to move this one over to the official MDC repository.

**Comment by tehfailsafe** [comment]
Yeah, thanks, the css  vars will work. 

It's nice to have a thin wrapper for React, but sometimes it creates mysteries for how files are being loaded under the hood. This is the first hiccup I ran into so far with your project though! 👍

**Comment by jamesmfriedman** [comment]
Thats great to hear, thanks for the positive feedback!

The docs need a lot of work, the stuff I have up now was just enough to get going. I'll make sure to detail styling in the final version.
