### ISSUE TITLE
Broken Button component

### ISSUE THREAD

**Issue by 9orky** [jamesmfriedman/rmwc#452]
* 5.3.1
* Webpack

After upgrading from 5.1.8 to 5.3.1 there is a problem with Button component. TS shows an error:

`
Type error: Type '{ label: string; }' is missing the following properties from type 'Pick<ComponentProps, "onClick" | "ref" | "key" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | "className" | ... 349 more ... | "onAuxClickCapture">': onAuxClick, onAuxClickCapture  TS2739
`

and this is how code looks like:

`
<Button label="Login"  />
`

Compilation crashed. Also error shows up in the sandbox.

**Comment by jamesmfriedman** [comment]
This has to do with your local package.lock file. I haven't been able to pinpoint what would have changed between versions, but removing your local lock file and re-installing fixes it which leads me to believe it is some internal issue with npm dependency  resolution, not the lib itself

**Comment by 9orky** [comment]
Ok, but take a look here, please: https://codesandbox.io/s/q8334l777j The Button component is underlined and error message is very similar to mine :)

**Comment by jamesmfriedman** [comment]
The sandbox and link you sent me is working as expected. This lends more credence to my theory this is a third party issue since I definitely didn't make any changes that would've fixed the broken sandbox. Please reopen if you run into this again.

**Comment by DJankauskas** [comment]
- 5.6.0
- create-react-app

After updating from 5.2.2 to 5.6.0, I'm experiencing a similar error as the original poster:

`'{ children: string; raised: true; className: string; }' is missing the following properties from type 'Pick<ComponentProps, "ref" | "cite" | "data" | "form" | "span" | "style" | "summary" | "title" | "pattern" | "tag" | "theme" | "accept" | "acceptCharset" | "action" | "allowFullScreen" | ... 343 more ... | "onAuxClickCapture">': onAuxClick, onAuxClickCapturets(2739)` 

I tried re-generating my package-lock.json and manually updating `@rmwc/button` (I install all modules through `rmwc`) but those did not fix the issue.

**Comment by jamesmfriedman** [comment]
Are you able to create a repro? This would be extremely hard to troubleshoot since it appears to be an isolated issue. 

One thing that might be causing problems is multiple versions of the same package. Try running `npm dedupe`

**Comment by DJankauskas** [comment]
I was unable to reproduce and `npm dedupe` didn't work. However, updating my React version from 16.8.4 to 16.9.0 fixed the issue. Maybe `onAuxClick` was incorrectly non-optional in that version of React.
