### ISSUE TITLE
resize Dialog windows

### ISSUE THREAD

**Issue by akonsowski** [jamesmfriedman/rmwc#454]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC? RMWC 

Do you really want it fixed? 
[https://codesandbox.io/s/92v6om9r3r](https://codesandbox.io/s/92v6om9r3r
)

- What RMWC Version are you using [major.minor.patch]: 5.3.1

- Name your build system [Webpack, Rollup...]: createreactapp

- Describe the bug with as much detail as possible: when setting the width of the dialog it moves the dialog box and does not increase the width

- What happened, and what was supposed to happen: In RMWC 1.x we used to be able to set the dialog surface which would change the width is there something like that in 5.x. I am able to change the size of all the dialog windows by setting the css for the dialog surface. However I don't want all my dialogs all the same size.

**Comment by akonsowski** [comment]
so I figured out the size of dialog window is calculated so if this is overridden and you wrap the contents of the dialog in a div you can set the width and height of the window using that div

**Comment by jamesmfriedman** [comment]
Sorry for the late reply on this! Could've pointed you to an example of targeting it with a css selector as well. Glad you were able to figure it out though.
