### ISSUE TITLE
Docs: List > Variants > Checkboxes hover issue

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#458]
**RMWC 5.5.1**

The example for the **List > Variants > Checkboxes** shows the hover item as a black block:

![image](https://user-images.githubusercontent.com/41152621/57308210-d7ac7e00-70dd-11e9-9777-62416ec405b9.png)

**Comment by jamesmfriedman** [comment]
![image](https://user-images.githubusercontent.com/975256/57308338-30ffb780-70b4-11e9-93f3-25751b857840.png)

Can I ge some more info? This is a screen shot of the docs from chrome.

**Comment by robcaldecottvelo** [comment]
I'm on MacOS 10.14.4
Chrome 74.0.3729.108

Any of the themes exhibit the issue when I hover with the mouse. If I turn on DevTools and force the element state to `:hover` same issue.

Safari and Firefox are fine though. I'll keep digging.

**Comment by akmittal** [comment]
Facing the same issue with Table and Card.
Chrome 74.0.3729.131
MacOS 10.14.4

**Comment by akmittal** [comment]
looks like it is fixed in MWC 2.2, looks like dependency need to be upgraded.

**Comment by jamesmfriedman** [comment]
Will be fixed with a new docs release today
