### ISSUE TITLE
TopAppBarNavigationIcon is not unselected when using tag="button"

### ISSUE THREAD

**Issue by maracuja-juice** [jamesmfriedman/rmwc#459]
- What RMWC Version are you using [major.minor.patch]: 5.5.1
(I wasn't able to exactly track down if this arises from MDC or RMWC 🙁. )

- Describe the bug with as much detail as possible:
When using this markup for a navigation:
```
<TopAppBar>
        <TopAppBarRow>
          <TopAppBarSection alignStart>
            <TopAppBarNavigationIcon
              tag="button"
              icon="menu"
              style={{ color: "inherit" }}
              aria-expanded={open}
              onClick={() => setOpen(!open)}
            >
              <span className="sr-only">Menu</span>
            </TopAppBarNavigationIcon>
            <TopAppBarTitle>An App</TopAppBarTitle>
          </TopAppBarSection>
        </TopAppBarRow>
      </TopAppBar>
      <TopAppBarFixedAdjust />
      <Drawer tag="nav" aria-label="Site" dismissible open={open}>
        <DrawerContent>
          <List>
            <ListItem activated>
              <ListItemGraphic
                icon={{
                  icon: "bug_report",
                  size: "medium",
                  "aria-hidden": true
                }}
              />
              <ListItemText>Report Bugs</ListItemText>
            </ListItem>
          </List>
        </DrawerContent>
      </Drawer>
```
The menu button is still selected when closing the menu. This issue is not present when you don't use the button tag and the standard i tag that comes with the component. From a semantic html and a11y standpoint that makes no sense though.

- What happened, and what was supposed to happen:
  - Happened: Menu button is still selected when closing the menu
  - Supposed to happen: Menu button is unselected when closing the menu

- Reproduction: 
https://codesandbox.io/s/oj0m760kpq

**Comment by akonsowski** [comment]
I believe you need to use `Tag="button"` the lowercase tag is not properly getting added to the html
 
Sandbox:
https://codesandbox.io/s/l5pmwyw969

**Comment by jamesmfriedman** [comment]
@akonsowski the use of tag in your example is not what @maracuja-juice is referring to. lowercase `tag` actually changes the HTML tag that render swith the component.

What he's referring to seems to be both a bug and / or an a11y issue.

@akonsowski isn't the purpose of `aria-role` to fix issues like this? You should be able to apply `aria-role=button` to fix this problem.

**Comment by akonsowski** [comment]
@jamesmfriedman yes that looks like the right fix to use `aria-role`. I am not too familiar with a11y and I thought @maracuja-juice  was attempting to add a custom attribute to the HTML called tag

**Comment by maracuja-juice** [comment]
It's always better to use the native tag, if possible, instead of the aria-role attribute. And I think that's definitely possible for this case.

**Comment by maracuja-juice** [comment]
This is caused by the class `mdc-ripple-upgraded--background-focused`. When I click to close the draw and then somewhere else, it is removed and the circle outline gone.

**Comment by maracuja-juice** [comment]
Only is an issue in Chrome actually and probably with the core library. Will open an issue with them.
