### ISSUE TITLE
missing `CardHorizontalBlock` support

### ISSUE THREAD

**Issue by scottastrophic** [jamesmfriedman/rmwc#46]
Hi there, [The Material Design Card component page](https://material.io/components/web/catalog/cards) mentions a horizontal block that you do seem to have included, but [with the wrong `className`](https://github.com/jamesmfriedman/rmwc/blob/master/src/Card/index.js#L81). The docs also refer to a "Media item" distinct from the media content block, meant for use inside the horizontal block for an effect like the orange cards on [the demo page](https://material-components-web.appspot.com/card.html). I am in need of that card layout and could try extending `Card` if you'd like.

**Comment by jamesmfriedman** [comment]
This is an easy fix I can get in today. Their docs and api have changed so much it’s hard to be proactive in keeping up with it.

**Comment by jamesmfriedman** [comment]
fixed in RC11 as well as added Media Item
