### ISSUE TITLE
collapsible list must be interacted with to minimize list

### ISSUE THREAD

**Issue by akonsowski** [jamesmfriedman/rmwc#460]
## RMWC or MDC?  RMWC

Sandbox:

https://codesandbox.io/s/nn2o044r3j

- What RMWC Version are you using [major.minor.patch]:
latest

- Name your build system [Webpack, Rollup...]:
create reactapp

- Describe the bug with as much detail as possible:

I believe that the toggle open is not getting called when the open state is changes which causes the class to not get removed from the component. 

- What happened, and what was supposed to happen:

when using collapsible list that is open the open property when changed with a interaction that does not involve clicking on the list to collapse the list will go away but the css that keeps the list expanded does not get removed. 

what should happen is when I set the state of open to false or true the list should collapse and expand depending on the state

**Comment by jamesmfriedman** [comment]
Fixed with 5.5.2
