### ISSUE TITLE
Consider using fixed version in rmwc/package.json

### ISSUE THREAD

**Issue by foisonocean** [jamesmfriedman/rmwc#461]
I found in `rmwc/package.json` (v5.5.1), all the rmwc components versions are declared like this:

```json
{
    "dependencies": {
        "@rmwc/avatar": "^5.5.1",
        "@rmwc/base": "^5.5.1",
        "@rmwc/button": "^5.5.1"
    }
}
```

Imagine one day I upgrade `rmwc` from v5.5.1 to v5.99.0 (or whatever other new minor versions or patch versions), then I found there's a bug with `@rmwc/button` v5.99.0, so I want to downgrade `rmwc` to v5.5.1. But `rmwc` v5.5.1 declare dependency `@rmwc/button` with a prefix `^`, which means `rmwc` is still going to install `@rmwc/button` v5.99.0. This make downgrade `rmwc` impossible without editing lock file manually.

If we can use fixed versions in `rmwc/package.json`, the problem will be solved:

```json
{
    "dependencies": {
        "@rmwc/avatar": "5.5.1",
        "@rmwc/base": "5.5.1",
        "@rmwc/button": "5.5.1"
    }
}
```

**Comment by jamesmfriedman** [comment]
RMWC honors standard semver behavior. Patch releases are for bug fixes, minor versions are for new features but include no breaking changes. There shouldn’t ever be a reason to not upgrade a minor version. You can also lock down exact versions using package-lock

**Comment by foisonocean** [comment]
@jamesmfriedman 
Maybe I didn't describe the problem clearly.

The package `rmwc` is basically a package to help users install rmwc packages like `@rmwc/avatar`, `@rmwc/button`, and others by using one install command `yarn add rmwc`.

And here is the problem, when I run `yarn add rmwc@^5.0.0`, it means I would like to accept all minor and patch updates, so finally the versions of the packages I installed are: `rmwc: 5.5.1`, `@rmwc/avatar: 5.5.1`, `@rmwc/button: 5.5.1`, which is fine, but when I run `yarn add rmwc@5.0.0`, this means I would like to install the specific version 5.0.0, and not accept any minor or patch updates, but actually the final version of the packages I installed are: `rmwc: 5.0.0`, `@rmwc/avatar: 5.5.1`, `@rmwc/button: 5.5.1`. All the component packages are still installed the latest version, which is not what I expect.

**Comment by jamesmfriedman** [comment]
Let me do some research on how other projects using Lerna handle this, thanks for the extra description!

**Comment by jamesmfriedman** [comment]
I think the appropriate solution here will be to use the `~` version instead of `^` for the main rmwc package specifically. This will ensure that you get the right versions going forward. Thoughts?

**Comment by foisonocean** [comment]
@jamesmfriedman 
Using `~` means all the patch versions are available, but sometimes patch versions also come up with new bugs. So I think it's better to use the version without any prefix, then we can always install the same version.

**Comment by jamesmfriedman** [comment]
I did a bit of research on this.

- I looked at how material-components-web manages this
- I searched github for "lerna" and looked at how other projects are handling having a single top level install with sub-dependencies

100% of the time, they're all using `^` to get the latest minor and patch versions.

I think this is the correct behavior. While I do understand where you're coming from, installing the 'rmwc' global is more for convenience than anything else. Even if I applied fixed package versions in RMWC's package.json file, all of the sub package json files are also using the `^`. This means I would have to apply fixed versions throughout all of the sub packages at which point I've made everyone's update cycle very manual and broken the typical dependency behavior of any project. For instance, installing @rmwc/textfield brings in about 5 other required packages.

As an aside, this project obeys SEMVER to the best of its abilities, and hasn't had a breaking change in months. While nothing is infallable, I'd rather fail forward and immediately patch any critical or blocking bugs. 

If fixed versions are important to your project you can leverage the package-lock.json, or yarn.lock file to guarantee the proper versions.

**Comment by jamesmfriedman** [comment]
Closing this out, fixed versions can be controlled via package-lock
