### ISSUE TITLE
How to customize the font family for the whole RMWC?

### ISSUE THREAD

**Issue by puru0019** [jamesmfriedman/rmwc#462]

**Comment by jamesmfriedman** [comment]
There is no font family specified other than the mdc-typography class on the body attempts to load the roboto font. In your own CSS just point .mdc-typography to your font of choice.

**Comment by puru0019** [comment]
Does that apply every where for example on the buttons or on the form fields?

**Comment by jamesmfriedman** [comment]
It should apply to everything. There aren’t any fonts hardcoded

**Comment by puru0019** [comment]
I think the fonts are hared coded. I applied my desired font family to .mdc-typography and its not applying to few components such as button, modal and form components, Because they have separate class names with Roboto as font (i.e .mdc-button has font-family as Roboto)

**Comment by jamesmfriedman** [comment]
Just went to verify this, you are absolutely correct. You can open an issue up with material-components-web and link this issue. I think you're right, they should all obey whatever is set for mdc-typography

**Comment by puru0019** [comment]
Any update on this bug?

**Comment by jamesmfriedman** [comment]
Again this is an issue with material components web, not RMWC. I see you opened an issue but it appears you did so on a fork of material components web, not the real project. 

At the end of the day this is just CSS, you can use standard css selectors to change the fonts to whatever you want. Just find the rules that are currently applying Roboto and override them.

**Comment by anthonysapien** [comment]
In the meantime, this worked for me:
https://stackoverflow.com/a/49601716

Updated to use "mdc-"

```
[class^='mdc-'], [class*=' mdc-'] {
    font-family: 'Source Sans Pro', sans-serif;
  }
  .material-icons {
    font-family: 'Material Icons';
  }
```

**Comment by jamesmfriedman** [comment]
Thanks for posting the example @anthonysapien thats exactly what I was saying but not showing 😜

**Comment by nicholaschiang** [comment]
Hey @puru0019 if you want to, you can customize the `font-family` when importing `@material`'s styling with Sass:
```sass
@use '@material/typography' with (
  $font-family: unquote('Poppins, sans-serif'),
);
```
And then you can import the desired styling beneath that and it should use the `font-family` specified above:
```sass
@use '@material/button/mdc-button';
@use '@material/card/mdc-card';
@use '@material/menu/mdc-menu';
```

**Comment by jamesmfriedman** [comment]
Google added a css var for it as well
`var(--mdc-typography-font-family,Roboto,sans-serif)`

**Comment by puru0019** [comment]
@jamesmfriedman you are saying,  we can override the var with new font family?

**Comment by anthonysapien** [comment]
hi @puru0019 i was able to set this style globally:

--mdc-typography-font-family: proxima-nova;

**Comment by puru0019** [comment]
Thank you @anthonysapien and @jamesmfriedman. Should I upgrade my RMWC version to `6.1.0` to apply this change. Currently I am using 5.7.2 version
