### ISSUE TITLE
Warning: Unknown event handler property `onInteraction` for Tab in React 16.8.6

### ISSUE THREAD

**Issue by anthonysapien** [jamesmfriedman/rmwc#463]
- This is my first time using the sandbox. Very cool. You can see the warning in the console.
https://codesandbox.io/s/rmwc-sandbox-ywo3f

- What RMWC Version are you using [major.minor.patch]:
5.5.1

- Name your build system [Webpack, Rollup...]:
create-react-app webpack

- Describe the bug with as much detail as possible:
When adding an event handler onInteraction to a Tab, a warning appears in the console.
React seems to not want an unexpected attribute on the DOM.

I'm also using an onActivate event handler on the TabBar, and there is no warning shown for that handler.

I'm pretty new to React, so I'm doing my best to guess what might be happening. Perhaps RMWC needs to process and remove the attribute before writing the DOM element.

- What happened, and what was supposed to happen:
Expected to see no warning. 

Thanks so much for taking a look!

**Comment by jamesmfriedman** [comment]
Yeah generally those types of bugs are from a prop that should have been removed before they where passed on to a dom element. Thanks for reporting, I’ll take a look.

**Comment by jamesmfriedman** [comment]
Fixed in 5.6.0

**Comment by anthonysapien** [comment]
Thanks so much!
