### ISSUE TITLE
Control TextField invalid state and helpText

### ISSUE THREAD

**Issue by cdock1029** [jamesmfriedman/rmwc#467]
- What RMWC Version are you using [major.minor.patch]: 
`5.5.1`
- Name your build system [Webpack, Rollup...]:
`Webpack`
- Describe the bug with as much detail as possible:

  Inability to control invalid state and/or helperText to show/not show when I want to, 
  specifically based on Formik error state or related logic.

- What happened, and what was supposed to happen:

  If I'm reading right there seems to be a way to override deferring to native validation state:
  `useNativeValidation(false)` in mdc-web? Though... i do like using the native validation 
   popover and having that just work (would calling this method turn that off?).
 
Maybe something related to this discussion?

https://github.com/material-components/material-components-web/issues/4574

Mainly I don't like the UI showing red while the user is typing and therefore already having their input in a valid state. Causes cognitive dissonance with them thinking something is wrong.. not changing state till they blur the field.

Demo in code sandbox: 

https://codesandbox.io/s/dark-firefly-zfcvz

See last example on this page:

https://material-components-web.appspot.com/text-field.html

**Comment by jamesmfriedman** [comment]
I haven't really gotten very much into the built in validation. Based on the thread you sent, you can probably get a reference to the RMWC input using `inputRef` and controlling the validity manually.

**Comment by jamesmfriedman** [comment]
@cdock1029 I'm clearing out some old issues and took another look at this one. I guess I don't understand the exact case. When I went to the sandbox it worked like I would expect it to, a little more clarity would help.

**Comment by cdock1029** [comment]
2 scenarios, different effects:
1. Click into the text field to focus it. Then, without typing, click out of it.
    The field shows red outline & invalid message ("Message text required").

    This is expected.

    Now click back in, and start typing. The invalid message goes away (because this field is controlled.)
    But the outline is still red. So the user is doing what they should, but is still seeing error outline.

2. Type text into the field, then click off. Red outline goes away, and invalid message is not present.
Works as expected.

    Click back into field. Erase all of the text. Red outline appears, as well as invalid message. Type again, outline disappears and message. This is how I would expect it to always work. When the invalid state no longer applies, message *AND* outline both go away.

It seems the outline is somewhat controlled internally by mdc? Basically UX seems ideal if scenario 2 always applied and both error signals (color & message) are synced.

Perhaps I am using this library & Formik incorrectly, so let me know if you have any thoughts.
