### ISSUE TITLE
Feature Request: Onboarding (TopUserBenefits)

### ISSUE THREAD

**Issue by danielmahon** [jamesmfriedman/rmwc#469]
Need to build a cross-platform (mobile/tablet/desktop) onboarding intro for my RMWC themed app, and have been itching to contribute more to RMWC since I started using it. Thought before I make something using RMWC components I would see if this is something you'd like me to attempt to create as an "Addon". Probably going to start with the "Top User Benefits" onboarding spec: https://material.io/design/communication/onboarding.html#top-user-benefits-model. Figured it could be organized into RMWC as "Onboarding -> TopUserBenefits", maybe later adding in the "SelfSelect" and "QuickStart" models. Thoughts?

![onboarding](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1GiLc9RlM6zN8MlyqIrNKRGQfPWr9g8KX%2Fonboarding-illo-01.png)

**Comment by jamesmfriedman** [comment]
Would love for you to contribute! 

Can you explain a little more of what you're talking about? Are you talking about building a reusable flow out?

For some of these higher level components I've thought about having separate repos and listing them in a community contribution section. Not opposed to having it in the codebase as well, just a heck of a lot of stuff to maintain at this point

**Comment by danielmahon** [comment]
Yea basically just looking at it as a higher level composition of existing RMWC components to produce something close to Google's spec. Looks like a simple combination of Tabs, Buttons, Layout, some default styling, and swipe handler. And yea I think perhaps keeping it in a separate repo is best (at least for now). Wouldn't want people hounding you over bugs in stuff I wrote. 😉  Plus I need to crank out something rather quick so it's going to be messy at first. You could always merge in "stable" community add-ons later if you wanted.  I'll close this and let you know when I have a working version up.
