### ISSUE TITLE
Dialog: Components are not exportet

### ISSUE THREAD

**Issue by j-o-d-o** [jamesmfriedman/rmwc#47]
using: master / 0.0.1-rc10 

Is there a particular reason why in src/index.js, only `Dialog` and `DialogFooterButton` are exported. I kind of need the other stuff too, like `DialogSurface`, `DialogHeader` etc. : )

**Comment by jamesmfriedman** [comment]
Nothing more than accidental oversight. I’ll get this fixed today.

**Comment by j-o-d-o** [comment]
Cool! I am currently changing my own mdc wrappers with the rmwc wrappers on a project, looks good so far. Good job and thanks for the effort!

**Comment by j-o-d-o** [comment]
Thanks for reminding. Haven't thought about it : )

**Comment by jamesmfriedman** [comment]
Either way, added in RC11
