### ISSUE TITLE
List doesn't work with sass theme

### ISSUE THREAD

**Issue by ruoshui-git** [jamesmfriedman/rmwc#470]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC is a React wrapper for Google's official MDC that provides a props based interface for their components. Is the bug being caused by RMWC, or MDC? Please do your best to track down where the bug is originating from and post your issue to the proper repository. MDC bugs should be filed here https://github.com/material-components/material-components-web/issues.

Do you really want it fixed? Make a repro in the sandbox!
> - Javascript Sandbox https://codesandbox.io/s/kpy13vqnr
> - Typescript Sandbox https://codesandbox.io/s/kl0w4xp95

- What RMWC Version are you using [major.minor.patch]:
5.2.2
- Name your build system [Webpack, Rollup...]:
Webpack
- Describe the bug with as much detail as possible:
Lists don't work with themes when theme is customized in sass file.

- What happened, and what was supposed to happen:
When custom themes are applied, lists should also display the primary color when an item is selected. The transition (ripple) should be a lighter variation of primary color. This is not the case in the library. Rmwc only applies the default ripple and selection color.
Then I checked out the official react-mdc library, and they support this by allowing a "singleSelection" and a "selectedIndex" prop on the List component. Rmwc doesn't support this.

It seems like the issue is that the class "mdc-list-item--activated" is not being added to the List item when it is clicked. Theme does get applied, though, when I manually add the class on there. (By that, I mean adding the class through the inspector, not code)

**Comment by jamesmfriedman** [comment]
I'd have to see a repro to better understand. RMWC doesn't handle any of the SASS so it sounds like that would be an issue with MDC.

You can use the "activated" prop on a list item to render it in an activated state

**Comment by ruoshui-git** [comment]
OK. I see how it should work. Theme does work when "activated" prop is put on a list item. But I'm still not sure how I can "deactivate" an item when I click another one. I guess I can figure that out. So this is not an issue anymore. Thank you!
