### ISSUE TITLE
Indeterminate CircularProgress is rendering as a black circle

### ISSUE THREAD

**Issue by maurusrv** [jamesmfriedman/rmwc#471]
in my package,json:
"rmwc": "^5.5.2",
"material-components-web": "^2.3.1",

using webpack to build my frontend, have you experience using CircularProgress but it renders a black circle instead of the indeterminate circle? Thanks in advance to solve this. last time i just resorted to using the linear progress because that one works.

here is a screenshot, i was trying to make a suggestion menu for a text field, and im trying to show that the suggestions are "loading" that's why i want to use circular progress.

![image](https://user-images.githubusercontent.com/34334455/61128045-8bb5f500-a4e3-11e9-8e1e-42053960f24c.png)

this screenshot is from using firefox developer edition on a linux os

in my component: 
```
<MenuItem disabled>
       <CircularProgress />
</MenuItem>
```

**Comment by jamesmfriedman** [comment]
I haven't been able to reproduce this. Can you repro it in the code sandbox?

**Comment by jamesmfriedman** [comment]
@maurusrv is this still an issue?

**Comment by jamesmfriedman** [comment]
Please reopen if you are still seeing this issue. Firefox is working correctly in my testing.
