### ISSUE TITLE
support use of react useRef hook for inputRef on TextField

### ISSUE THREAD

**Issue by eleith** [jamesmfriedman/rmwc#475]
currently, `inputRef` is typed as `(ref: HTMLInputElement | HTMLTextaAreaElement | null) => void`

so today, we need to use this method to get at the input ref

```javascript
let input: HTMLInputElement | HTMLTextaAreaElement | null;

<TextField
  ...
  inputRef={(ref) => input = ref}
  ...
/>
```

however with the `useRef` hook in latest versions of react, another potentially more convenient pattern of getting access to the underlying ref could look as follows

```javascript
const input = useRef<HTMLInputElement>(null);

<TextField
 ...
 inputRef={input}
 ...
/>
```

would you be interested in this functionality?

**Comment by jamesmfriedman** [comment]
I am, obviously it has to be on the typescript side. I want to continue to support versions of react without hooks.
