### ISSUE TITLE
Chip style issue

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#476]
RMWC 5.6.0

After upgrading from 5.5.x to 5.6.0 we noticed the styling of chips looks a little off, with the text not centred correctly. Weirdly the RMWC `Chip` docs look OK, but it seems the docs have some subtle differences with `Chip` `padding` and `border-width`.

This sandbox shows the issue: the first chip has some style overrides that (I think) match the RMWC docs. The remaining chips use the default MDC CSS and the text seems to be too close to the bottom of the chip:

https://codesandbox.io/s/quirky-glade-fpbu1

So were the RMWC docs tweaked for this issue or are we pulling in the wrong version of the MDC CSS? A `yarn list @material/chips` reports `3.1.0` which I assume is OK.

**Comment by robcaldecottvelo** [comment]
OK, odd. If I create a new `create-react-app` and add `rmwc` then `yarn list @material/chips` shows this:

```bash
rmwc-chip git:(master) yarn list @material/chips
yarn list v1.16.0
├─ @material/chips@1.1.1
└─ @rmwc/chip@5.6.0
   └─ @material/chips@3.1.0
```

Where is `v1.1.1` coming from? Could this be related do you think?

```bash
yarn create react-app rmwc-chips
cd rmwc-chips
yarn add rmwc
yarn list @material/chips
```

**Comment by robcaldecottvelo** [comment]
OK, it's pulling in an older CSS file. We can fix it with `yarn add @material/chips@3.1.0` for now.

**Comment by jamesmfriedman** [comment]
Very strange indeed, thanks for reporting, I'll check it out!

**Comment by anirban09** [comment]
When you install all of RMWC (i.e. with `yarn add rmwc`) and include the material-components-web CSS file (`material-components-web/dist/material-components-web.css`) in your app, it still uses the 1.x.x version.

https://github.com/jamesmfriedman/rmwc/blob/214827eaf5ff61a9e1822f66618d096ffe5b6a2b/src/rmwc/package.json#L82

**Comment by jamesmfriedman** [comment]
@robcaldecottvelo can you confirm if you are using the main RMWC install or individual packages? I'll get the main rmwc/package.json updated for the next release.

**Comment by robcaldecottvelo** [comment]
@jamesmfriedman Main RMWC install. We will try and switch to individual packages at some point but a fix for this is much appreciated as always.

**Comment by jamesmfriedman** [comment]
@robcaldecottvelo this was an outdated dep in the main RMWC install. This will be resolved in the next release.
