### ISSUE TITLE
why can't rmwc provide a feature to inject styles at the top the head tag like @material-ui/styles does?

### ISSUE THREAD

**Issue by puru0019** [jamesmfriedman/rmwc#479]
I came across following code in @material-ui library and they are providing a way to inject styles at top of the head tag, which will make styled-component styles at the end of the head tag.

https://codesandbox.io/s/k553lz1qrv

Can this be done in rmwc as well

**Comment by jamesmfriedman** [comment]
I understand the ask. My sense is that it is a bit out of scope for RMWC.

Material-UI uses JSS / style-components for all component styling while RMWC uses standard CSS. With RMWC, you are required to add the styles in a way that makes sense for your build system which could be anything from require / import statements, inline in the index.html, or some other dynamic means.

I bring this up to say that you technically already control the order of your styles :). Does that make any sense?

**Comment by puru0019** [comment]
> I understand the ask. My sense is that it is a bit out of scope for RMWC.
> 
> Material-UI uses JSS / style-components for all component styling while RMWC uses standard CSS. With RMWC, you are required to add the styles in a way that makes sense for your build system which could be anything from require / import statements, inline in the index.html, or some other dynamic means.
> 
> I bring this up to say that you technically already control the order of your styles :). Does that make any sense?

Following is the sample repo. I was trying to build a reusable library using rmwc components. As said in your documentation I was loading the css for the specific component(For example button styles inside button component). But when I write style-component styles to Button Those styles are appearing at the top and material styles are loading later

https://github.com/puru0019/testpro1/tree/loade-styled-components-at-the-end

If you can suggest a way to load the material styles prior to my style-component styles that would be helpful

![image](https://user-images.githubusercontent.com/23036485/62947103-8e1baf80-bdff-11e9-8ccb-31852ebe483b.png)

**Comment by jamesmfriedman** [comment]
Did a little googling. 

Apparently this is a very common issue with that has lots of related issues within styles components. https://github.com/styled-components/styled-components/issues/1

The suggestion seems to be to lift the specificity of your selector with leading &

As far as the injection order, it would take digging in and seeing how styled components adds its style tags. I think it’s a solvable issue, but one that is introduced by styled components and your build system, not RMWC

**Comment by puru0019** [comment]
I have installed styled-component@beta version which is 5.0.0.beta-8. This was solving the issue and this should be working in v5 release

**Comment by jamesmfriedman** [comment]
Sorry, to be clear, you’re saying this issue is solved for you after installing the beta?

**Comment by puru0019** [comment]
> Sorry, to be clear, you’re saying this issue is solved for you after installing the beta?

Yes. It was solving the problem

![image](https://user-images.githubusercontent.com/23036485/62993042-7aaa2c00-be73-11e9-8354-7e8676d51479.png)
