### ISSUE TITLE
Feature Suggestion: exposing controlling functions

### ISSUE THREAD

**Issue by j-o-d-o** [jamesmfriedman/rmwc#48]
### Feature Suggestion

It would be nice if the components that have interaction e.g. Menus, can also be opend by exposing a controller function. So a user could use the component like this:

```
<MenuAnchor>
	<Button onClick={this.menuCtrl.open()}>
		Open Menu
	</Button>

	<Menu provideCtrl={ctrl => this.menuCtrl = ctrl}>
		<MenuItem>Cookies</MenuItem>
		<MenuItem>Pizza</MenuItem>
		<MenuItem>Icecream</MenuItem>
	</Menu>
</MenuAnchor>
```

Thoughts?

**Comment by jamesmfriedman** [comment]
@j-o-d-o  They do, it's just poorly documented.

You can expose the mdc foundation instance on any of the components that have them using `apiRef`.

```
<MenuAnchor>
	<Button onClick={this.menuCtrl.show()}>
		Open Menu
	</Button>

	<Menu apiRef={api => this.menuCtrl = api}>
		<MenuItem>Cookies</MenuItem>
		<MenuItem>Pizza</MenuItem>
		<MenuItem>Icecream</MenuItem>
	</Menu>
</MenuAnchor>
```

The apis are documented under their respective components. https://material.io/components/web/catalog/menus/
