### ISSUE TITLE
Feature Request: CollapsibleList opening direction

### ISSUE THREAD

**Issue by brunezko** [jamesmfriedman/rmwc#480]
Hello everyone!
First of all, I want to thank you all for the huge amount of work and dedication you've put into this project, every component looks neat and the documentation is great.

I'm actually facing the following issue: I have a list of collapsibles, and whenever I open the last one (or closer to the end of the list) the list grows, but the content is thrown to the bottom (kind of a bad UX experience). However, when I scroll down after opening it the first time, I can see that the collapsible "remembers" its last position, and opens up towards the top of the list (which is what I want).

I was wondering if it is too hard to implement a ```direction``` prop or something for the CollapsibleList component? I see there are some styling properties that are changing depending on the collapsible position (```--mdc-ripple-fg-translate-start``` and ```--mdc-ripple-fg-translate--end```).

Thank you very much in advance.

**Comment by jamesmfriedman** [comment]
H! It would be helpful to see a brief video or a repro in the code sandbox for this one.

**Comment by jamesmfriedman** [comment]
@Brunezkey would love to help but need more information before anything actionable can be done.  A video or sandbox repro would work.
