### ISSUE TITLE
Ripple Color for Button Not working

### ISSUE THREAD

**Issue by rahulrsingh09** [jamesmfriedman/rmwc#482]
RMWC version - 5.6.0

I am trying to get a ripple color for my secondary button .

```
const secondaryThemeOptions = {
  primary: "#446278",
  onPrimary: "#000",
  secondary: "#2FC7FF"
};
    <ThemeProvider options={secondaryThemeOptions}>
      <Button label={btnLabel} {...buttonProps.btnOptions} ripple={{accent: true}}/>
    </ThemeProvider>
```

But the Ripple still takes the primary color, How can we have the ripple color different from the primary in this scenario

**Comment by jamesmfriedman** [comment]
![image](https://user-images.githubusercontent.com/975256/64549467-bc0cea80-d2fe-11e9-9b5f-403640bb97b5.png)

Sorry for the delay in looking into this. I can confirm that this is working as expected. Early on, Material used the terms "secondary" and "accent" interchangeably. `accent` reflects making the buttons ripple whatever the `secondary` option on the palette is. I made it red in my example to more clearly illustrate. So your code works just fine, I think the actual colors you picked are really close together.

![image](https://user-images.githubusercontent.com/975256/64549547-ebbbf280-d2fe-11e9-97b9-47e856e6e44d.png)

As an aside, I'm currently working off the latest MDC 3.1.x, but it doesn't appear they made any changes that would've caused this to be broken
