### ISSUE TITLE
mdc-dialog component fails to build

### ISSUE THREAD

**Issue by rahulrsingh09** [jamesmfriedman/rmwc#483]
I am trying to use the dialog component in my App.

but as soon as i import the Typescript compiler starts complaining 

```
[at-loader] ./node_modules/@rmwc/textfield/dist/index.d.ts:83:1302 
    TS2344: Type 'K' does not satisfy the constraint '"input" | "progress" | "select" | "error" | "scroll" | "reset" | "drag" | "submit" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | ... 70 more ... | "wheel"'.
  Type '"input" | "progress" | "select" | "error" | "scroll" | "reset" | "drag" | "submit" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | ... 72 more ... | "selectstart"' is not assignable to type '"input" | "progress" | "select" | "error" | "scroll" | "reset" | "drag" | "submit" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | ... 70 more ... | "wheel"'.
    Type '"selectionchange"' is not assignable to type '"input" | "progress" | "select" | "error" | "scroll" | "reset" | "drag" | "submit" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | ... 70 more ... | "wheel"'.
      Type 'K' is not assignable to type '"wheel"'.
        Type '"input" | "progress" | "select" | "error" | "scroll" | "reset" | "drag" | "submit" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | ... 72 more ... | "selectstart"' is not assignable to type '"wheel"'.
          Type '"input"' is not assignable to type '"wheel"'.


```

What might be the Cause of this problem . ?

**Comment by jamesmfriedman** [comment]
Typescript issues are hard to troubleshoot a repro case always helps, it usually ends up being a dependency issue

**Comment by rahulrsingh09** [comment]
@jamesmfriedman This was down to the version of typescript the stable release just came out 4 days back which has support for selectionChange.

Updating TypeScript version to at least `3.6.2` should fix this issue. In the error message we can see it's missing `selectionchange`. This event type has been added to the TypeScript DOM lib in version `3.6.2`.

### Detailed explanation

We start out in the type definitions file [`@rmwc/dialog/dist/index.d.ts`](https://unpkg.com/browse/@rmwc/dialog@5.6.0/dist/index.d.ts):

```typescript
export * from './dialog';
export * from './dialog-queue';
```

Moving on to [`dialog-queue.d.ts`](https://unpkg.com/browse/@rmwc/dialog@5.6.0/dist/dialog-queue.d.ts) we can see that it imports `@rmwc/textfield`. That's why those types even get processed even though you import the dialog package.

```typescript
import * as React from 'react';
import { SimpleDialogProps, DialogOnCloseEventT } from './dialog';
import { ArrayEmitter } from '@rmwc/base';
import { TextFieldProps } from '@rmwc/textfield';
```

Looking at [`@rmwc/textfield/dist/index.d.ts`](https://unpkg.com/browse/@rmwc/textfield@5.6.0/dist/index.d.ts) line 83 we see this:  
(parts omitted and re-formatted for readability)

```typescript
registerInputInteractionHandler:
    <K extends "error" | "input" | /*...*/ "selectionchange" /*...*/ | "wheel">
    (evtType: K, handler: SpecificEventListener<K>) => void;

```

The generic parameter `K` extends a huge union type of allowed event names. This list of names also includes `"selectionchange"`. `K` is then passed to `SpecificEventListener` which is imported from `@material/base`.

Continuing in [`@material/base/types.d.ts`](https://unpkg.com/browse/@material/base@3.1.0/types.d.ts) we see this:

```typescript
export declare type EventType = keyof GlobalEventHandlersEventMap;
export declare type SpecificEventListener<K extends EventType> = (evt: GlobalEventHandlersEventMap[K]) => void;
```

The parameter `K` from before must extend `EventType`. `keyof GlobalEventHandlersEventMap` constructs a union type of all property names of the `GlobalEventHandlersEventMap`.

Where does `GlobalEventHandlersEventMap` come from? It's defined in `lib.dom.d.ts` that ships with TypeScript itself. Looking at the version history of the file, we can see that `selectionchange` was added in [this commit](https://github.com/microsoft/TypeScript/commit/00bf32ca3967b07e8663d0cd2b3e2bbf572da88b#diff-46fd87925e4552c166ec188712741c3fR5462) for version `3.6.2`.
 
Thanks to @lukasgeiter for helping out for this solution and detailed explanation .

**Comment by jamesmfriedman** [comment]
Thanks for posting this! The typescript versions and react versions are usually the culprit. Create React App only officially supports 3.4.x right now so that would explain it as well.

**Comment by rahulrsingh09** [comment]
@jamesmfriedman Just out of curiosity as you mentioned create react app officially supports 3.4.x . If we upgrade to 3.6.2 will it break any thing. i couldn't find any break in build but just a thought .

**Comment by jamesmfriedman** [comment]
Create react app will throw a warning that anything about 3.4.x unsupported. Whether or not your app will actually build is dependent on a lot of factors other than just that so I can’t say for sure. There isn’t anything about RMWC specifically that shouldn’t work but as you saw above you can run into some uncommon errors.
