### ISSUE TITLE
Collapsible list is looking jerky while opening

### ISSUE THREAD

**Issue by kalaivanandevadas** [jamesmfriedman/rmwc#485]
RMWC Version - 5.6.0

Iam trying to write my own custom header and body for the collapsible list. But, while opening the list for that it is looking jerky. I think `max-height` is calculated wrongly while opening the list. Not sure on the issue.

Reproducible in the following sandbox,
https://codesandbox.io/s/react-example-qo2pf?fontsize=14

You can find that transition is not applied to the last item in the collapsible list.

**Comment by kalaivanandevadas** [comment]
UPDATE:

On digging into the issue, it is found that margin-block-start and margin-block-end which are applied by default to <ul> are not computed to its parents height (i.e., to `rmwc-collapsible-list__children-inner`). Hence, max-height of body component is computed with wrong height and looks jerky. I think its because of margin-collapsing.

For now, fixed this issue by setting `overflow: auto` to the `rmwc-collapsible-list__children-inner`.

**Comment by jamesmfriedman** [comment]
Thanks for investigation that. I think including them margin in the calculation would be a bad assumption to make, but I like your workaround of overflow: auto. I'll look to see if that causes any other side effects but it seems like a reasonable fix.

**Comment by jamesmfriedman** [comment]
Such a random simple fix. Confirming that it works. Will go out in the next release!

**Comment by jamesmfriedman** [comment]
Released with 5.7.0
