### ISSUE TITLE
Issues using custom list items with an enhanced Select

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#486]
When using a custom list with an enhanced select we have run into two issues:

1. Selecting an item correctly floats the label, but the label floats down again when the select loses focus.
2. The text displayed when selecting an item contains all the text from all the `ListItem` child elements and no obvious way to override this behaviour (this is certainly an MDC issue.)

Demo: https://codesandbox.io/s/jovial-night-64nbf

**Comment by jamesmfriedman** [comment]
Released with 5.7.0
