### ISSUE TITLE
Enhanced Select menu position differs from MDC

### ISSUE THREAD

**Issue by robcaldecottvelo** [jamesmfriedman/rmwc#489]
RMWC 5.7.0

When using an enhanced `Select`, the position of the menu differs from the base MDC component on the Google demo page. The MDC version positions the menu to the bottom left-hand corner of the select, whereas the RMWC version uses the top-left.

RMWC:

![image](https://user-images.githubusercontent.com/41152621/64774557-544bdf00-d54c-11e9-8184-d2c62a443e9f.png)

MDC:

![image](https://user-images.githubusercontent.com/41152621/64774606-6b8acc80-d54c-11e9-81b8-e10774150596.png)

A secondary minor issue is there does not seem to be a way to apply styles to the menu surface used by the RMWC component, so we cannot easily control the width.

**Comment by robcaldecottvelo** [comment]
Maybe the `elementRef` for an enhanced `Select` could return the underlying `Menu`?

**Comment by robcaldecottvelo** [comment]
We tried to get the width of the `Select` so we could size the menu items until we have access to the surface component props but there is no way to get a sensible `ref` to the root element as far as we can tell.

**Comment by jamesmfriedman** [comment]
This was fixed in 5.7.1
