### ISSUE TITLE
Callbacks should be optional

### ISSUE THREAD

**Issue by j-o-d-o** [jamesmfriedman/rmwc#49]
Things like onChange, onClick, onSelect etc. should always be optional. E.g. on the menus: https://jamesmfriedman.github.io/rmwc/menus if you open the console and select a menu item, there will be a TypeError in the console that onSelect is not a function. ~~Same issue with the Dialogs onClose()~~. 

It is not breaking anything, just annoying to have a bunch of Errors in the console.
I think all it takes is instead of calling the callback such as: 
`props.onSelected(evt); `
do this: 
`props.onSelected && props.onSelected(evt);`

I can take a look where I think it is missing and submit a pr if you wish.

**Comment by jamesmfriedman** [comment]
That would be excellent. I would love the contribution. 

In a lot of be api, I think I just set the default prop to a noop callback so I never had to think about it. PR would be welcomed.
