### ISSUE TITLE
Close an nested menu which has hoistToBody property will lead outer menu be closed.

### ISSUE THREAD

**Issue by JunYang-tes** [jamesmfriedman/rmwc#493]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC

Do you really want it fixed? Make a repro in the sandbox!
> - Typescript Sandbox https://codesandbox.io/s/stupefied-frog-ege5x

- What RMWC Version are you using [major.minor.patch]:
sandbox shows latest
- Name your build system [Webpack, Rollup...]:
I'm not sure.
- Describe the bug with as much detail as possible:
If inner menu has hoistToBody or not there is a different action when I try to close inner menu.
- What happened, and what was supposed to happen:
Outer menu was closed. I supposed that just inner menu be closed.

**Comment by jamesmfriedman** [comment]
I can't say that I've ever seen nested menus with RMWC. Interesting use case. For now, one option would be to make the menus controlled so they can't close. I'll look into this.
