### ISSUE TITLE
SnackbarQueue throws type error when using className or style prop

### ISSUE THREAD

**Issue by christopher-howard** [jamesmfriedman/rmwc#494]
- What RMWC Version are you using [major.minor.patch]:
"@rmwc/snackbar": "^5.7.0"

- Name your build system [Webpack, Rollup...]:
"react": "^16.8.6"
"typescript": "^3.5.2"
"@types/react": "^16.8.24"
created with create-react-app (uses webpack/babel by default), haven't ejected

- Describe the bug with as much detail as possible:
<SnackbarQueue className="test" style={{ color: 'red' }} />

- What happened, and what was supposed to happen:
Error thrown:
Property 'className' [or 'style'] does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<SnackbarQueue> & Readonly<SnackbarQueueProps> & Readonly<{ 
children?: ReactNode; }>'

Should have no error and class/style is applied to all Snackbars that appear.

- Temporary solution for other readers:
Use @ts-ignore to suppress type error like so,

        {/*
        // @ts-ignore: temp solution to type error */}
        <SnackbarQueue
          className="test"
          messages={notificationsQueue.messages}
          leading
          timeout={15000}
        />

**Comment by dohomi** [comment]
same happens to the use of `SimpleMenu` component. Pure TS error, I think you are missing to extend FunctionComponent or Component of React in the typings

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0.
