### ISSUE TITLE
Dialog is not opened in IE11

### ISSUE THREAD

**Issue by Lodin** [jamesmfriedman/rmwc#497]
> ## RMWC or MDC?
> 
> RMWC is a React wrapper for Google's official MDC that provides a props based interface for their components. Is the bug being caused by RMWC, or MDC? Please do your best to track down where the bug is originating from and post your issue to the proper repository. MDC bugs should be filed here https://github.com/material-components/material-components-web/issues.

It is definitely RMWC issue: if you take a look at the repro, you would see that the bare MDC dialog added for comparison works as expected.

> Do you really want it fixed? Make a repro in the sandbox!
> > - Javascript Sandbox https://codesandbox.io/s/kpy13vqnr
> > - Typescript Sandbox https://codesandbox.io/s/kl0w4xp95

Repro could be found [here](https://github.com/Lodin/rwmc-dialog-bug-repro). Unfortunately, codesandbox has bad support for the IE, so I prepared the repository only.

- What RMWC Version are you using [major.minor.patch]:
5.7.0
- Name your build system [Webpack, Rollup...]:
Webpack (through `create-react-app`).
- Describe the bug with as much detail as possible:
Dialog is not opened in IE11. No classes responsible for opening (`mdc-dialog--opening`, `mdc-dialog--open`) appear in the HTML code.
- What happened, and what was supposed to happen:
Dialog should open in IE11 as well as in other browsers.

**Comment by Lodin** [comment]
I found the source of the error. It was the native IE `Set` that is unable to work with with Babel `_spread` function. To solve the error you need to add the `Set` polyfill.

**Comment by jamesmfriedman** [comment]
Good to know, thanks for reporting that. IE11 support is definitely unknown, not sure how much longer google will support it either.
