### ISSUE TITLE
Add option to change default escape key action for dialog

### ISSUE THREAD

**Issue by Azolaan** [jamesmfriedman/rmwc#499]
Hello! It would be nice if the option to change the default behavior of the escape key (specifically to disable it) were exposed as an option for the Dialog component. I know that MDC has the option to set this property via the `setEscapeKeyAction()`  method but it doesn't look like that functionality is made available in RMWC. It would be great if there was a property that could change this default behavior.

**Comment by jamesmfriedman** [comment]
Agreed. Question with that, right now there is a prop `disableOutsideClick`. I'd imagine you would want that to be the same behavior? Is there a case where you would want to be able to click outside to close while also disabling the escape key?

**Comment by Azolaan** [comment]
For my current use case I would want the behavior to be the same as `disableOutsideClick`. I don't imagine there would be a case where you would want differing behaviors.

**Comment by jamesmfriedman** [comment]
Cool. I'll probably deprecate that prop and rename it then to something like `disableDismiss`. Any suggestions on what resonates with you?

**Comment by tata81** [comment]
@jamesmfriedman How does this sound ? `disableEscapeKeyDown,`?

**Comment by Subha27** [comment]
Is there any workaround to disable dialog on Escape key till the feature is available ?

**Comment by jamesmfriedman** [comment]
https://codesandbox.io/s/mystifying-snowflake-tqnmn

That should work as a workaround, but you need to check that it's actually the escape key

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0.
