### ISSUE TITLE
Why the CSS files aren't imported by the components that use them?

### ISSUE THREAD

**Issue by mrjeanp** [jamesmfriedman/rmwc#502]
## The real pain is keeping track of the styles that are already included

For example, the Menu component should do this in the component file:
```js 
import '@material/menu/dist/mdc.menu.css';
import '@material/menu-surface/dist/mdc.menu-surface.css';
import '@material/list/dist/mdc.list.css';
```
Can you spot the problem here?
```js
import '@material/drawer/dist/mdc.drawer.css';
import '@material/list/dist/mdc.list.css';
import '@material/top-app-bar/dist/mdc.top-app-bar.css';
import '@material/textfield/dist/mdc.textfield.css';
import '@material/floating-label/dist/mdc.floating-label.css';
import '@material/notched-outline/dist/mdc.notched-outline.css';
import '@material/line-ripple/dist/mdc.line-ripple.css';
import '@material/layout-grid/dist/mdc.layout-grid.css';
import '@material/icon-button/dist/mdc.icon-button.css';
import '@rmwc/tooltip/tooltip.css';
import '@material/select/dist/mdc.select.css';
import '@material/floating-label/dist/mdc.floating-label.css';
import '@material/notched-outline/dist/mdc.notched-outline.css';
import '@material/line-ripple/dist/mdc.line-ripple.css';
import '@material/list/dist/mdc.list.css';
import '@material/menu/dist/mdc.menu.css';
import '@material/menu-surface/dist/mdc.menu-surface.css';
import '@material/typography/dist/mdc.typography.css';
```
Answer: many styles are repeated, I just copied the Menu styles. Now i have to remove the repeated styles manually. 

Importing out of the box shouldn't be an issue because all classes are namespaced with `mdc-` and the files are not being repeated because webpack loads them once. It will save a lot of time whenever we want to install a new component (avoid creating a custom component that imports these styles).

I know the library tries to be un-opinionated but some opinion is good!

**Comment by jamesmfriedman** [comment]
In a project that is using create react app and webpack, I agree with you. As soon as you start to consider other methods of including styles this breaks down. 

Not all build systems include css loaders and there are many reasons you would want to keep the css separate (separate build process for css, no build process at all). Also some people use SASS for this project as well which is a separate compile process which means importing the css would be the wrong behavior. 

The simplest way that I’ve personally worked around this is to have a styles.js / styles.ts file at the root of the project that uses all of the import statements I need to pull in. I also keep the imports this file alphabetical with the exception of a few imports that should come first (theme is an example). 

I’m unsure about the idempotence of importing a css file (will importing the same file twice do a double import?). If webpack automatically resolves duplicate imports then there would be no harm in just dumping all the things in a file blindly. I believe that it will only include the file contents once in the bundle but  it will insert the style tag twice causing weird issues and degraded css performance. 

Happy to brainstorm, I just know with certainty that adding inline imports inside the component will break people. I could add a single styles.js file per component to import, but I believe you’ll run into the same issue I mentioned above which is double style tag inclusion.

**Comment by mrjeanp** [comment]
How about a different file that exports the component and imports the css?
```js
// file: @rmwc/component/button/index.js

import '@material/button/dist/mdc.button.css';
export { Button } from "@rmwc/button";
```

Now all we have to do is 
```js
import { Button } from "@rmwc/component/button";

function App() {
  return (
    <Button/>
  )
}
```

What do you think?

**Comment by jamesmfriedman** [comment]
I’m not opposed to it. There’s just a lot to maintain as it stands. Something like you’re describing is easy to setup, easy to forget, and hard to write a unit test for since it relies on a working webpack build system :/

**Comment by j-o-d-o** [comment]
I think there are so many different possibilities on how to include styles and build your web app that I would very much vote to keep the strict un-opinioned separation of js/ts and css.
I am quite certain that somehow some use-case will be destroyed or at the very least will have some performance loss or confusing bugs with such a change.

**Comment by jamesmfriedman** [comment]
This is definitely going to be out of scope. @j-o-d-o is right, there are just too many ways to include styles in your app these days. While the suggestion may seem convenient, it's likely to cause edge cases and maintainability issues just for a bit of developer convenience
