### ISSUE TITLE
Error running rmwc in mocha

### ISSUE THREAD

**Issue by jrajav** [jamesmfriedman/rmwc#503]
- What RMWC Version are you using [major.minor.patch]: 5.7.0

- Name your build system [Webpack, Rollup...]: Babel (Webpack too, but not used for Mocha tests)

- Describe the bug with as much detail as possible:

When running RMWC 5.7.0 inside of Mocha with babel-register (Mocha version 6.0.2), an error is thrown that Element doesn't exist.

- What happened, and what was supposed to happen:

```
ReferenceError: Element is not defined
      at Object.exports.closest (/home/jrajav/Development/myrepo/node_modules/@rmwc/menu/node_modules/@rmwc/base/dist/utils/ponyfills.js:4:28)
      at MenuSurface.componentDidMount (/home/jrajav/Development/myrepo/node_modules/@rmwc/menu/dist/menu-surface.js:89:33)
```

- Mitigation:

Mocking out Element on global in the Mocha setup script fixes the issue, but ideally this wouldn't be necessary:

```
global.Element = () => {}
```

- Similar-looking issues elsewhere:

https://github.com/component/matches-selector/issues/13
https://github.com/material-components/material-components-web-react/issues/561

**Comment by jamesmfriedman** [comment]
Mat-web relies on regular dom and JavaScript. Since RMWC just wraps it, it is definitely a dependency of some components even in testing. Not sure about your test setup but running in a JSDOM like environment is likely a hard requirement for testing which would explain the need to mock Element.

**Comment by jamesmfriedman** [comment]
Was that helpful at all ^?

**Comment by jamesmfriedman** [comment]
Reopen if you have some more context, but you definitely need Dom polyfills. If you have information on running with Mocha, it would be awesome to add some documentation for it. I'm only familiar with Jest.
