### ISSUE TITLE
Using ref with scrollTarget on TopAppBar

### ISSUE THREAD

**Issue by cpboyd** [jamesmfriedman/rmwc#505]
`scrollTarget` was added in response to #430.

I'm migrating from mdc-react since this stays more up-to-date with MDC releases.

mdc-react provided a ref option: https://github.com/material-components/material-components-web-react/blob/master/packages/top-app-bar/index.tsx#L50

Using a static `Element` seems to prevent me from referencing an element in the current component, likely because `scrollRef.current` gets dereferenced prior to the the ref is actually created.

```
render() {
  const scrollRef = useRef<Element>();

  return (
    <nav ref={scrollRef} className={getNavigatorClasses()}>
          <TopAppBar fixed scrollTarget={scrollRef.current}>
            <TopAppBarRow>
              <TopAppBarSection>
                <TopAppBarTitle>Title</TopAppBarTitle>
              </TopAppBarSection>
            </TopAppBarRow>
          </TopAppBar>
      <ul className="mui-list mdc-top-app-bar--fixed-adjust">
...
      </ul>
    </nav>
}
```

Repro:
https://codesandbox.io/s/awesome-visvesvaraya-5h6gx

- What RMWC Version are you using [major.minor.patch]:
`5.7.1`

- Name your build system [Webpack, Rollup...]:
Gatsby

- Describe the bug with as much detail as possible:
`scrollTarget` doesn't accept `ref`, so it's difficult to add a reference to another scroll target in the same component.

- What happened, and what was supposed to happen:
To be more React-friendly, it seems like the component should accept a `ref`.  Potentially keeping the option to specify `scrollTarget` or `scrollTargetRef`.

**Comment by cpboyd** [comment]
I've added a repro: https://codesandbox.io/s/awesome-visvesvaraya-5h6gx

Note how the fixed toolbar does not gain the shadow as the `scrollTarget` is scrolled.

**Comment by jamesmfriedman** [comment]
Actively looking into this, will let you know what I find. Thanks for the repro

**Comment by jamesmfriedman** [comment]
Finally getting back around to this.

Turns out a ref won't work anyways. React doesn't take refs into account for things like useEffect as they can change without updating state. The solution is to just keep the scroll target in a stateful variable to force react to re-render. Here is a working example.

https://codesandbox.io/s/reverent-austin-16zzi
