### ISSUE TITLE
Broken outline when using with TailwindCSS (fixed)

### ISSUE THREAD

**Issue by loicnestler** [jamesmfriedman/rmwc#506]
- What RMWC Version are you using [major.minor.patch]:
"@rmwc/textfield": "^5.7.0"

- Name your build system [Webpack, Rollup...]:
"next": "9.0.6"
"react": "16.9.0"
"tailwindcss": "^1.1.2"
created with create-next-app
I just added TailwindCSS to my project

- Describe the bug with as much detail as possible:
The TextField's active outline gets broken, when using with TailwindCSS.
![inactive](https://user-images.githubusercontent.com/48695625/67076956-7d384300-f18e-11e9-9c0d-2a44a78cc8f6.png)
![active](https://user-images.githubusercontent.com/48695625/67076980-85907e00-f18e-11e9-8b50-1393743a0557.png)

- Example:
  - [codesandbox](https://codesandbox.io/s/rmwc-sandbox-pisji)

**Comment by lspr98** [comment]
If anyone else is stumbling upon this, I managed to maintain the original TextField behaviour using:

`
.fix-textfield {
    .mdc-notched-outline__notch {
        border-left: none;
        border-right: none;
    }
}
`

And then apply it to the Textfield

`
<TextField className="fix-textfield" outlined ..../>
`
