### ISSUE TITLE
The import styles for Icons in the rmwc documentation were not working for me.

### ISSUE THREAD

**Issue by Dagofcode** [jamesmfriedman/rmwc#508]
This import '@rmwc/icon/icon.css' that is in the rmwc docs https://rmwc.io/icons did not work on my app. 

In order to get the styles for the icons working properly i had to install material-design-icons
and do this import 'material-design-icons/iconfont/material-icons.css' but it's not optimal since material design icons installs other stuff that I dont use. Is there something I'm doing wrong?

**Comment by jamesmfriedman** [comment]
This is present in the installation docs under optional steps. I can reiterate the same points on the icon docs page.

https://rmwc.io/installation

**Comment by jamesmfriedman** [comment]
Did that resolve your issue?

**Comment by Dagofcode** [comment]
I did end up using this method, I think it would be best to include it in the Icons section since it wasn't too specific on that part of the documentation.

**Comment by jamesmfriedman** [comment]
Will add with the next update, and leave this open to track.

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0.
