### ISSUE TITLE
Chip styles not working 

### ISSUE THREAD

**Issue by weiserhase** [jamesmfriedman/rmwc#509]
I now have a problem with Chips styles,
since 2 or 3 months the chip styles look very bad on my side 
We updatet rmwc but the problem remains on every browser exept firefox mobile 
there the styles work perfect

![Screenshot (74)](https://user-images.githubusercontent.com/44242102/67617994-58287d80-f7e9-11e9-9d63-7a927133d0bb.png)
![WhatsApp Image 2019-10-26 at 09 35 06](https://user-images.githubusercontent.com/44242102/67617983-1b5c8680-f7e9-11e9-8b02-f2eebfe1aaef.jpeg)

**Comment by jamesmfriedman** [comment]
It’s likely related to some local styles you have interfering. Can you provide a repro?

**Comment by weiserhase** [comment]
The Issue is located in \src\modules\cash_register\itempick\cash.js
https://github.com/knarxy/mpg-sas2020

**Comment by jamesmfriedman** [comment]
That’s a private repository. 

If you can reproduce your issue using the provided code sandbox I might be able to be of some help. It’s unlikely to be a problem with RMWC and more likely to be an issue with how you have it setup, or are importing the chip styles.

**Comment by weiserhase** [comment]
ok thanks
