### ISSUE TITLE
Update to Material Components Web 5.0

### ISSUE THREAD

**Issue by fjorgemota** [jamesmfriedman/rmwc#510]
Hey, thanks for this nice project. =)

This package still uses Material Components Web 3.10. But version 4.0 of the Material Components Web was released yesterday (2019-11-02) with [some quite big changes](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#400-2019-11-02).

**Comment by jamesmfriedman** [comment]
Lol yep. Takes a bit more than a day to get an update out after them, I usually trail 2-4 weeks but thanks for the heads up. I’ve been talking  with some people from that team for a while so I’m excited to see what’s new.

**Comment by j-o-d-o** [comment]
And here we go again. I am not sure what's more complicated. Rocket science or building a robust select component :D To be fair, I think the changes to the select very much make sense.

**Comment by jamesmfriedman** [comment]
I wish they would build new ones instead of continuing to break old ones, but I enjoy the challenge :)

**Comment by fjorgemota** [comment]
I agree totally with the fact that new components would be more welcome than breaking old ones, specially when these breakages have removal of features (for example, the new mdc-select doesn't support multiple selections, which was supported by the old native select component..).

**Comment by jamesmfriedman** [comment]
@fjorgemota got an empty PR going for this, I use their changelog as the checklist for checking and cross referencing so that should give you some visibility into this. Still hoping I can keep this to a non breaking release, I'm going to figure out a way to keep native selects around ;).

**Comment by fjorgemota** [comment]
@jamesmfriedman Nice! If you want I can just put that checklist on this issue, as a meta-issue, so everything can be tracked here, instead of on the PR.

The native selects update should be the harder to do right, I think. The other changes are a bit...small, it seems.

**Comment by jamesmfriedman** [comment]
RMWC is undergoing another massive transformation (about the 3rd one since it's been alive). Converted the whole internal api to hooks, and got rid of the abstractions to make everything look like idiomatic react. Published a 6.0.0 alpha release which you can install with rmwc@next or the individual components.

The mdc 4.x.x updates will be going in along with it, but had to get the api moved over first. Feedback welcomed.

**Comment by ryanolsonx** [comment]
As 5.x.x is out for mdc, would that be the target for version 6.0.0 of this?

**Comment by jamesmfriedman** [comment]
I did see that the other day. Yes that will be the target version for 6.0.0, I want to make sure I have all of the revisions in place from mdc 4 first.

**Comment by jamesmfriedman** [comment]
Update on this, branch is approaching release. Got everything updated to 5.x, just bug squashing and testing.

**Comment by jamesmfriedman** [comment]
Fixin in 6.0.0.
