### ISSUE TITLE
Drawer: dismissible drawer doesn't open

### ISSUE THREAD

**Issue by cpboyd** [jamesmfriedman/rmwc#516]
This may potentially be an MDC bug, but it's compounded by:
https://github.com/jamesmfriedman/rmwc/blob/master/src/drawer/index.tsx#L212

If the open parameter is already set, the open function does not get called.

I've managed to get my app (albeit inconsistently) into a funky state where the drawer should be open, but isn't.

If I can figure out how to consistently reproduce it, I'll work on a simplified repro.

- What RMWC Version are you using [major.minor.patch]: `5.7.1`

- Name your build system [Webpack, Rollup...]: `gatsby` / `webpack`

**Comment by cpboyd** [comment]
Potentially related to the issue you've already filed over at mdc:
https://github.com/material-components/material-components-web/issues/4357

The `mdc-drawer--open` class never gets applied for some reason.

**Comment by jamesmfriedman** [comment]
Can you be a bit more specific. Are you saying if the prop starts as open the drawer never gets the open class?

**Comment by cpboyd** [comment]
@jamesmfriedman I'm using the drawer for navigation.
What I *think* is happening is that the state is changing before the foundation `open()` / `close()` finishes.

The only thing I know for certain is that the state of `open` on the React component is `true`, but the `mdc-drawer--open` class never gets applied to the drawer element.

**Comment by jamesmfriedman** [comment]
A repro would definitely help if you get a chance :)

**Comment by cpboyd** [comment]
@jamesmfriedman My bad. I added a `transition` CSS to the `Drawer` component, which overrode the `transition-property` resulting in the `transform` not animating properly.

As a result, the `mdc-drawer` didn't transition between states properly.

**Comment by jamesmfriedman** [comment]
No worries man. Happens to the best of us.
