### ISSUE TITLE
Ability to add className prop to root elements of components

### ISSUE THREAD

**Issue by bruqui** [jamesmfriedman/rmwc#517]
I would like to be able to add my own className prop to the root level element of the RMWC components (SimpleMenu is one I know of currently) so I can add additional styling through SASS when needed.
 
> - Javascript Sandbox https://codesandbox.io/s/rmwc-sandbox-62fee

- What RMWC Version are you using [5.7.0]:

- Name your build system [Webpack, Rollup...]: Gatsby

**Comment by j-o-d-o** [comment]
For `SimpleMenu` the `rootProps={{className: "test-name"}}` should work. For the `TextField` the className is directly passed to the root and not to the `input`. You could then do something such as `.my-textfield input { ... }`.
Granted a bit inconsistent. Especially since the docu says:

> By default, props spread to the input. These props are for the component's root container.

**Comment by bruqui** [comment]
Closing... you are correct. :)
