### ISSUE TITLE
rmwc Tab Components Overlaps if there are tab inside tab

### ISSUE THREAD

**Issue by rahulrsingh09** [jamesmfriedman/rmwc#518]
If we have a tab inside tab the inner tab overlaps the outer tab if the scroll length is more, and setting the z-index only seems to help , is there a better solution to this

**Comment by jamesmfriedman** [comment]
You'll need to provide an example, not sure what you're talking about. Why would you have a tab inside another tab?

**Comment by rahulrsingh09** [comment]
You can have Tab Inside tab , Say i want to show some charts Inside a Tab and that Charts has two facets to it which i want it as a Tab View then we end up having it . i will show you a small example with a screenshot here

![image](https://user-images.githubusercontent.com/17721520/68886949-1df23200-073e-11ea-9389-dc7bdcd0a45f.png)

Normal Two Tabs 

Now once i scroll the bottom tab overlaps the top tab .

![image](https://user-images.githubusercontent.com/17721520/68887003-38c4a680-073e-11ea-8006-bba9ec501682.png)


I hope this images makes it clear

**Comment by jamesmfriedman** [comment]
ah yes thank you, that makes more sense. It looks like this is just a problem with how your app si setup. The container that the second level of tabs is in should be overflow hidden. Another solution is what you're mentioning, just correcting the z-index on the affected elements. This isn't a bug, just a reality of laying out stuff in CSS.

**Comment by rahulrsingh09** [comment]
I am not quite sure of the first approach my tab is set to overflow:auto as the text is too big and i donot want he user to keep scrolling till end of page i have some anchors for him to got , overflow of the outer tab is not a option. and z-index is a costly game as if we have modals and all it will  add further problems as we need to manually add it up. should this be taken care automatically as both have same background and the text overlaps strange . this dosen't happen with other html elements

**Comment by jamesmfriedman** [comment]
You can open up an issue with mat-web since they’re in control of the CSS, and likely give them a code repro to help them understand the issue.

**Comment by jamesmfriedman** [comment]
Closing this, please open an issue upstream with MDC
