### ISSUE TITLE
Collapsible List isnt closing

### ISSUE THREAD

**Issue by weiserhase** [jamesmfriedman/rmwc#520]
I just implemented the collapsible list. But the List is never closed state it shows the collasible div the whole time even if I try to close it with open = {false} 
`
    transactionDetails(i){
        this.setState({detailDialog: true})
        if(this.state.detailDialog == true){
            console.log('in transactionDetail')
            let dialog = []
        
        }
    }
    render() {
        if(this.state.initLoad) {
            this.loadData();  
            return <Card id="Transactions"><Loading active={true}></Loading></Card>
        }
        if(!this.state.fetched) {
            this.loadData()
        } else {
            this.state.fetched = false
        }
        var tr = this.state.data.transactions
        for(var i = 0; i < 3 ; i++){
            if(this.state.data.transactions[i].value> 999999999){
                tr[i].value = (tr[i].value /1000000000).toFixed(2) +' Mrd'
            }
            if(this.state.data.transactions[i].value > 999999){
                tr[i].value = (tr[i].value /1000000).toFixed(2) + ' M'  
            }
            if(this.state.data.transactions[i].value > 999){
                tr[i].value = (tr[i].value /1000).toFixed(2) + ' K'
            }
        }
        this.tr = tr
        Moment.globalFormat = 'DD.MM.YYYY | HH:MM';
        this.temptable = []
        for(var i = 0; i <3; i++){
            this.temptable.push(
                    <CollapsibleList                                        
                    onOpen={() => console.log('open')}
                    onClose={() => console.log('close')}
                        handle={
                            <SimpleListItem
                                text= {<Moment unix>{this.tr[i].timestamp}</Moment> + this.tr[i].type+' '+this.tr[i].direction+' '+this.tr[i].targetName +   this.tr[i].value+' $ ' }
                                graphic="help"
                                metaIcon="chevron_right"
                            />
                        }
                    >
                        <div style={{ padding: '0.5rem',}}>
                            test
                        </div>
                    </CollapsibleList>

            )                 
        }
        return(
            <Card id="Transactions">
                <List>
                <CollapsibleList
                    handle={<IconButton icon="favorite_outline" onIcon="favorite" />}
                    onOpen={() => console.log('open')}
                    onClose={() => console.log('close')}
                    >
                    <div
                        style={{
                        padding: '1rem',
                        background: 'red',
                        color: 'white',
                        display: 'inline-block'
                        }}
                    >
                        Favorited!
                    </div>
                    </CollapsibleList>
                    {this.temptable}
                </List>
            </Card>
        )      
    }
}
`

**Comment by jamesmfriedman** [comment]
Can you make a repro using the code sandbox?

**Comment by weiserhase** [comment]
ok i will do this later

**Comment by weiserhase** [comment]
I fixed it i havent importet the style for the list 
Withouot the style it doesn't work

**Comment by jamesmfriedman** [comment]
Cool. That’s why that sandbox always helps, it isolates whether or not it was just an issue like that ;). 

Anything that the docs could’ve done to help remind you?
