### ISSUE TITLE
Import helpers from tslib

### ISSUE THREAD

**Issue by ben-mckernan** [jamesmfriedman/rmwc#522]
RMWC 5.7.0

Currently the helper methods for assign, rest, spread, etc. are inlined in each file. This leads to a lot of duplication in our bundled code. Also since we are using rollup these methods are hoisted to the top level which results in "this has been rewritten to undefined" warnings.

How would you feel about setting `"importHelpers": true` in your TS compiler options? It would probably mean you need to add `tslib` as a dependency in each package that uses these helpers. But it would result in a nice drop in bundle size for users of this library.

**Comment by jamesmfriedman** [comment]
Love it. Actually stumbled across this the other night when I started analyzing bundle size. Definitely putting this in for the next release.

**Comment by jamesmfriedman** [comment]
Great callout, check it out, already down 60K from previous versions :) 

https://bundlephobia.com/result?p=rmwc@6.0.0-alpha.6

**Comment by jamesmfriedman** [comment]
The jump in 5.7.1 was the inclusion of tooltips, going to address that as well, but this was a major help

**Comment by ben-mckernan** [comment]
Brilliant! I'm glad it was an easy win 😄

**Comment by Lodin** [comment]
Wouldn't it be better to use babel compiler instead of typescript? And `@babel/runtime` instead of `tslib`?

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
