### ISSUE TITLE
How do we add ellipses for a Select Box Dropdown Text if the width is less ?

### ISSUE THREAD

**Issue by rahulrsingh09** [jamesmfriedman/rmwc#523]
Add Ellipses for Select Box when the Width of the text is more than the width of the Select box

Is there any way to set ellipses to the text ?

**Comment by jamesmfriedman** [comment]
I would open an issue with mdc to fix it, but an easy fix yourself is to use a combination of overflow hidden on the text container and text-overflow: ellipsis

**Comment by rahulrsingh09** [comment]
Adding text-overflow: ellipsis and hidden as overflow dosent seem to help too, that was the reason i had to open issue . it dosent seem to adhere to the css if i add it

**Comment by jamesmfriedman** [comment]
Hi, looked into this a bit more. This is actually a limitation of HTML and CSS in general. If you google the issue, there are lots of people trying to solve this. Short answer, doesn't appear to be possible with just CSS.

Google Search
https://www.google.com/search?q=html+select+text-overflow&oq=html+select&aqs=chrome.0.69i59j69i57.1344j0j4&sourceid=chrome&ie=UTF-8

This is a hack someone found, basically involves setting the text to the abridged value.
https://codepen.io/nikitahl/pen/vyZbwR

Whatever the particular solution is, it's likely out of scope for this library. One option you could employ if you can detect that the text is overflowing is to manually position an elipsis using :before or :after of the <select> elements parent container.

**Comment by jamesmfriedman** [comment]
Going to close this since it's a problem with HTML / CSS as a whole.
