### ISSUE TITLE
How to override default material icons to font awesome icons?

### ISSUE THREAD

**Issue by puru0019** [jamesmfriedman/rmwc#525]
**How to override default material icons to font awesome icons?**

In the below documentation url I can see entire icon set can be overridden
https://rmwc.io/provider

**Actual implementation**

`<RMWCProvider`
`icon={{ basename: 'material-icon' }}>`
`.......`
`.......`
`</RMWCProvider>`

**Expected Implementation(Which is not working)** 

`<RMWCProvider`
`icon={{ basename: 'fontawesome' }}>`
`.......`
`.......`
`</RMWCProvider>`

Still can see material icons are getting loaded instead of fontawesome icons

@jamesmfriedman

**Comment by jamesmfriedman** [comment]
I can update the docs with a more clear example, but read the icons section a little deeper. There is an example using ion icons about halfway down the page that is basically exactly what you want. All icon libraries work a bit different, for font awesome, you would need to do something like this...

1) Add the icon font via css somewhere in your app according to the directions on the font awesome site
2) According to their docs, an icon looks something like this `<i class="fas fa-camera"></i>` https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
3) with RMWC:
```jsx
<RMWCProvider icon={{
  strategy: 'className', // the method font awesome uses
  basename: 'fas', // the standalone classname
  prefix: 'fa-' // the prefix on the icon name
}}>
  <Icon icon="camera"/>
</RMWCProvider>


```

**Comment by puru0019** [comment]
I tried as you said and it resulted in two Icon tags on inside another

![image](https://user-images.githubusercontent.com/23036485/69931023-c1d42f80-14eb-11ea-90bb-f1c6ccfac8ad.png)

Is that valid? Because I am still getting material-icon as well

**Comment by jamesmfriedman** [comment]
Can you send the related code as well?

**Comment by puru0019** [comment]
Sorry I think I made a mistake

`<RMWCProvider`
       ` ripple={ripple}`
       ` icon={{`
          `strategy: 'className',`
          `basename: 'fas',`
          `prefix: 'fa-',`
       ` }}`
      `>`
`<Snackbar`
  ` icon={(<Icon name="close">)}`
`/>`
`</RMWCProvider>`

I Should not pass icon component directly but should pass icon name as below.This resolved the issue

`<RMWCProvider`
       ` ripple={ripple}`
       ` icon={{`
          `strategy: 'className',`
          `basename: 'fas',`
          `prefix: 'fa-',`
       ` }}`
      `>`
`<Snackbar`
  ` icon='close'`
`/>`
`</RMWCProvider>`

**Comment by puru0019** [comment]
Sorry I think I made a mistake

`<RMWCProvider`
       ` ripple={ripple}`
       ` icon={{`
          `strategy: 'className',`
          `basename: 'fas',`
          `prefix: 'fa-',`
       ` }}`
      `>`
`<Snackbar`
  ` icon={(<Icon name="close">)}`
`/>`
`</RMWCProvider>`

I Should not pass icon component directly but should pass icon name as below.

`<RMWCProvider`
       ` ripple={ripple}`
       ` icon={{`
          `strategy: 'className',`
          `basename: 'fas',`
          `prefix: 'fa-',`
       ` }}`
      `>`
`<Snackbar`
  ` icon='close'`
`/>`
`</RMWCProvider>`

But still my font awesome icon is not applied
![image](https://user-images.githubusercontent.com/23036485/69932532-863c6400-14f1-11ea-820d-e46ed7a3c2f8.png)

**Comment by jamesmfriedman** [comment]
Thanks for that, I can dig into this now. What you posted should work now, so it might be a bug.

**Comment by jamesmfriedman** [comment]
Not sure what you have going on in your app, but it's definitely working. I just included font awesome from the CDN in the index.html file.

https://codesandbox.io/s/youthful-paper-x20qp

**Comment by puru0019** [comment]
Yes its actually working in your code. I think I will check my code again where it went wrong. Thank you for spending some time on this

**Comment by jamesmfriedman** [comment]
Any update on this?

**Comment by puru0019** [comment]
This issue was causing because I am using older versions of @rmwc/provider and @rmwc/snackbar. I have updated them to latest version and issue is resolved.
