### ISSUE TITLE
grid align property uses the wrong style

### ISSUE THREAD

**Issue by giles7777** [jamesmfriedman/rmwc#526]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

RMWC is a React wrapper for Google's official MDC that provides a props based interface for their components. Is the bug being caused by RMWC, or MDC? Please do your best to track down where the bug is originating from and post your issue to the proper repository. MDC bugs should be filed here https://github.com/material-components/material-components-web/issues.

Do you really want it fixed? Make a repro in the sandbox!
> - Javascript Sandbox https://codesandbox.io/s/kpy13vqnr
> - Typescript Sandbox https://codesandbox.io/s/kl0w4xp95

- What RMWC Version are you using [major.minor.patch]:
5.7.1
- Name your build system [Webpack, Rollup...]:
react-app which I think uses Webpack

- Describe the bug with as much detail as possible:

When using the Grid align property it uses this MD css class(taken from grid/index.tsx):
mdc-layout-grid__cell--align-${props.align || ''}`

I think this should be(remove the cell for the root changes):
mdc-layout-grid--align-${props.align || ''}`

- What happened, and what was supposed to happen:
The alignment doesn't work.  I can manually make it work by adding:

className="mdc-layout-grid--align-left" on the Grid element instead of using the property

**Comment by jamesmfriedman** [comment]
You are correct, thanks for reporting

**Comment by jamesmfriedman** [comment]
Released and fixed in 5.7.2
