### ISSUE TITLE
button hover not working 

### ISSUE THREAD

**Issue by lordvoldemortrocks** [jamesmfriedman/rmwc#527]
Hi, I'm trying to use RMWC's Button component in my app but hovering over it doesn't change its background color. I was successful in trying to reproduce the issue on Sandbox (linked below). 

I used the Sandbox on your main Github page to reproduce the issue. I couldn't help but notice that even though your Getting Started guide says that `material-components-web` should be installed, it is NOT installed on your Sandbox; and still the demo is importing `material-components-web/dist/material-components-web.min.css` and it's working fine - the hover works. When I actually install the dependency, it seems to stop working (hover doesn't change background color). Can someone please explain how the demo is working fine.  

Sandbox Link: https://codesandbox.io/s/rmwc-sandbox-yt7r8
Version: 5.7.1

**Comment by jamesmfriedman** [comment]
The code from the docs is all you need. Usually something like this means you either forget to include the style sheets listed at the top of the docs page, or you have other css included in your app that is breaking the button styling. The sandbox just imports the entire css file for convenience, as noted in the setup guide.

**Comment by lordvoldemortrocks** [comment]
There's no css in the Sandbox I linked above and it still doesn't seem to work. The only difference my Sandbox has compared to the one mentioned on your README is that I actually installed the `material-components-web` package. 

How does your Sandbox work without installing the `material-components-web` package? How does that `import "material-components-web/dist/material-components-web.min.css";` work?

**Comment by jamesmfriedman** [comment]
I think you sent me a different sandbox link then you meant to. The link you sent DOES have the import of the material CSS. If you can send me a reproduction of your issue I'd love to help, the link you sent is working properly.

Here is another sandbox link, only including the button css file. It is also working as expected.
https://codesandbox.io/s/rmwc-sandbox-05t66

To reiterate what is in the getting started guide, there is an optimized way (individual components) and a Lazy developer / non optimized way which is installing the entire rmwc package. Importing the material-components-web.min.css file is the lazy way. It comes in as a dependency of the `rmwc` package. If you look in the repo, it's listed on this line, along with all of the other components. https://github.com/jamesmfriedman/rmwc/blob/45d947a05b243c52a0634777392cb77eaac77800/src/rmwc/package.json#L83

**Comment by lordvoldemortrocks** [comment]
Okay, so I was installing material-components-web because I thought rmwc needs it as a peer dependency. The latest stable version for that right now is 4.0.0, and maybe it overrides some styling but after installing that, hover didn't seem to be working. I uninstalled it and it's working now. 

Thanks!

**Comment by jamesmfriedman** [comment]
Awesome. Yes that makes sense that it would cause an issue. RMWC is pinned to the specific versions it works with.
