### ISSUE TITLE
Select: feature proposal

### ISSUE THREAD

**Issue by j-o-d-o** [jamesmfriedman/rmwc#53]
I often find myself that I want to use the select component to select for an array of objects. Then I have to create something like `{1: "label_1", 2: "label_2",... }` with the keys corresponding to the index of the original array of objects. It would be much easier to pass the objects as options and specify a key for the labels. and on select e.target.value would hold the selected object. 

Is that something that could be in the rmwc package or should this be left to the developer? Or am I missing something and there is a ways easier solution already in place?

**Comment by jamesmfriedman** [comment]
right now we can pass options in 3 ways
- as an array which will be used as both the label and value `['One', 'Two', 'Three']`
- an object of value -> label `{one: 'One', two: 'Two', three: 'Three}`
- directly as children
```
<Select
  value={text('value', 'Cookies')}
  onChange={evt => action('onChange: ' + evt.target.value)()}
>
  <ListItem role="option" id="Cookies" tabIndex="0">
    Cookies
  </ListItem>
  <ListItem role="option" id="Pizza" tabIndex="-1" aria-disabled="true">
    Pizza
  </ListItem>
  <ListItem role="option" id="Icecream" tabIndex="0">
    Icecream
  </ListItem>
</Select>
```

There is some work that needs to be done to improve the select handling, by I have no issue with supporting a variety of common ways to populate the select. Your case makes sense, I can see about adding it.

Related to #44 #43

**Comment by j-o-d-o** [comment]
Oh, didn't read carefully enough through the issues, sorry. I think it's best to close this and continue in #44.
