### ISSUE TITLE
fullwidth Outlined Textfield breaks 

### ISSUE THREAD

**Issue by nkumnberlin** [jamesmfriedman/rmwc#530]
- What RMWC Version are you using [major.minor.patch]:  latest

- Name your build system [Webpack, Rollup...]: webpack

- Describe the bug with as much detail as possible:
https://rmwc.io/text-fields -> second one from the Top: Outlined.
As soon as you add fullwidth as prop it breaks. 

- What happened, and what was supposed to happen:
Should not break.

**Comment by jamesmfriedman** [comment]
This is a documented shortcoming of MDC. I can build a warning for the console that complains when both are set. 

Honestly it makes no sense that they did it that way anyways, just use css or the style prop to set an outlined text field to width 100%

**Comment by wmadden** [comment]
It would be good to use a representation that prevents people choosing both at the same time, e.g. `variant: "filled" | "outlined" | "fullwidth" = "filled"`

**Comment by jamesmfriedman** [comment]
Some components in this library can have a large number of possible prop combinations which makes the concept of variant hard to maintain. Would be easier and more straight forward to add a warning in the console for this.
