### ISSUE TITLE
TopAppBar issue with webpack / electron

### ISSUE THREAD

**Issue by jfily** [jamesmfriedman/rmwc#531]
Hi,

I'm trying to migrate from @material/react and I have some troubles with TopAppbar.

Here is the simple code i use (with webpack and electron) :

```javascript
import React from 'react';
import { render } from 'react-dom';

import {
    SimpleTopAppBar,
    TopAppBarFixedAdjust
} from '@rmwc/top-app-bar';

render(
    <>
        <SimpleTopAppBar
            title="test"
            navigationIcon={{ onClick: () => console.log('Navigate') }}
            actionItems={[
                {
                    icon: 'file_download',
                    onClick: () => console.log('Do Something')
                },
                { icon: 'print', onClick: () => console.log('Do Something') },
                { icon: 'bookmark', onClick: () => console.log('Do Something') }
            ]}
        />
        <TopAppBarFixedAdjust />

        <div style={{ height: '100rem', padding: '1rem' }}>Scroll Me</div>
    </>,
    document.querySelector('#root')
);
```

And I got this error : 

Uncaught TypeError: Cannot read property 'bind' of undefined
    at TopAppBarBase.setScrollTarget (index.js?3fec:212)
    at eval (index.js?3fec:220)
    at TopAppBarBase.FoundationComponent.syncProp (foundation-component.js?018a:233)
    at TopAppBarBase.sync (index.js?3fec:218)
    at TopAppBarBase.FoundationComponent.componentDidMount (foundation-component.js?018a:210)
    at TopAppBarBase.componentDidMount (index.js?3fec:133)

Any ideas how to fix this ?

Thank you.

**Comment by jamesmfriedman** [comment]
Did you figure this out?

**Comment by jfily** [comment]
Yes, it was the optimization params of webpack.
```
optimization: {
        removeAvailableModules: false,
        removeEmptyChunks: false,
        splitChunks: false,
}
```

**Comment by jamesmfriedman** [comment]
Ok glad you found it. Do you have any idea why that was causing the error? Want to make sure it’s not something that has to be documented. Not sure why those options would cause the error.

**Comment by jfily** [comment]
I don't know why but it seems to be a webpack bug because, when i deactivated optimization, my app worked and then, I tried to reactivate optimization and now, it still works...
