### ISSUE TITLE
Feature Request: Min-Width Tabs

### ISSUE THREAD

**Issue by ben-mckernan** [jamesmfriedman/rmwc#532]
RMWC 5.7.0

MDC Web has support for styling tabs to the size of their content rather than expanding them to the width of the container. This is done via the `mdc-tab--min-width` class. I can currently do this when using RMWC by adding the class myself. However it would be nice if this was exposed by RMWC as a boolean prop for tabs.

**Comment by jamesmfriedman** [comment]
Cool, will add to the next release.

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
