### ISSUE TITLE
Typography color can't be changed/overwriten in a nested ThemeProvider.

### ISSUE THREAD

**Issue by Tiago5** [jamesmfriedman/rmwc#534]
- What RMWC Version are you using [major.minor.patch]:

5.7.1

- Name your build system [Webpack, Rollup...]:

Webpack

- Describe the bug with as much detail as possible:

The bug can be seen in here:
https://codesandbox.io/s/sleepy-breeze-1j91s

I was trying to overwrite some theme options on a nested ThemeProvider and noticed that Typography wasn't reflecting the changes.

As can be seen in the example, the property that gives the color to typography is _--mdc-theme-text-icon-on-dark_ and is initialy being applied with _!important_. This is not happening with other rmwc components.
After that, if we attempt to overwrite it with different option from another ThemeProvider(the nested one), they're not applied.

- What happened, and what was supposed to happen:

In the first set of options (first row of components on the example) the typography have the color **rgba(255, 255, 255, 0.5)** and on the second set the color is the same.

What should have happened is that in the second row of components the typography should have changed its color to **#e539ff**.

**Comment by jamesmfriedman** [comment]
Their naming scheme for variables is a bit verbose I'll admit. It appears you are just referencing the wrong property. For text, it should be textPrimaryOnBackground. Easiest way to find out is to inspect with your dev tools, look at the css properties, and see what color variable it has under its final computed value.

Working as expected?
https://codesandbox.io/s/vigilant-field-ukv95

**Comment by Tiago5** [comment]
I'm sorry I may not have been very clear, I was refering to the Typography component where it's typed 'Hello world'.
The others were already changing its color correctly. I've just added more components in the example (button and radio) to see that only typography wasn't changing its color. 
In your example it's also not changing.

If you inspect the 'Hello World' text you will see that its color its still the one from the first set of theme options instead of the second set of options (innerOptions).

**Comment by jamesmfriedman** [comment]
Oh oh, sorry about that.

This is an easy fix. If you look again at the HTML + CSS, by default the Typography component doesn't actually assign anything. 

- I added the "use" prop to specify what kind of text style to use
- Even after that, color is just inherited from whatever the parent is
- You can use the theme prop to specify a certain color, otherwise its just whatever is set in CSS above it. 
https://codesandbox.io/s/vigilant-field-ukv95

**Comment by Tiago5** [comment]
Oh, ok I see, I went through the documentation but didn't realize we could do that.
Thank you, is working now.
