### ISSUE TITLE
Slider in Dialog needs resize to work

### ISSUE THREAD

**Issue by knarxy** [jamesmfriedman/rmwc#538]
Do you really want it fixed? Make a repro in the sandbox!
--> https://codesandbox.io/s/suspicious-robinson-bpkeh?fontsize=14&hidenavigation=1&theme=dark

- What RMWC Version are you using [major.minor.patch]:
5.7.2

- Name your build system [Webpack, Rollup...]:
Webpack

- Describe the bug with as much detail as possible:
Slider in Dialog does not move and has max prop as standard value on onChange. Though, it does move and work correctly after resizing the window when the dialog is opened. It does also occur if the dialog is opened by default.
 
- What happened, and what was supposed to happen:
Slider does not work as intended. We were able to reproduce the bug in a sandbox.

**Comment by jamesmfriedman** [comment]
This is a known bug that needs some documentation (and a fix). 

For now a workaround is to manually fire a window resize event when the dialog opens. Will get this fixed in the next release.

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
