### ISSUE TITLE
Disabled on MenuItems inside SimpleMenu not working

### ISSUE THREAD

**Issue by rzk666** [jamesmfriedman/rmwc#539]
<!--- 
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## RMWC or MDC?

I'm pretty sure its RMWC

- What RMWC Version are you using [major.minor.patch]:

5.7.2

- Name your build system [Webpack, Rollup...]:

Webpack

- Describe the bug with as much detail as possible:
I have a SimpleMenu component that renders a list of options. the options are being served as an array of MenuItem, where every MenuItem receives a disabled boolean as a prop.
For some reason, the items act normally no matter if they're disabled or not

- What happened, and what was supposed to happen:
Items on the menu should be unclickable (disabled), but they can be clicked and change the menu value.

Code Example: * I've made sure 100% that the 'disabled' prop the Dropdown components gets and passes down to menu item has the current value. and I've also tried inserting values manually to the the ItemMenu disabled prop.

```
const Dropdown = (props) => {
  const {
    options, selected, placeholder, disabled, onChange,
  } = props;
  let title = placeholder;
  const dropDownOptions = options.map((elem) => {
    if (selected === elem.value) {
      ({ title } = elem);
    }
    return <MenuItem disabled={disabled} selected={selected === elem.value} key={elem.value}>{elem.title}</MenuItem>;
  });

  return (
    <SimpleMenu
      onSelect={e => onChange({ value: e.detail.index + 1 })}
      handle={
        <div className={classNames('mdc-select', styles.dropdownContainer)}>
          <div className={classNames('mdc-select__native-control', styles.dropdownInput)}>{title}</div>
        </div>
        }
    >
      {dropDownOptions}
    </SimpleMenu>
  );
};
```

**Comment by jamesmfriedman** [comment]
Cannot reproduce. Please reopen with a codesandbox and more description of the issue.
