### ISSUE TITLE
Select fails to show that a value is selected if options are rendered async.

### ISSUE THREAD

**Issue by izakfilmalter** [jamesmfriedman/rmwc#54]
### What RMWC Version are you using?

`"rmwc": "^0.0.1-rc11",`

### What browser(s) and React Version is this bug affecting?

Chrome Version 65.0.3292.0
React 16.1.0

### What build system are you using?

create-react-app

### What are the steps to reproduce the bug?

1. `Select` has a value prop passed in.
1. Options are being rendered based off of data from an api, data is there yet, so the render for the view fires with the `Select` having a `value`, but `options` is equal to `{}`.
1. Server sends data to redux, store updates, and then the view updates. `Select` stays in a no option selected state even though a matching `option` exists.

You can reproduce this by having a function return the options and have a delay on it, eg `if 100ms has not passed return {};`

### What is the expected behavior?

Select will show that an item is selected.

### What is the actual behavior?

Select doesn't show that an item is selected.

### Any other information you believe would be useful?

`aria-selected=true` doesn't happen at all. I tried manually passing in `ListItem` with the `aria-selected=true` on the correct item and there was no change.

**Comment by jamesmfriedman** [comment]
Awesome, this is definitely seems related #44 which has been annoying. Overall the Select needs to be rethought and refactored, but I'll definitely account for this case. Going to try and get this one fixed before the weekend.

**Comment by izakfilmalter** [comment]
Cool thanks. For now I am just doing the following which works:

```
const { dataFromApi } = this.props;
const { selectValue } = this.state;
[...]
        {dataFromApi && (
            <Select
              onChange={event => this.onChange(event, 'selectValue')}
              options={this.renderOptions(dataFromApi)}
              placeholder="Select"
              value={selectValue}
            />
        )}
```

**Comment by jamesmfriedman** [comment]
Yeah that makes sense, it's just forcing a re-render. Another way you could do that is add a "key" prop that changes when there is data. If the key is different, React will throw away the old one and rebuild it. That would help you avoid a FOIC
