### ISSUE TITLE
Cannot add className to CollapsibleList

### ISSUE THREAD

**Issue by claudiobernasconi** [jamesmfriedman/rmwc#543]
It is currently not possible to add a className definition to a CollapsibleList component.

The following sandbox shows the problem in action:
[![Edit determined-bouman-99u3d](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-bouman-99u3d?fontsize=14&hidenavigation=1&theme=dark)

Inspect the **CollapsibleList** component with the DevTools. The CSS class `collapsible-list-styles` is ignored.

The reason for this behavior is that the className is directly set on the **CollapsibleRoot** component without appending the className property from the props.

The following code is taken from the file: https://github.com/jamesmfriedman/rmwc/blob/master/src/list/collapsible-list.tsx

```
<CollapsibleRoot
        {...rest}
        onFocus={this.handleFocus}
        ref={(el: HTMLDivElement) => (this.root = el)}
        className={classNames('rmwc-collapsible-list', {
          ['rmwc-collapsible-list--open']: open
        })}
      >
```

In my opinion, the className of the props should be appended to the className(s) generated by the classNames function.

RMWC Version: 5.7.1
Build System: webpack

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
