### ISSUE TITLE
Dialog styles not imported in Production build (Webpack)

### ISSUE THREAD

**Issue by weiserhase** [jamesmfriedman/rmwc#548]
Not sure if this is a MDC or RMWC bug.
- What RMWC Version are you using [major.minor.patch]: 5.7.2

- Name your build system [Webpack, Rollup...]: Webpack

- Describe the bug with as much detail as possible:

When we run a production build on our Project and open it up in browser we get weired issues with the styling of the dialog component. We have a Dialog on the page wich works fine in the developent build. But as soon as we try the Production build we get the right structure of the Dialog but without any styles attached.(Screenshots attached) Any other rmwc component works fine in either dev or production build.
We tried to fix the behviour by specifying tree-shaking like prposed in the webpack documentation, https://github.com/webpack/webpack/issues/6741 and https://github.com/webpack/webpack/issues/6065 but with no luck.
`"sideEffects": [
        "**/*.css",
        "**/*.scss",
        "**/*.js",
        "@material/dialog/dist/mdc.dialog.css"
    ],`

`rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env']
        },
        sideEffects: true,
      },`
![production build](https://user-images.githubusercontent.com/44242102/72982322-135bb500-3ddf-11ea-92aa-5c2982da8ff5.png)
^production
![development build](https://user-images.githubusercontent.com/44242102/72982323-135bb500-3ddf-11ea-970e-00d97d4316a5.png)
^development
[mainbundle+index.html.zip](https://github.com/jamesmfriedman/rmwc/files/4102924/mainbundle%2Bindex.html.zip)

**Comment by weiserhase** [comment]
We fixed the bug by adding sideEffects to style loader rules .

`rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env']
        },
        sideEffects: true,
      },
      {
        test: /\.(css|scss)$/,
        use: [
          "style-loader",
          "css-loader",
          "sass-loader"
        ],
        sideEffects: true,
      },
      {
        test: /\.(jpg|png|jpeg|gif|mp3|svg)$/,
        loaders: ["file-loader"],
        sideEffects: true,
      }
    ]`

**Comment by jamesmfriedman** [comment]
Yeah this is a duplicate of #545 . Going to get this fixed on the RMWC side in the next release, until then your workaround is valid.
