### ISSUE TITLE
IconButton is hidden from accessibility tree

### ISSUE THREAD

**Issue by jmorahan** [jamesmfriedman/rmwc#549]
- What RMWC Version are you using [major.minor.patch]:

5.7.2

- Name your build system [Webpack, Rollup...]:

Webpack

- Describe the bug with as much detail as possible:

The IconButton component renders a `<button>` element with an `aria-hidden="true"` attribute by default. This removes the element from the accessibility tree, making it invisible to assistive technology. You can see this in the demos on https://rmwc.io/icon-buttons. (I guess this may have been copied from a [bad example](https://material.io/develop/web/components/buttons/icon-buttons/#icon-button-toggle) in the MDC documentation, but [MDC's own icon button demos](https://material-components.github.io/material-components-web-catalog/#/component/icon-button) don't have this attribute).

- What happened, and what was supposed to happen:

The IconButton component should render its `<button>` or other root element without the `aria-hidden="true"` attribute.

**Comment by jamesmfriedman** [comment]
Yeah, you're actually right. The IconButton component changed so many times on the MDC side, the aria-hidden attribute is left over from a previous implementation of the component... will definitely get this fixed, thanks for reporting.

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
