### ISSUE TITLE
TextField: Helptext renamed to HelperText

### ISSUE THREAD

**Issue by UFOMelkor** [jamesmfriedman/rmwc#55]
### What RMWC Version are you using?

0.0.1-rc11

### What browser(s) and React Version is this bug affecting?

every

### What build system are you using?

webpack

### What are the steps to reproduce the bug?

```jsx
<TextFieldHelpText>Optional help text.</TextFieldHelpText>
```

### What is the expected/actual behavior?

```diff
-<p class="mdc-text-field-helptext" aria-hidden="true">Optional help text.</p>
+<p class="mdc-text-field-helper-text"" aria-hidden="true">Optional help text.</p>
```

### Any other information you believe would be useful?
See material-components/material-components-web#1576

**Comment by j-o-d-o** [comment]
Hi, yes this WILL be an issue. The mcw commit will be in the upcomming 0.28.0 mcw version. rmwc is currently still on 0.26.0 mcw. 
I am sure it is on @jamesmfriedman bucked list to always keep up with the latest mcw version. But the mcw release cycle is quite quick (2 weeks) and usually with quite a bit of breaking changes, so I understand that it can not always happen immediately. 
Your PR definitely helps to make things easier to account for all the breaking changes! I would suggest leaving this issue open till the PR is merged and maybe add a little notice to the PR that it should be merged when rmwc will update mcw version to 0.28.0.

**Comment by UFOMelkor** [comment]
Following the [changelog](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0260-2017-11-27) this has shipped with v0.26.0 (or I am misreading something).

**Comment by j-o-d-o** [comment]
YES, it says 13 Nov on the commit, I somehow read 13 Dez ... sorry. Should be merged now!

**Comment by jamesmfriedman** [comment]
Just looked through the changelog for v27. So many things... 

I’ll get this PR merged in and then. I’m going to do a PR and include some active people on it or 27.

**Comment by j-o-d-o** [comment]
I think for most of the stuff we don't really need to do anything, e.g. api changes or mixin changes/usages. But I am happy to help, just assign me some stuff to do.

**Comment by jamesmfriedman** [comment]
Thanks @j-o-d-o, I appreciate the help. I'm really just looking for another set of eyes so I don't miss anything. A couple of times I published a major bug to NPM, and I'm looking to avoid that.
