### ISSUE TITLE
Enhancement Request: Range Slider

### ISSUE THREAD

**Issue by jcamato** [jamesmfriedman/rmwc#550]
### Request
Are there any plans to enhance [RMWC's slider wrapper](https://rmwc.io/sliders) to filter a range of values with two thumbs? This would be helpful in providing users the ability to select a minimum and maximum value to filter their results.

### Example
As an example, here is the feature through Material-UI:
https://material-ui.com/components/slider/#range-sliders

Thank you for all your awesome work, James!

**Comment by sangdth** [comment]
I have checked the source code of RMWC slider and think I could make a PR for this.

**Comment by sangdth** [comment]
I remember there was a comment that @jamesmfriedman said that he could suggest how to do this.

I've tried to look into the source code and my initial thought is, if I could change the value type to accept either ` number | string` and `( number | string)[]`, then duplicate the `SliderThumb` according to value type.

But then I encountered the problem with `MDCSliderFoundation`, I don't know how to move forward. Seem like I have to change more in other place, like the `useSliderFoundation` hook.

**Comment by suhaibmujahid** [comment]
It seems that the range sliders (two thumbs) have been implemented in [material-components-web](https://github.com/material-components/material-components-web). 

See this: [Continuous range slider](https://github.com/material-components/material-components-web/tree/master/packages/mdc-slider#continuous-range-slide)
