### ISSUE TITLE
Sort arrow icon in data table header cell pointing in opposite direction?

### ISSUE THREAD

**Issue by anirban09** [jamesmfriedman/rmwc#551]
- What RMWC Version are you using [major.minor.patch]: 5.7.2

- Name your build system [Webpack, Rollup...]: create-react-app

- Describe the bug with as much detail as possible:

Hey, isn't the sort arrow icon in the data table header cell pointing in the opposite direction? On https://rmwc.io/data-tables, if you click on `Quantity (Click Me)` in the first table, the sort arrow icon points downwards for ascending order (when `sortDir` is 1), and upwards for descending order (when `sortDir` is -1).

Of course, the data table is probably being rewritten for the v6.0.0 release, but just wanted to clarify if this is intended behaviour or not.

**Comment by jamesmfriedman** [comment]
Sorry for the late reply. You've got me second guessing myself on this one. I looked at about 15 different table sorting examples and found both versions, but what you're suggesting seems to be more "correct" and also aligns with the material spec. I'll fix the arrow direction with the next release.

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
