### ISSUE TITLE
Layout Grid Rows

### ISSUE THREAD

**Issue by lbell** [jamesmfriedman/rmwc#555]
Migrating from MDC-React, they had a handy `<Row>` element to add new rows to a grid. It seems the Material way for doing this _may be_ to simply add more than 12 columns to the grid and it will wrap to a new row, though it is undocumented: https://github.com/material-components/material-components-web/issues/1072

Curious if this is the suggested way to handle multiple rows with RMWC, and if so, how can I update the docs to reflect this?

**Comment by jamesmfriedman** [comment]
I think what you might be looking for is the GridInner Component? You can just add more inner grids, which are basically "rows". Not completely sure myself, I don't use the grid hardly ever since CSS grids are really powerful now.

**Comment by jamesmfriedman** [comment]
This is a minor breaking change, but I did rename this from GridInner to GridRow in the upcoming release

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
