### ISSUE TITLE
DataTable - height of rows increases if there is an IconButton in them

### ISSUE THREAD

**Issue by dardinier** [jamesmfriedman/rmwc#558]
- **What RMWC Version are you using [major.minor.patch]:**

5.7.2

- **Name your build system [Webpack, Rollup...]:**

webpack 4

- **Describe the bug with as much detail as possible:**

I have a DataTable in which I can have icon buttons. When an icon button is present in a row, the height of the row increase because of the height of the icon button. This creates a table with rows that have different heights.

An exemple here : https://codesandbox.io/s/rmwc-sandbox-8iiqz

- **What happened, and what was supposed to happen:**

All rows should have the same height no matter what is in this row.

I think this is a RMWC problem because I already did the same with MDC data-table and all rows had same height.

**Comment by jamesmfriedman** [comment]
Appears that this is fixed with the upcoming release. Tables have been refactored to use the MDC css underneath since they finally released their own.

https://codesandbox.io/s/rmwc-sandbox-3q9gl

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
