### ISSUE TITLE
Disable hoist to body for Select

### ISSUE THREAD

**Issue by Acidic9** [jamesmfriedman/rmwc#561]
- What RMWC Version are you using [major.minor.patch]: 5.7.2

- Name your build system [Webpack, Rollup...]: Webpack

- Describe the bug with as much detail as possible:
The select components dropdown menu is hoisted to become a direct child of the HTML body.
I want to prevent this and render the dropdown menu as-is so the width can match the select input's width.

- What happened, and what was supposed to happen:
Dropdown menu is hoisted to body and width is not matching select element.
The dropdown menu should not be hoisted to allow for the width to match the select element.

**Comment by jamesmfriedman** [comment]
I'll definitely look into this a bit more. MDC has changed their select handling in just about every release. Previously the menu hoisting to the body was their default way, and it looks like they have gone back on that decision.

**Comment by jamesmfriedman** [comment]
I removed this from hoisting by default, you can still enable the option by passing `hoistToBody`. Publishing now, you can check it out in the latest alpha.

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
