### ISSUE TITLE
Button Ripple didn't works with SASS @material/ripple style.

### ISSUE THREAD

**Issue by ArthurGerbelot** [jamesmfriedman/rmwc#564]
Hi,

I'm trying to use RMWC (v 5.7.2) and mix it with @material/___ styles in order to be able to use SASS .

I created a [Sandbox code example](https://codesandbox.io/s/rmwc-sandbox-9qebl) but I cannot make SCSS works on it, so I created the same on [GitHub repository](https://github.com/ArthurGerbelot/rmwc-ripple-not-working) .

Copy/Past to clone/install it:
`git clone git@github.com:ArthurGerbelot/rmwc-ripple-not-working.git && cd rmwc-ripple-not-working/ && npm i`

Run with `npm start`

## Basic code

I simply take TextField and Button from @rmwc/textfield and @rmwc/button in order to write HTML:

```js
import { Button } from "@rmwc/button";
import { TextField } from "@rmwc/textfield";

import './App.scss';

function App() {
  return (
    <div className="App">
      <TextField label="Foo" />
      <Button ripple>Button</Button>
    </div>
  );
}
```

And I handle styles using SCSS:

```scss
@use "@material/theme" with (
  $primary: red,
);
@import '@material/ripple/mdc-ripple';
@import '@material/button/mdc-button';
@import '@material/textfield/mdc-text-field';
```

**Note:** In order to make it works i have to add a `.env` file containing `SASS_PATH=./node_modules:./src`

## Resut

 - TextField is workings fine, and Ripple are present.
 - Button look like it can handle it (it have ripple class and they are updated with events) but nothing is displayed.

## Solutions ?

I tried to add `<div class="mdc-button__ripple"></div>` into the button, next to `<div class="mdc-button__label">Button</div>` to generated the same HTML that @material/button, and **It's working !**

Of course it also works fine if I replace all `@import '@material/__'` into the App.scss file and use instead: (but primary-color red will not been take account)
`@import '~material-components-web/dist/material-components-web.min.css';`

Did I miss something ? Or do @rmwc/button can implement this ?

**Comment by jamesmfriedman** [comment]
It looks like you have a version conflict. <div class="mdc-button__ripple"></div> is a change that they added in V4 of material-components-web, while the current version of RMWC is on V3. rmwc@next is in process of being finished and released and uses the latest version.

**Comment by ArthurGerbelot** [comment]
Ho. I got it !
Thank you for answering
