### ISSUE TITLE
TextField Label Disappears in Dialog Component

### ISSUE THREAD

**Issue by lbell** [jamesmfriedman/rmwc#568]
- What RMWC Version are you using [major.minor.patch]: 
5.7.2

- Name your build system [Webpack, Rollup...]: 
Webpack

- Describe the bug with as much detail as possible: 
Super-minor but odd bug. The label on a TextField component set to disabled disappears in a dialog window, but not in the main app. 

- What happened, and what was supposed to happen:
I'd suspect the label to show up. It doesn't.

https://codesandbox.io/s/rmwc-sandbox-gmofe

Again, it's extremely minor, but curious if there might be something bigger going on that this is a symptom of... Thanks!

**Comment by jamesmfriedman** [comment]
Checking the sandbox with latest dependencies, appears to be fixed!

https://codesandbox.io/s/rmwc-sandbox-9hbbb

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0

**Comment by lbell** [comment]
Almost... The label appears now, but the line doesn't break for it. (See sandbox). 

Again, super-minor issue. Otherwise, I'm poking around the 6.x release and it looks SOLID! Thanks!
