### ISSUE TITLE
Add Gitter chat for RMWC

### ISSUE THREAD

**Issue by rustemgareev** [jamesmfriedman/rmwc#57]
Would you like to enable Gitter channel for your project? Users might get instant feedback and help each other. Also, I'm considering to add such quick links to [awesome-material-components](https://github.com/webdenim/awesome-material-components) where possible.

**Comment by jamesmfriedman** [comment]
What’s Gitter chat?

**Comment by jamesmfriedman** [comment]
Sorry for the stupid question, I just woke up. Yeah it seems like it would be helpful. I’ll get it setup.

**Comment by jamesmfriedman** [comment]
Added. Never used Gitter, but looks pretty cool.
