### ISSUE TITLE
Missing dependency on material-components-web?

### ISSUE THREAD

**Issue by anthonysapien** [jamesmfriedman/rmwc#578]
- What RMWC Version are you using [major.minor.patch]: 5.7.2

- Name your build system [Webpack, Rollup...]: create-react-app

- Describe the bug with as much detail as possible: I was surprised to see the style missing from my TopAppBarActionItem icon. It wasn't styled like a button. It turns out that I did not have material-components-web installed. The RMWC installation instructions state that it should be included automatically as a peer dependency, but I think it might not be.

- What happened, and what was supposed to happen:
Expected material-components-web to be installed as a peer dependency.
It wasn't automatically installed as a peer dependency.

**Comment by jamesmfriedman** [comment]
> It turns out that I did not have material-components-web installed. The RMWC installation instructions state that it should be included automatically as a peer dependency, but I think it might not be.

^ this is only true if you do the shorthand version `npm i rmwc` which really isn't recommended since it will install everything.

The documentation is being updated for V6, but you are correct that you need some additional styles for this to work. Here is the full list.

```
@material/top-app-bar/dist/mdc.top-app-bar.css
@material/icon-button/dist/mdc.icon-button.css
@material/ripple/dist/mdc.ripple.css
@rmwc/icon/icon.css
```

**Comment by anthonysapien** [comment]
Hmm, my package.json only has a single RMWC component.

`{
  "name": "rmwc-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@rmwc/top-app-bar": "^5.7.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by jamesmfriedman** [comment]
I think maybe a bit of confusion about how node_modules / package.json works?

The other things you are need already a dependency of the top-app-bar, just include the additional css files listed above. Here is a link to the top-app-bars dependencies.
https://github.com/jamesmfriedman/rmwc/blob/master/src/top-app-bar/package.json

**Comment by jamesmfriedman** [comment]
@anthonysapien you good to close this out?

**Comment by anthonysapien** [comment]
Yes, I’m all set, thanks.
