### ISSUE TITLE
feat(list): implement missing adapter method `isRootFocused`

### ISSUE THREAD

**Issue by mgr34** [jamesmfriedman/rmwc#581]
(PR forthcoming)

The list adapter is missing `isRootFocused` which is utilized by the `foundation.handleKeyDown`

https://github.com/material-components/material-components-web/blob/e75deb8540fa70236087d335c9cd6280bd643285/packages/mdc-list/foundation.ts#L182

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.0
