### ISSUE TITLE
How to use outlined material icons?

### ISSUE THREAD

**Issue by FrancoSabadini** [jamesmfriedman/rmwc#584]
- What RMWC Version are you using: 5.7.2

- Name your build system [Webpack, Rollup...]: Webpack

- Describe the bug with as much detail as possible:

I'm trying to use the outlined version of the Material Icons but I can't seem to make that work. I added the following stylesheet:

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
```

but the RMWC components only have the `material-icons` class set and not the `material-icons-outlined` one. Is there a way to support this?

This answer can be useful in understanding how to use the different icon styles: https://stackoverflow.com/questions/50303454/how-to-use-the-new-material-design-icon-themes-outlined-rounded-two-tone-and/54902967

- What happened, and what was supposed to happen:

When I set the stylesheet mentioned above and try to use a material icon inside a `Button` or `IconButton` the icon doesn't appear. If I inspect the element in the browser and add the `material-icons-outlined` class to it then it works.

**Comment by jamesmfriedman** [comment]
Yeah, you can override the basename using the provider, or per icon.

https://rmwc.io/provider

**Comment by FrancoSabadini** [comment]
Thanks for the quick answer @jamesmfriedman, on the option of doing this per icon, how would I do that in a `Button`?

**Comment by jamesmfriedman** [comment]
`<Button icon={{icon: 'favorite', basename: 'material-icons-outlined'}}` />
