### ISSUE TITLE
Add documentation for controlled Selects

### ISSUE THREAD

**Issue by 101arrowz** [jamesmfriedman/rmwc#586]
The [`Select` documentation](https://rmwc.io/select-menus) appears incomplete. First off, there's no guide to use a `Select` as a controlled component. More importantly, the type information at the bottom is completely missing. I'd assume this is because of the recent update to v6.

Thanks for maintaining this amazing project! v6 is looking exciting already.

**Comment by jamesmfriedman** [comment]
Thanks for calling out the missing props. This project relies heavily on automatic documentation generation to stay in sync and a recent reorganization of the select code was preventing its props from being generated.

As for the select docs, I can add an example of using it as a controlled component, however it works just like a native select.

**Comment by 101arrowz** [comment]
@jamesmfriedman All but the `Select` and `Menu` documentation is missing from the site.

**Comment by jamesmfriedman** [comment]
Well, sometimes you fix one thing and break everything else.... Really fixed this time, thanks for reporting that.

**Comment by jamesmfriedman** [comment]
Just added a section for controlled vs uncontrolled selects in the docs.
