### ISSUE TITLE
Issue theming the title of a Top App Bar

### ISSUE THREAD

**Issue by anthonysapien** [jamesmfriedman/rmwc#588]
- What RMWC Version are you using [major.minor.patch]: 6.0.3

- Name your build system [Webpack, Rollup...]: create-react-app

- Describe the bug with as much detail as possible: 
I'm trying to override the Top App Bar title color using a ThemeProvider. The color seems to be hard-coded to "white" by MDC. I noticed that your Theme fixes file overrides color for ".mdc-top-app-bar .mdc-tab-bar". Would it make sense to override "color" for the title (or even the entire TopAppBar) as well?

I noticed that your Theme instructions suggest including the theme CSS before other components. I'm wondering how the theme fixes will work if they are declared before the components pull in MDC CSS. Won't the MDC hard-coded "white" color being imported after the fixes revert the fix?

- What happened, and what was supposed to happen:
My Top App Bar title text is white even though I changed the onPrimary color with a ThemeProvider.

Thanks!

**Comment by jamesmfriedman** [comment]
Yeah, that would definitely make sense to add. I used to report all of these issues up stream, but haven't made much progress. I'll add this to the list.

**Comment by jamesmfriedman** [comment]
Fixed with 6.0.4

**Comment by anthonysapien** [comment]
Thanks for the quick fix!
