### ISSUE TITLE
Fix MDC Linear Progress bug with text-align

### ISSUE THREAD

**Issue by 101arrowz** [jamesmfriedman/rmwc#590]
MDC has a bug [(which I have already reported)](https://github.com/material-components/material-components-web/issues/5758) where `text-align` affects the linear progress in a confusing way.

I was wondering if you could just hotfix this MDC bug. It's incredibly simple, you just need to add a `text-align: left` to all `<LinearProgress />` elements. At the same time, I suppose library users could just do this themselves. I just thought I should open an issue in case anyone else comes across this issue in the future (it seems that MDC takes a while to fix bugs.)

[JS Sandbox](https://codesandbox.io/s/rmwc-sandbox-6pifk)

**Comment by jamesmfriedman** [comment]
Yep. V6 I started doing this with a style fixes file because I also got tired of waiting :)

**Comment by jamesmfriedman** [comment]
Fixed in 6.0.10
