### ISSUE TITLE
Checkbox state doesn't change automatically with user interaction when `checked` is set from props

### ISSUE THREAD

**Issue by FrancoSabadini** [jamesmfriedman/rmwc#591]
- What RMWC Version are you using [major.minor.patch]: 6.0.5

- Name your build system [Webpack, Rollup...]: Webpack

- What happened, and what was supposed to happen:

When using a `Checkbox` and setting the `checked` property, the `checked` state doesn't automatically change when the user clicks the checkbox, instead, we have to do it manually as explained in the docs:

```javascript
function Example() {
  const [checked, setChecked] = React.useState(false);
  return (
    <Checkbox
      label="Cookies"
      checked={checked}
      onChange={evt => setChecked(!!evt.currentTarget.checked)}
    />
  );
}
```

While this is not a huge problem, it does make it a bit annoying, as I assume in most cases devs just want to set this `checked` state initially but allow the user to change it later on.

I'd suggest adding 2 different properties for these scenarios:

1. `checkedAlways: boolean` which behaves as the current `checked` property does and prevents the user from changing this state automatically.

2. `checkedInitial: boolean` which sets the initial checked state, but allows the user to change it automatically.

**Comment by jamesmfriedman** [comment]
This is just standard React and works the same as a native checkbox. I believe what you’re looking for is the “defaultChecked” prop.

**Comment by FrancoSabadini** [comment]
Thanks for the quick answer @jamesmfriedman, is there a `defaultChecked` property in the RMWC `Checkbox` component? I didn't see that in the docs or the source code.

**Comment by jamesmfriedman** [comment]
All of the components inherit from the full dom API. In the case of checkbox, it’s HTMLInputElement. When dealing with form controls, they should all have nearly identical behavior to plain old html form elements.

**Comment by FrancoSabadini** [comment]
Perfect, thanks for the info @jamesmfriedman 👍

**Comment by jamesmfriedman** [comment]
No problem, I’ll see about adding controlled vs uncontrolled examples to all form components.
