### ISSUE TITLE
<Select> not displaying selected value (since v6)

### ISSUE THREAD

**Issue by AntonioDell** [jamesmfriedman/rmwc#592]
- What RMWC Version are you using [major.minor.patch]: 
6.0.4 in my project
latest in sandbox/rmwc.io

- Name your build system [Webpack, Rollup...]: 
Webpack

- Describe the bug with as much detail as possible:
The <Select> component is broken. I identified two bugs, which I'm not sure if they have the same root cause.

1. On the official rmwc website https://rmwc.io/select-menus the examples don't work anymore. Selecting one of the options doesn't display the selected option. This is also true for the sandbox sample I created: https://codesandbox.io/s/rmwc-sandbox-n24c5

2. In my current project, using the <Select> as controlled input in such a way, that the first option get's set as value, when the options change, doesn't work anymore. Sadly, I cant get the sandbox sample to work, because of the first bug, so I only have the code I use:

```
const [currentValue, setCurrentValue] = useState();
const [currentOptions , setCurrentOptions ] = useState();

useEffect(() => {
       if (currentOptions != undefined && currentOptions.length > 0) {
            // Get's called, but the displayed value doesn't change
            setCurrentValue(currentOptions [0]);
        }
    }, [currentOptions]);

return <Select
	type="text"
	value={currentValue}
	options={currentOptions}
	onChange={(e) => {
		setCurrentValue(e.currentTarget.value);
	}}
/>
```

- What happened, and what was supposed to happen:
1. The samples on https://rmwc.io/select-menus are supposed to work (eg I was able to select values in 5.7.2)
2. The displayed value is supposed to change, when the options change (worked in 5.7.2)

**Comment by jamesmfriedman** [comment]
This was a regression caused by a single boolean check... I'm pretty infuriated that my test cases didn't catch this, going to modify them to be more like E2E tests using react-testing-library. Thanks for reporting. Fixing in 6.0.7
