### ISSUE TITLE
bug(scss): Intermixed v4 and v5 components

### ISSUE THREAD

**Issue by cpboyd** [jamesmfriedman/rmwc#593]
- What RMWC Version are you using [major.minor.patch]:
6.0.7

- Name your build system [Webpack, Rollup...]:
Gatsby

- Describe the bug with as much detail as possible:
Attempting to import certain mixins (like `'@material/elevation/mixins'`) fails because node_modules is intermixed with different versions.

- What happened, and what was supposed to happen:
Should be able to import SCSS files.

Likely the super-package's `package.json` is to blame, since almost all individual `@rmwc` components reference the v5 `@material` counterpart:
https://github.com/jamesmfriedman/rmwc/blob/master/src/rmwc/package.json#L80

**Comment by jamesmfriedman** [comment]
Yeah thats definitely the problem! I should really just remove the "install everything" directions, but in lieu of that this needs to be patched.

**Comment by jamesmfriedman** [comment]
Fixed with 6.0.8
