### ISSUE TITLE
Controlled <Select> not displaying right value

### ISSUE THREAD

**Issue by AntonioDell** [jamesmfriedman/rmwc#594]
- What RMWC Version are you using [major.minor.patch]:
6.08

- Name your build system [Webpack, Rollup...]:
Webpack

- Describe the bug with as much detail as possible:

One of the bugs in https://github.com/jamesmfriedman/rmwc/issues/592 wasn't resolved with the upgrade from 6.0.4 to 6.0.8, so I created a new ticket for it.

When using a simple controlled <Select>, the changed value doesn't display in the select component as being selected. 
Here an example of it: 
https://codesandbox.io/s/rmwc-sandbox-zjbbm

It worked in 5.7.2.

- What happened, and what was supposed to happen:
In the example: When clicking the button, "C" should get displayed. But it isn't. When opening the select options we can see, that it got selected, but just isn't displayed.

Thank you for maintaining this project!

**Comment by jamesmfriedman** [comment]
Brings me no joy to continue to have to patch these things, but I added a handful of tests this will prevent any more regressions in functionality. Thanks for reporting and for your patience.

Working with 6.0.9
https://codesandbox.io/s/rmwc-sandbox-wvp1v
