### ISSUE TITLE
<Select /> needs extra tab to activate/control the options menu

### ISSUE THREAD

**Issue by tstirrat** [jamesmfriedman/rmwc#595]
- What RMWC Version are you using [major.minor.patch]:

`@rmwc/select` 6.0.9
`@material/select` 5.1.0

- Name your build system [Webpack, Rollup...]: Create React App 2.0

- Describe the bug with as much detail as possible: 

Clicking the select's label, then pressing tab activates an intermediate element before another tab reaches the input. 

This means there are two tabs needed to reach the next input, and there is no visual indication change.

It also means pressing tab once into the select does not allow typing with keys to select an option, or pressing space to open the menu.

- What happened, and what was supposed to happen:

Expected:
- click label
- tab
- press space
- select menu opens

Actual:
- click label
- tab
- press space - nothing happens
- tab
- press space
- select menu opens

Attempted to fix with `<Select tabindex="-1" />` but this skips the select element so that space cannot open the options menu at all.

Similar to #79 but resurfaced in 6.0. And there is no `cssOnly` option anymore, AFAIK.

Works as expected in MDC: https://material-components.github.io/material-components-web-catalog/#/component/select
Does not work as expected in RMWC demo at 6.0.9: https://rmwc.io/select-menus

If you would like a minimal repro I can do that but it's clearly visible in the demo/docs site.

**Comment by jamesmfriedman** [comment]
Nope that’s a good enough description. The select has been a pain point in V6 so far, but we’re running out of things to fix.

**Comment by jamesmfriedman** [comment]
Found the fix for this. Google actually ditched native selects (again), which I find untenable so I chose to find a way to keep them in. This issue definitely stemmed from that. Will go out in the next patch release.

**Comment by jamesmfriedman** [comment]
@tstirrat Fixed, try it out. One thing that can be changed is that hitting enter on an enhanced select opens the menu, but on a native select, only the up and down arrow will trigger it. This is just standard browser behavior
