### ISSUE TITLE
Can't resolve '@material/dom/dist/mdc.dom.js'

### ISSUE THREAD

**Issue by dawsonc623** [jamesmfriedman/rmwc#597]
- What RMWC Version are you using [major.minor.patch]: 6.0.10

- Name your build system [Webpack, Rollup...]: Webpack

- Describe the bug with as much detail as possible:

Starting from a fresh project, I added `@rmwc/theme` as a dependency, and it threw the error in the title. Here is a sandbox exhibiting the same issue:

https://codesandbox.io/s/rmwc-typescript-sandbox-wtuk6

It looks like `@material/dom` is not listed as a dependency of `@rmwc/theme`.

- What happened, and what was supposed to happen:

`@material/dom` should be installed by `@rmwc/theme`, since `@material/dom` is requirement of `@rmwc/theme`.

**Comment by jamesmfriedman** [comment]
Fixed. It was actually an issue where it wasn't included in @rmwc/base. Google accidentally published a non ES5 module so I had to do some hacky workarounds to make it ES5 compliant.

Up with 6.0.11

**Comment by dawsonc623** [comment]
Works like a charm. Thanks!

By the way, I am loving this library. Thanks for providing it! If you need any help with it, let me know. I do not have a ton of extra time, but I am willing to give back a little when I can.

**Comment by jamesmfriedman** [comment]
I’ll take any and all help. Glad you’re enjoying it. Definitely a wide variety of random issues have popped up with the V6 release but I’m squashing then as fast they pop up. Never happy that anyone runs into an issue but fixing edge cases like this make the project stronger.
