### ISSUE TITLE
No support or documentation for `mdc-chipset--input`

### ISSUE THREAD

**Issue by nicholaschiang** [jamesmfriedman/rmwc#598]
> What RMWC Version are you using [major.minor.patch]: 

`^6.0.9`

> Name your build system [Webpack, Rollup...]: 

Next.js's default stuff as setup in [this repository](https://github.com/tutorbookapp/covid-tutoring).

> Describe the bug with as much detail as possible:

It looks as if you don't have support for the `mdc-chipset--input` options that are described on [MDC's official documentation](https://material.io/develop/web/components/chips/).

**Comment by jamesmfriedman** [comment]
A few things on this
- Yes it is described in MDCs documentation, but there is no demo of it
- In terms of styling, it doesn't apply any different styling to chip sets
- In terms of behavior, it doesn't modify the behavior of the chip set.

Their docs basically say add this class, but wire it up yourself. So you would have to do the same with React anyways.

I hacked together this sandbox. Interestingly enough it exposes a bug in Chipsets where the exit animation is being triggered when when a chip isn't interacted with, but this is the basic idea. 

https://codesandbox.io/s/rmwc-typescript-sandbox-y7516

**Comment by nicholaschiang** [comment]
Thanks, yeah, I'm working on wiring something similar up right now! The idea is to replicate the Gmail "to" field when composing an email:

![image](https://user-images.githubusercontent.com/20798889/78583561-d69f3780-77eb-11ea-95e3-21b34643e46d.png)

I'm thinking that I'm going to place a `ChipSet` into a `TextField` but I'm having trouble adding a `className` to the `TextField`'s input (it says that it should relay additional props to the native `input`, but React seems to be adding the `className` to the `mdc-text-field` `label` element).

I've modified your sandbox for a quick demo of what I'm thinking (though I'm not quite sure how to enable CSS Modules).

https://codesandbox.io/s/rmwc-typescript-sandbox-u0o5q

**Comment by jamesmfriedman** [comment]
className does get added to the root of the element. if you need to target the native input just add your class and select the input in css.

```
.myTextField input {
   ...mystyles
}
```

**Comment by nicholaschiang** [comment]
Thanks! That doesn't completely solve my problem, but I'm closing this issue as I'm more specific in #601.
