### ISSUE TITLE
Chips onRemove gets called when neighboring chips are interacted with

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#600]
Expected behavior, only the interacted chip should have the animation triggered https://codesandbox.io/s/rmwc-typescript-sandbox-y7516

**Comment by cordial-canary** [comment]
There are no chips at that link, and I can't reproduce the issue. Did the sandbox code change?

**Comment by jamesmfriedman** [comment]
Since I’m the code sandbox owner I accidentally edited the original and then had to revert it. But this is still an open issue.

**Comment by cordial-canary** [comment]
I'd like to try to hunt down this bug. Any hints on how to reproduce it? The onRemove handlers are only getting called when the chips are closed in this sandbox:

[https://codesandbox.io/s/rmwc-typescript-sandbox-lmd9h](https://codesandbox.io/s/rmwc-typescript-sandbox-lmd9h)
