### ISSUE TITLE
Installation errors while installing components 

### ISSUE THREAD

**Issue by solomonakp** [jamesmfriedman/rmwc#605]
Trying to install a component since I didnt install the whole npm package but I keep getting this error 
npm i @rmwc/select --save
: npm ERR! code Z_BUF_ERROR 
npm ERR! errno -5
npm ERR! zlib: unexpected end of file 
npm ERR! A complete log of this run can be found in: 
npm ERR!     C:\Users\Chokor solomon\AppData\Roaming\npm-cache\_logs\2020-04-07T06_33_23_927Z-debug.log  

I dont there is something wrong with my version of npm because i tried instaling other random packages
i needed and it worked just rmwc packages

**Comment by jamesmfriedman** [comment]
This isn’t a problem with this library. A quick google search. 

https://stackoverflow.com/questions/48739985/npm-err-code-z-buf-error-when-install
