### ISSUE TITLE
Initially no Notched Outlines in Dialogs

### ISSUE THREAD

**Issue by dave-hillier** [jamesmfriedman/rmwc#607]
This is probably an MDC bug, Notched outlines don't work correctly when inside a modal dialog. They work correctly when put in the body but when combined with a dialog they don't seem to be applying the notch style `mdc-notched-outline--notched`. When the control gains focus, the problem fixes itself. 

This can be observed when you combine the examples from SimpleDialog and Select:

```
function Example() {
  const [open, setOpen] = React.useState(false);
  return (
    <>
      <SimpleDialog
        title="This is a simple dialog"
        body="You can pass the body prop or children."
        open={open}
        onClose={evt => {
          console.log(evt.detail.action);
          setOpen(false);
        }}
      >
        <Select
          outlined
          enhanced
          label="With Icon"
          defaultValue="Pizza"
          helpText="Choose your favorite snack..."
          icon="favorite"
          options={['Cookies', 'Pizza', 'Icecream']}
        />
      </SimpleDialog>

      <Button raised onClick={() => setOpen(true)}>
        Open Simple Dialog
      </Button>
    </>
  );
}
```
It draws a line through the title. 

![image](https://user-images.githubusercontent.com/2045572/78808790-d787c300-79bd-11ea-9bbb-e7f8b369bfb1.png)

Version 6.0.14

**Comment by lbell** [comment]
Looks related: https://github.com/jamesmfriedman/rmwc/issues/568#issuecomment-605465345

**Comment by dave-hillier** [comment]
@lbell yeh, that looks like the same problem

**Comment by jamesmfriedman** [comment]
Yeah this is definitely strange. Looks like something that would be fixed by forcing the DOM to repaint. I'll take a look.
