### ISSUE TITLE
How could I change the border radius 

### ISSUE THREAD

**Issue by sangdth** [jamesmfriedman/rmwc#608]
Hi, thanks for the awesome work, I enjoy this lib at both work and personal projects.

I wonder how could I change the border radius in global, I mean every where, text field as well as buttons etc. I've tried to check the Theme section but the Option seem has only color or I miss something.

**Comment by jamesmfriedman** [comment]
There isn’t anything available yet on the css variable side but I think there border Mixins available if you’re using mat-webs sass files. Check out their documentation on it. There is a link in the styles / SASS section of the RMWC docs.

**Comment by sangdth** [comment]
Thanks @jamesmfriedman, I'm digging around and after spent hours slapping my head to the keyboard, I [can't make it](https://github.com/zeit/next.js/discussions/11808). Maybe I will just gave up now.

**Comment by jamesmfriedman** [comment]
ouch. Well, you can always just use CSS as well. What I've done on my previous projects, works just fine. Apply to whatever other things you want.

.mdc-button {
  border-radius: 10px !important;
}

**Comment by sangdth** [comment]
Thanks, but it's not what I want. It would end up in a really messy `!important` war. I will try to find another better solution.
