### ISSUE TITLE
Can't figure out how to focus a TextField

### ISSUE THREAD

**Issue by anthonysapien** [jamesmfriedman/rmwc#619]
- What RMWC Version are you using [major.minor.patch]: 6.1.0

- Name your build system [Webpack, Rollup...]: create-react-app

- Describe the bug with as much detail as possible: I'm unable to programmatically set focus to a TextField 

- What happened, and what was supposed to happen:
I tried to set a ref on the TextField and call ref.current.focus() but it doesn't seem to have an effect.

Thanks!

**Comment by jamesmfriedman** [comment]
There is an inputRef prop. Ref is a reference to the inputs container.

**Comment by anthonysapien** [comment]
I finally got to this, and it's working with inputRef. Thanks so much!
