### ISSUE TITLE
Update to material-components-web 8

### ISSUE THREAD

**Issue by victorandree** [jamesmfriedman/rmwc#620]
[material-components-web v8.0.0](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#800-2020-11-02) has been released with quite a few changes. This release has a decent amount of new features I'd personally love to use. Unfortunately, the list of breaking changes is also long.

Hoping to see the release incorporated into this project :)

PS. I hope it's helpful to create an issue for this.

_Edit:_ Since creating this issue, there's been 2 major releases for material-components-web. I've chosen to just edit this issue to skip the 6 and 7 upgrades, and go straight to 8.0.0.

**Comment by jamesmfriedman** [comment]
It’s fine as a place to coalesce around. I already read through the changes. Shouldn’t be that bad this time around, but they changed the Select again which is responsible for over half the patches this library gets...

**Comment by victorandree** [comment]
I've updated this to reflect that there's been another major release of material-components-web (v7!). Anything we can do to help with the upgrade process?

**Comment by jamesmfriedman** [comment]
I'll get a branch going that we can all fork and PR to and get this moving.

**Comment by suhaibmujahid** [comment]
[v8.0.0](https://github.com/material-components/material-components-web/releases/tag/v8.0.0) just got released.

**Comment by suhaibmujahid** [comment]
I would be happy to help with this. Also, `react` v17 is out there, it will be great to support it. The good news that `react` v17 is backward compatible.
