### ISSUE TITLE
Ripples not disabled with RMWCProvider

### ISSUE THREAD

**Issue by kapilgarg1996** [jamesmfriedman/rmwc#623]
I want to disable ripple only for TextField but after spending hours i couldn't find a way to do so. Why there isn't a basic option to enable/disable ripples on components which come with ripples by default. Did i miss anything in the documentation ? Or if such option is there then can it be highlighted in the documentation?

- RMWC Version: 6.0.14

- Name your build system : Webpack (create-react-app)

PS: I dont want to use global settings to disable ripple for all elements

**Comment by jamesmfriedman** [comment]
It sounds like you are talking about the underline, not the ripple effect. The ripple is the background ink drop thing that happens. 

The underline cannot be disabled currently but you can hide it with some basic css rules.

**Comment by kapilgarg1996** [comment]
Yes, i meant underline only and i ended up disabling it using CSS. I personally think there should be an option to disable the underline ripple also. But even if it is not going to come, there should be some documentation about the css hack.
