### ISSUE TITLE
Margin at TopAppBar it does not fit correctly

### ISSUE THREAD

**Issue by MikeCastillo1** [jamesmfriedman/rmwc#626]
- What RMWC Version are you using [major.minor.patch]:
6.014
- Name your build system [Webpack, Rollup...]:
webpack
- Describe the bug with as much detail as possible:
there is a margin when using top-app-bar
- What happened, and what was supposed to happen:

the top app bar should fit at the top of the browser without a margin, you can see on the following sandbox: 
https://codesandbox.io/s/rmwc-sandbox-9ctfw?file=/index.js

**Comment by jamesmfriedman** [comment]
The styles come directly from google, so this would be an upstream issue. 

But the actual issue is that every browser has a default margin / padding on the body. Either use a reset or just apply margin and padding of 0 to the body and HTML element.

**Comment by BalamChaac** [comment]
Hello James, 

Ok, I will review that, also I notice that the font does not adapt to different screen sizes, the ones that are featured like headline1 headline 3, etc.

do you have an example on how to manage this from rmwc?, thanks
