### ISSUE TITLE
Outlined buttons use grey color for border

### ISSUE THREAD

**Issue by francos** [jamesmfriedman/rmwc#631]
### What RMWC Version are you using [major.minor.patch]: 

6.0.14

### Name your build system [Webpack, Rollup...]: 

Webpack

### Describe the bug with as much detail as possible:

Outlined buttons border color is grey by default instead of using the primary color set. This can be seen in the RMWC website: https://rmwc.io/buttons

### What happened, and what was supposed to happen:

The border color for outlined buttons should use the same primary color set for the theme as it worked in version 5.x

**Comment by jamesmfriedman** [comment]
This is something you’d have to open with google. RMWC uses the css directly from Material components web, they have recently changed the spec.

**Comment by francos** [comment]
Thanks for the quick answer @jamesmfriedman, checking their website they are still showing the primary color for outlined colors: https://material.io/components/buttons (maybe their website is not updated though).

Is there a way to change the border color using RMWC or CSS properties?

**Comment by jamesmfriedman** [comment]
Oddly enough, the spec is updated, RMWC is right, their live docs are wrong. https://material.io/develop/web/components/buttons/

Just standard css. Target the button and set it's border color to `border-color: currentColor`

**Comment by francos** [comment]
Thanks for the info @jamesmfriedman! I'll close this then.
