### ISSUE TITLE
Textfield ignores theming options

### ISSUE THREAD

**Issue by wmadden** [jamesmfriedman/rmwc#633]
`<Textfield>` ignores theming options which should otherwise change its text color (and maybe background color). 

A really simple example of this is the RMWC docs in dark mode:

![image](https://user-images.githubusercontent.com/12165/82123113-df463e80-9797-11ea-87d4-21837a4a3138.png)

I'm not sure if it's a bug with MDC since the theme implementation is in RMWC but the SASS providing `input { color: black }` is in MDC 🤷‍♂️

**Comment by jamesmfriedman** [comment]
Yes this is a bit tricky. As a rule the majority of styling comes from MDC but their support for css variables is inconsistent. RMWC maintains a file that fixes a lot of these issues, so this might just be on that hasn’t been addressed. I’ll take a look.

**Comment by wmadden** [comment]
Looks like this is indeed a bug in MDC: https://github.com/material-components/material-components-web/issues/4709 (which I notice you [already commented on](https://github.com/material-components/material-components-web/pull/3145#issuecomment-463316463) @jamesmfriedman).

If certain components ignore the theme, dynamic theming in RMWC is effectively unusable. For my project I've hacked together a small fix for the `<TextField>` as follows:

```css
.mdc-text-field:not(.mdc-text-field--disabled) {
  background-color: var(--mdc-theme-background);
}
```

This simulates the behavior in MDC which sets the background-color [here](https://github.com/material-components/material-components-web/blob/f86f83f546b9c7eea07b4cbdae2c341423ad599c/packages/mdc-textfield/_mixins.scss#L2446) (called originally from [here](https://github.com/material-components/material-components-web/blob/f86f83f546b9c7eea07b4cbdae2c341423ad599c/packages/mdc-textfield/_mixins.scss#L1472)), if I'm reading their SCSS correctly.

It's not perfect, but it's a start. It might be good use a similar approach to patch the MDC CSS in RMWC so that the components actually respect the run-time theme.
