### ISSUE TITLE
Prefilled text fields aren't working well

### ISSUE THREAD

**Issue by nicholaschiang** [jamesmfriedman/rmwc#636]
> What RMWC Version are you using [major.minor.patch]: 

`6.1.0`

> Name your build system [Webpack, Rollup...]: 

Default setup that Next.js uses (pretty sure it's `webpack`).

> Describe the bug with as much detail as possible:

Your fix to #601 was awesome, but it doesn't look like it's working properly:

![floating-label-err](https://user-images.githubusercontent.com/20798889/82394827-e1f69d00-99fe-11ea-8f4f-72d50808f835.gif)

And I'm not referring to the label not floating after the text field is filled. I'm referring to the notch not closing up again when the label isn't floating.

You can see the basic recreation [here](https://codesandbox.io/s/rmwc-typescript-sandbox-sx37j).

> What happened, and what was supposed to happen:

The notch should close and the placeholder should no longer be width constricted when `floatLabel` is false.

**Comment by nicholaschiang** [comment]
FYI @jamesmfriedman [this is the project](https://tutorbook.org) that your component library has been put so hard to work on (if you're curious)! Feel free to send me any feedback on it.

**Comment by jamesmfriedman** [comment]
Looks great! Hopefully the good has outweighed the issues you’ve hit.

**Comment by nicholaschiang** [comment]
Any fix on this yet @jamesmfriedman? I'm waiting on it to push to production.
