### ISSUE TITLE
Can't set value from Menu selection in TextField

### ISSUE THREAD

**Issue by francos** [jamesmfriedman/rmwc#638]
### What RMWC Version are you using [major.minor.patch]:

5.7.2

### Name your build system [Webpack, Rollup...]:

Webpack

### Describe the bug with as much detail as possible:

I'm building a component that has a `TextField` and a `Menu` that behaves like this: 

1. When the user starts typing on the `TextField`, I perform an async search with the text entered.

2. The result of the search is a list of strings that I show in the `Menu` that appears under the `TextField`.

3. When the user selects an item from the `Menu`, I write this value in the `TextField`.

Steps 1 and 2 are working fine, but I'm having issues making step 3 work. When I try to set the value in the `TextField` I have 2 property options:

1. `defaultValue`: This only works for the initial value so it's not setting it because I already have some text in the `TextField`.

2. `value`: I can't use this property because then the `TextField` becomes "controlled" and then the user can't write on it.

I'm sure I'm doing something wrong cause this is a common use case so this should work, but I can't figure out what it is. Is there some property that I'm missing that works for this scenario?

**Comment by jamesmfriedman** [comment]
Not sure about your specific issue, but this just sounds like a standard react thing and maybe a gap in knowledge.

Here is a super basic example of using a controlled textfield and setting the value. This isn't RMWC specific, the same would work with a standard input.

https://codesandbox.io/s/rmwc-typescript-sandbox-37131?file=/src/index.tsx

**Comment by francos** [comment]
Thanks for the answer @jamesmfriedman, it was indeed a gap in knowledge. What was happening was that I was setting an empty `String` to the `value` when it was created the first time and that prevented me from typing on it for some reason. Once I stopped setting that value at the beginning it all started working as expected.

Thanks for the help :)
