### ISSUE TITLE
Support overriding material-icons with @mdi/font

### ISSUE THREAD

**Issue by jahirfiquitiva** [jamesmfriedman/rmwc#643]
- What RMWC Version are you using [major.minor.patch]: 6.1.0

- Name your build system [Webpack, Rollup...]: webpack

- Describe the bug with as much detail as possible:
I am trying to use custom icons from [`@mdi/font`](https://www.npmjs.com/package/@mdi/font), but the icons are not shown.

This is my provider:
```javascript
<RMWCProvider
    icon={{
      strategy: 'className',
      basename: 'mdi',
      prefix: 'mdi-',
    }}>
	{...}
</RMWCProvider>
```

**Comment by jahirfiquitiva** [comment]
Temporarily fixed like this but 😕 
```javascript
<TopAppBarActionItem icon={''}>
	<span className={'mdi mdi-24px mdi-star-outline'}/>
</TopAppBarActionItem>
```

**Comment by jamesmfriedman** [comment]
that does appear to be setup properly, but I'd need to see a repro in order to better assist. At any rate, it is indeed supported. Stackoverflow is a better place for questions since I don't believe there is a bug present here.

Is it possible that you forgot to include your icon font?

**Comment by jahirfiquitiva** [comment]
no, I didn't forget to include the font... for some reason it works in certain components but not all... will try to make an example later

**Comment by jahirfiquitiva** [comment]
hey @jamesmfriedman  this was working for buttons but after v 6.1.3 it doesn't work anymore and the icon name is put inside the `i` tag for the icon, even though I have set the `strategy` to `className`
