### ISSUE TITLE
Clicking fab makes site reload

### ISSUE THREAD

**Issue by jahirfiquitiva** [jamesmfriedman/rmwc#645]
- What RMWC Version are you using [major.minor.patch]: 6.1.0

Watch the gif and see how `?` is added to the url, the favicon becomes a spinner and the site reloads

![Grabación de pantalla 2020-05-27 a la(s) 16 09 47](https://user-images.githubusercontent.com/10360816/83073011-5354d200-a035-11ea-8f41-0897efe745cb.gif)

**Comment by jamesmfriedman** [comment]
I don't know what your code looks like, but I'm reasonably certain that fab doesn't have anything to do with it

**Comment by jahirfiquitiva** [comment]
Woops, sorry... I forgot I put the fields inside a form, because they didn't stack vertically but horizontally...

Is there some way to make them stack vertically without adding `<br/>`s ?

**Default**
![Shot 2020-05-27 at 16 22 15](https://user-images.githubusercontent.com/10360816/83073555-3ff63680-a036-11ea-9e93-e54add563d43.png)

**Expected**
![Shot 2020-05-27 at 16 21 37](https://user-images.githubusercontent.com/10360816/83073571-44baea80-a036-11ea-89ac-1715af2cef22.png)

**Comment by jamesmfriedman** [comment]
Just wrapping them in divs or a BR. They're inline-block by default.

**Comment by jahirfiquitiva** [comment]
Thanks, wrapping in `div`s worked
