### ISSUE TITLE
Export DialogQueueSpec

### ISSUE THREAD

**Issue by aktary** [jamesmfriedman/rmwc#646]
- What RMWC Version are you using [major.minor.patch]: 6.0.14

- Name your build system [Webpack, Rollup...]: Parcel

- Describe the bug with as much detail as possible: Simple TypeScript issue.  Need to add the `export` keyword to DialogQueueSpec in `dialog-queue.d.ts`

- What happened, and what was supposed to happen:  Without the `export`, TS complains:
>Exported variable 'dialogQueue' has or is using name 'DialogQueueSpec' from external module ".../node_modules/@rmwc/dialog/dist/dialog-queue" but cannot be named.

Adding the `export` keyword will fix it.

**Comment by jamesmfriedman** [comment]
Never had this issue. Is it possible that this is a tsconfig setting?

**Comment by aktary** [comment]
Maybe.  [This](https://github.com/microsoft/TypeScript/issues/5711) issue suggests that the `--declaration` flag may be causing TS to try to generate declaration files, but since DialogQueueSpec isn't exported, it can't do it's job.  I've tried disabling that in `tsconfig.json`, but TS is still complaining, so 🤷‍♂️.  That interface is the only one in the file that isn't exported... is exporting it a problem?

**Comment by aktary** [comment]
it's really a very small, non-breaking change. I'd greatly appreciate if you'd implement it... or if you'd prefer, I can put in a PR... just seems silly to do that for such a small thing.

**Comment by jamesmfriedman** [comment]
Releasing now, should be live in a few minutes.
