### ISSUE TITLE
RMWC with postcss-custom-properties / postcss-cssnext / Rails and Webpacker (needs documentation)

### ISSUE THREAD

**Issue by sidot3291** [jamesmfriedman/rmwc#65]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

### What RMWC Version are you using?

0.0.1-rc12

### What build system are you using?

Rails with Webpacker Gem

### What are the steps to reproduce the bug?

 - Create new rails app with webpacker set to React
 - yarn add rmwc
 - Add `import 'material-components-web/dist/material-components-web.css'` to pack

### What is the expected behavior?

You can argue that everything is behaving as expected.

MCW uses a styling behavior that postcss-custom-properties doesn't accept by default.

So, by default when using rmwc, compiling throws off a bunch of warnings and the styling is broken:

Example Warning (there are a bunch of these):
```
    WARNING in ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/ROOT/.postcssrc.yml"}}!./node_modules/material-components-web/dist/material-components-web.css
    (Emitted value instead of an instance of Error) postcss-custom-properties: /ROOT/node_modules/material-components-web/dist/material-components-web.css:9325:5: Custom property ignored: not scoped to the top-level :root element (.mdc-text-field--box.mdc-ripple-upgraded { ... --mdc-ripple-fg-opacity: ... })
    NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-properties: /ROOT/node_modules/material-components-web/dist/material-components-web.css:9325:5: Custom property ignored: not scoped to the top-level :root element (.mdc-text-field--box.mdc-ripple-upgraded { ... --mdc-ripple-fg-opacity: ... })
        at Object.emitWarning (/ROOT/node_modules/webpack/lib/NormalModule.js:117:16)
        at result.warnings.forEach (/ROOT/node_modules/postcss-loader/lib/index.js:149:49)
        at Array.forEach (native)
        at postcss.process.then (/ROOT/node_modules/postcss-loader/lib/index.js:149:27)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Rendered button (this is active state, there's no background color in bare state):
<img width="85" alt="screen shot 2017-12-22 at 10 25 29 am" src="https://user-images.githubusercontent.com/614945/34303231-75d737b2-e702-11e7-9d59-3368e7d3198c.png">

### Solution

The solution is to pass the preserve = true option to postcss-custom-properties:
https://github.com/postcss/postcss-custom-properties#options

Or, if you're using postcss-cssnext, passing it *through* that plugin:
```
postcss([
  cssnext({
    features: {
      customProperties: {
        preserve: true
      }
    }
  })
])
```
http://cssnext.io/usage/#features

Or, if you're using the webpacker gem, updating .postcssrc.yml in your app's root to include:
```
plugins:
  postcss-cssnext: {
    features: {
      customProperties: {
        preserve: true
      }
    }
  }
```

Note: setting `warnings: true` will also disable the compile-time warnings.

---

I'm not sure if notes on this belong in RMWC.  Since RMWC is un-opinionated, I can imagine that means helping users through installation issues even if they are caused by dependencies.  But I can also see it going the other way.

Interestingly, the Angular MCW wrapper has issues about the warnings but not the styling errors.  This is because Angular uses `preserve: true` by default:
Issue: https://github.com/trimox/angular-mdc-web/issues/394
Default: https://github.com/angular/angular-cli/blob/9caa7ca0d1ab175301b60fcb5d3c42379a51a58d/packages/%40angular/cli/models/webpack-configs/styles.ts#L8

**Comment by jamesmfriedman** [comment]
I ran into this exact same problem last week. I agree some documentation is needed. I’ll make sure to add it to the new docs QuickStart guide.

**Comment by jamesmfriedman** [comment]
@sidot3291 I added documentation to the getting started guide on the docs. Can you validate that it accurately informs about this issue?

**Comment by jamesmfriedman** [comment]
This is documented in the pending V1 release

**Comment by jamesmfriedman** [comment]
Hi @mickeypuri, sorry for the late reply on this.

- It's not always an issue, it only happens with certain configurations that have been hard to pinpoint.
- If you are experiencing this issue and do not want to eject, I would recommend using https://github.com/timarney/react-app-rewired. It allows you to modify the CRA configuration on the fly. I personally almost never eject now, I just use this.
- If you look in the root dir of this project at the file config-overrides, you'll see an example of it being used.

**Comment by jamesmfriedman** [comment]
This issue hasn't come up in a long time. I'm removing this from the main docs and posting here if it ever pops up again.

* Issue: postcss-cssnext messes up CSS variables. This can cause broken styles and extreme slowdowns when using web developer tools like the Chrome inspector. You'll know if you're having this issue because dev tools and the browser will slow to a crawl.
  * Solution: set customProperties to false. This may require ejecting or other workarounds if you are using Create React App. [See issue #65](https://github.com/jamesmfriedman/rmwc/issues/65).

```javascript
postcss([
  cssnext({
    features: {
      customProperties: {
        preserve: true
      }
    }
  })
]);
```
