### ISSUE TITLE
Forms do not work in Dialogs

### ISSUE THREAD

**Issue by fdc-viktor-luft** [jamesmfriedman/rmwc#652]
### Sandbox
https://codesandbox.io/s/rmwc-typescript-sandbox-g63tq

### Version of @rmwc/dialog
6.1.0

### build system 
Webpack (Create React App)

### Description
When opening a `Dialog` and setting `preventOutsideDismiss` to `true` the dialog closes as soon as you hit ENTER on your keyboard when the focus is within a text field.

### What happened, and what was supposed to happen
The dialog closes with a "cancel" event.

The dialog should not close. Because of the current behaviour, I can not use form submission within dialogs correctly. `preventOutsideDismiss` should not prevent to close the modal when clicking outside the scrim but also when submitting a form. It might be even incorrect behaviour regardless the value of `preventOutsideDismiss`.

Please fix this issue or you are forcing me to implement my own dialog :(

Additional note:
Submitting the form still works but I can not stop the Dialog from closing. But this is necessary if submitting returns with validation errors.

**Comment by rikvdk** [comment]
Removing the `isDefaultAction` from the second DialogButton seems to fix your problem:
```jsx
<DialogButton action="accept">
    Sweet!
</DialogButton>
```
Hope this helps.

**Comment by fdc-viktor-luft** [comment]
It does 🤯 How could I not see this one. Thanks for your help 👍
