### ISSUE TITLE
Responsive example

### ISSUE THREAD

**Issue by jahirfiquitiva** [jamesmfriedman/rmwc#654]
Hello

I just wanted to ask for a responsive example. I think the framework isn't mobile-first, so it's been hard for me to achieve a responsive result.

Would be great to have better support for that.

Thanks

**Comment by jamesmfriedman** [comment]
@jahirfiquitiva the docs themselves are responsive. Material design itself is modeled to be mobile first and mobile friendly. Have you checked the material.io for design guidance?

**Comment by jahirfiquitiva** [comment]
are the docs open source too? mind linking me to their source?

and btw, I wasn't looking for design guidance, but rather implementation guidance.

Like a section where you explain how to "transform" toolbar items into a drawer when in mobile devices, or something like that?

Maybe even components that do that... transform their contents/look based on breakpoints

**Comment by jamesmfriedman** [comment]
They're hacked together, but you can find some examples of mobile implementation on there. Honestly I think the only difference is the main navigation. 

https://github.com/jamesmfriedman/rmwc/tree/master/src/rmwc/docs

**Comment by jahirfiquitiva** [comment]
thanks for sharing

**Comment by jamesmfriedman** [comment]
No problem
