### ISSUE TITLE
Typography defaults to <span> instead of <div>

### ISSUE THREAD

**Issue by sidot3291** [jamesmfriedman/rmwc#66]
### What RMWC Version are you using?

0.0.1rc12

### What build system are you using?

Webpack

### What are the steps to reproduce the bug?

```
<Typography use="display-4">Test</Typography>
```

### What is the expected behavior?
```
<div class="mdc-typography--display4">Display 4</div>
```

The docs say div is the default tag:
https://jamesmfriedman.github.io/rmwc/typography

### What is the actual behavior?
```
<span class="mdc-typography--display4">Test</span>
```

### Any other information you believe would be useful?

From inspecting MCW's demo, you can see they use semantic tags, h1, h2, p, etc depending on the typography type:
https://material-components-web.appspot.com/typography.html

I would prefer this, but perhaps light wrappers are a better place for adding semantics?

e.g.
```
<Display4>Test</Display4>
```

maps to:

```
<Typography use="display4" tag="h1">Test</Typography>
```

**Comment by jamesmfriedman** [comment]
Definitely need to update the docs on this. What’s your preference?

My reasoning for using a span was that its inline and won’t affect the flow of content, making it much easier to just style text while allowing you to use the tag prop to define your own semantics.

**Comment by sidot3291** [comment]
`div` for Typography makes more sense to me.  The only time I really use inline styling is for *bold* or _italics_, and those are infrequent.

That said, I'd probably build myself individual wrapper components since they're a bit more readable for me within an application.

**Comment by sidot3291** [comment]
I ended up make a `<Text>` component to wrap Typography being used in a "text context."  I applied semantic tags and set adjustMargin to true, but otherwise kept the `use` prop for consistency.

It was inspired by this bit in the documentation:
> A note about mdc-typography--adjust-margin, mdc-typography--adjust-margin will change the margin properties of the element it is applied to, to align text correctly. mdc-typography--adjust-margin should only be used in a text context; using this property on UI elements such as buttons may cause them to be positioned incorrectly.
https://material.io/components/web/catalog/typography/

```jsx
export function Text(props) {
  const tags = {
    display4: "h1",
    display3: "h1",
    display2: "h1",
    display1: "h1",
    title: "h2",
    subheading2: "h3",
    subheading1: "h4",
    body1: "p",
    body2: "aside",
    caption: "span"
  };
  return (
    <Typography tag={tags[props.use]} adjustMargin={true} {...props}>
      {props.children}
    </Typography>
  );
}
```

**Comment by jamesmfriedman** [comment]
I just saw that the demo page is where you got your tag mapping from. @j-o-d-o @UFOMelkor what are your opinions on this?

We can change those to be the defaults for each individual item.

**Comment by sidot3291** [comment]
One extra point to consider:

If RMWC endorses the mapping on the demo, does it also endorse the demo's use of Normalize?

That would be problematic because mapping by default isn't good for any case:

If you're rendering block text, you have to fix the normalize's margins by setting adjustMargin to true.

If you're rendering something else (within another component), you'd have to find a way to disable normalize's margins.

**Comment by jamesmfriedman** [comment]
I'm interested in not mapping because semantics and styling vary widely between projects. For instance, if a reset isn't applied, a lot of times h1 - h5 have default styles and margins on them that can be inherited by the typography classes.

RMWC does have the (undocumented) concept of a provider where you can set some global defaults. Would the ability to set the default typography tag help?

**Comment by izakfilmalter** [comment]
I prefer `span` by far. Of not is that it is super easy to change the tab.

**Comment by jamesmfriedman** [comment]
@sidot3291 I'm a bit confused by your last comment when I reread it. Are you satisfied with closing this out?. Creating wrapper classes seems like a viable workaround if you want to couple a specific tag to a typography class. I'm not highly opinionated on this one, it's one of those gray areas that are open to interpretation.

**Comment by sidot3291** [comment]
I'm satisfied as is, though I rarely use Typography directly.  That comment was to warn against defaulting to semantic elements without also defaulting to adjustMargin to true, since semantic elements often have different margin defaults applied to them from other stylesheets (e.g User Agent, Normalize).

Unless I'm doing something with custom alignment, I have been using the following Text component to display text.  I use this more than Typography directly because I usually want block elements with the recommended margins.

```
import { Typography } from 'rmwc';

export function Text(props) {
  const tags = {
    display4: "h1",
    display3: "h1",
    display2: "h1",
    display1: "h1",
    headline: "h1",
    title: "h2",
    subheading2: "h3",
    subheading1: "h4",
    body1: "p",
    body2: "aside",
    caption: "span"
  };
  return (
    <Typography tag={tags[props.use]} adjustMargin={true} {...props}>
      {props.children}
    </Typography>
  );
}
```

**Comment by jamesmfriedman** [comment]
Not to mention that `Text` is markedly less annoying to type than `Typography`. If I wasn't so intent on maintaining identical naming conventions to MDC, that would have been my choice as well.

I'll go ahead and close this out, thanks for your input.
