### ISSUE TITLE
Feature: Multiline text fields

### ISSUE THREAD

**Issue by nickmccurdy** [jamesmfriedman/rmwc#660]
There is a [multiline prop in Material UI](https://material-ui.com/components/text-fields/#multiline) that allows you to render a textarea that starts with one line, and dynamically expands its heights to allow for new lines rather than scrolling. RMWC seems to only allow static height textareas, but I think this would be a convenient additional especially when migrating apps from Material UI.

It's worth noting that there's also a [reusable TextareaAutosize component](https://material-ui.com/components/textarea-autosize/) that's maintained by material UI but not coupled with their styles. I wonder if we could use this, but I don't have a very good understanding of how MDC's adapters work.

**Comment by jamesmfriedman** [comment]
I agree, this would be very useful.

I've built a 101 of these in the past, there are some really easy ways to make it happen. I'll look into it.
