### ISSUE TITLE
Bottom Navigation

### ISSUE THREAD

**Issue by anthonysapien** [jamesmfriedman/rmwc#664]
Hi, I'm wondering if you're planning to add 'Bottom Navigation' support:
https://material.io/components/bottom-navigation

Should I just use Tabs in the meantime? If so, I'd need to fix them to the bottom.

Thanks!

**Comment by jamesmfriedman** [comment]
They haven't implemented it upstream yet. But yes, I think it would be very useful. Personally I have just used tabs myself.

**Comment by anthonysapien** [comment]
Cool, thanks for responding. I'll go with tabs for now.
