### ISSUE TITLE
Icon not showing in textfield 

### ISSUE THREAD

**Issue by kamarajuPrathi** [jamesmfriedman/rmwc#666]
<img width="216" alt="Screenshot 2020-07-07 at 3 41 52 PM" src="https://user-images.githubusercontent.com/25597219/86840525-6dd48f00-c068-11ea-8120-f74312e76353.png">
Latest version of @rmwc/textfield , unable  to show the icons even i import the styles as mentioned in the documentation 

https://codesandbox.io/s/flexible-rmwc-textfield-size-cbihe?file=/src/App.js

**Comment by jamesmfriedman** [comment]
Updated the sandbox, you forget to include the icon font. Look at the change in public/index.html
