### ISSUE TITLE
@rmwc textfield customization 

### ISSUE THREAD

**Issue by kamarajuPrathi** [jamesmfriedman/rmwc#668]
I am trying to use @rmwc/textfield as the control component for react-select (https://react-select.com/home)

the input box should behave as a select with menu options and chips as part of it .. i have inherit the children props from react select to @rmwc/textfield , will that work ?

**Comment by kamarajuPrathi** [comment]
What does rootprops take in @rmwc/textfield ?

**Comment by kamarajuPrathi** [comment]
for @material-ui Text Field I can provide the below inputs in this format

 `<TextField
      InputProps={{
        inputComponent,
        inputProps: {
          className: props.selectProps.classes.input,
          inputRef: props.innerRef,
          children: props.children,
          ...props.innerProps
        }
      }}
      fullWidth={true}
      {...props.selectProps.textFieldProps}
    />`

Is there a way for @rmwc/TextField can i provide the Input Comoponent and children like that

**Comment by kamarajuPrathi** [comment]
@jamesmfriedman can you please respond

**Comment by nicholaschiang** [comment]
@kamarajuPrathi I've actually implemented something similar to what you're describing (i.e. the [`react-select` multi component](https://react-select.com/home)) for the [Tutorbook website](https://tutorbook.org):

![demo-of-select](https://user-images.githubusercontent.com/20798889/87735245-d4089280-c789-11ea-9742-2d05706225ae.gif)

I'm using a combination RMWC components:
- `ChipSet`, `Chip` for the selected options.
- `MenuSurface`, `MenuSurfaceAnchor` for the drop-down menu.
- `List`, `ListItem`, `Checkbox` for the suggestion items (in the select drop-down).
- `TextField` (with a resizable `textarea`) for the actual input.

You can view my open-source implementation [here](https://github.com/tutorbookapp/tutorbook/blob/develop/components/select/index.tsx#L359) if you're interested. You can copy the source code for that `Select` component and wrap it yourself like so:

```tsx
import Select from 'components/select';

const OPTIONS: string[] = ['Option A', 'Option B', 'Option C'];

interface OptionSelectProps {
  value: string[];
  onChange: (value: string[]) => void;
}

interface Option {
  value: string;
  label: string;
}

export default function OptionSelect({ value, onChange }: OptionSelectProps): JSX.Element {
  return (
    <Select
      getSuggestions={async () => OPTIONS.map((o) => ({ label: o, value: o }))}
      value={value.map((v) => ({ label: v, value: v }))}
      onChange={(updated: Option[]) => onChange(updated.map(({ value }) => value))}
    />
  );
}
```

That should produce a basic (controlled) multi-select component using RMWC-only components with some advanced features (that you most likely won't need):
- The `getSuggestions` callback is super useful for async search operations (e.g. querying a database or Algolia index). 
- You can also support i18n by dynamically updating your option `label`s (in the example above, the labels are the same as the option values; but for i18n, you'll want different labels for each locale). 

Let me know if this helps!

**Comment by kamarajuPrathi** [comment]
@nicholaschiang thank you for the detailed information , i dont see you using react-select
