### ISSUE TITLE
Tabs added after initial render are not upgraded

### ISSUE THREAD

**Issue by developerdizzle** [jamesmfriedman/rmwc#67]
### What RMWC Version are you using?

0.0.1-rc12

### What browser(s) and React Version is this bug affecting?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

React ^16.2.0

### What build system are you using?

Webpack

### What are the steps to reproduce the bug?

Create an app where the number of tabs dynamically changes from 1 to 2.

### What is the expected behavior?

Both tabs are "upgraded" (` mdc-ripple-upgraded`, etc.).

### What is the actual behavior?

The first tab is "upgraded", but the second is not.

### Any other information you believe would be useful?

![2017-12-22 14_55_39-localhost_8080_ sh7hfjvi1kzt5y5xqjsntlidnz03_u0wfkx6bgvpd3stqevxi69ex9pm1](https://user-images.githubusercontent.com/1398136/34310935-48039a9e-e728-11e7-8062-9c6d7a7ac5e3.png)

**Comment by jamesmfriedman** [comment]
Thanks for filing. So you’re saying when you dynamically add a tab it doesn’t work as intended? I think I know what would be causing the issue, it’s likely the MDC class has to be reinit when it changes.

**Comment by developerdizzle** [comment]
Yup, that's correct!
