### ISSUE TITLE
Text field character count just doesn't work

### ISSUE THREAD

**Issue by nicholaschiang** [jamesmfriedman/rmwc#671]
- What RMWC Version are you using [major.minor.patch]: 

6.1.3

- Name your build system [Webpack, Rollup...]: 

Default that comes with [Next.js](https://nextjs.org) (which is `webpack`).

- Describe the bug with as much detail as possible:

The `characterCount` prop on the `TextField` component just doesn't do anything. The `TextFieldCharacterCount` component renders fine, but it's content never changes:

![char-counter](https://user-images.githubusercontent.com/20798889/87804206-6780a880-c808-11ea-8507-c6f52ba180a2.gif)

I poked around a little and it looks like the `TextFieldCharacterCount` component renders fine, but it's `MDCTextFieldCharacterCountFoundation` isn't be connected properly to the underlying `MDCTextFieldFoundation`. It seems like when `useFoundation()` initializes the `MDCTextFieldFoundation`, it does so with an `undefined` value for `characterCounter`:

```typescript
      const getFoundationMap = () => {
        return {
          characterCounter: characterCounter.current
            ? characterCounter.current.getFoundation()
            : undefined,
          helperText: undefined,
          leadingIcon: leadingIcon.current
            ? leadingIcon.current.getFoundation()
            : undefined,
          trailingIcon: trailingIcon.current
            ? trailingIcon.current.getFoundation()
            : undefined
        };
      };
```

And then, when the ref value changes for `characterCounter` (set by the `useTextFieldCharacterCountFoundation` hook), the underlying `MDCTextFieldFoundation` never gets updated. Instead, it still has the `undefined` character counter foundation reference.

- What happened, and what was supposed to happen:

The content of the character count never changed. Instead, it should be updated every time the `input` or `textarea` content changes.

**Comment by jmasukawa** [comment]
I'm having the same issue as reported above, on 6.1.4. This was working on 5.7.2 in the same demo: https://rmwc.io/version/5.7.2/text-fields
