### ISSUE TITLE
Can we have a size property for chip for different size variations 

### ISSUE THREAD

**Issue by kamarajuPrathi** [jamesmfriedman/rmwc#672]
Can we have chip with multiple sizes

**Comment by nicholaschiang** [comment]
@kamarajuPrathi You're referring to the height (i.e. density) of the chip, right?

You could just use the MDC Sass mixins (if you're compiling using Sass) like so:
```scss
@use '@material/chips';

.myChip {
  @include chips.height(22px);
}
```

And then just make sure to add that class name to your component. Using `css-modules`, that will look like:
```tsx
import { Chip } from '@rmwc/chips';

import styles from './chips.module.scss';

<Chip className={styles.myChip} />
```
