### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by remy90** [jamesmfriedman/rmwc#674]
[Question]
- RMWC or MDC?
MDC, but bare with me

- What RMWC Version are you using:
rmwc@6.1.3 
- Name your build system:
webpack@4.43.0 

typescript@3.9.7 
next@9.4.4 

- What happened, and what was supposed to happen:

This probably isn't a bug but simply my implementation
```
// mybutton.tsx
import { Button } from '@rmwc/button'
import '@rmwc/button/styles'

const MyButton = (props): JSX.Element => <Button label="ahoy" />

export default MyButton
```
Button is referenced in another tsx file as:
```<MyButton label="ahoy" />```
error message:

> error - ./node_modules/@material/button/dist/mdc.button.css
> Global CSS cannot be imported from within node_modules.
> Read more: https://err.sh/next.js/css-npm
> Location: node_modules/@rmwc/button/styles.js

The link above states: Reach out to the maintainer and ask for them to publish a compiled version of their dependency. My attempt has been to create a local component style reference via mybutton.module.scss but when I @use '@rmwc/button/styles' it can't be found, so I've run out of options. While the error states the issue in MDC, an issue of this nature wouldn't go unnoticed by all users on this version, if that were the case. Any ideas?

**Comment by jamesmfriedman** [comment]
I'm not sure what  `@use` is although I believe it is an scss directive.

@rmwc/buttons/styles is a javascript file that imports other css files. If you need to do @use you'll have to import the styles individually.

Screenshot from the docs. @use doesn't use the css-loader, it uses sass. So you'll have to go with the second option "or include stylesheets"

![image](https://user-images.githubusercontent.com/975256/88071134-74233a80-cb41-11ea-903d-c9c24a4a3de3.png)

**Comment by remy90** [comment]
As you can see from the snippet provided, i've also tried importing. It's not a requirement of mine to use scss, I just can't follow the getting started example provided due to the error stated

**Comment by remy90** [comment]
@jamesmfriedman is it possible this is an issue with next.js?

**Comment by bruqui** [comment]
@jamesmfriedman I've actually answered these questions with @remy90 in Discord, but thought I'd go ahead and put an answer here for you although this isn't related to your library. The @use is part of SASS and node-sass doesn't seem to like it. The way around that is to use the [npm sass library](https://www.npmjs.com/package/sass) instead by adding `implementation: sass` to the options and more than likely, `webpackImporter: false` will also have to be set. These are things that have to be done primarily when you're using the @material SASS files so I thought it might be useful to add this information here in case other users of your library are using @material SASS instead of your css files. Here's an example of how to do it in the next.config.js file...

```
const withStyles = require('@webdeb/next-styles');
const path = require('path');

// SASS
module.exports = withStyles({
    sass: true, // use .scss files
    modules: false, // style.(m|module).css & style.(m|module).scss for module files
    sassLoaderOptions: {
        implementation: require('sass'),
        webpackImporter: false,
        sassOptions: {
            // @import 'variables'; # loads (src/styles/varialbes.scss), you got it..
            includePaths: [
                path.join(__dirname, 'node_modules'),
                path.join(__dirname, 'src/styles'),
            ],
        },
    },
    miniCssExtractOptions: {
        ignoreOrder: true, // for https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-544898772
    },
});
```

...and for Gatsby, this would need to be added to the gatsby-config.js file...

```
const sass = require('sass');
const path = require('path');

module.exports = {
    plugins: [
       {
            resolve: 'gatsby-plugin-sass',
            options: {
                implementation: sass,
                includePaths: [
                    path.join(__dirname, 'node_modules'),
                    path.join(__dirname, 'node_modules/@material/*'),
                    path.join(__dirname, 'src/styles'),
                ],
                webpackImporter: false,
            },
        },
    ]
}
```

**Comment by jamesmfriedman** [comment]
Thanks for posting the answer @bruqui

**Comment by 4cm4k1** [comment]
FYI, [support for importing global CSS was just added on the `canary` release channel in Next.js](https://github.com/vercel/next.js/releases/tag/v9.5.4-canary.10). This may be useful to you. 😄
