### ISSUE TITLE
MultiSelect? Is there any way to achieve the multiselect functionality using <Select>?

### ISSUE THREAD

**Issue by aershov24** [jamesmfriedman/rmwc#676]
Love the lib! I see that MultiSelect was removed from the library. Is there any way to achieve the same multiselect functionality using <Select> and additional options?

**Comment by jamesmfriedman** [comment]
These types of questions are better left to the Discord Channel.

Multiselects were removed pretty early on from the Google team. I think checkbox lists are a valid replacement (look under lists) but you can also just use the browsers standard multi-select.
