### ISSUE TITLE
Cannot read property 'menuIsOpen' of undefined

### ISSUE THREAD

**Issue by GalGreenfield** [jamesmfriedman/rmwc#68]
- RMWC Version: 0.0.1-rc12

- Browser:
    - Type: Google Chrome 
    - Version: 63.0.3239.84 (Official Build) (64-bit) (cohort: Stable)
    - User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.3
- React Version: 16.2.0
- Build System: Create React App

- Steps to reproduce the problem: 
    1. Copy-paste: `import {Menu, MenuAnchor, MenuItem, MenuIsOpen } from 'rmwc;`
    2. Copy-paste the code from here: https://pastebin.com/sZ1VSina
 
- Expected Behavior:  a working dropdown menu as shown in the docs

- Actual behavior: an error: "TypeError: Cannot read property 'menuIsOpen' of undefined"

- Component/code doing things they shouldn't: the `menuIsOpen` property - it doesn't work,

- Other information: it looks to me like this property doesn't even exists, yet there's code that uses it in the documentation and a demo of it there that works.

**Comment by jamesmfriedman** [comment]
This Isn’t a problem with rmwc. It’s simply telling you that this.state is undefined which means you’re probably using a stateless component instead of a React.Component class.

**Comment by GalGreenfield** [comment]
I copied the code as-is from the docs, without changing anything or putting it anywhere, and rendered it with `ReactDOM.render()`, so I don't know how I'm using it wrong.

Other components of RMWC that I used in the same way worked just fine for me.

**Comment by jamesmfriedman** [comment]
Again, this is not a problem with RMWC. Please read the documentation on state in React. The docs have a global state that they use, so this.state is defined.

https://reactjs.org/docs/state-and-lifecycle.html

```
class MyComponent extends React.Component {
    constructor() {
        this.state = {
            menuIsOpen: false
        }
    }
   render() {
       // the code you had in pastebin goes here.
   }
}
```
