### ISSUE TITLE
Hello from Preact 👋🏻

### ISSUE THREAD

**Issue by prateekbh** [jamesmfriedman/rmwc#683]
RMWC.

Hi! This message is a friendly 👋🏻 from Preact team.
I am not sure if you are aware but we maintained a similar [wrapper](https://github.com/prateekbh/preact-material-components) over MDC-web for Preact alone. 

With the increasing release speed of mdc-web's major version packages and more requirement of focus in some other areas we are looking to deprecate our fork in favor of anything that matches closely our efforts.

`rmwc` seems to be very close to what we want. I would personally like to offer help in form of maintenance help instead of a maintaining a whole repo on our own.

We are planning to make this the default for the material template of [preact-cli](https://github.com/preactjs/preact-cli) and as a part of it would like to make contributions towards the gaps that we may find for preactX compatibility.
If this works then I would love to extend some help towards maintaining the overall project releases, bugs etc.

Thanks from Me and @developit. 👍

**Comment by jamesmfriedman** [comment]
@prateekbh. Yes yes and yes. Ping me on discord or linkedin and maybe we could do a quick chat.

**Comment by prateekbh** [comment]
I am dumb and dont know how to discord! 🙈
My code is prateekbh#3043

**Comment by jamesmfriedman** [comment]
@prateekbh just saw this, sent you a friend request on Discord

**Comment by mk2s6** [comment]
So, What went over the Discord. LoL

**Comment by prateekbh** [comment]
🙈 I was quite caught up, slowly coming back to my routine and stuff that got dropped

**Comment by jamesmfriedman** [comment]
@prateekbh I was just thinking about reaching back out to you! Lets connectt.
