### ISSUE TITLE
IconButton forced false state toggleable

### ISSUE THREAD

**Issue by juliancoleman** [jamesmfriedman/rmwc#689]
[Typescript Sandbox](https://codesandbox.io/s/rmwc-typescript-sandbox-forked-uhmof?file=/src/index.tsx)

- What RMWC Version are you using [major.minor.patch]: `6.1.3`

- Name your build system [Webpack, Rollup...]: `Webpack`

- Describe the bug with as much detail as possible:

According to [the documentation](https://rmwc.io/icon-buttons), `IconButton`'s `checked` property is explained as `Controls the on / off state of the a toggleable button`. However, if `false` is passed as the `checked` property, and is never set to `true`, the IconButton shouldn't activate its `on` state.

- What happened, and what was supposed to happen:

Clicking an `IconButton` whose `checked` property is always `false` activates `on` state.

**Comment by juliancoleman** [comment]
Why was this closed with no discourse?

**Comment by EmiBemi** [comment]
Hi @juliancoleman, please see the message in the readme on https://github.com/jamesmfriedman/rmwc
"We recently closed all issues for a full reset as we get back to the most recent Google version. If any still apply, please reopen."
