### ISSUE TITLE
Avatar component not working when using font awesome as base font instead of material icons

### ISSUE THREAD

**Issue by puru0019** [jamesmfriedman/rmwc#690]
Avatar component not working when using font awesome as base font instead of material icons. Following is the code to reproduce the issue.  This is happening when Avatar component upgraded to 6.1.3

Remove icon prop from RMWCProvider then it is working properly. 
https://codesandbox.io/s/react-hooks-usestate-forked-vk49m?file=/src/index.js

**Comment by jamesmfriedman** [comment]
It's actually a precedence issue. The avatar component is technically just an icon, and setting strategy to classname is breaking it. Thanks for reporting this.
