### ISSUE TITLE
Prevent scrolling to tabs on page load (also focusOnActivate not exist in Tab!) BUG

### ISSUE THREAD

**Issue by 7iomka** [jamesmfriedman/rmwc#692]
- What RMWC Version are you using [latest]:

- Name your build system [Next.js]:

- Describe the bug with as much detail as possible:
With simple usage of tabs components on page (in my case this is landing page) when page is opened it get scrolled to the section with tabs. Why? It's because focus on first active tab is? I need focus when tab is active (for styling for example..), but I don't want this unexpected scrolling...How to fix that?
![image](https://user-images.githubusercontent.com/18473137/92334350-a6f3a480-f095-11ea-8cc1-946b20b67b55.png)

- What happened, and what was supposed to happen: I don't know how to solve this problem.

**Comment by 7iomka** [comment]
Any news on this?

**Comment by 7iomka** [comment]
Also I see - package on npm have wrong types!
Tab component not support focusOnActivate prop!
Please fix this!

**Comment by jamesmfriedman** [comment]
@7iomka happy to accept a PR

**Comment by 7iomka** [comment]
> @7iomka happy to accept a PR
If there is no quick fix for the bug, then I thought that you can turn off the `focusOnActivate` available from the original plugin.
I see https://github.com/jamesmfriedman/rmwc/blob/ab155a96036541633e07bacbeb416d2ff57f2131/src/tabs/tab.tsx#L42
But what I see on installed latest version from `yarn add @rmwc/tabs`
![image](https://user-images.githubusercontent.com/18473137/92982747-579fe080-f4a8-11ea-9315-3236155e2633.png)

I don't know why this happen on published version, and I don't know how I could help.

**Comment by 7iomka** [comment]
As I see, this was added in newest v 6.1.4
Thanks.
But, I think `focusOnActivate` need to be setted to `false` by default.
This is default behavior in original version
Open: https://material.io/components/tabs
How you see - Tab one is NOT focused by default!
At the moment I need to disable this on every Tab inside Tabs - this is bad :(

**Comment by 7iomka** [comment]
And I don't understand what `focusOnActivate` does except how to remove forced focus on automatic activation of the first type by default? when activating other tabs manually, the tab itself still receives focus (the backlight works)
