### ISSUE TITLE
Dialog with open={true} can become closed.

### ISSUE THREAD

**Issue by OHUSAR** [jamesmfriedman/rmwc#694]
- What RMWC Version are you using [major.minor.patch]:

**6.1.3**

- Name your build system [Webpack, Rollup...]:

**Create React App**

- Describe the bug with as much detail as possible:

**I want to control the state of the dialog (open / closed) by a prop. When the dialog is closed by scrim click or a escape key, the `open` prop on the dialog stays `true`, but the dialog closes.**

- What happened:

**On scrim click, dialog closes, but the `open` prop remains `true`.**

- What was supposed to happen:

**I want the dialog to be opened when the prop is set to true. When I click outside the dialog, I would expect the `onClose` callback to be called with `undefined` value of `evt.details.action` and there I can decide, if I want to close the dialog (by setting the value of `open` to `false` or I want to keep it open.**

- Sandbox

https://codesandbox.io/s/rmwc-typescript-sandbox-forked-qxlm7?fontsize=14&hidenavigation=1&theme=dark

*Is this expected behaviour?*

Thank you for your answer!

**Comment by OHUSAR** [comment]
Any updates on this please?

**Comment by anthonysapien** [comment]
Hi, I'm having a related issue. I'm using a form as the content of my dialog, and I'd like to prevent the dialog from closing if the form fails to submit due to validation or an error. Similar to the OHUSAR's problem, I can't seem to keep the dialog open. It closes even when the 'open' prop is set to true.

**Comment by jamesmfriedman** [comment]
Yeah, I'm also having the same problem. Under some deadlines right now at work, but if someone wants to fix it I'd happily take a PR.

**Comment by thdk** [comment]
I'm not sure if rmwc can fix this as material/dialog already closes the dialog and then calls the ´notifyClosing´and ´notifyClosed´ foundation methods after which we all call setOpen(false) but the ui will have changed already before the state is updated. So calling setOpen(false) here is only done to 'match' the state value with the actual UI.

I can be wrong of course.
