### ISSUE TITLE
ListItem's hover/active effects not working

### ISSUE THREAD

**Issue by danilobjr** [jamesmfriedman/rmwc#696]
### First try

I started use this lib in a personal project, but hover/active effect doesn't work for ListItem. I imported styles using **SASS** as mentioned in docs of each component. 

### Second try

I was thinking if I was doing something wrong so I started a fresh Next.js app with only a single page. Inside that I put a Button, Drawer with List/ListItems. All of them installed individually. But I've got the same problem.

### Third try

I also tried to start another fresh Next.js app and install only original material components:

```
yarn add @material/button @material/drawer @material/list
```

This time it worked properly. So the problem seems to be in rmwc side.

### Question

Is rmwc outdated related to material? Can anyone help? Am I doing something wrong?

Thanks in advance!

#### Stack:

| Lib/Framework |  Version |
|---|---|
| Next.js | 9.5.3 |
| React | 16.13.1 |
| ReactDom | 16.13.1 |
| SASS | 1.26.10 |
| @rmwc/button | 6.1.4 |
| @rmwc/drawer | 6.1.4 |
| @rmwc/list | 6.1.4 |

#### package.json:

```json
{
  "name": "rmwc-ts",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@rmwc/button": "6.1.4",
    "@rmwc/drawer": "6.1.4",
    "@rmwc/list": "6.1.4",
    "next": "9.5.3",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "devDependencies": {
    "@types/node": "14.10.1",
    "@types/react": "16.9.49",
    "@types/react-dom": "16.9.8",
    "sass": "1.26.10",
    "typescript": "4.0.2"
  }
}
```

#### React part:

```jsx
import React, { useState } from 'react'
import {
  Drawer,
  DrawerHeader,
  DrawerTitle,
  DrawerSubtitle,
  DrawerContent,
} from '@rmwc/drawer'
import { List, ListItem } from '@rmwc/list'
import { Button } from '@rmwc/button'

export default function Home() {
  const [open, setOpen] = useState(false)

  return (
    <>
      <Drawer modal open={open} onClose={() => setOpen(false)}>
        <DrawerHeader>
          <DrawerTitle>DrawerHeader</DrawerTitle>
          <DrawerSubtitle>Subtitle</DrawerSubtitle>
        </DrawerHeader>
        <DrawerContent>
          <List>
            <ListItem>Item 1</ListItem>
            <ListItem>Item 2</ListItem>
            <ListItem>Item 3</ListItem>
          </List>
        </DrawerContent>
      </Drawer>

      <Button onClick={() => setOpen(!open)} raised>
        Toggle Modal
      </Button>
    </>
  )
}
```

#### SASS:

```scss
@import '~@material/drawer/dist/mdc.drawer.css';
@import '~@material/list/dist/mdc.list.css';
@import '~@material/button/dist/mdc.button.css';
@import '~@material/ripple/dist/mdc.ripple.css';
```

**Comment by lightandbright** [comment]
Im experiencing similar issues (on hover or select does not highlight list item), but only when List is child of DialogContent. I notice your list is inside Drawer, perhaps, that could be an issue (similar to my list being inside dialog).

not sure what the solution is, css imported as you do
