### ISSUE TITLE
Initial Loading screen

### ISSUE THREAD

**Issue by mk2s6** [jamesmfriedman/rmwc#698]
Hi James,

Its not a bug issue, but a Feature Request for Initial Loading Screen.

Thanks and regards,
Siva Kusi

**Comment by jamesmfriedman** [comment]
Can you elaborate on this?

**Comment by mk2s6** [comment]
It was that, the Starting Loading screen just like we get in mobile apps until the DOM is rendered and loaded all necessaries.

**Comment by jamesmfriedman** [comment]
I think thats out of scope for this particular project. This is (mostly) a wrapper for the google provided vanilla JS components. If they were to offer one, I would include it.

**Comment by mk2s6** [comment]
Sad, But yeah, I like your work, and if there are more features and additions just like material-ui kit, this would go beyond any other framework, as your Work and Documentation are better than anybody out there. hope you continue to add features outside wrappers as well. Please do consider as a request and also a better upgradation and development opportunity.

**Comment by mk2s6** [comment]
have you seen material-ui.com for react? They got many features as is. Just like kind of, not the initial loading screen, but like carousels, and like that.
