### ISSUE TITLE
Cannot read property 'menuIsOpen' of undefined - AGAIN

### ISSUE THREAD

**Issue by GalGreenfield** [jamesmfriedman/rmwc#70]
- RMWC Version: 0.0.1-rc12
 
- Browser:
 
    - Type: Google Chrome
    - Version: 63.0.3239.84 (Official Build) (64-bit) (cohort: Stable)
    - User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/63.0.3239.84 Safari/537.3
    - React Version: 16.2.0

- Build System: Create React App
 
- Steps to reproduce the problem:
    - Copy-paste: `import {Menu, MenuAnchor, MenuItem, MenuIsOpen } from 'rmwc;`
    - Copy-paste the code from here: https://pastebin.com/sZ1VSina

- Expected Behavior: a working dropdown menu as shown in the docs

- Actual behavior: an error: "TypeError: Cannot read property 'menuIsOpen' of undefined"
 
- Component/code doing things they shouldn't: the menuIsOpen property - it doesn't work,
 
- Other information:
    - It looks to me like this property doesn't even exists, yet there's code that uses it in the documentation and a demo of it there that works.Cannot read property 'menuIsOpen' of undefined
    - Also, James Friedman closed my previous ticket about this.
I told him that I copied the code AS-IS from the docs, so if there's a problem with the code, it's not *my code*, but *RMWC*'s docs code. So is there a problem with the docs' code, unless I don't understand something crucial here, as I'm a new to React.

**Comment by j-o-d-o** [comment]
I can not reproduce that error. Menu works just fine.
First of all here: `import {Menu, MenuAnchor, MenuItem, MenuIsOpen } from 'rmwc;`. rmwc does not export any `MenuIsOpen`. In fact, `menuIsOpen` has nothing to do with rmwc at all. You could call it anything you want as long as it is some kind of boolean that get's passed to the `open` property of the menu. The doc just shows an example how you can control menu opening and closing with the react.js state. 

This is basically the code from the docs and it works.
```javascript
import React from 'react';
import { Button, MenuAnchor, Menu, MenuItem } from 'rmwc';

class Home extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      menuIsOpen: false
    }
  }

  render() {
    return <div>
      <MenuAnchor>
        <Button
          raised
          onClick={evt => this.setState({ 'menuIsOpen': !this.state.menuIsOpen })}
        >
          Open Menu
        </Button>

        <Menu
          open={this.state.menuIsOpen}
          onClose={evt => this.setState({ menuIsOpen: false })}
        >
          <MenuItem>Cookies</MenuItem>
          <MenuItem>Pizza</MenuItem>
          <MenuItem>Icecream</MenuItem>
        </Menu>
      </MenuAnchor>

    </div>
  }
};
export default Home;


```

**Comment by GalGreenfield** [comment]
I completely missed what James wrote: "The docs have a global state that they use, so this.state is defined."
I'm sorry about the double posting.
Thanks for clearing that up!

By the way, where did you get the full code from the docs? The files from the package?

**Comment by jamesmfriedman** [comment]
@GalGreenfield, the docs are generated dynamically. There is no copy and paste solution for you, just read reacts docs. 

GitHub issues is reserved for bugs and not the best forum to discuss this kind of stuff. Please use gitter or stackoverflow if you’re looking for help on how to learn to use React components.
