### ISSUE TITLE
Toggle Buttons

### ISSUE THREAD

**Issue by anthonysapien** [jamesmfriedman/rmwc#700]
Hi, just wondering if you have plans to implement these:
https://material.io/components/buttons#toggle-button

Thanks!

**Comment by jamesmfriedman** [comment]
Don't know if they're included in MDC but i'll take a look

**Comment by EskiMojo14** [comment]
I believe this is what the [MDC Segmented Button](https://github.com/material-components/material-components-web/tree/master/packages/mdc-segmented-button) package is aiming to achieve. Not sure which version they were added in.
