### ISSUE TITLE
support for react 17.x.x

### ISSUE THREAD

**Issue by mk2s6** [jamesmfriedman/rmwc#705]
RMWC 6.1.4 does not work for new version of react that is 17.x.x, please do add support for it.

**Comment by SvenAlHamad** [comment]
Interested in the same thing. Are there any plans on adding support for React v17?

**Comment by Pavel910** [comment]
Ran into this today. RMWC is referencing `this._reactInternalFiber.key` and `this._reactInternalFiber` is `undefined` in React 17. This is happening in RMWC `v5.*` as well with React 17.

**Comment by suhaibmujahid** [comment]
It will be great if the support of React 17 comes with updating to `material-components-web` v8 (#620).

**Comment by antoniogamizbadger** [comment]
Any updates on this? :(((

**Comment by thaestrup** [comment]
Support for React 17 is out now in the latest version. Updates of material-components-web are next in pipeline. There is a PR for v6 here https://github.com/jamesmfriedman/rmwc/pull/748.
Update to v7 is being worked on ATM and the rest of the version updates will follow after that.
