### ISSUE TITLE
Not able to stop update value of @rmwc/switch box even change chandler is not there...!

### ISSUE THREAD

**Issue by sravanApt** [jamesmfriedman/rmwc#706]
While using rmwc switch, it's value is updating for first click on it event change handler is not there...!

my case as follows:- 

<SwitchBox
                  name="cookies"
                  checked={false}
                  onChange={(event) => {
                    // event.preventDefault();
                    // event.stopImmediatePropagation();
                    console.log(event.target);
                  }}
                />

after clicking on switch box it is showing as below:-

![image](https://user-images.githubusercontent.com/73094313/99376101-7f695580-28ea-11eb-8dbb-5853f2db5044.png)

Please look into this issue....

- What RMWC Version are you using [major.minor.patch]:

- Name your build system [Webpack, Rollup...]:

- Describe the bug with as much detail as possible:

- What happened, and what was supposed to happen:

**Comment by sravanApt** [comment]
Using latest rmwc version 6.1.3.
build - webpack 4
I need to stop update switch value until some condition passed. but it is changing before that condition checks...!

**Comment by ryanolsonx** [comment]
I'm having the same issue too. It's almost like it doesn't really become controlled.

**Comment by ryanolsonx** [comment]
@jamesmfriedman Closed because fixed?

**Comment by EmiBemi** [comment]
Hi @ryanolsonx, please see the message in the readme on https://github.com/jamesmfriedman/rmwc
"We recently closed all issues for a full reset as we get back to the most recent Google version. If any still apply, please reopen."
