### ISSUE TITLE
TextField focused styles not working when focus is set programmatically

### ISSUE THREAD

**Issue by rbare1** [jamesmfriedman/rmwc#709]
- What RMWC Version are you using [major.minor.patch]:
6.1.4

- Name your build system [Webpack, Rollup...]:
Both webpack and rollup

- Describe the bug with as much detail as possible:
When setting the input focus programmatically using the inputRef, the label doesn't move to the top of the TextField like it does when focus is set by clicking on the TextField.

- What happened, and what was supposed to happen:
https://codesandbox.io/s/rmwc-typescript-sandbox-forked-x4iyl?file=/src/index.tsx
1. Load page
2. Focus is set programatically
Expected:  TextField should get a purple outline and the label should move to the top.
Actual: TextField input is focused, but there are no styling changes and the label remains as placeholder text

![image](https://user-images.githubusercontent.com/3473227/101341829-f5c1fd80-3881-11eb-80ae-68d0a39fee1d.png)
![image](https://user-images.githubusercontent.com/3473227/101342676-32422900-3883-11eb-8410-0238cca084ca.png)

**Comment by thdk** [comment]
I think setting prop _autoFocus_ should work for you. See this sandbox:

https://codesandbox.io/s/rmwc-typescript-sandbox-forked-n0l7t
```
import React, { ChangeEvent, useState } from "react";
import * as ReactDOM from "react-dom";

// Includes all of material-components-web styles from the latest version
import "rmwc/styles";

import { TextField } from "@rmwc/textfield";

function Sandbox() {
  const [value, setValue] = useState("");
  return (
    <TextField
      value={value}
      onChange={(e: ChangeEvent<HTMLInputElement>) =>
        setValue(e.currentTarget.value)
      }
      label="Label"
      outlined
      autoFocus
    />
  );
}
```
