### ISSUE TITLE
[Bug] Failure to test RMWC TabBar using React Testing Library - onActivate not called when click on tab

### ISSUE THREAD

**Issue by conanak99** [jamesmfriedman/rmwc#710]
- **What RMWC Version are you using**: 5.7.1
- **Name your build system**: Jest and React Testing Library
- **Describe the bug with as much detail as possible**: Using React Testing Library, I'm trying to simulate clicking on a tab. However, `onActivate` function is not called.
- **What happened, and what was supposed to happen**: `onActivate` callback is not called when clicking on a tab using `fireEvent.click`. `onActivate` is supposed to be called.

**How to reproduce**
- Render a TabBar with 3 tabs (Sandbox: https://codesandbox.io/s/rmwc-typescript-sandbox-forked-mj0c0)
```tsx
import { TabBar, Tab } from '@rmwc/tabs'

<TabBar
  activeTabIndex={1}
  onActivate={evt => {
    const tabIndex = evt.detail.index
    console.log({ tab: tabIndex })
}}>
  <Tab>Tab 1</Tab>
  <Tab data-testid="tab-2">Tab 2</Tab>
  <Tab>Tab 3</Tab>
</TabBar>
```

- Try to click Tab 2 with `fireEvent.click`
```tsx
import { render, fireEvent } from '@testing-library/react'

it('should call onActivate', () => {
    const wrapper = render(<Sandbox />)
    fireEvent.click(wrapper.getByTestId('tab-2'))
    // console.log not called, no log
})
```

- The button is rendered properly with testId though
```html
<button class="mdc-tab" data-testid="tab-2">
   <div class="mdc-tab__content">
      <span class="mdc-tab__text-label">
      Tab2
      </span>
   </div>
   <span class="mdc-tab-indicator">
     <span
        aria-hidden="true"
        class="mdc-tab-indicator__content mdc-tab-indicator__content--underline" />
   </span>
   <div class="mdc-tab__ripple "/>
</button>
```

- **Workaround**: The above code work if I listen to `onClick` event directly on `Tab` component
```tsx
<Tab data-testid="tab-2" onClick={() => console.log('clicked')}>Tab 2</Tab>
```

**Comment by thdk** [comment]
Can you try using _user-event_? https://github.com/testing-library/user-event

**Comment by conanak99** [comment]
Thank for your suggestion, I tried using `user-event`, `onActivate` is still not called :(

```tsx
import userEvent from '@testing-library/user-event'

it('should call onActivate', () => {
    const wrapper = render(<Sandbox />)
    userEvent.click(wrapper.getByTestId('tab-2'))
    // still console.log is not called
})
```

**Comment by bjarkehs** [comment]
I experience the same issue in 6.14. My workaround is to put the callback on `<Tab onInteraction={callback}>Tab 1</Tab>`

**Comment by conanak99** [comment]
> I experience the same issue in 6.1.4. My workaround is to put the callback on `<Tab onInteraction={callback}>Tab 1</Tab>`

Yeah I can also use `onClick` on everytab `Tab` component itself. I feel like it's not the ideal solution :(

**Comment by bjarkehs** [comment]
`onInteraction` is better since it supports both click and keyboard events.
