### ISSUE TITLE
How to disable `mdc-dialog--stacked` in RMWC

### ISSUE THREAD

**Issue by b-d-m-p** [jamesmfriedman/rmwc#712]
When calling a dialog from inside another dialog, this `mdc-dialog--stacked` class is added and dialog buttons are stacked instead of being displayed in a row like they normally are. I would like to disable this. 

According to MDC, in the "Action button arrangement" section...

> This will also be disabled if the mdc-dialog--stacked modifier class is applied manually to the root element before the component is instantiated, but note that dialog action button labels are recommended to be short enough to fit on a single line if possible.

https://material.io/develop/web/components/dialogs

How can I accomplish this in RMWC?

**Comment by jfily** [comment]
+1

The option ```dialog.autoStackButtons = false;``` is available in MDC but I don't know how to pass it.
