### ISSUE TITLE
Hope you find some love that you needed from this Issue.

### ISSUE THREAD

**Issue by mk2s6** [jamesmfriedman/rmwc#717]
Hi James, 

I have been using RMWC of yours and loved every bit of it, it's Simplicity is what makes it so lovely and passionate on work. I don't know much about developing a package or a library, but as you I am a Dev who works hard to find love with what we do. So would love to Learn and be of support to you. 

Hope you find this message and feel great that, people are looking at you for more as you have kept the expectations at Everest with the Simplest beauty that you have provided to the world.

It's far best and simplest ever UI Library  that I have ever used and seen, Would love you Help you out on developing and maintaining the project with some help.

Thanks and regards,
Siva Kusi.

--Couldn't find your email or discord and couldn't ping in LinkedIn. 😆 ❤️ Hope this finds you refreshing. 😃 Hope to see the project on the go. and forward.

**Comment by jamesmfriedman** [comment]
Thanks Siva, I did need this. I haven't had much time lately to dedicate to doing a major update, but I want to find some additional maintainers to lighten the load. Chat me up on discord if you'd like to join in the fun.

**Comment by mk2s6** [comment]
Hi James would love to join the revolution ❤️ alongside with you, couldn't find your discord on any of the websites, so here's my discord I'd MK2S#8702

**Comment by rbare1** [comment]
@mk2s6 You can find the discord link here: https://rmwc.io/resources
