### ISSUE TITLE
Maintenance request

### ISSUE THREAD

**Issue by gugu** [jamesmfriedman/rmwc#722]
Hi!

I'm interested in spending time on the maintenance and development of the module because we (short.io) use it. I plan to fix current issues with development and try to update it to the latest mdc version. You can find my commits in material-components-web-react repo (before that module died)

**Comment by suhaibmujahid** [comment]
Thank you @gugu, this will be great. 

@jamesmfriedman could you check this?

**Comment by gugu** [comment]
Sorry for disappointing. After some research I've chose that material-components-web-components will be better choice for me - it also requires support and bugfixing, but at least I will not be alone

I've tried to upgrade rmwc to v10 of material components. You can check my (incomplete) work here: https://github.com/Short-io/rmwc. Most of components upgraded successfully except of textfield (this was easy), select (mostly fixed). They removed native version and kept enhanced only and slider. Slider was completely rewritten and I've did some work but was stuck with it

**Comment by suhaibmujahid** [comment]
Thank you Andrii for sharing the insights of your attemption. It's sad seeing this project becoming abandoned.
