### ISSUE TITLE
MDCTabBarScroller creates own instance of MDCTabBar.

### ISSUE THREAD

**Issue by vdkdev** [jamesmfriedman/rmwc#73]
### What RMWC Version are you using?

> Master at 353e4d40c6be518297ff6f9056b4f75f8f2a6785

### What browser(s) and React Version is this bug affecting?

> All

### What build system are you using?

> Webpack

### What are the steps to reproduce the bug?

> Wrap TabBar in TabBarScroller. Click on tabs.  Examine devtools console for errors.

I've submitted a PR for this one.

**Comment by jamesmfriedman** [comment]
This is fixed in the V1 release
