### ISSUE TITLE
Initial activeTabIndex: 0 does not add .mdc-tab--active

### ISSUE THREAD

**Issue by jesnil01** [jamesmfriedman/rmwc#75]
### What RMWC Version are you using?

> 0.0.1-rc12

### What browser(s) and React Version is this bug affecting?

> Chrome, Safari, Firefox

### What build system are you using?

> Webpack

### What are the steps to reproduce the bug?

> Clone master, install dependencies, run storybook
> Navigate to "Tabs > TabBar"

### What is the expected behavior?

> The first tab should have the class .mdc-tab--active on mount.

### What is the actual behavior?

> The first tab is missing the class .mdc-tab--active.
> It does add the class when navigating to another tab and then back.
> It does add the class to the second tab when mounting with activeTabIndex: 1

### Any other information you believe would be useful?

> I've tried to debug this and see where it originates but without success.

**Comment by izakfilmalter** [comment]
I have the same issue. Have nasty short term hack:

```jsx
<Tab className={activeTabIndex === 0 && 'mdc-tab--active'}>
  tab
</Tab>
```
Obviously you have to do this for each tab.

**Comment by jamesmfriedman** [comment]
This should be fixed in V1 @jesnil01. Let me know if the issue persists.

**Comment by jesnil01** [comment]
@jamesmfriedman Actually doesn't seems to work for me. Just cloned master and started storybook. Still no .mdc-tab--active class. You can see that first tab is missing the black color.

**Comment by jamesmfriedman** [comment]
Please check out the relevant pending PR #97. Verification that it works would be helpful in getting it merged in.
