### ISSUE TITLE
TextField `characterCount` does not work.

### ISSUE THREAD

**Issue by jmasukawa** [jamesmfriedman/rmwc#777]
Re-opening per "issue bankruptcy / full reset", this one is still an issue.

- What RMWC Version are you using [major.minor.patch]: 7.0.2

- Describe the bug with as much detail as possible:
See @nicholaschiang's original issue (https://github.com/jamesmfriedman/rmwc/issues/671), which has a lot of details about the problem, and is still an accurate description of the bug. 

This was originally reported on v6.1.3 (and I experienced on v6.1.4 and v7.0.2).

This issue is also reproducible on the RMWC demo site ("Textareas", https://rmwc.io/text-fields):
![image](https://user-images.githubusercontent.com/1621643/160910122-f0bb00cd-a5d6-46ee-a8b5-9353efcc995f.png)

I could make a code sandbox for you if that really helps, but I figured the RMWC demo site may be a good enough substitute, let me know.

Thanks for all your hard work on this project!

**Comment by b-d-m-p** [comment]
@jmasukawa Thanks! I'll look into it!

**Comment by EmiBemi** [comment]
Closed as it has now been fixed and released with v8!

**Comment by jmasukawa** [comment]
> Closed as it has now been fixed and released with v8!

Thank you so much!!
