### ISSUE TITLE
Testing Select WIth Jest

### ISSUE THREAD

**Issue by izakfilmalter** [jamesmfriedman/rmwc#78]
Writing some Jest tests for my forms to make sure they function as expected. Getting the following error when forms contain a select.

Wondering what the workaround is.

```
console.warn node_modules/rmwc/Base/withMDC.js:133
      MDCSelect failed to initialize because of the following error: TypeError: Cannot use 'in' operator to search for 'mdcRippleIsUnbounded' in undefined
          at MDCRipple.initialSyncWithDOM 
```

Using the following lib versions:
```json
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.0",
    "react": "^16.2.0",
    "react-scripts": "1.0.17",
    "rmwc": "^0.0.1-rc12"
```

**Comment by jamesmfriedman** [comment]
Ugh, yeah I've had this issue as well. A few places in MDC they check el.dataset, which is undefined in some test environments.

When testing RMWC, I've resorted to grabbing a DOM reference and adding it in. I can see about doing this in all cases so this doesn't become an issue again.

**Comment by izakfilmalter** [comment]
Thanks for all the work on this lib btw. Been super nice and easy to use.

**Comment by izakfilmalter** [comment]
My current workaround is to force the css only select to render for tests.

**Comment by jamesmfriedman** [comment]
No problem. Thanks for the positive feedback, it keeps me going.

**Comment by jamesmfriedman** [comment]
Yeah just realized that I have the same problem in my tests, I'm just catching them as a warning instead of an error. I'll prioritize finding a fix, or if you feel like getting your hands dirty, see what you can come up with.

**Comment by jamesmfriedman** [comment]
@izakfilmalter The answer was so ridiculously easy it's embarrassing... in your setupTests file for jsdom, or wherever you configure your tests:

```
window.HTMLElement.prototype.dataset = {};
```

This will patch an empty dataset onto every HTML element.
