### ISSUE TITLE
cssOnly Select's wrapper div gets activated instead of activating the actual select control when navigating with Tab key

### ISSUE THREAD

**Issue by fterradev** [jamesmfriedman/rmwc#79]
### What RMWC Version are you using?

rc13; rc12 did have the same issue.

### What browser(s) and React Version is this bug affecting?

Chrome 63 and React 16.1.1

### What build system are you using?

Create React App

### What are the steps to reproduce the bug?

Use a cssOnly Select, for example:
```jsx
<Select
  cssOnly
  name="category"
  required
  options={{
    '': 'Pick a category',
    ...categories.options
  }}
  defaultValue={categoryPath}
/>
```

Access the page and navigate through the controls with Tab key, until the Select is highlighted for the first time. Press Enter, Space, Arrow Up or Arrow Down, as trying to interact with the select.

### What is the expected behavior?

The select options should show up by pressing Enter or Space. Or its value should change when pressing Arrow Up or Down.

### What is the actual behavior?

The page is scrolled. That's because you're interacting with the wrapper div, which happens because it renders with a `tabindex="0"`. You must press Tab again to start interacting with the select.

### Any other information you believe would be useful?

A workaround for current version is to use `tabIndex=""` in the Select.

**Comment by jamesmfriedman** [comment]
@fterradev check out that commit and verify that it will fix this issue.

**Comment by fterradev** [comment]
Tried to use it by running:
`
npm uninstall rmwc --save
`
followed by
`
npm install jamesmfriedman/rmwc#a6b487f
`

But then it fails with:
"./src/components/App.js
Module not found: Can't resolve 'rmwc' in 'C:\\...\src\components'"

Can you help me and say what's the proper way of installing a specific commit version?
I've also tried:
`
npm install jamesmfriedman/rmwc#master
`

But got the same result...

**Comment by jamesmfriedman** [comment]
It goes through a build process before it gets published to npm. For testing purposes, try this:

Change directory to node_modules/rmwc. Run npm install && npm run babelfy. You should be able I run or app after that.  

Let me know if that works, and I can document how to run from a git branch.

**Comment by jamesmfriedman** [comment]
This should be fixed in V1.
