### ISSUE TITLE
Want to be a Collaborator? Comment here.

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#80]
Hi all, I started this project out of a an unmet need and opportunity I saw to fill it. RMWC has been getting some good traction and feedback, and I'd like to find some people to help take it to the next level.

If you're interested, comment on this issue and lets get a conversation going.

**Comment by izakfilmalter** [comment]
I would like to help. In the middle of trying to get my startup off the ground. Once it is launch I can def help for about 5 hours a week.

**Comment by j-o-d-o** [comment]
I'd have some time I could spend.

**Comment by jamesmfriedman** [comment]
Thanks @izakfilmalter, let me know when your time gets freed up.

@j-o-d-o, I just added you as a collaborator.

**Comment by jrajav** [comment]
I am interested but can't commit regular time. I will try to take a look at a few issues at least.

**Comment by jamesmfriedman** [comment]
Thanks @jrajav, every little bit helps

**Comment by GideonFlynn** [comment]
I would love to contribute to this awesome project. I have a flexible schedule and can start with about 3 hours a week.

**Comment by jamesmfriedman** [comment]
Thanks @GideonFlynn, how about checking out the massive #88 PR?

**Comment by bernharduw** [comment]
I could get a project done within 3 days thanks to rmwc! I want to give back (although I won't be able to contribute too much for now). I'd like to do those theming issues, #89 and maybe @90, because this was what my project was about.

**Comment by jamesmfriedman** [comment]
Thanks @bernharduw, happy to accept PR's for either if you get the time to work on it. Just chime in on those issues.

**Comment by ALMaclaine** [comment]
I'm very interested in helping. I'm still somewhat new, just about 3 years.  I'm very interested in Material Design, React and helping maintain a professional framework. Might need some help getting jump started on understanding the code base but I believe I could be useful in some capacity.

**Comment by jamesmfriedman** [comment]
Thanks @ALMaclaine. Feel free to look through the issues and submit any PRs. Theres a growing group here for guidance and help.

**Comment by ALMaclaine** [comment]
@jamesmfriedman will do, thank you.

**Comment by ricardobrandao** [comment]
Hi @jamesmfriedman. It's good to see that RMWC has been evolving over time! 👍 

I was doing my own version of the react material components but I'm now willing to give a try to RMWC. Therefore, I'll gladly help with the project. Right now I have a lot on my plate but I'll try to dedicate some time to this.

**Comment by jamesmfriedman** [comment]
Thanks @ricardobrandao. Every little bit from the community makes this thing better!

**Comment by jamesmfriedman** [comment]
This project is and will always be open to new collaborators. Easiest thing to do is to pick up any of the open issues and submit a pr for them. After a bit you can be added to the collaborators list. Hit me up on gitter for General questions, excited to welcome someone new.

**Comment by simsim0709** [comment]
Hi, @jamesmfriedman 
First, thank you for the great library.
I use this library for my service I use it silently, though. 
I'm willing to help out as much as I can.

**Comment by mutsys** [comment]
I have been cheerfully submitting PRs over the last few months when I have something to contribute back to the project but I would be happy to commit some of my time to participate on a more formal basis.

**Comment by jamesmfriedman** [comment]
@mutsys I've appreciated the help. I've added you to the collaborators list!

**Comment by CoVoCre** [comment]
Hey ! I think we should try to work with google on this 😅I noticed they recently started to implement their own react wrapper for material design components for the web MDCW : https://github.com/material-components/material-components-web-react
Also, I told them about us on the discord conversation for the react MDC project.

**Comment by jamesmfriedman** [comment]
@CoVoCre I've actually met some of the team in person before and have had a handful of conversations with them. They are very aware of this projects existence and decided they wanted to create their own which is totally their prerogative. To date, it is not feature complete.

I will continue to support this library as long as myself and others are gaining benefit from it. For me, the docs + ssr + flow and typescript support, and a handful of production apps are what will keep me using this for the foreseeable future.

**Comment by tata81** [comment]
Hey! @jamesmfriedman Thanks for this amazing project, me and my team are using it for a while, I would love to contribute to this awesome project. Would you please guide me where to start? Thanks

**Comment by SleeplessByte** [comment]
@tata81 https://github.com/jamesmfriedman/rmwc/blob/master/CONTRIBUTING.md

**Comment by jamesmfriedman** [comment]
@tata81 would love to have your contribution! The mdc 4.x.x branch represents a major internal refactor specifically aimed at making it easier for people to contribute. Discord is the best place to plan and collaborate, so message me or the channel there and we can figure out something good to work on.
