### ISSUE TITLE
Update to MDC 0.28.0

### ISSUE THREAD

**Issue by j-o-d-o** [jamesmfriedman/rmwc#86]
https://github.com/material-components/material-components-web/blob/v0.28.0/CHANGELOG.md

Quite a big release in terms of changes. Here is a list what I think is relevant for us (please add or change anything I might have missed):

*From Features*
- [x] Add `mdc-text-field--dense` to the className props, that being said, should all other cssClasses also be mappend there e.g. 'mdc-text-field--focused'
- [x] Support outlined textfields

*From Breaking Changes*
- [x] Rename drawer classes
- [x] Move select tabIndex and API reference from root element to surface element
- [x] Rename `__start-detail` has been renamed to `__graphic`, and `__end-detail` has been renamed to `__meta` on list
  
Also when there is a Changelog file in rmwc, it is important to always link to the MDC changelog and tell the users to also keep these changes in mind as some mdc functionality is accessed directly or just passed through from rmwc.

**Comment by jamesmfriedman** [comment]
Nice @j-o-d-o! Good call on the changelog stuff as well. A few things.

- We should add a CONTRIBUTING.md file with some patterns we can agree on moving forward, especially what we do with an MDC release.
- I have a V1 branch going that we can do the v28 work in. I've already covered
  - Menu positioning #83 : the docs were actually way wrong this. Those helper classes don't exist and don't do anything to my knowledge. There is a method called setAnchorPosition which takes 1 of 8 constants that I was about to get working. You can now pass anchorPosition as a string and it will pick use one of the constants. 0981b3dfdb4f3c306fe38be746f728b85514803e
  - I'm currently working on Drawers as we speak
  - I should be able to get through the rest of the breaking changes this morning. This branch needs a hefty amount of checking and double checking. 
  - MDC's docs continue to lie, the best source of truth seems to be the demos, the changelog, a little bit of the docs, and trial and error.

Whatcha think?

**Comment by jamesmfriedman** [comment]
Got the drawers done, it was much much worse than just renaming, but got to remove a lot of repeat code.

**Comment by jamesmfriedman** [comment]
K, all of it should be taken care of in the V1 branch. Still going to continue to scrub the docs for verification of a working V1, but closing this one out in favor of continuing #77.
