### ISSUE TITLE
Ripple Issues

### ISSUE THREAD

**Issue by izakfilmalter** [jamesmfriedman/rmwc#93]
Just want to document some ripple issues from the new ripple mixins from https://github.com/material-components/material-components-web.

Seems like stuff stays selected when clicked:
https://github.com/material-components/material-components-web/issues/1951

Update 1:
From what I can tell the issue is pressent in their [docs](http://material-components-web.appspot.com/tabs.html#three), but not in RMWC's [docs](https://jamesmfriedman.github.io/rmwc/tabs).

Update 2:
Seems to be connected to the tag, eg `a` vs `div`.

**Comment by izakfilmalter** [comment]
From what I can tell the issue is pressent in their [docs](http://material-components-web.appspot.com/tabs.html#three), but not in RMWC's [docs](https://jamesmfriedman.github.io/rmwc/tabs).

**Comment by jamesmfriedman** [comment]
Awesome. So actual issue to be fixed, or just something we'll get downstream eventually?

**Comment by izakfilmalter** [comment]
More pointing it out since it's not happening in rmwc docs but in theres, but can happen in an app using this lib.

**Comment by jamesmfriedman** [comment]
@izakfilmalter you ok with me closing this out since it's MDC related?

**Comment by izakfilmalter** [comment]
Yep.
