### ISSUE TITLE
bug(tabs): activeTabIndex doesn't set active tab of 0 on load.

### ISSUE THREAD

**Issue by izakfilmalter** [jamesmfriedman/rmwc#94]
If you set `activeTabIndex` `0` on load then the tab is not active. If you set it to `'0'` it is. Probably some check on the `activeTabIndex` that is checking boolean and failing on `0`.

**Comment by izakfilmalter** [comment]
I am gonna try to fix this.

**Comment by jamesmfriedman** [comment]
Ah, good catch. Though this one was fixed, if you find out what it is, lets add a test case so it doesn't happen again.

**Comment by jamesmfriedman** [comment]
Just verified the same issue. The "0" hack works on the regular TabBar but not TabBarScroller. Definitely a timing / rendering issue as well as likely an inferred boolean style check like you mentioned.

**Comment by izakfilmalter** [comment]
Ya I am digging through your code. Best I have right now is to add this to `tabs/index.js`:

```js
  onMount(props, api) {
    if (!api) return;

    api.activeTabIndex = props.activeTabIndex + '';
  },
```

Super ugly and breaks tests. I am guessing that api comes from `material-web-components`?

**Comment by izakfilmalter** [comment]
After some more debugging `console.log(api.activeTabIndex);`. Seems like this value doesn't change when set to `0`.

**Comment by izakfilmalter** [comment]
Seems like the issue is coming from here:

https://github.com/material-components/material-components-web/blob/c3cb0e04bb2b011ebeede33c8011df5b1e637f7a/packages/mdc-tabs/tab-bar/foundation.js#L112

**Comment by jamesmfriedman** [comment]
You are correct. Anywhere you see "api" you're actually dealing with the real foundation api. I appreciate you looking into that, going to save a bunch of time. I'll see about getting this fixed.

**Comment by izakfilmalter** [comment]
You may need children of `TabBar` to fire a callback in their `componentDidMount` before you initialize `TabBar`. Maybe even just the first `Tab`.
