### ISSUE TITLE
bug(inputs): styled-components can't add className to TextFieldIcon

### ISSUE THREAD

**Issue by izakfilmalter** [jamesmfriedman/rmwc#99]
I am still on `v0.0.1-rc13` with this issue. I seem to not be able to add `className` to `TextFieldIcon`.

**Comment by jamesmfriedman** [comment]
Just verified it's working as expected in 1.0. Tracked the fix down to this commit https://github.com/jamesmfriedman/rmwc/commit/bb6f036d39aa8803c8b410e2a04bd6f29f9f928a

**Comment by jamesmfriedman** [comment]
Also @izakfilmalter do you want to write a quick paragraph on how to use styled-components with RMWC and I'll add it to the docs?

**Comment by izakfilmalter** [comment]
Ya I can open a pr for that.
